import axios from 'axios'

// List of all markdown files in the public/pages directory
const PAGE_FILES = [
  'README.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_Besides_the_Czech_Republic,_which_other_countries_have_pledged_support_following_the_disaster?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_How_are_global_leaders_from_the_US,_Israel,_India,_Pakistan,_and_Ukraine_responding_to_the_disaster_in_Turkey_and_what_kind_of_support_have_they_pledged?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_How_did_Christian_Atsu's_presence_in_Turkey_during_the_earthquake_influence_international_attention_and_response_to_the_disaster?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_How_did_the_Christian_Atsu_earthquake_affect_Atsu's_professional_career_and_personal_life_in_the_immediate_aftermath_of_the_earthquake?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_How_did_the_earthquake_impact_the_Hatayspor_team_and_the_general_morale_in_the_club?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_How_do_the_aftershocks,_particularly_those_measuring_6.0_or_greater,_compound_the_damage_caused_by_the_original_earthquake_in_Turkey?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_How_do_the_aftershocks_impact_the_rescue_operations_and_the_survivors_of_the_7.8_magnitude_earthquake_in_southern_Turkey?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_How_do_the_death_and_injury_tolls_compare_between_government-controlled_and_rebel-held_areas_in_Syria_following_the_quakes?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_How_does_the_Turkey-Syria_earthquake_death_toll_compare_to_previous_earthquakes_in_the_region_in_terms_of_impact_and_the_response_it_has_garnered?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_How_does_the_decreasing_frequency_and_magnitude_of_aftershocks_over_time_affect_the_overall_seismic_activity_following_the_main_quake_in_southern_Turkey?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_How_does_the_proximity_of_the_epicenter_to_the_border_with_Syria_affect_the_regional_seismic_activity_and_potential_cross-border_impacts_following_the_main_quake_in_southern_Turkey?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_How_have_the_death_and_injury_numbers_in_Turkey_and_Syria_fluctuated_over_time_and_what_might_have_been_the_contributing_factors_to_the_changes?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_How_have_the_death_toll_and_injury_numbers_in_Turkey_and_Syria_varied_over_the_course_of_the_earthquake's_aftermath?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_How_is_the_health_infrastructure_in_both_Turkey_and_Syria_coping_with_the_large_number_of_injured_individuals_following_the_quake?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_What_are_the_details_of_the_Netherlands'_commitment_to_send_a_search_and_rescue_team_to_Turkey?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_What_are_the_key_characteristics_and_specialties_of_the_Czech_Republic's_USAR_team_being_deployed_to_Turkey?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_What_are_the_ongoing_efforts_to_confirm_Christian_Atsu's_condition_and_whereabouts_after_the_conflicting_reports?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_What_are_the_patterns_emerging_from_the_frequency_and_magnitude_of_the_aftershocks_following_the_main_quake_in_southern_Turkey?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_What_criteria_are_used_to_decide_which_countries_send_assistance_and_how_is_the_assistance_coordinated?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_What_is_the_expected_timeline_for_the_arrival_and_deployment_of_search_and_rescue_teams_from_the_Netherlands_and_Germany_in_Turkey?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_What_is_the_role_of_the_United_States_Geological_Survey_(USGS)_and_Turkey's_Disaster_and_Emergency_Management_Agency_(AFAD)_in_monitoring_and_reporting_the_earthquake_and_its_aftershocks?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_What_measures_are_being_taken_to_account_for_the_rapid_rise_in_the_death_toll_in_both_Turkey_and_Syria_following_the_earthquake?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_What_measures_are_being_taken_to_ensure_the_safety_and_wellbeing_of_other_foreign_footballers_currently_based_in_Turkey_besides_Christian_Atsu?.md',
  'claim_summaries_gpt4_cite_feb_6_13.json_What_were_the_circumstances_leading_up_to_Christian_Atsu's_experience_during_the_earthquake_in_Turkey?.md',
  'claim_summaries_withcite_Oct_16_30.json_How_has_Ukraine_responded_to_the_increased_use_of_kamikaze_drones_by_Russia_in_the_Russia-Ukraine_conflict?.md',
  'claim_summaries_withcite_Oct_16_30.json_How_has_the_conflict_in_Ukraine_affected_Russia's_economy?.md',
  'claim_summaries_withcite_Oct_16_30.json_How_have_Western_countries_responded_to_increased_use_of_kamikaze_drones_by_Russia_in_Ukraine?.md',
  'claim_summaries_withcite_Oct_16_30.json_How_have_kamikaze_drones_changed_the_nature_of_the_Russia-Ukraine_conflict?.md',
  'claim_summaries_withcite_Oct_16_30.json_How_might_other_countries_react_to_the_suspension_of_the_Russian_grain_deal?.md',
  'claim_summaries_withcite_Oct_16_30.json_How_might_the_Ukrainian_government_respond_if_Russia_does_indeed_leave_the_Black_Sea_Grain_Initiative?.md',
  'claim_summaries_withcite_Oct_16_30.json_How_might_the_delays_in_grain_shipments_impact_the_global_food_supply?.md',
  'claim_summaries_withcite_Oct_16_30.json_How_might_the_global_food_crisis_worsen_if_the_Black_Sea_grain_deal_is_not_renewed?.md',
  'claim_summaries_withcite_Oct_16_30.json_How_might_the_international_community_respond_if_it_is_revealed_that_Russia_was_behind_a_false-flag_operation_involving_a_dirty_bomb_in_Ukraine?.md',
  'claim_summaries_withcite_Oct_16_30.json_What_are_Putin's_goals_in_declaring_martial_law_in_four_Ukrainian_regions?.md',
  'claim_summaries_withcite_Oct_16_30.json_What_are_Russia's_motivations_for_accusing_Ukraine_of_planning_to_use_a_dirty_bomb?.md',
  'claim_summaries_withcite_Oct_16_30.json_What_are_the_advantages_of_using_kamikaze_drones_in_Ukraine?.md',
  'claim_summaries_withcite_Oct_16_30.json_What_are_the_causes_of_the_delays_in_grain_shipments_in_Ukraine?.md',
  'claim_summaries_withcite_Oct_16_30.json_What_are_the_goals_of_each_side_in_the_conflict?.md',
  'claim_summaries_withcite_Oct_16_30.json_What_are_the_implications_of_Russia_suspending_its_participation_in_the_Black_Sea_grain_deal?.md',
  'claim_summaries_withcite_Oct_16_30.json_What_are_the_implications_of_a_dirty_bomb_being_used_in_Ukraine?.md',
  'claim_summaries_withcite_Oct_16_30.json_What_are_the_risks_and_benefits_of_a_military_campaign_for_Ukraine?.md',
  'claim_summaries_withcite_Oct_16_30.json_What_could_be_the_motivations_behind_Russia's_decision_to_suspend_the_grain_deal?.md',
  'claim_summaries_withcite_Oct_16_30.json_What_goals_does_Ukraine_hope_to_achieve_through_military_force?.md',
  'claim_summaries_withcite_Oct_16_30.json_What_implications_does_Putin's_decision_to_declare_martial_law_have_for_the_people_of_the_Donetsk_and_Luhansk_regions?.md',
  'claim_summaries_withcite_Oct_16_30.json_What_is_the_international_community's_response_to_Russian_President_Putin's_decision_to_declare_martial_law?.md',
  'claim_summaries_withcite_Oct_16_30.json_What_is_the_reason_for_Putin's_decision_to_declare_martial_law?.md',
  'claim_summaries_withcite_Oct_16_30.json_What_is_the_significance_of_the_Black_Sea_grain_deal_between_Ukraine_and_Russia?.md',
  'claim_summaries_withcite_Oct_16_30.json_What_is_the_status_of_the_Black_Sea_Grain_Initiative?.md',
  'claim_summaries_withcite_Oct_16_30.json_What_measures_can_be_taken_to_prevent_delays_in_shipments_under_the_Black_Sea_Grain_Initiative?.md',
  'claim_summaries_withcite_Oct_16_30.json_What_motivated_Russia_to_make_these_unsubstantiated_claims?.md',
  'claim_summaries_withcite_Oct_16_30.json_Who_has_the_advantage_in_terms_of_resources_in_Ukraine's_war_with_Russia?.md',
  'claim_summaries_withcite_Oct_16_30.json_Why_has_Russia_step_up_its_use_of_"kamikaze_drones"_in_its_assault_against_Ukraine?.md',
  'claim_summaries_withcite_Oct_1_15.json_How_have_Russian_officials_reacted_to_the_news_of_the_retreat_of_Russian_troops_from_Lyman?.md',
  'claim_summaries_withcite_Oct_1_15.json_How_have_authorities_in_Belarus,_Russia_and_Ukraine_reacted_to_the_news_of_the_Nobel_Peace_Prize_award?.md',
  'claim_summaries_withcite_Oct_1_15.json_How_might_Russia_respond_if_the_US_does_supply_Ukraine_with_advanced_air_defense_systems?.md',
  'claim_summaries_withcite_Oct_1_15.json_How_might_Russia_respond_if_the_US_provides_Ukraine_with_more_advanced_weaponry?.md',
  'claim_summaries_withcite_Oct_1_15.json_How_might_the_Russia-Ukraine_conflict_impact_the_safety_of_the_Zaporizhzhia_nuclear_power_plant?.md',
  'claim_summaries_withcite_Oct_1_15.json_How_might_the_international_community_respond_to_the_annexation_of_the_Zaporizhzhia_nuclear_power_plant?.md',
  'claim_summaries_withcite_Oct_1_15.json_How_might_the_restarting_of_one_of_the_reactors_at_the_Zaporizhzhia_nuclear_power_plant_impact_the_situation?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_are_Macron's_goals_in_providing_military_aid_to_Ukraine?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_are_some_implications_of_the_retreat_for_the_Russia-Ukraine_conflict?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_are_the_implications_of_the_European_investigation_of_the_Nord_Stream_gas_pipeline_leaks?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_are_the_implications_of_the_withdrawal_of_Russian_troops_from_Lyman_for_the_future_of_the_conflict?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_are_the_long-term_prospects_for_the_work_of_human_rights_campaigners_in_Ukraine,_Russia_and_Belarus?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_are_the_possible_implications_of_Russia_seizing_control_of_the_Zaporizhzhia_nuclear_power_plant?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_are_the_possible_motivations_for_the_countries_that_are_interested_in_the_Nord_Stream_gas_pipeline_being_decommissioned?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_are_the_possible_motives_for_sabotage_of_the_Nord_Stream_gas_pipelines?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_are_the_potential_consequences_of_the_Nord_Stream_gas_pipeline_being_decommissioned?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_are_the_potential_consequences_of_the_Nord_Stream_gas_pipeline_not_being_decommissioned?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_are_the_potential_outcomes_of_the_IAEA_chief's_trip_to_Ukraine?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_are_the_risks_associated_with_the_US_getting_more_involved_in_the_conflict_in_Ukraine?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_challenges_do_the_Nobel_Peace_Prize_winners_face_in_their_work?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_impact_do_the_Nobel_Peace_Prize_winners_hope_to_achieve_through_their_work?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_is_France's_strategy_for_supporting_Ukraine_in_the_Russia-Ukraine_crisis?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_is_the_European_Union's_strategy_for_supporting_Ukraine_in_the_Russia-Ukraine_crisis?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_is_the_Ukrainian_government's_strategy_for_dealing_with_the_Russian_aggression?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_is_the_long-term_strategy_for_the_US_in_supporting_Ukraine?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_is_the_potential_impact_of_a_nuclear_accident_at_the_Zaporizhzhia_nuclear_power_plant?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_is_the_purpose_of_IAEA_chief_Rafael_Mariano_Grossi's_visit_to_Kyiv_and_Moscow?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_is_the_role_of_the_International_Atomic_Energy_Agency_in_the_Russia-Ukraine_conflict?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_is_the_significance_of_Lyman_for_the_Russian_military?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_is_the_significance_of_the_US_providing_Ukraine_with_advanced_air_defense_systems?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_is_the_status_of_negotiations_around_the_establishment_of_a_nuclear_safety_and_security_zone_around_the_Zaporizhzhia_nuclear_power_plant?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_is_the_status_of_the_Zaporizhzhia_nuclear_power_plant_and_the_surrounding_area?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_motivated_the_Norwegian_Nobel_Committee_to_award_the_Nobel_Peace_Prize_to_human_rights_campaigners_in_Ukraine,_Russia_and_Belarus?.md',
  'claim_summaries_withcite_Oct_1_15.json_What_was_the_reason_for_the_withdrawal_of_Russian_troops_from_Lyman?.md',
  'claim_summaries_withcite_dec_16_30.json_How_has_the_EU_and_US_responded_to_the_growing_Russian-Belarusian_alliance?.md',
  'claim_summaries_withcite_dec_16_30.json_How_has_the_Ukrainian_military_responded_to_the_Russian_shelling_in_Kherson?.md',
  'claim_summaries_withcite_dec_16_30.json_How_has_the_shelling_impacted_the_ability_of_civilian_populations_in_Kherson_to_access_basic_services_such_as_heat,_water_and_electricity?.md',
  'claim_summaries_withcite_dec_16_30.json_How_has_the_strategic_partnership_between_Russia_and_Belarus_affected_the_Russia-Ukraine_crisis?.md',
  'claim_summaries_withcite_dec_16_30.json_How_have_Russian_forces_been_able_to_maintain_a_sustained_level_of_shelling_of_Kherson_and_other_recently_liberated_settlements?.md',
  'claim_summaries_withcite_dec_16_30.json_How_have_other_countries_reacted_to_the_missile_attacks_in_Kyiv?.md',
  'claim_summaries_withcite_dec_16_30.json_How_will_the_US-Ukraine_partnership_be_strengthened_through_President_Zelensky's_visit?.md',
  'claim_summaries_withcite_dec_16_30.json_How_will_the_additional_security_assistance_from_the_United_States_benefit_Ukraine?.md',
  'claim_summaries_withcite_dec_16_30.json_What_additional_measures_can_be_taken_by_the_United_States_to_support_Ukraine_in_the_face_of_Russia's_aggression?.md',
  'claim_summaries_withcite_dec_16_30.json_What_are_the_potential_consequences_of_Belarus_becoming_a_vassal_state_of_Russia?.md',
  'claim_summaries_withcite_dec_16_30.json_What_are_the_primary_targets_of_the_Russian_shelling_in_Kherson?.md',
  'claim_summaries_withcite_dec_16_30.json_What_can_be_done_to_improve_the_humanitarian_situation_in_Kherson?.md',
  'claim_summaries_withcite_dec_16_30.json_What_economic_and_political_incentives_has_Putin_offered_Belarus_in_exchange_for_its_support_during_the_Ukraine_crisis?.md',
  'claim_summaries_withcite_dec_16_30.json_What_have_been_the_economic_impacts_of_the_Russian_missile_attacks_on_Kyiv?.md',
  'claim_summaries_withcite_dec_16_30.json_What_impact_have_Western_sanctions_had_on_the_relationship_between_Russia_and_Belarus?.md',
  'claim_summaries_withcite_dec_16_30.json_What_is_the_Kremlin's_reaction_to_President_Zelensky's_visit_to_the_United_States?.md',
  'claim_summaries_withcite_dec_16_30.json_What_is_the_capability_of_Ukraine's_air_defense_systems_in_repelling_the_missile_attacks_from_Russian_missiles_in_Kyiv?.md',
  'claim_summaries_withcite_dec_16_30.json_What_is_the_primary_purpose_of_President_Zelensky's_visit_to_the_United_States?.md',
  'claim_summaries_withcite_dec_16_30.json_What_is_the_purpose_of_the_Russian_missile_strikes_in_Kyiv?.md',
  'claim_summaries_withcite_dec_16_30.json_What_measures_have_been_taken_to_protect_civilians_in_the_affected_areas_of_Kyiv_from_Russian_missile_attacks?.md',
  'claim_summaries_withcite_dec_1_15.json_How_can_US-French_alliance_support_Ukraine_in_its_fight_against_Russia?.md',
  'claim_summaries_withcite_dec_1_15.json_How_can_the_International_Atomic_Energy_Agency_(IAEA)_best_ensure_the_safety_of_the_Zaporizhzhia_nuclear_power_plant_in_the_face_of_potential_nuclear_terrorism?.md',
  'claim_summaries_withcite_dec_1_15.json_How_can_the_international_community_best_support_Ukraine_in_protecting_the_Zaporizhzhia_nuclear_power_plant?.md',
  'claim_summaries_withcite_dec_1_15.json_How_has_the_Russian_shelling_in_Nikopol_impacted_the_security_of_the_region?.md',
  'claim_summaries_withcite_dec_1_15.json_How_has_the_media_in_Ukraine_and_Russia_reported_on_the_Russian_shelling_in_Nikopol?.md',
  'claim_summaries_withcite_dec_1_15.json_How_have_the_Ukrainian_and_Russian_governments_responded_to_the_presence_of_the_Russian_air_base_in_Ukraine?.md',
  'claim_summaries_withcite_dec_1_15.json_How_have_the_people_of_Melitopol_been_affected_by_the_Ukrainian_missile_attack?.md',
  'claim_summaries_withcite_dec_1_15.json_How_is_President_Biden's_stance_towards_Russia_different_from_that_of_his_predecessor,_Donald_Trump?.md',
  'claim_summaries_withcite_dec_1_15.json_How_is_the_US_attempting_to_limit_Putin's_potential_to_profit_from_the_oil_market?.md',
  'claim_summaries_withcite_dec_1_15.json_How_is_the_international_community_responding_to_the_situation_in_Melitopol?.md',
  'claim_summaries_withcite_dec_1_15.json_How_might_Ukraine_benefit_from_the_oil_price_cap?.md',
  'claim_summaries_withcite_dec_1_15.json_How_will_Russia_respond_to_the_price_cap_set_by_western_nations?.md',
  'claim_summaries_withcite_dec_1_15.json_What_are_the_implications_of_the_use_of_longer-range_weaponry_in_the_Ukraine-Russia_conflict?.md',
  'claim_summaries_withcite_dec_1_15.json_What_are_the_legal_implications_of_Russia’s_occupation_of_the_Zaporizhzhia_nuclear_power_plant?.md',
  'claim_summaries_withcite_dec_1_15.json_What_are_the_strategic_implications_of_the_Russian_air_base_in_Ukraine_for_both_countries?.md',
  'claim_summaries_withcite_dec_1_15.json_What_implications_would_the_acceptance_of_annexed_Ukrainian_regions_as_part_of_Russia_have_for_US-Russia_relations?.md',
  'claim_summaries_withcite_dec_1_15.json_What_is_Russia's_position_on_the_possibility_of_talks_between_Biden_and_Putin?.md',
  'claim_summaries_withcite_dec_1_15.json_What_is_the_current_status_of_the_Russian_air_base_in_Ukraine_and_how_has_it_evolved_over_time?.md',
  'claim_summaries_withcite_dec_1_15.json_What_is_the_long-term_impact_that_the_shelling_in_Nikopol_will_have_on_the_region's_civilians?.md',
  'claim_summaries_withcite_dec_1_15.json_What_kind_of_military_hardware_did_Ukraine_use_to_attack_Melitopol?.md',
  'claim_summaries_withcite_dec_1_15.json_What_measures_are_being_taken_by_the_Ukrainian_military_to_protect_the_community_from_further_shelling?.md',
  'claim_summaries_withcite_dec_1_15.json_What_measures_can_be_taken_by_the_international_community_to_address_the_presence_of_the_Russian_air_base_in_Ukraine?.md',
  'claim_summaries_withcite_dec_1_15.json_What_measures_has_Russia_taken_to_ensure_the_security_of_Russian_air_bases_in_Ukraine?.md',
  'claim_summaries_withcite_dec_1_15.json_What_measures_is_the_US_taking_to_support_Ukraine_in_the_conflict_with_Russia?.md',
  'claim_summaries_withcite_dec_1_15.json_What_other_strategies_could_be_employed_to_reduce_inflows_to_Russian_President_Vladimir_Putin's_war_chest_in_addition_to_retaliating_against_the_oil_price_cap?.md',
  'claim_summaries_withcite_dec_1_15.json_What_potential_risks_does_the_oil_price_cap_pose_to_global_energy_markets?.md',
  'claim_summaries_withcite_dec_1_15.json_What_steps_can_be_taken_to_ensure_that_the_Zaporizhzhia_nuclear_power_plant_is_not_used_as_a_tool_of_political_leverage_by_either_side_in_the_Russia-Ukraine_crisis?.md',
  'claim_summaries_withcite_dec_1_15.json_What_steps_can_be_taken_to_ensure_the_safety_and_security_of_the_Zaporizhzhia_nuclear_power_plant_in_the_context_of_the_Russia-Ukraine_crisis?.md',
  'claim_summaries_withcite_dec_1_15.json_What_was_the_goal_and_strategy_behind_Ukraine's_missile_attack_on_Melitopol?.md',
  'claim_summaries_withcite_dec_1_15.json_What_was_the_purpose_of_the_Russian_shelling_in_Nikopol_during_the_Russia-Ukraine_crisis?.md',
  'claim_summaries_withcite_jan_16_30.json_Are_there_other_forms_of_military_aid_that_the_US_and_Germany_could_provide_to_Ukraine_that_would_be_more_effective_in_deterring_Russian_aggression?.md',
  'claim_summaries_withcite_jan_16_30.json_How_can_the_US_and_Germany_ensure_their_tanks_do_not_become_a_target_of_attack_from_Russian_forces?.md',
  'claim_summaries_withcite_jan_16_30.json_How_did_Andrei_Medvedev_manage_to_cross_the_Norwegian_border_and_seek_asylum?.md',
  'claim_summaries_withcite_jan_16_30.json_How_has_the_Swedish_government_supported_the_IAEA's_mission_in_Ukraine?.md',
  'claim_summaries_withcite_jan_16_30.json_How_has_the_Ukrainian_government_responded_to_the_tragedy_of_the_Brovary_helicopter_crash_near_the_kindergarten_in_Brovary?.md',
  'claim_summaries_withcite_jan_16_30.json_How_has_the_Wagner_group_been_involved_in_the_Russia-Ukraine_conflict?.md',
  'claim_summaries_withcite_jan_16_30.json_How_have_the_Russian_and_Ukrainian_governments_responded_to_the_news_of_Andrei_Medvedev’s_asylum_request?.md',
  'claim_summaries_withcite_jan_16_30.json_How_might_Russia's_war_on_Ukraine_contribute_to_or_impede_the_NATO_bid_process_for_Turkey,_Sweden_and_Finland?.md',
  'claim_summaries_withcite_jan_16_30.json_What_are_the_implications_of_Russia's_control_of_the_Zaporizhzhia_nuclear_power_plant_on_the_security_of_the_region?.md',
  'claim_summaries_withcite_jan_16_30.json_What_are_the_implications_of_the_US_designating_the_Wagner_group_as_a_“transnational_criminal_organization”?.md',
  'claim_summaries_withcite_jan_16_30.json_What_are_the_key_objectives_of_Rafael_Grossi's_visit_to_Ukraine_in_relation_to_the_Russia-Ukraine_crisis?.md',
  'claim_summaries_withcite_jan_16_30.json_What_are_the_legal_implications_of_granting_asylum_to_a_former_Wagner_commander_in_Norway?.md',
  'claim_summaries_withcite_jan_16_30.json_What_are_the_potential_consequences_for_Germany's_security_and_the_regional_security_of_Europe_if_Germany_decides_to_send_tanks_to_Ukraine?.md',
  'claim_summaries_withcite_jan_16_30.json_What_are_the_potential_risks_and_rewards_of_a_successful_NATO_bid_for_Turkey,_Sweden_and_Finland?.md',
  'claim_summaries_withcite_jan_16_30.json_What_caused_the_helicopter_crash_near_the_kindergarten_in_Brovary?.md',
  'claim_summaries_withcite_jan_16_30.json_What_impact_could_the_recent_Quran-burning_incident_have_on_the_NATO_bid_process_for_Turkey,_Sweden_and_Finland?.md',
  'claim_summaries_withcite_jan_16_30.json_What_inquiries_are_being_conducted_into_the_Brovary_helicopter_crash?.md',
  'claim_summaries_withcite_jan_16_30.json_What_is_the_current_status_of_the_IAEA's_presence_in_Ukraine?.md',
  'claim_summaries_withcite_jan_16_30.json_What_is_the_rationale_behind_the_US_and_Germany's_reluctance_to_send_tanks_to_Ukraine?.md',
  'claim_summaries_withcite_jan_16_30.json_What_is_the_role_of_the_US,_UK_and_other_European_countries_in_the_NATO_bid_of_Sweden_and_Finland?.md',
  'claim_summaries_withcite_jan_16_30.json_What_measures_has_the_IAEA_taken_to_ensure_the_safety_of_Ukraine's_nuclear_power_plants?.md',
  'claim_summaries_withcite_jan_16_30.json_What_role_should_NATO_allies_play_in_providing_military_assistance_to_Ukraine?.md',
  'claim_summaries_withcite_jan_16_30.json_What_safety_measures_were_in_place_when_the_Brovary_helicopter_crashed?.md',
  'claim_summaries_withcite_jan_16_30.json_What_steps_does_Turkey_need_to_take_in_order_to_support_Sweden_and_Finland's_bid_for_NATO_membership?.md',
  'claim_summaries_withcite_jan_16_30.json_Who_were_the_other_victims_of_the_Brovary_helicopter_crash,_and_what_were_their_roles_in_the_Ukrainian_government?.md',
  'claim_summaries_withcite_jan_1_15.json_How_did_the_Ukrainian_government_respond_to_the_attack_on_Russian_missile_in_Dnipro?.md',
  'claim_summaries_withcite_jan_1_15.json_How_has_the_Russian_missile_strike_in_Dnipro_impacted_the_ongoing_Russia-Ukraine_conflict?.md',
  'claim_summaries_withcite_jan_1_15.json_How_have_the_Russian_forces_adapted_their_tactics_to_successfully_take_Soledar?.md',
  'claim_summaries_withcite_jan_1_15.json_How_is_the_international_community_responding_to_the_Russian_capture_of_Soledar?.md',
  'claim_summaries_withcite_jan_1_15.json_How_will_the_capture_of_Soledar_affect_the_morale_of_Ukrainian_forces_in_the_region?.md',
  'claim_summaries_withcite_jan_1_15.json_What_are_the_potential_political_and_military_implications_of_a_Russian_capture_of_Soledar_for_Ukraine_and_its_allies?.md',
  'claim_summaries_withcite_jan_1_15.json_What_are_the_strategic_benefits_of_the_capture_of_Soledar_for_the_Wagner_mercenary_group?.md',
  'claim_summaries_withcite_jan_1_15.json_What_kind_of_missile_was_used_and_where_did_the_missile_come_from?.md',
  'claim_summaries_withcite_jan_1_15.json_What_was_the_extent_of_the_damage_caused_by_the_missile_in_Dnipro?.md',
  'claim_summaries_withcite_jan_1_15.json_What_were_the_motives_behind_the_attack_on_Russian_missile_in_Dnipro?.md',
  'claim_summaries_withcite_nov_16_30.json_How_can_the_US_and_its_allies_respond_to_the_Polish_missile_attack_in_Bali_in_a_way_that_de-escalates_tensions_while_still_holding_Russia_accountable_for_its_actions?.md',
  'claim_summaries_withcite_nov_16_30.json_How_has_Russia_responded_to_the_missile_strike_in_Poland?.md',
  'claim_summaries_withcite_nov_16_30.json_How_has_the_energy_infrastructure_in_Ukraine_been_impacted_by_the_ongoing_conflict?.md',
  'claim_summaries_withcite_nov_16_30.json_How_has_the_ongoing_Russia-Ukraine_crisis_impacted_the_operations_of_the_Zaporizhzhia_power_plant?.md',
  'claim_summaries_withcite_nov_16_30.json_What_are_the_implications_of_the_Polish_missile_attack_for_regional_security_in_Europe_and_beyond?.md',
  'claim_summaries_withcite_nov_16_30.json_What_are_the_potential_long-term_impacts_of_the_Russia-Ukraine_crisis_on_nuclear_power_plants_in_the_region?.md',
  'claim_summaries_withcite_nov_16_30.json_What_evidence_exists_to_prove_that_the_Polish_missile_attack_in_Bali_was_launched_from_Russia_or_Ukraine?.md',
  'claim_summaries_withcite_nov_16_30.json_What_measures_can_be_taken_to_ensure_that_further_attacks_of_the_Polish_missile_attack_in_Bali_are_prevented?.md',
  'claim_summaries_withcite_nov_16_30.json_What_role_does_the_International_Atomic_Energy_Agency_(IAEA)_play_in_guaranteeing_the_safety_and_security_of_nuclear_power_plants_in_Ukraine?.md',
  'claim_summaries_withcite_nov_16_30.json_What_steps_have_been_taken_to_secure_the_safety_and_security_of_the_Zaporizhzhia_nuclear_power_plant?.md',
  'claim_summaries_withcite_nov_1_15.json_How_can_Ukraine_ensure_it_is_not_taken_advantage_of_by_Russia_during_peace_talks?.md',
  'claim_summaries_withcite_nov_1_15.json_How_can_the_United_Nations_help_to_ensure_a_lasting_peace_between_Ukraine_and_Russia?.md',
  'claim_summaries_withcite_nov_1_15.json_How_could_Iran's_delivery_of_weapons_to_Russia_affect_the_dynamics_of_the_Russia-Ukraine_crisis?.md',
  'claim_summaries_withcite_nov_1_15.json_How_has_the_G7_responded_to_the_crisis_in_Ukraine_and_what_specific_actions_have_they_taken_to_support_the_country?.md',
  'claim_summaries_withcite_nov_1_15.json_How_has_the_presence_of_Russian_forces_affected_the_daily_lives_of_civilians_in_Melitopol?.md',
  'claim_summaries_withcite_nov_1_15.json_How_is_the_Ukrainian_government_responding_to_the_missile_attacks,_and_what_measures_is_it_taking_to_ensure_the_safety_of_its_citizens?.md',
  'claim_summaries_withcite_nov_1_15.json_How_is_the_international_community_responding_to_the_missile_attacks_on_Ukraine?.md',
  'claim_summaries_withcite_nov_1_15.json_How_will_the_withdrawal_of_Russian_forces_from_the_west_bank_of_the_Dnipro_River_impact_the_Ukraine-Russia_crisis?.md',
  'claim_summaries_withcite_nov_1_15.json_How_would_Russian_use_of_Iranian_missiles_impact_Ukraine's_infrastructure_and_energy_sector?.md',
  'claim_summaries_withcite_nov_1_15.json_What_are_the_motivations_of_Iran_in_sending_missiles_to_Russia?.md',
  'claim_summaries_withcite_nov_1_15.json_What_are_the_objectives_of_the_Ukrainian_military_in_their_push_towards_Kherson_city?.md',
  'claim_summaries_withcite_nov_1_15.json_What_are_the_strategic_goals_of_Russia_in_launching_the_missile_attacks_on_Ukraine?.md',
  'claim_summaries_withcite_nov_1_15.json_What_impact_have_the_power_outages_had_on_the_everyday_lives_of_Ukrainian_citizens?.md',
  'claim_summaries_withcite_nov_1_15.json_What_is_the_Russian_military's_primary_objective_in_occupying_Melitopol?.md',
  'claim_summaries_withcite_nov_1_15.json_What_is_the_cost_associated_with_the_repairs_and_restorations_of_the_power_infrastructure_in_Ukraine?.md',
  'claim_summaries_withcite_nov_1_15.json_What_is_the_international_community's_response_to_the_occupation_of_Melitopol?.md',
  'claim_summaries_withcite_nov_1_15.json_What_is_the_likelihood_of_further_military_action_in_the_region_following_the_Russian_withdrawal_from_Kherson?.md',
  'claim_summaries_withcite_nov_1_15.json_What_is_the_potential_long-term_impact_of_the_power_outages_on_Ukraine's_economy?.md',
  'claim_summaries_withcite_nov_1_15.json_What_is_the_response_of_NATO_to_Iran_sending_missiles_to_Russia?.md',
  'claim_summaries_withcite_nov_1_15.json_What_is_the_role_of_the_US_in_promoting_peace_talks_between_Ukraine_and_Russia?.md',
  'claim_summaries_withcite_nov_1_15.json_What_is_the_strategy_behind_the_Russian_withdrawal_from_Kherson?.md',
  'claim_summaries_withcite_nov_1_15.json_What_measures_can_the_United_States_take_to_prevent_further_shipments_of_weapons_from_Iran_to_Russia?.md',
  'claim_summaries_withcite_nov_1_15.json_What_measures_has_the_Ukrainian_government_taken_to_protect_its_critical_infrastructure_and_power_sources_from_Russian_attacks?.md',
  'claim_summaries_withcite_nov_1_15.json_What_measures_should_the_international_community_take_to_ensure_that_Russia_does_not_use_its_military_power_to_further_destabilize_the_region?.md',
  'claim_summaries_withcite_nov_1_15.json_What_other_steps_is_the_Ukrainian_government_taking_to_secure_sovereignty_in_the_face_of_Russian_aggression_besides_withdrawal_of_Russian_forces_from_the_west_bank_of_the_Dnipro_River?.md',
  'claim_summaries_withcite_nov_1_15.json_What_role_has_NATO_played_in_responding_to_the_missile_attacks_on_Ukraine?.md',
  'claim_summaries_withcite_nov_1_15.json_What_steps_can_be_taken_to_ensure_the_safety_of_civilians_in_the_city_of_Melitopol?.md',
  'claim_summaries_withcite_nov_1_15.json_What_strategies_are_being_used_by_the_Russian_forces_to_protect_the_city_from_further_attack?.md',
  'claim_summaries_withcite_nov_1_15.json_What_strategies_can_Ukraine_employ_to_ensure_that_public_support_for_the_war_effort_does_not_wane?.md',
  'claim_summaries_withcite_nov_1_15.json_What_strategies_can_Ukraine_use_to_ensure_their_territorial_integrity_and_sovereignty_is_respected_in_any_potential_negotiations_with_Russia?.md',
  'claim_summaries_withcite_sept_16_30.json_How_can_the_United_States_best_pressure_Russia_to_engage_in_good_faith_negotiations_for_the_release_of_Paul_Whelan_and_Brittney_Griner?.md',
  'claim_summaries_withcite_sept_16_30.json_How_could_a_Chernobyl-style_disaster_be_prevented_at_the_Zaporizhzhia_nuclear_power_plant?.md',
  'claim_summaries_withcite_sept_16_30.json_How_do_the_American_prisoners_of_war_feel_about_being_released?.md',
  'claim_summaries_withcite_sept_16_30.json_How_have_women_been_affected_by_the_Russia-Ukraine_crisis?.md',
  'claim_summaries_withcite_sept_16_30.json_How_many_of_the_Russian_detained_anti-war_protesters_were_women?.md',
  'claim_summaries_withcite_sept_16_30.json_How_might_Kyiv_and_the_West_respond_to_the_results_of_the_Ukrainian_referendums?.md',
  'claim_summaries_withcite_sept_16_30.json_How_might_the_international_community_react_to_the_Ukrainian_referendums?.md',
  'claim_summaries_withcite_sept_16_30.json_How_were_the_protesters_arrested_in_Russia?.md',
  'claim_summaries_withcite_sept_16_30.json_How_will_the_Finnish_government's_decision_to_restrict_Russian_citizens'_entry_into_the_country_impact_relations_between_Finland_and_Russia?.md',
  'claim_summaries_withcite_sept_16_30.json_How_will_the_closure_of_the_Russian_border_affect_Russian_citizens_who_are_in_transit_to_other_countries?.md',
  'claim_summaries_withcite_sept_16_30.json_What_are_the_Russian_goals_in_holding_the_referendum?.md',
  'claim_summaries_withcite_sept_16_30.json_What_are_the_Ukrainian_objectives_in_preventing_the_referendums_from_taking_place?.md',
  'claim_summaries_withcite_sept_16_30.json_What_are_the_conditions_that_the_American_prisoners_of_war_were_released_under?.md',
  'claim_summaries_withcite_sept_16_30.json_What_are_the_implications_of_Russia's_crackdown_on_anti-war_protesters?.md',
  'claim_summaries_withcite_sept_16_30.json_What_are_the_implications_of_the_Donetsk_referendum_for_the_wider_Russia-Ukraine_conflict?.md',
  'claim_summaries_withcite_sept_16_30.json_What_are_the_implications_of_the_Nord_Stream_pipeline_leaks_for_the_energy_war_between_Europe_and_Russia?.md',
  'claim_summaries_withcite_sept_16_30.json_What_are_the_implications_of_the_Nord_Stream_pipeline_leaks_for_the_security_situation_in_the_Baltic_Sea_region?.md',
  'claim_summaries_withcite_sept_16_30.json_What_are_the_implications_of_the_Russia-Ukraine_conflict_for_nuclear_safety_and_security_in_Europe?.md',
  'claim_summaries_withcite_sept_16_30.json_What_are_the_implications_of_the_results_of_the_Ukrainian_referendums?.md',
  'claim_summaries_withcite_sept_16_30.json_What_are_the_implications_of_the_sabotage_for_the_Russia-Ukraine_conflict?.md',
  'claim_summaries_withcite_sept_16_30.json_What_are_the_possible_motivations_for_sabotaging_the_Nord_Stream_pipelines?.md',
  'claim_summaries_withcite_sept_16_30.json_What_are_the_possible_reasons_for_the_Russian_government's_decision_to_partially_mobilize_its_citizens?.md',
  'claim_summaries_withcite_sept_16_30.json_What_are_the_respective_situations_of_Paul_Whelan_and_Brittney_Griner?.md',
  'claim_summaries_withcite_sept_16_30.json_What_are_the_risks_and_potential_benefits_of_a_prisoner_swap_between_the_United_States_and_Russia?.md',
  'claim_summaries_withcite_sept_16_30.json_What_are_the_risks_associated_with_the_Zaporizhzhia_nuclear_power_plant?.md',
  'claim_summaries_withcite_sept_16_30.json_What_challenges_do_the_American_prisoners_of_war_face_as_they_return_home?.md',
  'claim_summaries_withcite_sept_16_30.json_What_has_been_the_effect_of_the_Russia-Ukraine_crisis_on_relations_between_Russia_and_the_West?.md',
  'claim_summaries_withcite_sept_16_30.json_What_is_the_US_government's_position_on_the_case_of_Brittney_Griner?.md',
  'claim_summaries_withcite_sept_16_30.json_What_is_the_likelihood_that_the_Donetsk_referendum_will_lead_to_an_actual_change_in_status_for_the_Donetsk_region?.md',
  'claim_summaries_withcite_sept_16_30.json_What_is_the_reason_for_the_increased_number_of_Russians_crossing_the_border_into_Finland?.md',
  'claim_summaries_withcite_sept_16_30.json_What_is_the_significance_of_the_Zaporizhzhia_nuclear_power_plant?.md',
  'claim_summaries_withcite_sept_16_30.json_What_is_the_status_of_efforts_to_secure_the_release_of_Paul_Whelan_and_Brittney_Griner?.md',
  'claim_summaries_withcite_sept_16_30.json_What_motivated_Russia_to_annex_Crimea?.md',
  'claim_summaries_withcite_sept_16_30.json_What_motivated_the_US_government_to_get_involved_in_the_prisoner_exchange_between_Russia_and_Ukraine?.md',
  'claim_summaries_withcite_sept_16_30.json_What_role_did_Saudi_Arabia_play_in_the_prisoner_exchange_between_Russia_and_Ukraine?.md',
  'claim_summaries_withcite_sept_16_30.json_What_was_the_government's_response_to_the_protests_in_Russia?.md',
  'claim_summaries_withcite_sept_16_30.json_Who_are_the_likely_suspects_in_the_Nord_Stream_pipeline_sabotage?.md',
  'claim_summaries_withcite_sept_16_30.json_Why_is_the_Zaporizhzhia_nuclear_power_plant_a_target_for_Russia?.md',
  'claim_summaries_withcite_sept_1_15.json_Can_Ukrainian_forces_sustain_momentum_and_drive_the_Russians_out_of_Luhansk?.md',
  'claim_summaries_withcite_sept_1_15.json_How_could_the_price_cap_on_Russian_oil_be_effective?.md',
  'claim_summaries_withcite_sept_1_15.json_How_has_the_Russia-Ukraine_crisis_affected_the_safety_of_the_Zaporizhzhia_nuclear_plant?.md',
  'claim_summaries_withcite_sept_1_15.json_How_might_the_Russian_government_respond_to_the_growing_dissent_of_deputies_calling_for_Putin's_impeachment?.md',
  'claim_summaries_withcite_sept_1_15.json_How_will_the_Russians_react_to_the_new_offensive_against_Lysychansk?.md',
  'claim_summaries_withcite_sept_1_15.json_What_are_the_Russian_supply_lines_to_parts_of_occupied_Luhansk_region?.md',
  'claim_summaries_withcite_sept_1_15.json_What_are_the_challenges_faced_by_the_IAEA_in_conducting_its_inspection_of_the_Zaporizhzhia_nuclear_plant?.md',
  'claim_summaries_withcite_sept_1_15.json_What_are_the_implications_of_increasing_dissent_among_municipal_deputies_in_Russia?.md',
  'claim_summaries_withcite_sept_1_15.json_What_are_the_implications_of_the_IAEA_report_on_the_Zaporizhzhia_nuclear_power_plant's_condition?.md',
  'claim_summaries_withcite_sept_1_15.json_What_are_the_long-term_implications_of_the_deputies'_actions_for_Russian_politics?.md',
  'claim_summaries_withcite_sept_1_15.json_What_are_the_motivations_of_the_deputies_who_are_calling_for_Putin's_impeachment?.md',
  'claim_summaries_withcite_sept_1_15.json_What_are_the_next_steps_for_the_IAEA_team_of_inspectors_at_the_Zaporizhzhia_nuclear_plant?.md',
  'claim_summaries_withcite_sept_1_15.json_What_are_the_risks_of_a_nuclear_accident_at_the_Zaporizhzhia_nuclear_power_plant?.md',
  'claim_summaries_withcite_sept_1_15.json_What_are_the_risks_of_an_accident_at_the_plant?.md',
  'claim_summaries_withcite_sept_1_15.json_What_is_the_goal_of_the_price_cap?.md',
  'claim_summaries_withcite_sept_1_15.json_What_is_the_goal_of_the_price_cap_on_Russian_oil?.md',
  'claim_summaries_withcite_sept_1_15.json_What_is_the_potential_impact_of_a_nuclear_accident_at_the_Zaporizhzhia_nuclear_plant?.md',
  'claim_summaries_withcite_sept_1_15.json_What_is_the_potential_impact_of_the_deputies'_actions_on_the_Russia-Ukraine_crisis?.md',
  'claim_summaries_withcite_sept_1_15.json_What_is_the_primary_reason_for_the_G7_meeting?.md',
  'claim_summaries_withcite_sept_1_15.json_What_is_the_reason_for_Britain's_Chancellor_of_the_Exchequer_Nadeem_Zahawi_to_be_in_the_US?.md',
  'claim_summaries_withcite_sept_1_15.json_What_is_the_role_of_the_International_Atomic_Energy_Agency_at_the_Zaporizhzhia_nuclear_power_plant?.md',
  'claim_summaries_withcite_sept_1_15.json_What_is_the_role_of_the_Zaporizhzhia_nuclear_power_plant_in_the_Russia-Ukraine_conflict?.md',
  'claim_summaries_withcite_sept_1_15.json_What_is_the_significance_of_Svatove_in_the_conflict?.md',
  'claim_summaries_withcite_sept_1_15.json_What_is_the_significance_of_the_city_of_Lysychansk?.md',
  'claim_summaries_withcite_sept_1_15.json_What_is_the_status_of_the_nuclear_power_plant?.md'
]

export class PagesService {
  static formatTitle(filename) {
    // Remove .md extension
    let title = filename.replace('.md', '')
    
    // Extract question part after .json_
    const parts = title.split('.json_')
    if (parts.length > 1) {
      title = parts[1]
    }
    
    // Replace underscores with spaces and decode
    title = decodeURIComponent(title.replace(/_/g, ' '))
    
    // Clean up
    title = title.replace(/\?/g, '')
    
    return title
  }

  static async getAllPages() {
    return PAGE_FILES.map(filename => ({
      filename,
      title: this.formatTitle(filename),
      category: this.getCategory(filename)
    }))
  }

  static getCategory(filename) {
    if (filename.includes('gpt4_cite_feb_')) return 'Turkey-Syria Earthquake (Feb)'
    if (filename.includes('withcite_dec_')) return 'Ukraine Analysis (Dec)'
    if (filename.includes('withcite_jan_')) return 'Ukraine Analysis (Jan)'
    if (filename.includes('withcite_nov_')) return 'Ukraine Analysis (Nov)'
    if (filename.includes('withcite_sept_')) return 'Ukraine Analysis (Sept)'
    if (filename.includes('withcite_oct_')) return 'Ukraine Analysis (Oct)'
    return 'General Analysis'
  }

  static async loadPageContent(filename) {
    try {
      const response = await axios.get(`/pages/${filename}`)
      return response.data
    } catch (error) {
      console.error('Error loading page content:', error)
      throw new Error('Failed to load document content')
    }
  }

  static markdownToHtml(markdown) {
    // Basic markdown to HTML conversion
    // For production, consider using a proper markdown parser like marked.js
    return markdown
      .replace(/^### (.*$)/gim, '<h3>$1</h3>')
      .replace(/^## (.*$)/gim, '<h2>$1</h2>')
      .replace(/^# (.*$)/gim, '<h1>$1</h1>')
      .replace(/^\* (.*$)/gim, '<li>$1</li>')
      .replace(/^\- (.*$)/gim, '<li>$1</li>')
      .replace(/\*\*(.*?)\*\*/gim, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/gim, '<em>$1</em>')
      .replace(/`(.*?)`/gim, '<code>$1</code>')
      .replace(/\n\n/gim, '</p><p>')
      .replace(/\n/gim, '<br>')
      .replace(/^/, '<p>')
      .replace(/$/, '</p>')
      .replace(/<p><\/p>/gim, '')
      .replace(/<p>(<h[1-6]>)/gim, '$1')
      .replace(/(<\/h[1-6]>)<\/p>/gim, '$1')
      .replace(/<p>(<li>)/gim, '<ul>$1')
      .replace(/(<\/li>)<\/p>/gim, '$1</ul>')
  }

  static searchPages(pages, query) {
    if (!query.trim()) return pages
    
    const searchTerm = query.toLowerCase()
    return pages.filter(page => 
      page.title.toLowerCase().includes(searchTerm) ||
      page.category.toLowerCase().includes(searchTerm)
    )
  }

  static getPagesByCategory(pages) {
    const categories = {}
    pages.forEach(page => {
      if (!categories[page.category]) {
        categories[page.category] = []
      }
      categories[page.category].push(page)
    })
    return categories
  }
}

export default PagesService