# How does the proximity of the epicenter to the border with Syria affect the regional seismic activity and potential cross-border impacts following the main quake in southern Turkey?

## Summary
The 7.8 magnitude earthquake that struck southern Turkey has had major cross-border impacts, with the epicenter's proximity to the Syrian border influencing regional seismic activity <font color=#FF3399>[1,2]</font>. The aftershocks have been felt over a stretch of more than 300 kilometers along the fault zone that ruptured in southern Turkey, extending from the border with Syria up through the province of Malatya <font color=#FF3399>[1,2]</font>. The United States Geological Survey has reported at least 43 significant aftershocks of 4.3 or greater magnitude that were felt in the earthquake zone, including a massive 7.5 magnitude earthquake north of the epicenter <font color=#FF3399>[2]</font>. This seismic activity has led to considerable destruction in both Turkey and Syria, with over 2,000 homes destroyed in Turkey and the extent of devastation in Syria yet to be determined <font color=#FF3399>[3]</font>. The continual aftershocks present people with the difficult choice of returning to potentially unstable homes or seeking shelter elsewhere, with severe cold weather further exacerbating the situation <font color=#FF3399>[3]</font>. In addition to the damage in Turkey, the earthquake and subsequent aftershocks have resulted in at least 1,451 deaths in Syria, particularly affecting the regions of Aleppo, Hama, Latakia, and Tartus (5

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> The aftershocks stretch for more than 300 kilometers (186 miles) along the fault zone that ruptured in southern Turkey, oriented from southwest to northeast and stretching from the border with Syria up through the province of Malatya.<a href="https://www.cnn.com/middleeast/live-news/turkey-earthquake-latest-020623/h_eedc589e2eb33110889e3b1191e13cee" target="_blank">Source</a>| At least 100 aftershocks measuring 4.0 or greater have occurred since the 7.8 magnitude earthquake struck southern Turkey on Monday morning local time, according to the United States Geological Survey. As the time from the original earthquake extends, the frequency and magnitude of the aftershocks tend to decrease.However, 5.0 to 6.0-plus aftershocks are still likely to occur and bring a risk of additional damage to structures that are compromised from the original earthquake.This brings a continued threat to rescue teams and survivors. The aftershocks stretch for more than 300 kilometers (186 miles) along the fault zone that ruptured in southern Turkey, oriented from southwest to northeast and stretching from the border with Syria up through the province of Malatya.|
|<font color=#FF3399>[2]</font> The aftershocks stretch for more than 300 kilometers (about 186 miles) along the fault zone that ruptured in southern Turkey oriented from southwest to northeast and stretching from the border with Syria up through the province of Malatya.<a href="https://www.cnn.com/middleeast/live-news/turkey-earthquake-latest-020623/h_4a110263beaf94827b0998a15d8d799d" target="_blank">Source</a>| Separately, the United States Geological Survey (USGS), which only reports the more significant aftershocks that are actually felt by those in the earthquake zone, reported at least 43 aftershocks of 4.3 or greater magnitude. Three of the aftershocks measured 6.0 or greater, including the massive 7.5 magnitude earthquake that struck 95 kilometers (59 miles) north of the epicenter of the morning's main quake, according to USGS. The aftershocks stretch for more than 300 kilometers (about 186 miles) along the fault zone that ruptured in southern Turkey oriented from southwest to northeast and stretching from the border with Syria up through the province of Malatya.|
|<font color=#FF3399>[3]</font> Severe cold weather has only made matters worse with temperatures dropping below freezing at night, increasing the risk of hypothermia, and hampering relief efforts.<a href="https://reliefweb.int/report/turkiye/massive-earthquake-has-hit-turkiye-turkey-and-syria-killing-over-five-thousand-people-injuring-many-thousands-more-and-devastating-entire-communities" target="_blank">Source</a>| Over 2,000 homes have been destroyed in Trkiye (Turkey) and the scale of the devastation in Syria is yet to emerge. In addition, significant aftershocks continue to be felt across both countries meaning people have to face the agonizing choice of returning to homes that may collapse in an aftershock or seeking shelter elsewhere. Severe cold weather has only made matters worse with temperatures dropping below freezing at night, increasing the risk of hypothermia, and hampering relief efforts. How Were Responding|
|<font color=#FF3399>[4]</font> The frequency and magnitude of the aftershocks are decreasing as is expected as we get further out in the time from the original earthquake.However, 5.0 to 6.0+ aftershocks are still possible and bring a risk of additional damage to structures that are compromised from the original earthquake.This brings a continued threat to rescue teams and survivors.<a href="https://www.cnn.com/middleeast/live-news/turkey-syria-earthquake-updates-2-7-23-intl/h_a9e1d082dd54c67187fd51322f95eaf2" target="_blank">Source</a>| At least 125 aftershocks measuring 4.0 or greater have occurred since the 7.8 magnitude earthquake struck southern Turkey on Monday morning local time, according to the United States Geological Survey. The frequency and magnitude of the aftershocks are decreasing as is expected as we get further out in the time from the original earthquake.However, 5.0 to 6.0+ aftershocks are still possible and bring a risk of additional damage to structures that are compromised from the original earthquake.This brings a continued threat to rescue teams and survivors. The aftershocks stretch for more than 400 kilometers (or about 250 miles) along the fault zone that ruptured in southern Turkey, oriented from southwest to northeast and stretching from the Mediterranean Sea off the northern coast of Syria up through the province of Malatya.|
|<font color=#FF3399>[5]</font> In neighboring Syria, at least 1,451 people have died.<a href="https://www.cnn.com/2023/02/05/europe/earthquake-hits-turkey-intl-hnk/index.html" target="_blank">Source</a>| One of the strongest earthquakes to hit the region in a century shook residents from their beds at around 4 a.m. on Monday, sending tremors as far away as Lebanon and Israel. In Turkey, at least 2,921 people were killed and more than 15,800 others injured, according to Turkeys head of disaster services, Yunus Sezer. In neighboring Syria, at least 1,451 people have died. According to the Syrian state news agency SANA, 711 people have died across government-controlled areas, mostly in the regions of Aleppo, Hama, Latakia, and Tartus.|
