# How did the Christian Atsu earthquake affect Atsu's professional career and personal life in the immediate aftermath of the earthquake?

## Summary
Christian Atsu, a Ghanaian international soccer player, was reported missing after a series of devastating earthquakes hit parts of Turkey and Syria, impacting both his professional career and personal life <font color=#FF3399>[1]</font><font color=#FF3399>[4]</font>. Atsu, who played for Turkish Super Lig club Hatayspor, was believed to have been in a collapsed building in the southern Turkish city of Antakya, in the Hatay province <font color=#FF3399>[2]</font>. This news came just after Atsu had celebrated scoring a last minute winner for his club's home league game, emphasizing the sudden shock of the disaster <font color=#FF3399>[3]</font>. However, the player was eventually found alive and was reported to be in a "stable" condition at a local hospital after a successful rescue operation from the rubble of the collapsed building <font color=#FF3399>[3]</font><font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Ghanaian soccer star Christian Atsu is still missing after the earthquakes that wrought massive devastation across parts of Turkey and Syria.<a href="https://www.marketwatch.com/story/soccer-star-christian-atsu-still-missing-after-turkey-earthquakes-i-still-pray-and-believe-that-hes-alive-says-partner-cfd47272" target="_blank">Source</a>| Ghanaian soccer star Christian Atsu is still missing after the earthquakes that wrought massive devastation across parts of Turkey and Syria. The former Chelsea, Newcastle and Everton star plays for Turkish Super Lig club Hatayspor in the city of Antakya in southern Turkey.|
|<font color=#FF3399>[2]</font> Ghana international soccer player Christian Atsu remains missing more than a week after the deadly earthquakes which struck Turkey, his agent said Tuesday.<a href="https://www.cbsnews.com/news/ghanian-footballer-christian-atsu-missing-turkey-earthquakes/" target="_blank">Source</a>| Ghana international soccer player Christian Atsu remains missing more than a week after the deadly earthquakes which struck Turkey, his agent said Tuesday. Atsu was believed to have been in a building which collapsed in the southern Turkish city of Antakya, in the Hatay province, his Turkish club, Hatayspor, previously reported.|
|<font color=#FF3399>[3]</font> Ghana soccer star Christian Atsu is in a "stable" condition at a local hospital after being successfully rescued from the rubble of a collapsed building after a powerful earthquake struck southern Turkey on Monday, his agent, Nana Sechere, told CNN Tuesday.<a href="https://www.cnn.com/middleeast/live-news/turkey-syria-earthquake-updates-2-7-23-intl/h_a5316e0649982f84d9e98c2746564574" target="_blank">Source</a>| Ghana soccer star Christian Atsu is in a "stable" condition at a local hospital after being successfully rescued from the rubble of a collapsed building after a powerful earthquake struck southern Turkey on Monday, his agent, Nana Sechere, told CNN Tuesday. Atsu, who plays for Hatayspor in Turkey, had been celebrating on Sunday night after he scored a last minute winner in his club's 1-0 home league game against Kasimpasa, his agent said.|
|<font color=#FF3399>[4]</font> Ghanaian soccer player Christian Atsu is still missing, days after two massive earthquakes struck Turkey and Syria.<a href="https://www.okayafrica.com/christian-atsu-turkey-earthquake/" target="_blank">Source</a>| Ghanaian soccer player Christian Atsu is still missing, days after two massive earthquakes struck Turkey and Syria. Volkan Demirel, the manager of Turkish football club Hataysporthe team Atsu plays forconfirmed the news to Reuters on Wednesday.|
|<font color=#FF3399>[5]</font> International football player Christian Atsu has been found alive and is in "stable condition" at a local hospital following Monday's earthquake in southern Turkey, the Ghana Football Association and Atsu's agent said on Tuesday.<a href="https://www.cnn.com/middleeast/live-news/turkey-syria-earthquake-updates-2-8-23-intl/h_2633dc9faa0364bcbe83ffc8bbfdf3be" target="_blank">Source</a>| International football player Christian Atsu has been found alive and is in "stable condition" at a local hospital following Monday's earthquake in southern Turkey, the Ghana Football Association and Atsu's agent said on Tuesday. Atsu's agent, Nana Sechere, told CNN on Tuesday that his client was in a "stable" condition at a local hospital after being successfully rescued from the rubble of a collapsed building.|
