# How are global leaders from the US, Israel, India, Pakistan, and Ukraine responding to the disaster in Turkey and what kind of support have they pledged?

## Summary
Global leaders from the US, Israel, India, Pakistan, and Ukraine have offered condolences and pledged to support Turkey in the aftermath of a devastating earthquake <font color=#FF3399>[1]</font>. The U.S Department of State is coordinating all U.S. government support to Turkey, with the U.S. Ambassador to Turkey, Jeffry Flake, greeting USAID’s Disaster Assistance Response Team at Incirlik Air Base as they provided the initial wave of humanitarian aid <font color=#FF3399>[2]</font>. Furthermore, specialized search and rescue teams from the United States have been activated by the U.S. Agency for International Development to assist in the rescue efforts <font color=#FF3399>[4]</font>. Other nations, such as the Netherlands, have also pledged to send search and rescue teams in response to Turkey's call for international help <font color=#FF3399>[3]</font>. Mexico is contributing to the rescue efforts by sending a team of 16 search and rescue dogs <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Global support: Leaders from the US, Israel, India, Pakistan and Ukraine are among countries to offer condolences and pledge support following the disaster.<a href="https://www.cnn.com/middleeast/live-news/turkey-earthquake-latest-020623/h_1e001e3c6dd2f40f226875fd19efac72" target="_blank">Source</a>| Germany is ready to provide assistance to Turkey and Syria after a powerful earthquake rocked the region early Monday, its foreign minister said. Global support: Leaders from the US, Israel, India, Pakistan and Ukraine are among countries to offer condolences and pledge support following the disaster. The Netherlands said it will send a search and rescue team to Turkey after the country's disaster agency asked the international community for help.|
|<font color=#FF3399>[2]</font> Ambassador to Trkiye, visited Incirlik Air Base to greet USAIDs DART as they provided the first wave of humanitarian support.<a href="https://www.incirlik.af.mil/News/Article-Display/Article/3292036/urban-search-and-rescue-teams-arrive-at-incirlik-air-base/" target="_blank">Source</a>| The U.S. Department of State via the U.S. Mission to Trkiye coordinates all U.S. government support to the Turkish government and the people affected by the earthquake. Jeffry Flake, U.S. Ambassador to Trkiye, visited Incirlik Air Base to greet USAIDs DART as they provided the first wave of humanitarian support. "Over the past several years, Trkiye has responded to natural disasters in more than 50 countries on five continents and now, the world is returning the favor, with more than 70 countries offering assistance," said Flake.|
|<font color=#FF3399>[3]</font> Turkey'sDisaster and Emergency Management Agency (AFAD) earlier called on the international community for help with search and rescue efforts.<a href="https://www.cnn.com/middleeast/live-news/turkey-earthquake-latest-020623/h_d5379cd77c9c5bb7f2c21b64101f1d8c" target="_blank">Source</a>| The Netherlands will send a search and rescue team to Turkey to assist in the response to the earthquake that has left hundreds dead, Dutch Foreign Minister Wopke Hoekstra said on Monday. Turkey'sDisaster and Emergency Management Agency (AFAD) earlier called on the international community for help with search and rescue efforts.|
|<font color=#FF3399>[4]</font> Activated by the U.S. Agency for International Development (USAID), which is a government agency leading international development and humanitarian efforts, these U.S. teams will work in coordination with others on the ground to provide rapid aid to the people of Turkey.<a href="https://news.caloes.ca.gov/california-sends-highly-specialized-search-and-rescue-unit-to-support-efforts-in-wake-of-turkey-earthquake/" target="_blank">Source</a>| "These US&R-trained professional firefighters will use their highly technical skills to assist in search and rescue efforts." This team from Los Angeles will join a team from Fairfax County Fire and Rescue Department in Virginia, known as USA-1, as the two teams who will lend aid on behalf of the United States. Activated by the U.S. Agency for International Development (USAID), which is a government agency leading international development and humanitarian efforts, these U.S. teams will work in coordination with others on the ground to provide rapid aid to the people of Turkey. About the earthquake|
|<font color=#FF3399>[5]</font> Mexico is sending its beloved search and rescue dogs to Turkey, to help find survivors in the rubble following Mondays devastating earthquake that toppled thousands of buildings in the country.<a href="https://www.cnn.com/2023/02/07/americas/mexico-rescue-dogs-turkey-intl-latam/index.html" target="_blank">Source</a>| CNN Mexico is sending its beloved search and rescue dogs to Turkey, to help find survivors in the rubble following Mondays devastating earthquake that toppled thousands of buildings in the country. At least 16 dogs, alongside their handlers, took off on Tuesday for Turkey, according to Marcelo Ebrard, Mexicos Foreign Affairs Secretary.|
