# How do the death and injury tolls compare between government-controlled and rebel-held areas in Syria following the quakes?

## Summary
The death and injury tolls following the earthquakes in Syria have varied between government-controlled and rebel-held areas. In government-controlled parts of Syria, 1,262 deaths were reported (Context 3), increasing to 1,408 (Context 1) and later 1,347 (Context 4). In contrast, rebel-held areas in the northwest of Syria reported higher figures, with 2,168 deaths initially (Context 1), which climbed to 2,030 (Context 4). The death toll in Syria overall increased to 3,377 (Context 4). Regarding injuries, the number of people injured in Syria across all territories, both government-controlled and rebel-held, rose to 5,108 (Context 3), and later to 5,245 (Context 4). It was noted that the number of injured people in both types of territories was relatively similar, with 2,295 in government-controlled and 2,950 in rebel-held areas (Context 4).

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> In Syria, the total number of deaths stands at 3,576, including 2,168 in rebel-held areas in the northwest, according to the "White Helmets" civil defense group, and 1,408 deaths in government-controlled parts of Syria, according to Syrian state media citing the health ministry on Saturday.<a href="https://www.cnn.com/2023/02/12/middleeast/deaths-turkey-syria-earthquake-intl/index.html" target="_blank">Source</a>| The latest figures show that 33,181 have died across both countries. The death toll in Turkey has climbed to 29,605, Turkish Emergency Coordination Center SAKOM said Sunday. In Syria, the total number of deaths stands at 3,576, including 2,168 in rebel-held areas in the northwest, according to the "White Helmets" civil defense group, and 1,408 deaths in government-controlled parts of Syria, according to Syrian state media citing the health ministry on Saturday. The White Helmets, who announced the end of their search and rescue operations on Friday, told CNN on Saturday that the total number of dead was expected to rise much higher.|
|<font color=#FF3399>[2]</font> In Syria, the total number of deaths now stands at 2,802, including 1,540 in rebel-held areas in the northwest, according to the "White Helmets," and 1,262 deaths in government-controlled parts of Syria, Health Minister Dr. Hassan al-Ghobash announced, according to Syrian state media.<a href="https://www.cnn.com/middleeast/live-news/turkey-syria-earthquake-updates-2-8-23-intl/h_812c6e105cef2056469b14d607847b9a" target="_blank">Source</a>| The death toll from the devastating earthquake that hit Turkey and Syria has reached at least11,376, according to authorities. In Turkey, the death toll has risen to at least 8,574, with nearly 50,000 others reported injured, Turkish President Recep Tayyip Erdogan said in a televised briefing Wednesday, during a visit to disaster areas near the epicenter of Monday's earthquake. In Syria, the total number of deaths now stands at 2,802, including 1,540 in rebel-held areas in the northwest, according to the "White Helmets," and 1,262 deaths in government-controlled parts of Syria, Health Minister Dr. Hassan al-Ghobash announced, according to Syrian state media. The total number of injured people in Syria across all affected territories rose to 5,008 [2,258 in government-controlled and 2,750 in the rebel-held area].|
|<font color=#FF3399>[3]</font> The total number of injured people in Syria across all affected territories rose to 5,108, in both rebel and government-held areas.<a href="https://www.cnn.com/middleeast/live-news/turkey-syria-earthquake-updates-2-8-23-intl/h_7a2a3aa890c610382695423b907e7612" target="_blank">Source</a>| At least 1,262 deaths are in government-controlled parts of Syria, according to Syrian state media. The total number of people killed in Turkey now stands at least 9,057 with 52,979 others reported injured, according to Turkish President Recep Tayyip Erdogan. The total number of injured people in Syria across all affected territories rose to 5,108, in both rebel and government-held areas. At least 58,087 people have been injured in both Syria and Turkey,according to figures from the Turkish government, the White Helmets and Syrian state media.|
|<font color=#FF3399>[4]</font> The total number of injured people in Syria across all affected territories rose to 5,245, with 2,295 in government-controlled areas and 2,950 in rebel-held areas.<a href="https://www.cnn.com/middleeast/live-news/turkey-syria-earthquake-updates-2-9-23-intl/h_9865832cc9c7030643795648506c0089" target="_blank">Source</a>| The total number of deaths in Syria climbed to 3,377, including 2,030 in rebel-held areas in the northwest, according to the White Helmets civil defense group. An additional 1,347 deaths were reported in government-controlled parts of Syria, according to Syrian state media. The total number of injured people in Syria across all affected territories rose to 5,245, with 2,295 in government-controlled areas and 2,950 in rebel-held areas. At least 75,592 people have been injured in Syria and Turkey overall, according to figures from the Turkish government, the White Helmets and Syrian state media.|
|<font color=#FF3399>[5]</font> In Syria, already devastated by nearly 12 years of civil war, more than 3,300 people have died, according to the government and a rescue service in the rebel-held northwest.<a href="https://www.reuters.com/world/middle-east/death-toll-syria-turkey-quake-rises-more-than-8700-2023-02-08/" target="_blank">Source</a>| Authorities say some 6,500 buildings in Turkey collapsed and countless more were damaged. The death toll in Turkey rose to 17,406, Health Minister Fahrettin Koca said. In Syria, already devastated by nearly 12 years of civil war, more than 3,300 people have died, according to the government and a rescue service in the rebel-held northwest. In the devastated Syrian town of Jandaris, Ibrahim Khalil Menkaween walked in the rubble-strewn streets clutching a white body bag.|
