# How do the aftershocks impact the rescue operations and the survivors of the 7.8 magnitude earthquake in southern Turkey?

## Summary
The 7.8 magnitude earthquake in southern Turkey has resulted in a series of dangerous aftershocks, complicating rescue efforts and heightening the risk for survivors (Context 3). The United States Geological Survey has reported over 100 aftershocks measuring 4.0 or greater, with the frequency and magnitude of these aftershocks expected to decrease over time (Context 3). However, substantial aftershocks ranging from 5.0 to 6.0+ are still likely to occur, posing a risk of additional damage to structures already compromised by the original earthquake and presenting an ongoing threat to rescue teams and survivors (Context 3, Context 4). The aftershocks have spanned more than 300 kilometers along the fault zone that ruptured in southern Turkey, stretching from the border with Syria up through the province of Malatya (Context 3). This large area of impact has further challenged rescue operations, as over 2,000 homes in Turkey have been destroyed and the scale of devastation in Syria is yet to emerge (Context 1). The severe cold weather has exacerbated the situation, with below-freezing temperatures at night increasing the risk of hypothermia and hindering relief efforts (Context 1).

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Severe cold weather has only made matters worse with temperatures dropping below freezing at night, increasing the risk of hypothermia, and hampering relief efforts.<a href="https://reliefweb.int/report/turkiye/massive-earthquake-has-hit-turkiye-turkey-and-syria-killing-over-five-thousand-people-injuring-many-thousands-more-and-devastating-entire-communities" target="_blank">Source</a>| Over 2,000 homes have been destroyed in Trkiye (Turkey) and the scale of the devastation in Syria is yet to emerge. In addition, significant aftershocks continue to be felt across both countries meaning people have to face the agonizing choice of returning to homes that may collapse in an aftershock or seeking shelter elsewhere. Severe cold weather has only made matters worse with temperatures dropping below freezing at night, increasing the risk of hypothermia, and hampering relief efforts. How Were Responding|
|<font color=#FF3399>[2]</font> Rescuers are now racing against time and the elements to pull survivors out from under debris on both sides of the border.<a href="https://www.cnn.com/2023/02/07/middleeast/earthquake-turkey-syria-why-deadly-intl/index.html" target="_blank">Source</a>| A magnitude 6.7 aftershock followed 11 minutes after the first quake hit, but the largest temblor, which measured 7.5 in magnitude, struck about nine hours later. More than 125 aftershocks have been recorded so far. Rescuers are now racing against time and the elements to pull survivors out from under debris on both sides of the border. More than 5,700 buildings in Turkey have collapsed, according to the countrys disaster agency.|
|<font color=#FF3399>[3]</font> As the time from the original earthquake extends, the frequency and magnitude of the aftershocks tend to decrease.However, 5.0 to 6.0-plus aftershocks are still likely to occur and bring a risk of additional damage to structures that are compromised from the original earthquake.This brings a continued threat to rescue teams and survivors.<a href="https://www.cnn.com/middleeast/live-news/turkey-earthquake-latest-020623/h_eedc589e2eb33110889e3b1191e13cee" target="_blank">Source</a>| At least 100 aftershocks measuring 4.0 or greater have occurred since the 7.8 magnitude earthquake struck southern Turkey on Monday morning local time, according to the United States Geological Survey. As the time from the original earthquake extends, the frequency and magnitude of the aftershocks tend to decrease.However, 5.0 to 6.0-plus aftershocks are still likely to occur and bring a risk of additional damage to structures that are compromised from the original earthquake.This brings a continued threat to rescue teams and survivors. The aftershocks stretch for more than 300 kilometers (186 miles) along the fault zone that ruptured in southern Turkey, oriented from southwest to northeast and stretching from the border with Syria up through the province of Malatya.|
|<font color=#FF3399>[4]</font> The frequency and magnitude of the aftershocks are decreasing as is expected as we get further out in the time from the original earthquake.However, 5.0 to 6.0+ aftershocks are still possible and bring a risk of additional damage to structures that are compromised from the original earthquake.This brings a continued threat to rescue teams and survivors.<a href="https://www.cnn.com/middleeast/live-news/turkey-syria-earthquake-updates-2-7-23-intl/h_a9e1d082dd54c67187fd51322f95eaf2" target="_blank">Source</a>| At least 125 aftershocks measuring 4.0 or greater have occurred since the 7.8 magnitude earthquake struck southern Turkey on Monday morning local time, according to the United States Geological Survey. The frequency and magnitude of the aftershocks are decreasing as is expected as we get further out in the time from the original earthquake.However, 5.0 to 6.0+ aftershocks are still possible and bring a risk of additional damage to structures that are compromised from the original earthquake.This brings a continued threat to rescue teams and survivors. The aftershocks stretch for more than 400 kilometers (or about 250 miles) along the fault zone that ruptured in southern Turkey, oriented from southwest to northeast and stretching from the Mediterranean Sea off the northern coast of Syria up through the province of Malatya.|
|<font color=#FF3399>[5]</font> At least 77 aftershocks measuring 4.0 or greater have occurred since a magnitude 7.8 earthquake struck southern Turkey Monday morning local time, according to the United States Geological Survey.<a href="https://www.cnn.com/middleeast/live-news/turkey-earthquake-latest-020623/h_5745a89a155a3581fb376620f76a6df2" target="_blank">Source</a>| At least 77 aftershocks measuring 4.0 or greater have occurred since a magnitude 7.8 earthquake struck southern Turkey Monday morning local time, according to the United States Geological Survey. Three of the aftershocks have measured 6.0 or greater, including a magnitude 7.5 earthquake that struck 95 kilometers (59 miles) north of the epicenter of the main quake.|
