# What are the key characteristics and specialties of the Czech Republic's USAR team being deployed to Turkey?

## Summary
The Czech Republic is dispatching a 68-person specialized Urban Search and Rescue (USAR) team to Turkey to aid in the aftermath of an earthquake <font color=#FF3399>[1]</font>. The team is fully equipped and trained for operations that include finding and pulling people out of rubble, utilizing search and rescue dog units and medical personnel <font color=#FF3399>[1]</font>. The USAR team specializes in earthquake search and rescue operations <font color=#FF3399>[1]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> An official from the fire service said the USAR (Urban Search and Rescue) team specializes in earthquake search and rescue, and is fully equipped and trained for operations that include finding and pulling people out of rubble.<a href="https://www.cnn.com/middleeast/live-news/turkey-earthquake-latest-020623/h_40a86c5f97f8bf0d483e6ecb1f5a66f9" target="_blank">Source</a>| The Czech Republic is sending a 68-person specialized search and rescue team to Turkey following a request for help from the Turkish side, the Fire Rescue services of the Czech Republic said Monday. An official from the fire service said the USAR (Urban Search and Rescue) team specializes in earthquake search and rescue, and is fully equipped and trained for operations that include finding and pulling people out of rubble. The teams include search and rescue dog units and medical personnel.|
|<font color=#FF3399>[2]</font> Activated by the U.S. Agency for International Development (USAID), which is a government agency leading international development and humanitarian efforts, these U.S. teams will work in coordination with others on the ground to provide rapid aid to the people of Turkey.<a href="https://news.caloes.ca.gov/california-sends-highly-specialized-search-and-rescue-unit-to-support-efforts-in-wake-of-turkey-earthquake/" target="_blank">Source</a>| "These US&R-trained professional firefighters will use their highly technical skills to assist in search and rescue efforts." This team from Los Angeles will join a team from Fairfax County Fire and Rescue Department in Virginia, known as USA-1, as the two teams who will lend aid on behalf of the United States. Activated by the U.S. Agency for International Development (USAID), which is a government agency leading international development and humanitarian efforts, these U.S. teams will work in coordination with others on the ground to provide rapid aid to the people of Turkey. About the earthquake|
|<font color=#FF3399>[3]</font> They train for all types of rescues, are highly skilled, and they are all volunteers.<a href="https://www.nbclosangeles.com/news/local/la-county-sheriffs-members-help-rescue-mother-and-son-from-rubble-in-turkey/3094318/" target="_blank">Source</a>| they flew out of here on this past Thursday," Ruiz said. The team will be in Turkey for one week. They train for all types of rescues, are highly skilled, and they are all volunteers. "Keep in mind this personnel doesnt get paid, they do it out of the kindness of their heart.|
|<font color=#FF3399>[4]</font> The 728th Air Mobility Squadron stationed at Incirlik AB supported the U.S. Government efforts in receiving a deployment of USAIDs Disaster Assistance Response Team (DART), a specialized quick reaction force of experts in the disaster and recovery field to integrate with and support Turkish authorities.<a href="https://www.incirlik.af.mil/News/Article-Display/Article/3292036/urban-search-and-rescue-teams-arrive-at-incirlik-air-base/" target="_blank">Source</a>| Two Urban Search and Rescue (USAR) teams and a critical aid package in support of U.S. Agency for International Development (USAID) response operations arrived by aircraft at Incirlik Air Base, Trkiye, Feb. 8, to provide humanitarian assistance to Trkiye following devastating earthquakes that occurred on Feb. 6. In coordination with U.S. Transportation Command (USTRANSCOM), U.S. European Command (USEUCOM) and U.S. Air Forces in Europe (USAFE), 161 USAR personnel, 12 military working dogs and approximately 170,000 lb (77,000 kg) of humanitarian purposed equipment arrived to Incirlik AB on two Air Force C-17 Globemaster III aircraft. The 728th Air Mobility Squadron stationed at Incirlik AB supported the U.S. Government efforts in receiving a deployment of USAIDs Disaster Assistance Response Team (DART), a specialized quick reaction force of experts in the disaster and recovery field to integrate with and support Turkish authorities. The DART will assess the situation, identify priority humanitarian needs, and assist with search and rescue.|
|<font color=#FF3399>[5]</font> Fairfax County's Urban Search and Rescue Team has been dispatched to assist in the rescue efforts following the 7.8 magnitude earthquake that struck eastern Turkey and neighboring Syria Monday.<a href="https://www.fox5dc.com/news/turkey-earthquake-fairfax-county-urban-search-and-rescue-team-deployed-to-help" target="_blank">Source</a>| Fairfax County's Urban Search and Rescue Team has been dispatched to assist in the rescue efforts following the 7.8 magnitude earthquake that struck eastern Turkey and neighboring Syria Monday. The team consists of 79 members and six dogs.|
