# How did Christian Atsu's presence in Turkey during the earthquake influence international attention and response to the disaster?

## Summary
Christian Atsu, a Ghanaian soccer star who plays for Turkish Super Lig club Hatayspor, was reported missing following a devastating earthquake in Turkey and Syria, which drew international attention to the disaster (Context 2). His presence in the disaster area and the subsequent search for him united the football world in prayers for his safety (Context 1). After a successful rescue, Atsu was reported to be in a stable condition in a local hospital, news that was widely disseminated by his agent, Nana Sechere (Context 3). Prior to his move to Turkey, Atsu had played for several English clubs, which further amplified the international interest in the disaster (Context 4). His rescue was confirmed by his agent and the Ghanaian Football Association, providing some relief amidst the tragedy that had killed over 19,000 people and injured tens of thousands (Context 5).

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Atsu, who plays for Turkish side Hatayspor, was trapped under the rubble together with the clubs sporting director Taner Savut.<a href="https://www.pulse.com.gh/sports/football/christian-atsu-players-wife-says-she-believes-hes-still-alive/xtrx1wj" target="_blank">Source</a>| Atsu, who plays for Turkish side Hatayspor, was trapped under the rubble together with the clubs sporting director Taner Savut. Both are still yet to be found, with the football world uniting in praying for their safety and rescue from beneath the rubble.|
|<font color=#FF3399>[2]</font> Ghanaian soccer star Christian Atsu is still missing after the earthquakes that wrought massive devastation across parts of Turkey and Syria.<a href="https://www.marketwatch.com/story/soccer-star-christian-atsu-still-missing-after-turkey-earthquakes-i-still-pray-and-believe-that-hes-alive-says-partner-cfd47272" target="_blank">Source</a>| Ghanaian soccer star Christian Atsu is still missing after the earthquakes that wrought massive devastation across parts of Turkey and Syria. The former Chelsea, Newcastle and Everton star plays for Turkish Super Lig club Hatayspor in the city of Antakya in southern Turkey.|
|<font color=#FF3399>[3]</font> Ghana soccer star Christian Atsu is in a "stable" condition at a local hospital after being successfully rescued from the rubble of a collapsed building after a powerful earthquake struck southern Turkey on Monday, his agent, Nana Sechere, told CNN Tuesday.<a href="https://www.cnn.com/middleeast/live-news/turkey-syria-earthquake-updates-2-7-23-intl/h_a5316e0649982f84d9e98c2746564574" target="_blank">Source</a>| Ghana soccer star Christian Atsu is in a "stable" condition at a local hospital after being successfully rescued from the rubble of a collapsed building after a powerful earthquake struck southern Turkey on Monday, his agent, Nana Sechere, told CNN Tuesday. Atsu, who plays for Hatayspor in Turkey, had been celebrating on Sunday night after he scored a last minute winner in his club's 1-0 home league game against Kasimpasa, his agent said.|
|<font color=#FF3399>[4]</font> Teams are racing to rescue survivors as aid agencies warn that new snowfall, as well as a lack of water, communications and power, could cause a deadly "secondary disaster."<a href="https://www.cnn.com/2023/02/09/football/christian-atsu-turkey-earthquake-update-spt-intl/index.html" target="_blank">Source</a>| Prior to joining Hatayspor last year, Atsu represented several different English clubs, including Chelsea, Everton, Bournemouth and Newcastle. More than 19,000 people have been killed and tens of thousands injured after the magnitude 7.8 earthquake struck Turkey and Syria on Monday, officials said. Teams are racing to rescue survivors as aid agencies warn that new snowfall, as well as a lack of water, communications and power, could cause a deadly "secondary disaster."|
|<font color=#FF3399>[5]</font> Later the Ghanaian Football Association also tweeted that Atsu had "been successfully rescued from the rubble of the collapsed building and is receiving treatment."<a href="https://www.nbcnews.com/news/world/soccer-star-christian-atsu-remains-missing-turkey-earthquake-rcna69984" target="_blank">Source</a>| Ghanaian winger Christian Atsu, who starred for Chelsea, Newcastle United and several other teams in the English Premier League, had been reported safe by his agent Nana Sechere on Tuesday. Sechere tweeted that officials at Atsus current club Hatayspor, who play in Turkeys top Super Lig, had told him that Atsu had been "pulled out of the rubble alive." Later the Ghanaian Football Association also tweeted that Atsu had "been successfully rescued from the rubble of the collapsed building and is receiving treatment." Christian Atsu in Newcastle upon Tyne, England, in January 2021.|
