# What were the circumstances leading up to Christian Atsu's experience during the earthquake in Turkey?

## Summary
Christian Atsu, a Ghanaian footballer who plays for Hatayspor in Turkey, was in the southern city of Antakya when a series of devastating earthquakes struck the region <font color=#FF3399>[3]</font>. The former Chelsea, Newcastle, and Everton star had been celebrating a recent victory in which he scored the winning goal <font color=#FF3399>[1]</font>. Atsu was believed to be inside a building that collapsed during the tremors <font color=#FF3399>[2]</font>. He and Hatayspor's sporting director Taner Savut, who were both in the building at the time of the earthquake, remain missing <font color=#FF3399>[4]</font>. Despite initial reports that Atsu had been successfully rescued and was in a stable condition at a local hospital, his agent later reversed this claim, stating his whereabouts were still unknown <font color=#FF3399>[1, 5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Ghana soccer star Christian Atsu is in a "stable" condition at a local hospital after being successfully rescued from the rubble of a collapsed building after a powerful earthquake struck southern Turkey on Monday, his agent, Nana Sechere, told CNN Tuesday.<a href="https://www.cnn.com/middleeast/live-news/turkey-syria-earthquake-updates-2-7-23-intl/h_a5316e0649982f84d9e98c2746564574" target="_blank">Source</a>| Ghana soccer star Christian Atsu is in a "stable" condition at a local hospital after being successfully rescued from the rubble of a collapsed building after a powerful earthquake struck southern Turkey on Monday, his agent, Nana Sechere, told CNN Tuesday. Atsu, who plays for Hatayspor in Turkey, had been celebrating on Sunday night after he scored a last minute winner in his club's 1-0 home league game against Kasimpasa, his agent said.|
|<font color=#FF3399>[2]</font> Ghana international soccer player Christian Atsu remains missing more than a week after the deadly earthquakes which struck Turkey, his agent said Tuesday.<a href="https://www.cbsnews.com/news/ghanian-footballer-christian-atsu-missing-turkey-earthquakes/" target="_blank">Source</a>| Ghana international soccer player Christian Atsu remains missing more than a week after the deadly earthquakes which struck Turkey, his agent said Tuesday. Atsu was believed to have been in a building which collapsed in the southern Turkish city of Antakya, in the Hatay province, his Turkish club, Hatayspor, previously reported.|
|<font color=#FF3399>[3]</font> Ghanaian soccer star Christian Atsu is still missing after the earthquakes that wrought massive devastation across parts of Turkey and Syria.<a href="https://www.marketwatch.com/story/soccer-star-christian-atsu-still-missing-after-turkey-earthquakes-i-still-pray-and-believe-that-hes-alive-says-partner-cfd47272" target="_blank">Source</a>| Ghanaian soccer star Christian Atsu is still missing after the earthquakes that wrought massive devastation across parts of Turkey and Syria. The former Chelsea, Newcastle and Everton star plays for Turkish Super Lig club Hatayspor in the city of Antakya in southern Turkey.|
|<font color=#FF3399>[4]</font> Atsu, who plays for Turkish side Hatayspor, was trapped under the rubble together with the clubs sporting director Taner Savut.<a href="https://www.pulse.com.gh/sports/football/christian-atsu-players-wife-says-she-believes-hes-still-alive/xtrx1wj" target="_blank">Source</a>| Atsu, who plays for Turkish side Hatayspor, was trapped under the rubble together with the clubs sporting director Taner Savut. Both are still yet to be found, with the football world uniting in praying for their safety and rescue from beneath the rubble.|
|<font color=#FF3399>[5]</font> The agent of Ghanaian soccer starChristian Atsusays the player's whereabouts are still not known, reversing course just a few days after tellingCNN Sportthat the Hatayspor winger was rescued from rubble after being caught inthe earthquakes that struck southern Turkey.<a href="https://www.cnn.com/middleeast/live-news/turkey-syria-earthquake-updates-2-10-23-intl/h_65bb9329733c2185ccb1ec393be943c2" target="_blank">Source</a>| The agent of Ghanaian soccer starChristian Atsusays the player's whereabouts are still not known, reversing course just a few days after tellingCNN Sportthat the Hatayspor winger was rescued from rubble after being caught inthe earthquakes that struck southern Turkey. On Wednesday, Secheretweetedthat it had come to light, contrary to prior reports, that Atsu was still missing.|
