# What is the likelihood that the Donetsk referendum will lead to an actual change in status for the Donetsk region?

## Summary
The likelihood that the referendum in Donetsk, which is part of Donbas and partially occupied by the Russian military, will lead to an actual change in status for the region is high. Russian President Vladimir Putin has already announced the incorporation of Donetsk, Luhansk, Kherson and Zaporizhia into Russia after the pro-Russian referendums (1). These referendums have been slammed by Kyiv and the West as illegal since international observers and the Ukrainian government expressed similar concerns in 2014, when Russia annexed Crimea after a referendum carried out in the presence of Russian troops (2). Results so far have shown overwhelming support from the people, with over 98% voting in favor of the measure in Donetsk, 93% in Zaporizhia, and 87% in Kherson (3). Former President Dmitry Medvedev has said that folding the regions into Russia itself would make redrawn frontiers "irreversible" (4). As the referendums are expected to go Moscow's way, the votes are unlikely to be recognized by Western governments (5).

## Claims
| Claim Sentence | Context |
|---|---|
|Some context: Authorities in Kyiv and other Western countries say that the referendums are a "sham" whose outcome has been preordained, and which are carried out often literally at the barrel of a gun.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-26-22/h_5dc9dc391f9bbe7aa8c4e0da6961b676" target="_blank">Source</a>| Donetsk, which is a part of Donbas, is partially occupied by the Russian military. As Russian forces continue to advance through the Donbas region, pro-Russian leaders in Donetsk and Luhansk are holding referendums on joining Russia. Some context: Authorities in Kyiv and other Western countries say that the referendums are a "sham" whose outcome has been preordained, and which are carried out often literally at the barrel of a gun. International observers and the Ukrainian government expressed similar concerns in 2014 when Russia unilaterally annexed Crimea after a referendum carried out in the presence of Russian troops.|
|President Vladimir Putin announces incorporation of Donetsk, Luhansk, Kherson and Zaporizhia into Russia after referendums slammed by Kyiv and the West as illegal.<a href="https://www.aljazeera.com/news/2022/9/21/mapping-the-ukraine-regions-voting-on-joining-russia" target="_blank">Source</a>| President Vladimir Putin announces incorporation of Donetsk, Luhansk, Kherson and Zaporizhia into Russia after referendums slammed by Kyiv and the West as illegal. Russia has formally announce the annexation of four partially occupied provinces of eastern and southern Ukraine.|
|The referendums are widely viewed as an initial Kremlin move toward formal Russian annexation of the territories, even as the exact timetable remains unclear.<a href="https://www.npr.org/2022/09/27/1125322026/russia-ukraine-referendums" target="_blank">Source</a>| Ukraine and its international partners have dismissed the highly controversial referendums as shams and a violation of international law. The Russian-run referendum votes took place over five days, from Sept. 23 through Sept. 27, despite international outrage. The referendums are widely viewed as an initial Kremlin move toward formal Russian annexation of the territories, even as the exact timetable remains unclear. Results reported Tuesday by Russian state media allegedly showed over 98% voting in favor of the measure in the self-proclaimed Donetsk and Luhansk People's Republics; while 93% voted for it in the Zaporizhzhia region and 87% in the Kherson region.|
|The votes, in territory Russia already controls, are expected with near-certainty to go Moscows way but are unlikely to be recognized by Western governments backing Ukraine with military and other support.<a href="https://www.pbs.org/newshour/world/separatist-controlled-areas-in-ukraine-to-vote-on-joining-russia" target="_blank">Source</a>| The announcements of referendums starting Friday in the Donetsk, Luhansk, Kherson and partly Russian-controlled Zaporizhzhia regions came after a close ally of Russian President Vladimir Putin said votes were needed, as Moscow loses ground in the war that began nearly seven months ago. Former President Dmitry Medvedev said folding regions into Russia itself would make redrawn frontiers "irreversible" and enable Moscow to use "any means" to defend them. The votes, in territory Russia already controls, are expected with near-certainty to go Moscows way but are unlikely to be recognized by Western governments backing Ukraine with military and other support. Luhansk and Donetsk together form much of the Donbas region, which has been gripped by separatist fighting since 2014 and which Putin has set as a primary objective of the Russian invasion.|
|The Russian-backed authorities in Ukraine's Donetsk region much of which is still controlled by Ukraine claimed Monday that turnout so far has been 77%.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-26-22/h_ab82b45b2adfb24bf462f5f39ee4f12b" target="_blank">Source</a>| International observers and the Ukrainian government expressed similar concerns in 2014, when Russia unilaterally annexed Crimea after a referendum carried out in the presence of Russian troops. In the Kherson region, the deputy head of the Russian-backed administration said Monday that there is already enough of a margin to say that that region has approved seceding from Ukraine and joining Russia. The Russian-backed authorities in Ukraine's Donetsk region much of which is still controlled by Ukraine claimed Monday that turnout so far has been 77%. Russian-backed authorities in the Luhansk region said that it is already 76.09%.|
