# What is the US government's position on the case of Brittney Griner?

## Summary
The US government regards Brittney Griner and Paul Whelan as wrongfully detained and is working relentlessly to secure their release (2). Secretary of State Antony Blinken took the unusual step of announcing two months ago that the administration had made a substantial proposal to Russia to negotiate their release (3). However, so far Russia has not responded to this proposal (4, 5). The US is also urging Russia to put forward a serious counteroffer, but has not yet received a response (4).

## Claims
| Claim Sentence | Context |
|---|---|
|The U.S. government regards both as wrongfully detained, placing their cases with the office of its top hostage negotiator.<a href="https://www.fox5vegas.com/2022/09/16/biden-meeting-with-families-whelan-griner-white-house/" target="_blank">Source</a>| She was sentenced last month to nine years in prison after pleading guilty and has appealed the punishment. Whelan is serving a 16-year sentence on espionage-related charges that he and his family say are false. The U.S. government regards both as wrongfully detained, placing their cases with the office of its top hostage negotiator. Secretary of State Antony Blinken took the unusual step of announcing two months ago that the administration had made a substantial proposal to Russia.|
|The U.S. government regards both as wrongfully detained.<a href="https://www.ny1.com/nyc/all-boroughs/news/2022/09/20/biden-griner-whelan-jake-sullivan-russia-us" target="_blank">Source</a>| She has since appealed the sentence. Whelan is serving a 16-year sentence on espionage-related charges that he and his family say are false. The U.S. government regards both as wrongfully detained. Secretary of State Antony Blinken took the unusual step of announcing two months ago that the administration had made a substantial proposal to Russia.|
|US Secretary of State Antony Blinken said the administration is working relentlessly to secure the release of Americans detained abroad, including Brittney Griner and Paul Whelan, who are being held in Russia.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-16-22/h_64f2c56f9c985bb3bf07b0398adba77e" target="_blank">Source</a>| US Secretary of State Antony Blinken said the administration is working relentlessly to secure the release of Americans detained abroad, including Brittney Griner and Paul Whelan, who are being held in Russia. Speaking at a news conference Friday, Blinken said the matter is "at the very top of my priority list."|
|Where the negotiations stand: A senior administration official told CNN Thursday that there has been "movement but not breakthrough" on the efforts to free Whelan and WNBA star Brittney Griner.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-17-22/h_4392813436930e3a6c7e2faf703a3705" target="_blank">Source</a>| Paul Whelan has been imprisoned in Russia for more than three years after being convicted on espionage charges that he vehemently denies. He was sentenced in June 2020 to 16 years in prison in a trial US officials denounced as unfair. Where the negotiations stand: A senior administration official told CNN Thursday that there has been "movement but not breakthrough" on the efforts to free Whelan and WNBA star Brittney Griner. The official said that the United States has urged Russia to put forward "a serious counteroffer" to the proposal on the table to secure the release of the two, but "we've not gotten a serious response back."|
|National Security Council coordinator John Kirby says Russia has not responded to the "substantial proposal" the U.S. offered back in July regarding the release of WNBA star Brittney Griner and former U.S. Marine Paul Whelan.<a href="https://www.foxnews.com/sports/russia-responded-us-offer-regarding-brittney-griner-paul-whelan-release-biden-administration-says" target="_blank">Source</a>| National Security Council coordinator John Kirby says Russia has not responded to the "substantial proposal" the U.S. offered back in July regarding the release of WNBA star Brittney Griner and former U.S. Marine Paul Whelan. Kirby told the media during Fridays White House press briefing that the U.S. has made a "serious offer" to negotiate the return of Griner and Whelan, but added that those discussions are "still ongoing."|
