# What goals does Ukraine hope to achieve through military force?

## Summary
Ukraine hopes to achieve multiple goals through the use of military force, most notably the recapture of its territory, and to end the Russian blockade on Ukrainian exports (3,5). By accepting cryptocurrency donations, the Ministry of Digital Transformation has raised over $100 million for its humanitarian aid and military programs (1). In addition, the agreement made in Istanbul enabled the resumption of vital grain exports from Ukrainian Black Sea ports, resulting in the export of over 9 million tons of grains (5). Finally, the call-up of British specialists to lead the Ukrainian armed forces is a further indication of Ukraine's commitment to achieving its goals (2).

## Claims
| Claim Sentence | Context |
|---|---|
|The nations Ministry of Digital Transformation is currently in charge of the fund, which was set up in conjunction with Kuna, FTX and Everstake to buttress Ukraines humanitarian aid and military programs.<a href="https://cointelegraph.com/news/what-the-russia-ukraine-conflict-has-revealed-about-crypto" target="_blank">Source</a>| The Russia-Ukraine conflict has shown that cryptocurrencies can be used for fundraising in military conflicts. Notably, the Ukrainian government began accepting crypto donations at the beginning of the year in a bid to enhance donor inclusivity, and this led to the creation of the Crypto Fund of Ukraine. The nations Ministry of Digital Transformation is currently in charge of the fund, which was set up in conjunction with Kuna, FTX and Everstake to buttress Ukraines humanitarian aid and military programs. The project has enabled the Ukrainian government to raise over $100 million in cryptocurrency donations so far.|
|It said the move was "in connection with the actions of the Ukrainian armed forces, which were led by British specialists" and that these actions "were directed... against Russian ships that ensured the functioning of the said humanitarian corridor".<a href="https://www.bbc.com/news/world-europe-63439760" target="_blank">Source</a>| It said the move was "in connection with the actions of the Ukrainian armed forces, which were led by British specialists" and that these actions "were directed... against Russian ships that ensured the functioning of the said humanitarian corridor".|
|Artillerymen of Ukraine's Armed Forces destroy the Russian invaders with the help of the German 155-mm FH70 howitzer, Zaporizhzhia Region, southeastern Ukraine.<a href="https://www.cbsnews.com/news/russia-invasion-ukraine-signs-unraveling/" target="_blank">Source</a>| The call-up followed weeks of embarrassing setbacks for Russian forces, as Ukraine has retaken swaths of its territory. And in the Russian-occupied city of Kherson, officials appointed by Moscow have evacuated civilians ahead of another expected Ukrainian counter-offensive. Artillerymen of Ukraine's Armed Forces destroy the Russian invaders with the help of the German 155-mm FH70 howitzer, Zaporizhzhia Region, southeastern Ukraine. Oct. 27, 2022.|
|Although the grain deals primary goal was to end Russias blockade on Ukrainian exports, which had been contributing to a global food crisis, it also allowed for more shipments of Russian grain and fertilizer.<a href="https://www.nytimes.com/live/2022/10/29/world/russia-ukraine-war-news" target="_blank">Source</a>| "Now Moscow uses a false pretext to block the grain corridor which ensures food security for millions of people," he wrote on Twitter. "I call on all states to demand Russia to stop its hunger games and recommit to its obligations." Although the grain deals primary goal was to end Russias blockade on Ukrainian exports, which had been contributing to a global food crisis, it also allowed for more shipments of Russian grain and fertilizer. As part of the deal, the United States and the European Union gave assurances that banks and companies involved in trading Russian grain and fertilizer would be exempt from sanctions.|
|Some background: In July, Ukraine and Russia agreed to the deal that allowed the resumption of vital grain exports from Ukrainian Black Sea ports, a major diplomatic breakthrough at the time, aimed at easing a global food crisis sparked by the war.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-28-22/index.html" target="_blank">Source</a>| "The impact of the agreement signed in Istanbul has been clearly demonstrated. Exports of grains and other food products under the Black Sea Grain Initiative have surpassed 9 million tonnes," Guterres said in a statement Friday. Some background: In July, Ukraine and Russia agreed to the deal that allowed the resumption of vital grain exports from Ukrainian Black Sea ports, a major diplomatic breakthrough at the time, aimed at easing a global food crisis sparked by the war. Ministers from both countries signed an agreement brokered by the United Nations and Turkey in Istanbul.|
