# What are the goals of each side in the conflict?

## Summary
The conflict between Russia and Ukraine has been ongoing since 2014, when Moscow illegally annexed Crimea. Since then, the two countries have been in a state of political tension, with each side trying to achieve different goals. Russia is attempting to force Ukraine and the West to negotiate, while Ukraine is trying to end the Russian blockade on Ukrainian exports (1) and secure the safe shipment of grains and fertilizer through the Black Sea Grain Initiative (4). Meanwhile, the United States and the European Union have attempted to intervene by giving assurances that banks and companies involved in trading Russian grain and fertilizer would be exempt from sanctions (3).

## Claims
| Claim Sentence | Context |
|---|---|
|However, the Russia-Ukraine conflict has demonstrated that its possible for regional blocs and major jurisdictions to impose bans and exert control over cryptocurrencies.<a href="https://cointelegraph.com/news/what-the-russia-ukraine-conflict-has-revealed-about-crypto" target="_blank">Source</a>| Governments can limit crypto Satoshi Nakamoto, the pseudonymous creator of Bitcoin (BTC), developed the first cryptocurrency in order to devolve the control of money away from governments and centralized financial institutions. However, the Russia-Ukraine conflict has demonstrated that its possible for regional blocs and major jurisdictions to impose bans and exert control over cryptocurrencies. In October, the European Commission announced sweeping sanctions targeting Russian crypto custodial wallets under the control of European enterprises and exchanges.|
|"The key takeaway is that there are no pristine Russian military units that can fight in Ukraine because theyve already done so and theyve all been degraded," Barros said, adding that Putins drive to mobilize more fighters would not prove that helpful.<a href="https://www.cnn.com/2022/10/28/europe/ukraine-russia-war-winter-intl-cmd/index.html" target="_blank">Source</a>| Thats when the mud season begins," Barros said. Another reason for Ukraine to step up its counteroffensive is the state of the Russian military, which has been severely depleted over the past eight months. "The key takeaway is that there are no pristine Russian military units that can fight in Ukraine because theyve already done so and theyve all been degraded," Barros said, adding that Putins drive to mobilize more fighters would not prove that helpful. "Pulling in all these men is not actually going to generate effective combat power, because theyre not receiving adequate training and theyre not receiving adequate supply," Haring said.|
|Although the grain deals primary goal was to end Russias blockade on Ukrainian exports, which had been contributing to a global food crisis, it also allowed for more shipments of Russian grain and fertilizer.<a href="https://www.nytimes.com/live/2022/10/29/world/russia-ukraine-war-news" target="_blank">Source</a>| "Now Moscow uses a false pretext to block the grain corridor which ensures food security for millions of people," he wrote on Twitter. "I call on all states to demand Russia to stop its hunger games and recommit to its obligations." Although the grain deals primary goal was to end Russias blockade on Ukrainian exports, which had been contributing to a global food crisis, it also allowed for more shipments of Russian grain and fertilizer. As part of the deal, the United States and the European Union gave assurances that banks and companies involved in trading Russian grain and fertilizer would be exempt from sanctions.|
|Ukraine's defense minister told CBS News Russia is exhausted, and trying to force Ukraine and the West to negotiate.<a href="https://www.cbsnews.com/news/russia-invasion-ukraine-signs-unraveling/" target="_blank">Source</a>| "I'm not guaranteeing you that it's a false flag operation yet, don't know," said President Joe Biden. "But it would be a serious, serious mistake." Ukraine's defense minister told CBS News Russia is exhausted, and trying to force Ukraine and the West to negotiate. In a bizarre speech this week, Putin railed against the West, including gay pride parades and so-called cancel culture.|
|The agreement facilitates the safe shipment of grains and fertilizer from Ukraine.<a href="https://www.washingtonpost.com/world/2022/10/29/russia-ukraine-war-latest-updates/" target="_blank">Source</a>| Sevastopol is the largest city in Crimea, which was illegally annexed by Moscow in 2014. U.N. Secretary General Antnio Guterres on Friday urged participating countries to allow a renewal of the Black Sea Grain Initiative, which is set to expire Nov. 19. The agreement facilitates the safe shipment of grains and fertilizer from Ukraine. Many countries, particularly which is set to expire Nov. 19.The agreement facilitates the safe shipment of grains and fertilizer from Ukraine.|
