# How might the Ukrainian government respond if Russia does indeed leave the Black Sea Grain Initiative?

## Summary
The Ukrainian government is likely to strongly condemn Russia if it does leave the Black Sea Grain Initiative. They have accused Russia of creating a "hunger games" (2) by blocking the grain export deal, which has brought down global food prices (1). Ukraine has denied the alleged drone attack (4), which Russia used as a pretext for leaving the agreement (3). Ukrainian Foreign Minister Dmytro Kuleba has called on other states to demand Russia to recommit to its obligations and to stop its "hunger games" (5).

## Claims
| Claim Sentence | Context |
|---|---|
|Russia announced Saturday that it will move to suspend its implementation of a U.N.-brokered grain deal that has seen more than 9 million tons of grain exported from Ukraine during the war and has brought down soaring global food prices.<a href="https://www.fox9.com/news/russia-suspending-ukraine-grain-export-deal" target="_blank">Source</a>| Russia announced Saturday that it will move to suspend its implementation of a U.N.-brokered grain deal that has seen more than 9 million tons of grain exported from Ukraine during the war and has brought down soaring global food prices. The Russian Defense Ministry cited an alleged Ukrainian drone attack against Russias Black Sea Fleet ships moored off the coast of occupied Crimea, which Russia says took place early Saturday, as the reason for the move.|
|Later,President Vladimir Putin weighed in, saying Russia would shut the export corridors if they are used to carry out "terrorist attacks."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-23-22/h_1fb0f92038712fb60caf322afa4d3e84" target="_blank">Source</a>| But in recent weeks, Russia has complained that part of the agreement allowing for the export of its agricultural products and fertilizer, is not being upheld. Gennady Gatilov, Russia's ambassador to the UN in Geneva, said last week that Moscow could leave the deal,according to Reuters. Later,President Vladimir Putin weighed in, saying Russia would shut the export corridors if they are used to carry out "terrorist attacks."|
|Later,President Vladimir Putin weighed in, saying Russia would shut the export corridors if they are used to carry out "terrorist attacks."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-21-22/h_1529f74d286c70462cee902ad309acd8" target="_blank">Source</a>| The agreement ended five months of a Russian blockade, allowing ships carrying grain from Ukrainian ports in Odesa to navigate a safe corridor through the Black Sea, helping alleviate global food shortages. Gennady Gatilov, Russia's ambassador to the UN in Geneva, said last week that Moscow could leave the deal,according to Reuters. Later,President Vladimir Putin weighed in, saying Russia would shut the export corridors if they are used to carry out "terrorist attacks."|
|Ukraine has denied the attack, saying that the Russians mishandled their own weapons.<a href="https://apnews.com/article/russia-ukraine-europe-government-and-politics-3b563bd6f79f815c7e9f33505dd25334" target="_blank">Source</a>| Ukraine accused Russia of creating a world "hunger games." The Russian Defense Ministry cited an alleged Ukrainian drone attack Saturday against Russias Black Sea Fleet ships moored off the coast of occupied Crimea as the reason for the move. Ukraine has denied the attack, saying that the Russians mishandled their own weapons. The Russian declaration came one day after U.N. chief Antonio Guterres urged Russia and Ukraine to renew the grain export deal, which was scheduled to expire on Nov. 19.|
|"I call on all states to demand Russia to stop its hunger games and recommit to its obligations."<a href="https://www.cnbc.com/2022/10/29/russia-halts-participation-in-the-black-sea-grain-initiative.html" target="_blank">Source</a>| Ukrainian Foreign Minister Dmytro Kuleba said Russia was using the attack as a "false pretext" for blocking the "grain corridor which ensures food security for millions of people." "We have warned of Russia's plans to ruin the Black Sea Grain Initiative," Kuleba wrote in a tweet. "I call on all states to demand Russia to stop its hunger games and recommit to its obligations." Before the war, Ukraine and Russia accounted for almost a quarter of global grain exports until those shipments came to a severe halt for nearly six months.|
