# What role did Saudi Arabia play in the prisoner exchange between Russia and Ukraine?

## Summary
Saudi Arabia played a key role in negotiating a prisoner exchange between Russia and Ukraine that saw the release of 10 foreign nationals. (1) This included two Americans, Alexander Drueke and Andy Huynh, who were captured in June while fighting in Ukraine's Kharkiv province. (3) The prisoner exchange was brokered by the Saudi government, and the freed fighters included five British citizens, two Americans, a Croatian, a Moroccan, and a Swedish national. (2) Huynh's fiancée said it was "amazing" to hear his voice again, and the two men arrived back in the US on Friday. (4, 5)

## Claims
| Claim Sentence | Context |
|---|---|
|Saudi Crown Prince Mohammed bin Salman reportedly mediated between Ukraine and Russia for the release of the 10 foreign nationals.<a href="https://www.coffeeordie.com/ukrainian-pows-prisoners-war" target="_blank">Source</a>| Captured by Russian forces while serving in defense of the Azovstal steel factory redoubt in Mariupol, Gustavsson described his captors as "pure sadist psychos." He faced the death penalty after a Russian occupation court in the city of Donetsk charged him last month with being a mercenary. Saudi Crown Prince Mohammed bin Salman reportedly mediated between Ukraine and Russia for the release of the 10 foreign nationals. Those freed fighters included five British citizens, two Americans, a Croatian, a Moroccan and Gustavsson.|
|Five British citizens who were held by Russian-backed forces for months were also released as part of the prisoner swap, which was brokered by Saudi Arabia.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-24-22/h_6d98d13e1b46c46ab22556d646c17287" target="_blank">Source</a>| Their pro-Russian captors, the self-declared Donetsk People's Republic, has governed a breakaway portion of Ukraine's Donetsk region since 2014. Even after being captured, their families say the men have no regrets about going over to fight with the Ukrainians. Five British citizens who were held by Russian-backed forces for months were also released as part of the prisoner swap, which was brokered by Saudi Arabia. And three prisoners who are Moroccan, Swedish and Croatian nationals were released in the swap, the Saudi Ministry of Foreign Affairs said.|
|Two American vets captured this summer while fighting alongside the Ukrainian military were released on Wednesday part of a deal brokered by Saudi Arabia to free 10 foreigners held by the Kremlin.<a href="https://nypost.com/2022/09/21/russia-frees-us-prisoners-of-war-after-saudi-mediation/" target="_blank">Source</a>| Two American vets captured this summer while fighting alongside the Ukrainian military were released on Wednesday part of a deal brokered by Saudi Arabia to free 10 foreigners held by the Kremlin. Alexander Drueke, 39, and Andy Huynh, 27, were captured in June during a fierce firefight in Ukraines Kharkiv province.|
|Huynh and another American, Alexander John-Robert Drueke, were captured in June while fighting in Ukraine.They were released, along with eight others, in a prisoner swap between Russia and Ukraine that was spearheaded by the government of Saudi Arabia.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-21-22/h_c83a75febe02691c43ed6a21646b8130" target="_blank">Source</a>| It was her first conversation with Huynh since June 8. "It was just so amazing to finally get to hear his voice again and speak to him," she said. Huynh and another American, Alexander John-Robert Drueke, were captured in June while fighting in Ukraine.They were released, along with eight others, in a prisoner swap between Russia and Ukraine that was spearheaded by the government of Saudi Arabia. "It's just so good to know that they are OK and that they're going to come home," Black said.|
|Alexander John-Robert Drueke and Andy Tai Ngoc Huynh arrived in New York City after they were released earlier this week in a prisoner swap between Russia and Ukraine that was brokered by Saudi Arabia.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-23-22/h_38b11d717816e5c7faa251a50c93d19d" target="_blank">Source</a>| Two Americans who had been held by Russian-backed forces in Ukraine formore than threemonthswere back on US soil on Friday. Alexander John-Robert Drueke and Andy Tai Ngoc Huynh arrived in New York City after they were released earlier this week in a prisoner swap between Russia and Ukraine that was brokered by Saudi Arabia. CNN obtained a selfie of the two men.|
