# What challenges do the Nobel Peace Prize winners face in their work?

## Summary
The 2022 Nobel Peace Prize has been awarded to human rights campaigners in Ukraine, Russia and Belarus, in recognition of their outstanding effort to document war crimes, human rights abuses and abuse of power in their respective countries (1). However, the winners face a number of challenges in their work, such as the difficulty of achieving justice (1), the lack of readiness to use the documentation of war crimes (4, 5) and the even greater risk of nuclear disaster due to the Russian invasion of Ukraine (3).

## Claims
| Claim Sentence | Context |
|---|---|
|Matviichuk and her colleagues at CCL are well familiar with the difficulties of trying to achieve justice.<a href="https://www.washingtonpost.com/world/2022/10/14/ukrainian-nobel-laureate-demands-new-approach-wartime-justice/" target="_blank">Source</a>| That effort accelerated dramatically after Russian President Vladimir Putin launched a full-scale invasion of Ukraine on Feb. 24, subjecting cities like Mariupol to indiscriminate bombing, displacing millions, and seizing control of territories that Russia now claims to have annexed in violation of international law. Since then, CCL has recorded details of some 21,000 incidents of alleged war crimes or crimes against humanity, relying on a network of regional groups and volunteers who field reports from across Ukraine. Matviichuk and her colleagues at CCL are well familiar with the difficulties of trying to achieve justice. After years of referring alleged incidents of sexual assault, torture and forced disappearances to state authorities and outside organizations including the Organization for Security and Cooperation in Europe (OSCE), Matviichuk said she and her colleagues grew frustrated that such abuses continued to occur.|
|The winners were honored for "an outstanding effort to document war crimes, human right abuses and the abuse of power" in their respective countries.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-07-22/h_98f3516703a278bfe3d32be8d05dd318" target="_blank">Source</a>| The Nobel Peace Prize has been awarded to human rights campaigners in Ukraine, Russia and Belarus. Belarusian human rights advocate Ales Bialiatski and two organizations from Russia and Ukraine Memorial and the Center for Civil Liberties, respectively were announced as the winners of the 2022 award on Friday morning. The winners were honored for "an outstanding effort to document war crimes, human right abuses and the abuse of power" in their respective countries. "They have for many years promoted the right to criticise power and protect the fundamental rights of citizens," the Norwegian Nobel Committee said.|
|This year's Nobel Prize season approaches as Russia's invasion of Ukraine has shattered decades of almost uninterrupted peace in Europe and raised the risks of a nuclear disaster.<a href="https://www.voanews.com/a/nobel-prize-season-arrives-amid-war-nuclear-fears-hunger/6770145.html" target="_blank">Source</a>| This year's Nobel Prize season approaches as Russia's invasion of Ukraine has shattered decades of almost uninterrupted peace in Europe and raised the risks of a nuclear disaster. The secretive Nobel committees never hint who will win the prizes in medicine, physics, chemistry, literature, economics or peace.|
|Russian human rights organization Memorial, one of the winners of the 2022 Nobel Peace Prize, was established in 1987 by human rights activists in the former Soviet Union to expose the abuses and atrocities of the Stalinist era.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-07-22/h_ab13d0e1f7a9e22d692397bbdf8064dc" target="_blank">Source</a>| Russian human rights organization Memorial, one of the winners of the 2022 Nobel Peace Prize, was established in 1987 by human rights activists in the former Soviet Union to expose the abuses and atrocities of the Stalinist era. The group "wanted to ensure that the victims of the communist regime's oppression would never be forgotten," according to the Nobel committee.|
|They don't know whether they'll use or not use it."<a href="https://www.bbc.com/news/world-europe-63177635" target="_blank">Source</a>| In an interview in Kyiv with the BBC's John Simpson and Hugo Bachega, he said: "They are not ready to do it, to use it. But they begin to communicate. They don't know whether they'll use or not use it."|
