# What is the significance of the Black Sea grain deal between Ukraine and Russia?

## Summary
The Black Sea Grain Initiative, brokered in July by the UN and Turkey, was an agreement between Ukraine and Russia that allowed the export of more than nine million metric tonnes of grain and other food products to populations around the world, amidst a devastating global food crisis (3). This agreement was of critical importance as Ukraine is the world's fourth-largest exporter of corn and the fifth-largest exporter of wheat (2). The impact of the agreement was clear, as it helped lower global food prices and provided relief to those most vulnerable to severe hunger (3). However, Russia announced on Saturday that it was suspending its implementation of the agreement, citing an alleged Ukrainian drone attack against its Black Sea Fleet ships (1). This move was met with regret from the US and UN (3, 4, 5), as Ukraine accused Russia of creating a world “hunger games” (5).

## Claims
| Claim Sentence | Context |
|---|---|
|Russia announced Saturday that it will move to suspend its implementation of a U.N.-brokered grain deal that has seen more than 9 million tons of grain exported from Ukraine during the war and has brought down soaring global food prices.<a href="https://www.fox9.com/news/russia-suspending-ukraine-grain-export-deal" target="_blank">Source</a>| Russia announced Saturday that it will move to suspend its implementation of a U.N.-brokered grain deal that has seen more than 9 million tons of grain exported from Ukraine during the war and has brought down soaring global food prices. The Russian Defense Ministry cited an alleged Ukrainian drone attack against Russias Black Sea Fleet ships moored off the coast of occupied Crimea, which Russia says took place early Saturday, as the reason for the move.|
|TheBlack Sea Grain Initiative brokered in July by the UN and Turkey ended months of the blockade, allowing grain ships to navigate a safe corridor through the Black Sea, helping alleviate global food shortages.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-20-22/h_a745a8d56b576bafa7cef6099dece796" target="_blank">Source</a>| Before the war, wheat supplies from Russia and Ukraine accounted for almost 30% of global trade, and Ukraine is the world's fourth-largest exporter of corn and the fifth-largest exporter of wheat, according to the US State Department. However, Moscow's blockade of Black Sea ports earlier this year stalled millions of tons of grain exports from Ukraine. TheBlack Sea Grain Initiative brokered in July by the UN and Turkey ended months of the blockade, allowing grain ships to navigate a safe corridor through the Black Sea, helping alleviate global food shortages. Earlier this week, Ukrainian President Volodymyr Zelensky emphasized the importance of the deal, adding that since July Ukraine has exported 8 million tons of food by sea.|
|She touted the "tremendous success" of the deal so far, crediting it with lowering global food prices and providing relief to those "most vulnerable to severe hunger."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-30-22/h_7a212ad0102564430de7de246a316266" target="_blank">Source</a>| "Russia's comments about suspending its participation in the Black Sea Grain Initiative are regrettable. This life-saving agreement between Russia,Ukraine, and Turkey, brokered in July by the United Nations, has allowed the export of more than nine million metric tons of grain and other food products to populations around the world in the midst of a devastating global food crisis," USAID Administrator Samantha Power wrote in a statement Sunday. She touted the "tremendous success" of the deal so far, crediting it with lowering global food prices and providing relief to those "most vulnerable to severe hunger." Remember: Moscow announced it was leaving the grain deal after blaming Ukraine for adrone attackon Crimea Saturday.|
|Some background: In July, Ukraine and Russia agreed to the deal that allowed the resumption ofvital grain exportsfrom Ukrainian Black Sea ports, a major diplomatic breakthrough at the time, aimed at easing a global food crisis sparked by the war.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-28-22/h_b30a7604a9715213627f72b83c992553" target="_blank">Source</a>| "The impact of the agreement signed in Istanbul has been clearly demonstrated. Exports of grains and other food products under the Black Sea Grain Initiative have surpassed 9 million tonnes," Guterres said in a statement Friday. Some background: In July, Ukraine and Russia agreed to the deal that allowed the resumption ofvital grain exportsfrom Ukrainian Black Sea ports, a major diplomatic breakthrough at the time, aimed at easing a global food crisis sparked by the war. Ministers from both countries signed an agreement brokered by the United Nations and Turkey in Istanbul.|
|KYIV, Ukraine (AP) Russia announced Saturday that it will immediately suspend its implementation of a U.N.-brokered grain deal that has seen more than 9 million tons of grain exported from Ukraine during the war and has brought down soaring global food prices.<a href="https://ca.movies.yahoo.com/russians-said-clearing-ukrainian-regions-111458303.html" target="_blank">Source</a>| KYIV, Ukraine (AP) Russia announced Saturday that it will immediately suspend its implementation of a U.N.-brokered grain deal that has seen more than 9 million tons of grain exported from Ukraine during the war and has brought down soaring global food prices. Ukraine accused Russia of creating a world "hunger games."|
