# Who has the advantage in terms of resources in Ukraine's war with Russia?

## Summary
The Ukraine-Russia conflict has been a test of resources and capabilities, with both sides facing difficult conditions. Ukraine has a psychological advantage, with volunteers sending warm clothes and supplies to assist the army (2). This contrasts with reports of new Russian troops not having food or blankets (1). Additionally, Ukraine has been able to utilize blockchain to support humanitarian efforts (3). Meanwhile, Russia has been accused of creating a world "hunger games" and has been taking resources from cities such as Kherson (4). Furthermore, the Black Sea Grain Initiative, brokered by the UN and Turkey, has allowed for more than 9 million tonnes of grains and other food products to be exported (5). Therefore, Ukraine has had a greater advantage in terms of resources in the war with Russia. (1,2,3,4,5)

## Claims
| Claim Sentence | Context |
|---|---|
|The freezing cold conditions are of course hard on both sides, but experts say the Ukrainians have a psychological advantage: an army of volunteers trying to help where they can, sending warm clothes, supplies, even making equipment.<a href="https://www.cnn.com/2022/10/28/europe/ukraine-russia-war-winter-intl-cmd/index.html" target="_blank">Source</a>| "There are credible reports of new Russian troops not having food or blankets. Imagine what happens when winter really strikes," she said. The freezing cold conditions are of course hard on both sides, but experts say the Ukrainians have a psychological advantage: an army of volunteers trying to help where they can, sending warm clothes, supplies, even making equipment. Vadym Osadchy is one such volunteer.|
|The Russia-Ukraine conflict has tested the capabilities of crypto in a real-world conflict where sanctions and inventive blockchain crowdfunding models abound.<a href="https://cointelegraph.com/news/what-the-russia-ukraine-conflict-has-revealed-about-crypto" target="_blank">Source</a>| The Russia-Ukraine conflict has tested the capabilities of crypto in a real-world conflict where sanctions and inventive blockchain crowdfunding models abound. The war, which is drawing into its ninth month, has uncovered a raft of blockchain benefits, such as the capacity to support humanitarian endeavors.|
|Ukraine has denied the attack, saying that the Russians mishandled their own weapons.<a href="https://apnews.com/article/russia-ukraine-europe-government-and-politics-3b563bd6f79f815c7e9f33505dd25334" target="_blank">Source</a>| Ukraine accused Russia of creating a world "hunger games." The Russian Defense Ministry cited an alleged Ukrainian drone attack Saturday against Russias Black Sea Fleet ships moored off the coast of occupied Crimea as the reason for the move. Ukraine has denied the attack, saying that the Russians mishandled their own weapons. The Russian declaration came one day after U.N. chief Antonio Guterres urged Russia and Ukraine to renew the grain export deal, which was scheduled to expire on Nov. 19.|
|Ukrainian soldiers are making steady advances in Kherson, which was seized by Russia in the early days of the war, becoming the first major city to fall into their hands.<a href="https://www.telegraph.co.uk/world-news/2022/10/29/russian-troops-fleeing-hospitals-kherson-soldiers-purge-supplies/" target="_blank">Source</a>| "I constantly see how they take everything out of the city. Washing machines, air conditioners, ambulances, fire engines, and rescue vehicles, literally from my window," she told the Telegraph. Ukrainian soldiers are making steady advances in Kherson, which was seized by Russia in the early days of the war, becoming the first major city to fall into their hands.|
|Some background: In July, Ukraine and Russia agreed to the deal that allowed the resumption of vital grain exports from Ukrainian Black Sea ports, a major diplomatic breakthrough at the time, aimed at easing a global food crisis sparked by the war.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-28-22/index.html" target="_blank">Source</a>| "The impact of the agreement signed in Istanbul has been clearly demonstrated. Exports of grains and other food products under the Black Sea Grain Initiative have surpassed 9 million tonnes," Guterres said in a statement Friday. Some background: In July, Ukraine and Russia agreed to the deal that allowed the resumption of vital grain exports from Ukrainian Black Sea ports, a major diplomatic breakthrough at the time, aimed at easing a global food crisis sparked by the war. Ministers from both countries signed an agreement brokered by the United Nations and Turkey in Istanbul.|
