# What was the goal and strategy behind Ukraine's missile attack on Melitopol?

## Summary
Ukraine launched a missile attack on the Russian-occupied city of Melitopol <font color=#FF3399>[1,2,4,5]</font> with the goal of pushing Russian forces out of southern Ukraine <font color=#FF3399>[1]</font> and isolating and destroying enemy troops in and around the city <font color=#FF3399>[1]</font>. The attacks targeted a number of different locations, including a church being used as a base by Russian forces <font color=#FF3399>[2]</font>. Ukrainian authorities in the town of Melitopol announced that the country's Armed Forces had launched an offensive against Russian troops stationed outside the town <font color=#FF3399>[3]</font>. Yevgeny Balitsky, Russias acting governor of Zaporizhzhia, reported that the missile attack on Melitopol had "completely destroyed" a recreation center where "people, civilians, and [military] base personnel were having dinner on Saturday night" <font color=#FF3399>[5]</font>. Ivan Fedorov, Ukraines former administrator of Melitopol city, said they had targeted Russian military bases <font color=#FF3399>[5]</font>. The move is seen as a potential path to drive Russian forces all the way back to Crimea <font color=#FF3399>[1]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> As it explained, Ukrainian forces are seeking to isolate and destroy enemy troops in and around the city, using long-range precision missiles, diversion and attacks on elected representatives of the occupation authorities.<a href="https://tvpworld.com/65096013/ukrainian-forces-take-melitopol-as-a-target-hinting-offensives-direction-us-daily" target="_blank">Source</a>| The Ukrainian army has recently taken the Russian-occupied city of Melitopol as its target, indicating that the Ukrainians next move is likely to be an offensive to push Russian forces out of southern Ukraine, the "New York Times" daily wrote. As it explained, Ukrainian forces are seeking to isolate and destroy enemy troops in and around the city, using long-range precision missiles, diversion and attacks on elected representatives of the occupation authorities. "Melitopol is a key hub, and regaining control over it could help Ukraines forces take back not only the full Zaporizhzhia region, but also the rest of neighbouring Kherson," it explained, further adding that the move "could then potentially even give them a path to drive Russian forces all the way back to Crimea, which the Russians had controlled prior to the invasion."|
|<font color=#FF3399>[2]</font> Ukrainian forces struck the Russian-occupied city ofMelitopolover the weekend, opening a new front in Kyiv's fight to reclaim land in the south of the country and underlining the importance of longer-range weaponry.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-13-22/h_6cc26eee5ea9574348b5fe2588371dae" target="_blank">Source</a>| Ukrainian forces struck the Russian-occupied city ofMelitopolover the weekend, opening a new front in Kyiv's fight to reclaim land in the south of the country and underlining the importance of longer-range weaponry. The attacks struck a number of different locations, including a church being used as a base by Russian forces, according to the city's exiled mayor, Ivan Fedorov, who shared a video filmed at night of a fire burning in the distance.|
|<font color=#FF3399>[3]</font> Ukrainian authorities in the town of Melitopol announced Friday that the country's Armed Forces have launched an offensive against Russian troops stationed outside the town.<a href="https://www.msn.com/en-ca/news/world/ukraine-launches-attack-on-russian-forces-stationed-on-the-outskirts-of-melitopol/ar-AA14PnPk" target="_blank">Source</a>| Ukrainian authorities in the town of Melitopol announced Friday that the country's Armed Forces have launched an offensive against Russian troops stationed outside the town. As reported by the mayor of Melitopol, Ivan Fedorov, on his Telegram channel, the region as a whole is getting "hellishly hot" for Russia's troops.|
|<font color=#FF3399>[4]</font> Ukraine launched a missile attack on the Russian-occupied city of Melitopol Saturday, according to officials on both sides.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-11-22/h_18b347fc4f4476aba1d5c702297c4603" target="_blank">Source</a>| Ukraine launched a missile attack on the Russian-occupied city of Melitopol Saturday, according to officials on both sides. Melitopol's Moscow-installed administrators said four missiles struck the city, killing two people and wounding 10.|
|<font color=#FF3399>[5]</font> The strikes were acknowledged by Ivan Fedorov, Ukraines former administrator of Melitopol city, who said they had targeted Russian military bases.<a href="https://www.cnn.com/2022/12/11/europe/ukraine-crimea-melitopol-odesa-intl-hnk/index.html" target="_blank">Source</a>| Melitopol, in Ukraines Zaporizhzhia Oblast, has been under Russian occupation since early March. Yevgeny Balitsky, Russias acting governor of Zaporizhzhia, said the missile attack on Melitopol had "completely destroyed" a recreation center where "people, civilians, and [military] base personnel were having dinner on Saturday night." The strikes were acknowledged by Ivan Fedorov, Ukraines former administrator of Melitopol city, who said they had targeted Russian military bases. Federov last month said Russia had turned Melitopol into "one giant military base."|
