# What impact have Western sanctions had on the relationship between Russia and Belarus?

## Summary
Western sanctions have had a significant impact on the relationship between Russia and Belarus. In 2020, Russia increased its influence over Belarusian President Alexander Lukashenko by providing $1.5 billion in loans, striking preferential deals to supply oil and gas, and backing Lukashenko's crackdown on the opposition movement <font color=#FF3399>[1]</font>. This pushed Belarus further into Russia's arms and led to Putin making a rare foreign trip to Minsk in December <font color=#FF3399>[2]</font>. During their meeting, Putin said Russia was the largest investor in Belarus with $4 billion and that the two countries had overcome the negative consequences of sanctions pressure <font color=#FF3399>[3]</font>. Putin has also been laying the groundwork to transform Belarus into a vassal state, and Lukashenko has supported Russia's military actions from the sidelines <font color=#FF3399>[4]</font>. During their most recent meeting, the two leaders discussed deepening economic integration, resisting sanctions pressure, and coordinating steps to minimize the impact of Western restrictions <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Sanctions imposed on Minsk by western governments pushed Belarus further into Russias arms.<a href="https://www.washingtonpost.com/business/energy/why-belarus-is-backing-russia-in-its-war-in-ukraine/2022/12/30/63a74b5a-885a-11ed-b5ac-411280b122ef_story.html" target="_blank">Source</a>| The relationship began to change in 2020 when Putin gained more sway over a weakened Lukashenko by supporting his crackdown on a well-organized opposition movement that threatened to topple him. Moscow gained further leverage by providing $1.5 billion in loans and striking preferential deals to supply oil and gas to its smaller neighbor. Sanctions imposed on Minsk by western governments pushed Belarus further into Russias arms. Putin visited Lukashenko in December in Belarus, a rare foreign trip for the increasingly reclusive leader, underscoring how close the two had become.|
|<font color=#FF3399>[2]</font> The European Union and the United States have imposed a range of sanctions on Belarus, principally against senior officials of Lukashenko's government as well as air travel and some exports.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-19-22/h_70a00635eb215cf419cb24b437cd7801" target="_blank">Source</a>| Putin said that Russia remains the largest investor in Belarus, to the tune of some $4 billion. For his part, Belarus President Alexander Lukashenko said that 2022 had been a record for Russian-Belarusian relations on all levels and claimed that "sanctions had a painful boomerang effect on their initiators." The European Union and the United States have imposed a range of sanctions on Belarus, principally against senior officials of Lukashenko's government as well as air travel and some exports. "Because the collective West has reared its ugly head at us, we must coordinate our efforts," Lukashenko said.|
|<font color=#FF3399>[3]</font> Lukashenko also mentioned economic relations, saying that"Thanks to joint work, Russia and Belarus managed to overcome the possible negative consequences of sanctions pressure."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-19-22/h_e71b63caf9ee08c80855ef5e24fc3855" target="_blank">Source</a>| But Lukashenko has gone to some lengths to ensure that Belarus troops do not become involved in Russia's "special military operation." Russia also has strike aircraft based in Belarus. Lukashenko also mentioned economic relations, saying that"Thanks to joint work, Russia and Belarus managed to overcome the possible negative consequences of sanctions pressure."|
|<font color=#FF3399>[4]</font> Russia backed theruthless crackdownon demonstrations, and gave Belarus a $1.5 billion lifeline to evade the brunt of sanctions, but it came with strings attached.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-20-22/h_495871910650c8a45c8cd76af31435b0" target="_blank">Source</a>| Putin has been laying the groundwork to transform Belarus into a vassal state for some time. After a rigged presidential election in 2020 cemented Lukashenko's long reign, triggeringwidespread pro-democracy protests, he clung to power with the help of Putin. Russia backed theruthless crackdownon demonstrations, and gave Belarus a $1.5 billion lifeline to evade the brunt of sanctions, but it came with strings attached. Beholden to the Kremlin, Lukashenko has supported Russia's military actions from the sidelines, so far avoiding sending his own troops into the fray.|
|<font color=#FF3399>[5]</font> Calling the two countries "the closest allies and strategic partners", Putin said Russia and Belarus are consistently deepening economic integration, together resisting sanction pressure, and coordinating steps to minimize the impact of Western restrictions.<a href="https://www.chinadaily.com.cn/a/202212/20/WS63a110a0a31057c47eba53b6.html" target="_blank">Source</a>| MOSCOW - Russian President Vladimir Putin visited Minsk and held talks with his Belarusian counterpart Alexander Lukashenko on Monday to boost comprehensive cooperation between the two countries. "The main issues of Russian-Belarusian relations in economic, cultural, humanitarian, security and defense spheres were discussed in a businesslike and constructive manner," Putin said at a joint press conference following the meeting. Calling the two countries "the closest allies and strategic partners", Putin said Russia and Belarus are consistently deepening economic integration, together resisting sanction pressure, and coordinating steps to minimize the impact of Western restrictions. Bilateral trade turnover will hit a record of over 40 billion US dollars by the end of this year, while Russia remains the largest investor in the Belarusian economy with over 4 billion dollars, he noted.|
