# What is the Russian military's primary objective in occupying Melitopol?

## Summary
The Russian military is primarily focused on maintaining control of Melitopol, a southern Ukrainian city, which they have occupied since the early days of the invasion <font color=#FF3399>[1]</font>. According to the city's mayor, Ivan Fedorov, Russian forces have turned the city into a "huge military base" <font color=#FF3399>[1]</font>. On Thursday, the Russian headquarters in Melitopol were attacked and destroyed <font color=#FF3399>[2]</font>. The Russian Federation is also trying to hold the temporarily occupied territories in the Zaporizhzhia Oblast and is conducting offensive actions on the Bakhmut, Avdiivka and Novopavlivka fronts <font color=#FF3399>[4]</font>. Furthermore, they are defending against Ukrainian forces attempting to advance on Kherson city, which could threaten Crimea <font color=#FF3399>[5]</font>. Therefore, the primary objective of the Russian military in occupying Melitopol is to maintain control of the city and the surrounding areas.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> The mayor of the southern Ukrainian city of Melitopol, Ivan Fedorov, says Russian forces have turned the city into a "huge military base" while under their occupation.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-14-22/h_dce9d898240a4b6a13187074d5919cc0" target="_blank">Source</a>| The mayor of the southern Ukrainian city of Melitopol, Ivan Fedorov, says Russian forces have turned the city into a "huge military base" while under their occupation. Melitopol has been held by Russian forces since the early days of the invasion.|
|<font color=#FF3399>[2]</font> The Russian headquarters in Melitopol in southern Ukraine were attacked and destroyed on Thursday, according to the city's mayor.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-04-22/h_150a8688e7b2af06a222b6b2397aadfc" target="_blank">Source</a>| The Russian headquarters in Melitopol in southern Ukraine were attacked and destroyed on Thursday, according to the city's mayor. Melitopol has been occupied by Russian forces since the early days of the invasion.|
|<font color=#FF3399>[3]</font> The Russian headquarters in Melitopol in southern Ukraine were attacked and destroyed on Thursday, according to the city's mayor.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-04-22/h_150a8688e7b2af06a222b6b2397aadfc" target="_blank">Source</a>| The Russian headquarters in Melitopol in southern Ukraine were attacked and destroyed on Thursday, according to the city's mayor. Melitopol has been occupied by Russian forces since the early days of the invasion.|
|<font color=#FF3399>[4]</font> Details: In general, the Russian Federation is trying to hold the temporarily occupied territories, focusing its efforts on deterring the actions of the Ukrainian defence forces on certain fronts.<a href="https://news.yahoo.com/armed-forces-ukraine-successfully-operating-162944956.html" target="_blank">Source</a>| to hospitals in Tokmak and Melitopol. Due to the regular deaths of collaborators and their refusal to perform their duties, the enemy is holding competitions to fill vacant positions in the occupation authorities in the temporarily occupied territory of Zaporizhzhia Oblast." Details: In general, the Russian Federation is trying to hold the temporarily occupied territories, focusing its efforts on deterring the actions of the Ukrainian defence forces on certain fronts. The Russians are conducting offensive actions on the Bakhmut, Avdiivka and Novopavlivka fronts.|
|<font color=#FF3399>[5]</font> So far, Russian are holding their positions, repelling the ongoing Ukrainian attacks and fortifying their defences.<a href="https://slguardian.org/no-end-in-view-for-ukraine-war/" target="_blank">Source</a>| The Ukrainian forces are on the prowl poking the Russian defence line incessantly to break through to advance toward the city of Kherson. A large-scale Ukrainian offensive backed by western advisors and mercenaries is to be expected any day. So far, Russian are holding their positions, repelling the ongoing Ukrainian attacks and fortifying their defences. From Kherson city, Ukrainian artillery can threaten Crimea.|
