# What is the Kremlin's reaction to President Zelensky's visit to the United States?

## Summary
The Kremlin has received President Zelensky's visit to the United States with criticism and skepticism. Russia's Deputy Chairman of the Security Council Dmitry Medvedev dismissed the trip as an empty gesture, and some more hawkish voices even called for Ukraine to be "destroyed" altogether. In response to the U.S. announcement of an additional $1.85 billion in military assistance to Ukraine, including a Patriot Air Defense System, President Putin said Russia would find a way to counter this missile and that it would not help in settling the conflict. The White House responded with skepticism, noting that Putin has "shown absolutely zero indication that he's willing to negotiate an end to the war" <font color=#FF3399>[3, 5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Russian officials and other prominent figures have dismissed Ukrainian President Volodymyr Zelenskys first wartime trip to the United States as an empty gesture that would not advance Russian-Ukrainian peace talks.<a href="https://www.themoscowtimes.com/2022/12/22/empty-words-russian-officials-unswayed-by-zelenskys-us-visit-a79771" target="_blank">Source</a>| Russian officials and other prominent figures have dismissed Ukrainian President Volodymyr Zelenskys first wartime trip to the United States as an empty gesture that would not advance Russian-Ukrainian peace talks. More hawkish voices, meanwhile, called for Ukraine to be "destroyed" altogether following Zelenskys meeting with U.S. President Joe Biden and widely praised address to Congress.|
|<font color=#FF3399>[2]</font> Much of the West and other powerful nations have condemned the war.<a href="https://www.businessinsider.com/ex-russia-president-meets-china-xi-before-zelenskyy-us-visit-2022-12" target="_blank">Source</a>| Medvedev, who was formerly Russia's president and prime minister, is now the deputy chairman of Russia's Security Council. Ukrainian president Volodymyr Zelenskyy was traveling to the US on Wednesday, where he was due to address Congress, the White House said. Much of the West and other powerful nations have condemned the war. They have sought to punish and isolate Russia for its invasion of Ukraine, which started in February.|
|<font color=#FF3399>[3]</font> As Ukrainian President Volodymyr Zelenskyy returned from Washington, D.C. having secured billions of dollars in U.S. aid and multiple standing ovations in Congress the Kremlin was quick to criticize the trip.<a href="https://www.npr.org/2022/12/22/1145004513/russia-ukraine-us-proxy-war-zelenskyy-visit" target="_blank">Source</a>| Russia responds to Zelenskyy's visit by accusing the U.S. of a proxy war in Ukraine Enlarge this image toggle caption Mandel Ngan/AFP via Getty Images Mandel Ngan/AFP via Getty Images As Ukrainian President Volodymyr Zelenskyy returned from Washington, D.C. having secured billions of dollars in U.S. aid and multiple standing ovations in Congress the Kremlin was quick to criticize the trip. The Biden administration announced on Wednesday it would provide an additional $1.85 billion in military assistance to Ukraine, including, for the first time, a Patriot Air Defense System.|
|<font color=#FF3399>[4]</font> President Volodymyr Zelenskys White House visit Wednesday will symbolically bolster Americas role as the arsenal of democracy in the bitter war for Ukraines survival and send a stunning public rebuke to Russian President Vladimir Putin.<a href="https://www.cnn.com/2022/12/21/politics/us-visit-zelensky-analysis/index.html" target="_blank">Source</a>| CNN President Volodymyr Zelenskys White House visit Wednesday will symbolically bolster Americas role as the arsenal of democracy in the bitter war for Ukraines survival and send a stunning public rebuke to Russian President Vladimir Putin. The trip Zelenskys first outside Ukraine since Russias invasion in February also highlights President Joe Bidens historic role in reviving the Western alliance that kept the Soviet Union at bay and is now countering new expansionism by Moscow in an effective proxy war between nuclear superpowers.|
|<font color=#FF3399>[5]</font> The United States is taking Putin's comments on ending the war with skepticism.<a href="https://www.cnbctv18.com/videos/world/zelensky-visit-to-us-has-been-seen-as-the-best-christmas-gift-for-ukraine-john-spencer-15499361.htm" target="_blank">Source</a>| The Biden administration has announced another 2 billion dollars in military aid for Ukraine, including a patriot missile system. President Putin said Russia will find a way to counter this missile also adding that it would not help in settling the conflict. The United States is taking Putin's comments on ending the war with skepticism. White House spokesman John Kirby said Putin had "Shown absolutely zero indication that he's willing to negotiate an end to the war."|
