# What are the long-term prospects for the work of human rights campaigners in Ukraine, Russia and Belarus?

## Summary
The work of human rights campaigners in Ukraine, Russia and Belarus have seen a number of important developments in recent years. In 1987, Russian human rights organization Memorial was established to expose the abuses of the Stalinist era <font color=#FF3399>[1]</font>. Belarusian activist Ales Bialiatski founded Viasna in 2007 to document and protest the authorities' use of torture against political prisoners <font color=#FF3399>[2]</font>. The Center for Civil Liberties (CCL) in Ukraine was established in 2007 to promote human rights values and strengthen democracy in the country <font color=#FF3399>[3]</font>. CCL's head, Oleksandra Matviichuk, has called for an international tribunal to bring war criminals to justice <font color=#FF3399>[4]</font>. Despite these developments, the Nobel Peace Prize committee noted that the conflicts seem never-ending and treaties are often violated <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Russian human rights organization Memorial, one of the winners of the 2022 Nobel Peace Prize, was established in 1987 by human rights activists in the former Soviet Union to expose the abuses and atrocities of the Stalinist era.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-07-22/h_ab13d0e1f7a9e22d692397bbdf8064dc" target="_blank">Source</a>| Russian human rights organization Memorial, one of the winners of the 2022 Nobel Peace Prize, was established in 1987 by human rights activists in the former Soviet Union to expose the abuses and atrocities of the Stalinist era. The group "wanted to ensure that the victims of the communist regime's oppression would never be forgotten," according to the Nobel committee.|
|<font color=#FF3399>[2]</font> Belarusian activist Ales Bialiatski, one of the winners of the 2022 Nobel Peace Prize, is the founder ofViasna(Spring), a human rights organization that has documented and protested the authorities' use of torture against political prisoners.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-07-22/h_fa550571e8af41caeccf7ca9abef40b9" target="_blank">Source</a>| Belarusian activist Ales Bialiatski, one of the winners of the 2022 Nobel Peace Prize, is the founder ofViasna(Spring), a human rights organization that has documented and protested the authorities' use of torture against political prisoners. As one of the initiators of the democracy movement that emerged in the mid-1980s in Belarus, he has "devoted his life to promoting democracy and peaceful development in his home country," the Nobel committee said Friday.|
|<font color=#FF3399>[3]</font> The committee commended its work on strengthening Ukrainian civil society and the pressure that it's put on authorities to "make Ukraine a full-fledged democracy."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-07-22/h_9422c8b5b492267791ed61d268362e27" target="_blank">Source</a>| Ukraine's Center for Civil Liberties (CCL), another of Friday's Nobel Peace Prize winners, was established in 2007 to promote human rights values in Ukraine and strengthen democracy in the country. The committee commended its work on strengthening Ukrainian civil society and the pressure that it's put on authorities to "make Ukraine a full-fledged democracy." "The center is playing a pioneering role in holding guilty parties accountable for their crimes," it said.|
|<font color=#FF3399>[4]</font> The head of the Center for Civil Liberties, Oleksandra Matviichuk, whose organization jointly won the Nobel Peace Prize on Friday, has called for an international tribunal to bring Russian President Vladimir Putin, Belarusian President Alexander Lukashenko and "other war criminals to justice."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-07-22/h_de6e4db839d959de52f8718b46fcae45" target="_blank">Source</a>| The head of the Center for Civil Liberties, Oleksandra Matviichuk, whose organization jointly won the Nobel Peace Prize on Friday, has called for an international tribunal to bring Russian President Vladimir Putin, Belarusian President Alexander Lukashenko and "other war criminals to justice." In a Facebook post on Friday, Matviichuk said she was glad that the center had received the prize, along with the human rights group Memorial and jailed Belarusian advocate Ales Bialiatski.|
|<font color=#FF3399>[5]</font> 2022 AFP<a href="https://www.france24.com/en/live-news/20221005-ukraine-war-climate-favourites-for-nobel-peace-prize" target="_blank">Source</a>| "Nobody can claim to have made any great breakthroughs in the field of peace, the conflicts seem never-ending, and treaties seem to be there to be violated," he told AFP. Last year, the Nobel Peace Prize was awarded to two champions of press freedom -- Maria Ressa of the Philippines, whose news outlet is under threat of being shut down, and Russia's Dmitry Muratov, whose media organisation has had its licence revoked. 2022 AFP|
