# What measures can be taken to prevent delays in shipments under the Black Sea Grain Initiative?

## Summary
The United Nations is calling for "urgent measures to be taken" <font color=#FF3399>[1]</font> to prevent delays to ships sailing under the Black Sea Grain Initiative and has estimated that the reduction of prices for staple foods have indirectly prevented some 100 million people from falling into extreme poverty <font color=#FF3399>[2]</font>. The agreement initially lasted for 120 days and can be extended automatically on 19th November if no party objects <font color=#FF3399>[2]</font>. All parties are urged to make every effort to renew the Black Sea Grain Initiative and implement both agreements to their fullest <font color=#FF3399>[3]</font>. Ukraine’s Infrastructure Minister Oleksandr Kubrakov has stated that the fragile Black Sea grain deal will continue after Nov. 22 <font color=#FF3399>[4]</font> and the United Kingdom has denied Moscows claim that Britain helped Ukraine plan the Crimean drone attacks <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> The United Nations is calling for "urgent measures to be taken" to prevent delays to ships sailing under the Black Sea Grain Initiative, UN spokeswoman Ismini Palla told CNN on Sunday.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-24-22/h_1c126ffbb9875e3e93da72c0d7c04a78" target="_blank">Source</a>| The United Nations is calling for "urgent measures to be taken" to prevent delays to ships sailing under the Black Sea Grain Initiative, UN spokeswoman Ismini Palla told CNN on Sunday. Ukrainian officials have claimed that Moscow is intentionally slowing down food shipments made under the agreement signed in July by Ukraine, Russia, Turkey and the UN.|
|<font color=#FF3399>[2]</font> We urge all parties to make every effort to renew the Black Sea Grain Initiative and implement both agreements to their fullest, including the expedited removal of any remaining impediments to Russian grain and fertilizer export.<a href="https://reliefweb.int/report/ukraine/secretary-general-urges-renewal-full-implementation-black-sea-grain-initiative-noting-resultant-food-price-drop-has-saved-100-million-people-extreme-poverty" target="_blank">Source</a>| According to our estimates based on the World Bank model, the reduction of prices for staple foods has indirectly prevented some 100 million people from falling into extreme poverty. The initial duration of the agreement to facilitate grains and fertilizer exports from Ukraine is 120 days and can be extended automatically on 19 November if no party objects. We urge all parties to make every effort to renew the Black Sea Grain Initiative and implement both agreements to their fullest, including the expedited removal of any remaining impediments to Russian grain and fertilizer export. The United Nations is fully committed to continuing to work with all parties to ensure that we reach this goal.|
|<font color=#FF3399>[3]</font> We urge all parties to make every effort to renew the Black Sea Grain Initiative and implement both agreements to their fullest, including the expedited removal of any remaining impediments to Russian grain and fertilizer export.<a href="https://reliefweb.int/report/ukraine/secretary-general-urges-renewal-full-implementation-black-sea-grain-initiative-noting-resultant-food-price-drop-has-saved-100-million-people-extreme-poverty" target="_blank">Source</a>| According to our estimates based on the World Bank model, the reduction of prices for staple foods has indirectly prevented some 100 million people from falling into extreme poverty. The initial duration of the agreement to facilitate grains and fertilizer exports from Ukraine is 120 days and can be extended automatically on 19 November if no party objects. We urge all parties to make every effort to renew the Black Sea Grain Initiative and implement both agreements to their fullest, including the expedited removal of any remaining impediments to Russian grain and fertilizer export. The United Nations is fully committed to continuing to work with all parties to ensure that we reach this goal.|
|<font color=#FF3399>[4]</font> The minister also emphasized the importance of getting faster ship inspections by the Joint Coordination Center.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-16-22/h_0f298f6abd1f25d1c1add8eb5ef69527" target="_blank">Source</a>| The fragile Black Sea grain deal will continue after Nov. 22, when it is set to expire, Ukrainian Infrastructure MinisterOleksandr Kubrakov said Sunday. Kubrakov made the comments during a meeting with Turkish Defense Minister Hulusi Akar in Istanbul.They come after Russian officials, including President Vladimir Putin, cast doubt on the deal's future this week. The minister also emphasized the importance of getting faster ship inspections by the Joint Coordination Center. This allows for "a significant increase in the volume of grain exports to the countries of Africa, Asia, and Europe and prevents the formation of inspection queues," he said.|
|<font color=#FF3399>[5]</font> Russia pledged to unblock ports on the Black Sea to allow the safe passage of grain and oilseeds some of Ukraines most important exports.<a href="https://www.cnn.com/2022/10/29/europe/russia-ukraine-grain-deal-suspended-intl/index.html" target="_blank">Source</a>| The United Kingdom has denied Moscows claim that Britain helped Ukraine plan the Crimean drone attacks, saying Russia is "peddling false claims of an epic scale." In July, following months of negotiations, ministers from both Ukraine and Russia signed the agreement brokered by the UN and Turkey. Russia pledged to unblock ports on the Black Sea to allow the safe passage of grain and oilseeds some of Ukraines most important exports. The deal is set to expire next month, and Moscow officials have cast doubt on whether they will extend their participation.|
