# What measures have been taken to protect civilians in the affected areas of Kyiv from Russian missile attacks?

## Summary
In response to the Russian missile attacks on Kyiv, air-raid sirens have been sounded across the country <font color=#FF3399>[1]</font> and the military has activated air-defense systems in Kyiv <font color=#FF3399>[2]</font>. Metro service has been suspended <font color=#FF3399>[3]</font> and underground stations are being used as shelters <font color=#FF3399>[3]</font>. The city police have located and published a photo of a downed missile <font color=#FF3399>[2]</font>. Power has been switched off in Kryvyi Rih as a precaution <font color=#FF3399>[5]</font>. <font color=#FF3399>[1,2,3,5]</font>

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Air-raid sirens rang out across the country, and the military activated air-defense systems in Kyiv, the regional administration said.<a href="https://www.kktv.com/2022/12/29/ukraine-facing-another-russian-missile-attack/" target="_blank">Source</a>| The strikes also wounded at least seven people across the country, although the toll of the attacks was growing as officials assessed the days events. Russia dispatched explosive drones to selected regions overnight before broadening the barrage with air and sea-based missiles, the Ukrainian air force said. Air-raid sirens rang out across the country, and the military activated air-defense systems in Kyiv, the regional administration said. Ukraines defense ministry said the attack damaged 18 residential buildings and 10 pieces of critical infrastructure in 10 regions.|
|<font color=#FF3399>[2]</font> "The missile was destroyed by air defense forces.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-16-22/h_3a51029a2c0206ec2856081d2b2664df" target="_blank">Source</a>| Metro service is suspended on all lines and "underground stations work as shelters," the mayor added. Kyiv city police have locatedand published a photo of what they claim is a downed Russian missile. "The missile was destroyed by air defense forces. Fortunately, there were no casualties," police said on Twitter.|
|<font color=#FF3399>[3]</font> Earlier Friday, the deputy head of the Ukrainian Presidential Office urged people to stay in shelters as air raid sirens sounded across the country.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-16-22/h_69ebf33df3506408b40097537a9303c2" target="_blank">Source</a>| CNN teams in Kyiv have reported hearing explosions, as well as seeing and hearing missiles. They also heard the air defense systems working in the Ukrainian capital. Earlier Friday, the deputy head of the Ukrainian Presidential Office urged people to stay in shelters as air raid sirens sounded across the country.|
|<font color=#FF3399>[4]</font> They also heard the air defense systems working in the Ukrainian capital.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-16-22/h_ebf47e174f1613205823f423721415e2" target="_blank">Source</a>| Missile attacks were reported across Ukraine overnight including in Kyiv, Odesa, Poltava, Zhytmoyr,Kharkivand Sumy. CNN teams in the city have reported hearing explosions, as well as seeing and hearing missiles. They also heard the air defense systems working in the Ukrainian capital.|
|<font color=#FF3399>[5]</font> Power in the city had been switched off as a "precaution", he added.<a href="https://www.bbc.com/news/world-europe-64114784" target="_blank">Source</a>| Oleksandr Vilkul, head of the Military Administration in the central city of Kryvyi Rih, said missiles fired at his city had been launched from Russian "ships and planes from the Black Sea". Power in the city had been switched off as a "precaution", he added.|
