# How might the Russian government respond to the growing dissent of deputies calling for Putin's impeachment?

## Summary
In response to the growing dissent of deputies calling for Vladimir Putin's impeachment, the Kremlin has warned that criticism of the president and military leadership must remain within the law <font color=#FF3399>[1]</font>. Several elected deputies in the St. Petersburg area have been summoned by police after calling for the impeachment of Putin <font color=#FF3399>[2]</font>, and nearly two dozen municipal deputies in Moscow and St. Petersburg have signed a petition demanding Putin's resignation <font color=#FF3399>[3, 4, 5]</font>. The Kremlin has emphasized that public criticism of Putin must remain within the law and that there is a "very, very thin" line between pluralism and criminal behavior <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> In a rare display of dissent in Russia, the local deputies from the Smolninskoye municipality appealed to the Russian Duma to impeach Putin for what they called crimes of high treason.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-09-22/h_a3a7dc69d56736f29fc46275b565b3e6" target="_blank">Source</a>| Several elected deputies in the St. Petersburg area have been summoned by police after calling for the impeachment of Russian President Vladimir Putin. In a rare display of dissent in Russia, the local deputies from the Smolninskoye municipality appealed to the Russian Duma to impeach Putin for what they called crimes of high treason. Palyuga and fellow deputy Nikita Yuferev later posted on Twitter a summons issued to them by the St. Petersburg police for "discrediting of the ruling establishment."|
|<font color=#FF3399>[2]</font> Deputies from 18 municipal districts in Moscow, St. Petersburg and Kolpino have called for Russian President Vladimir Putin's resignation, according to a petition with a list of signatures posted on Twitter on Monday.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-12-22/h_280c69104479678d4adeb8a2a1e12d6e" target="_blank">Source</a>| Deputies from 18 municipal districts in Moscow, St. Petersburg and Kolpino have called for Russian President Vladimir Putin's resignation, according to a petition with a list of signatures posted on Twitter on Monday. The petition follows Russia's first regional and municipal elections since the start of the war, which brought a sweeping victory for pro-Kremlin candidates.|
|<font color=#FF3399>[3]</font> Deputies from 18 municipal districts in Moscow, St. Petersburg and Kolpino have called for Russian President Vladimir Putins resignation, according to a petition with a list of signatures posted on Twitter on Monday.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-13-22/h_5ec7b367f6a1438740ed9472229ca097" target="_blank">Source</a>| Deputies from 18 municipal districts in Moscow, St. Petersburg and Kolpino have called for Russian President Vladimir Putins resignation, according to a petition with a list of signatures posted on Twitter on Monday. "We, the municipal deputies of Russia, believe that the actions of its president Vladimir Putin are detrimental to Russias and its citizens future.|
|<font color=#FF3399>[4]</font> Nearly two dozen municipal deputies in Moscow and St. Petersburg have signed a petition demanding Vladimir Putins resignation as president.<a href="https://meduza.io/en/news/2022/09/12/municipal-deputies-in-moscow-and-st-petersburg-demand-putin-s-resignation" target="_blank">Source</a>| Nearly two dozen municipal deputies in Moscow and St. Petersburg have signed a petition demanding Vladimir Putins resignation as president. Shared by St. Petersburg councilwoman Ksenia Thorstrom, the document says, "We, the municipal deputies of Russia, believe that President Vladimir Putins actions harm the future of Russia and its citizens."|
|<font color=#FF3399>[5]</font> Some Russian officials took the brave step of publicly calling for Putins resignation.<a href="https://news.yahoo.com/russian-forces-ordered-retreat-kharkiv-190800110.html" target="_blank">Source</a>| "As for other points of view, critical points of view, as long as they remain within the law, this is pluralism, but the line is very, very thin, one must be very careful here", he added. The response from the Kremlin came after outright criticism of Putin and the military leadership earlier in the week. Some Russian officials took the brave step of publicly calling for Putins resignation. District councils in the long-serving leaders home city of St Petersburg were among those who have urged the country to oust the 69-year-old.|
