# What are the implications of the IAEA report on the Zaporizhzhia nuclear power plant's condition?

## Summary
The International Atomic Energy Agency (IAEA) released a report on the situation at the Zaporizhzhia nuclear power plant in Ukraine, which found that the shelling in the area had not yet triggered a nuclear emergency but it is a constant threat to nuclear safety and security, with potential impact on critical safety functions that could lead to radiological consequences <font color=#FF3399>[1,3]</font>. The IAEA called for the immediate establishment of a nuclear safety and security protection zone around the ZNPP in order to facilitate the plant's secure and safe operations <font color=#FF3399>[4]</font>. On Sunday, the last operating reactor at the plant was shut down and disconnected from the grid, and arrangements were being made to transfer it to a cold state <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> "Any further escalation affecting the six-reactor plant could lead to a severe nuclear accident with potentially grave radiological consequences for human health and the environment in Ukraine and elsewhere," the IAEA warned.<a href="https://www.cbsnews.com/news/ukraine-zaporizhzhia-nuclear-power-plant-risks-chernobyl-comparison/" target="_blank">Source</a>| After the shutdown, Zaporizhzhia will enter a "cold state," according to Ukrainian nuclear operator Energoatom. But the integrity of the plant has been compromised by weeks of shelling, according to a 52-page report compiled by the United Nations-backed global nuclear watchdog, the International Atomic Energy Agency (IAEA), which sent a team of inspectors to Zaporizhzhia at the beginning of September. "Any further escalation affecting the six-reactor plant could lead to a severe nuclear accident with potentially grave radiological consequences for human health and the environment in Ukraine and elsewhere," the IAEA warned. The agency's Director General, Rafael Grossi, noted in the report that the Ukrainian technicians who've continued operating the plant under Russian occupation are "under constant high stress and pressure, especially with the limited staff available."|
|<font color=#FF3399>[2]</font> Zaporizhzhia nuclear power plant is now relying on a reserve line to supply electricity to the grid, the International Atomic Energy Agency (IAEA) said.<a href="https://www.cnn.com/2022/09/04/europe/ukraine-zaporizhzhia-sunday-intl/index.html" target="_blank">Source</a>| CNN Ukraines largest nuclear plant lost its main connection to the power grid again Saturday amid sustained shelling, despite the presence of international inspectors. Zaporizhzhia nuclear power plant is now relying on a reserve line to supply electricity to the grid, the International Atomic Energy Agency (IAEA) said. Inspectors from the UN nuclear watchdog arrived at the site Thursday despite concerns about constant shelling in the area.|
|<font color=#FF3399>[3]</font> The report determines that although the ongoing shelling around the ZNPP "has not yet triggered a nuclear emergency", it continues to "represent a constant threat to nuclear safety and security with potential impact on critical safety functions that may lead to radiological consequences with great safety significance".<a href="https://www.securitycouncilreport.org/whatsinblue/2022/09/ukraine-briefing-on-the-zaporizhzhia-nuclear-power-plant.php" target="_blank">Source</a>| Grossi warned that the gravest risk to the ZNPP is physical damage to equipment, from shelling, that could lead to a release of radiation, adding that disruptions in external power to cool reactor cores could lead to a meltdown. The IAEA released a report today (6 September) about the nuclear safety, security and safeguards situation at several nuclear facilities in Ukraine, which includes an overview of the findings of the IAEAs 1 September visit. The report determines that although the ongoing shelling around the ZNPP "has not yet triggered a nuclear emergency", it continues to "represent a constant threat to nuclear safety and security with potential impact on critical safety functions that may lead to radiological consequences with great safety significance". It calls for the immediate cessation of shelling of the site and in its vicinity and says that to facilitate the plants secure and safe operations, all relevant parties need to agree on the establishment of "a nuclear safety and security protection zone around the ZNPP".|
|<font color=#FF3399>[4]</font> Last week, a report from the International Atomic Energy Agency (IAEA) called for the "immediate establishment of a nuclear safety and security protection zone" around thenuclear power plant.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-11-22/h_c44c18e57c9e32b7b59404641307e889" target="_blank">Source</a>| Energoatom said that one of the transmission lines was restored to its operational capacity Saturday, making it possible to power the plant from Ukraine's energy system and shut down the number 6 power unit and transfer it to the "safest state cold shutdown." The reactor was disconnected from the Ukrainian grid last week and was operating in an "island mode," generating electricity and using its own energy to power cooling systems. Last week, a report from the International Atomic Energy Agency (IAEA) called for the "immediate establishment of a nuclear safety and security protection zone" around thenuclear power plant. The highly anticipated report came days after IAEA Director General Rafael Grossi led an expert mission to Zaporizhzhia, in what was the first independent look at the condition of the facility since Russia seized it at the start of the war.|
|<font color=#FF3399>[5]</font> The last operating reactor at the Zaporizhzhia nuclear power plant in southern Ukraine has been completely shut down and disconnected from the grid, the Ukrainian operator Energoatom said on Sunday.<a href="https://www.politico.eu/article/zaporizhzhia-nuclear-power-plant-is-being-shut-down-operator-says/" target="_blank">Source</a>| The last operating reactor at the Zaporizhzhia nuclear power plant in southern Ukraine has been completely shut down and disconnected from the grid, the Ukrainian operator Energoatom said on Sunday. "Arrangements for its cooling and transfer to a cold state are underway," Energoatom said, adding that in recent days the sixth and last operating reactor at the plant had been powering exclusively the facility's in-house needs because "all transmission lines linking the Zaporizhzhya NPP to the Ukrainian power system were damaged due to Russian shelling."|
