# What is the rationale behind the US and Germany's reluctance to send tanks to Ukraine?

## Summary
The Biden administration and Germany have been in a standoff over sending tanks to Ukraine due to the logistical costs of maintaining them <font color=#FF3399>[1]</font>. The Western weapons, namely the Leopard 2 and the M1 Abrams, are more advanced and require less maintenance <font color=#FF3399>[2]</font>. Ukraine has requested long-range missiles and aircraft from NATO but the US has been wary of sending M1 Abrams tanks <font color=#FF3399>[3]</font>. The US ultimately promised to send 31 tanks to persuade Germany to pledge its Leopard 2 tanks <font color=#FF3399>[4]</font>, which have been seen as less likely to escalate tensions with Moscow <font color=#FF3399>[5]</font>. [1-5]

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> The tank standoff comes amid a much larger debate between the US and its European allies over whether to send increasingly sophisticated weaponry to Ukraine, including longer-range missiles that would allow Ukraine to hit targets as far as 200 miles away.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-1-20-23/h_fd60534a1419dbc0d1cc2349cb0bbca2" target="_blank">Source</a>| The Biden administration is stuck in a standoff with Germany over whether tosend tanks to Ukraineahead of a key meeting of Western defense leaders in Germany on Friday. In recent days, German officials have indicated they won't send their Leopard tanks to Ukraine, or allow any other country with the German-made tanks in their inventory to do so, unless the US also agrees to send its M1 Abrams tanks to Kyiv something the Pentagon has said for months it has no intention of doing given the logistical costs of maintaining them. The tank standoff comes amid a much larger debate between the US and its European allies over whether to send increasingly sophisticated weaponry to Ukraine, including longer-range missiles that would allow Ukraine to hit targets as far as 200 miles away. The UK, Poland, Finland and the Baltic states have all been pushing for NATO members to provide heavier equipment to Kyiv amid what they believe is a key inflection point in the war.|
|<font color=#FF3399>[2]</font> Germany, for historical and political reasons, was particularly reluctant.<a href="https://www.vox.com/world/23552619/ukraine-war-germany-leopard-tanks-zelenskyy-russia-putin" target="_blank">Source</a>| The Western weapons specifically, the Leopard 2, the German tanks, and the US M1 Abrams are more modern, more advanced, and may be easier to repair since they work with Western and NATO systems. Even as Ukraines partners promised to deliver new tranches of weapons to Ukraine, they worried sending tanks could escalate tensions with Moscow. Germany, for historical and political reasons, was particularly reluctant. Those public worries ultimately caused visible cracks in the Western unity, and the USs decision to send tanks is likely an effort to give Germany cover to send, and let others send, their Leopard 2 tanks which will also get to the front lines much faster.|
|<font color=#FF3399>[3]</font> The United States has been wary of deploying its difficult-to-maintain M1 Abrams tanks, but ultimately promised 31 to persuade Germany to pledge its more easily operated German-built Leopards.<a href="https://www.reuters.com/world/europe/ukraine-pledges-sweeping-personnel-changes-allies-jostle-over-tanks-2023-01-23/" target="_blank">Source</a>| Maintaining Kyiv's drumbeat of requests, Zelenskiy said he had spoken to NATO Secretary General Jens Stoltenberg and asked for long-range missiles and aircraft. Ukraine's allies have already provided billions of dollars in military aid, including sophisticated U.S. missile systems that have helped turn the tide of the war. The United States has been wary of deploying its difficult-to-maintain M1 Abrams tanks, but ultimately promised 31 to persuade Germany to pledge its more easily operated German-built Leopards. Germany will initially send 14 tanks from its inventory and approve shipments by allied European states, with the ultimate aim of equipping two battalions - in the region of 100 tanks.|
|<font color=#FF3399>[4]</font> Until Wednesday, Scholz had expressed reluctance to send Leopards, fearing it could escalate tensions with Moscow.<a href="https://www.axios.com/2023/01/25/germany-us-ukraine-leopard-abrams-battle-tanks" target="_blank">Source</a>| "The M1 (Abrams) is a complex weapons system that is challenging to maintain ... that was true yesterday, that is true today and will be true in the future," Pentagon spokesperson Brig. Gen. Pat Ryder told reporters on Tuesday. Until Wednesday, Scholz had expressed reluctance to send Leopards, fearing it could escalate tensions with Moscow. German officials also reportedly privately linked its own commitment to providing its tanks to a U.S. decision to send Abrams as well.|
|<font color=#FF3399>[5]</font> The long-awaited decision came after US officials said Tuesday that a preliminary agreement had been struck for the United States to send M1 Abrams tanks to help Ukraine's troops push back Russian forces that remain entrenched in the country's east almost a year after Russia invaded its neighbour.<a href="https://tt.loopnews.com/content/germany-send-leopard-tanks-ukraine-5" target="_blank">Source</a>| After weeks of hesitation that saw growing impatience among Germany's allies, Berlin announced Wednesday that it would initially provide Ukraine with one company of Leopard 2 A6 tanks, which comprises 14 vehicles, from its own stocks. The goal is for Germany and its allies to provide Ukraine with a total of two battalions, or 88 tanks. The long-awaited decision came after US officials said Tuesday that a preliminary agreement had been struck for the United States to send M1 Abrams tanks to help Ukraine's troops push back Russian forces that remain entrenched in the country's east almost a year after Russia invaded its neighbour. Scholz had insisted that any decision to provide Ukraine with powerful Leopard 2 tanks would need to be taken in conjunction with Germany's allies, chiefly the United States.|
