# How do the American prisoners of war feel about being released?

## Summary
Alexander John-Robert Drueke and Andy Tai Ngoc Huynh, two Americans released in a prisoner swap between Ukraine and Russia, have expressed their happiness and relief at being back home <font color=#FF3399>[1]</font>. The men were captured in June while fighting for Ukraine in a battle near Kharkiv <font color=#FF3399>[5]</font>. But even after being taken prisoner, they said they had no regrets <font color=#FF3399>[5]</font>. US Secretary of State Antony Blinken welcomed the prisoner exchange, thanking Saudi Arabia for spearheading the initiative <font color=#FF3399>[4]</font>. Drueke and Huynh’s families were thrilled to hear their voices again <font color=#FF3399>[2,3]</font> and Huynh is looking forward to having spaghetti with meat for his homecoming in Alabama <font color=#FF3399>[3]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Alexander John-Robert Drueke, one of the Americans released in a prisoner swap between Ukraine and Russia, said he is "very happy" to be home after landing at Birmingham International Airport in Alabama.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-24-22/h_6d98d13e1b46c46ab22556d646c17287" target="_blank">Source</a>| Alexander John-Robert Drueke, one of the Americans released in a prisoner swap between Ukraine and Russia, said he is "very happy" to be home after landing at Birmingham International Airport in Alabama. Drueke and fellow US POW Andy Tai Ngoc Huynh were freed Wednesday and returned to the US Friday after being captured by Russia while fighting in Ukraine.|
|<font color=#FF3399>[2]</font> "We are thrilled to announce that Alex and Andy are free," Diana Shaw, a spokesperson for both families and Druekes aunt, told CNN.<a href="https://news.yahoo.com/americans-released-prisoner-swap-russia-ukraine-war-183135825.html" target="_blank">Source</a>| Two U.S. military veterans who were captured by Russian-backed forces while fighting for Ukraine and held captive for months have reportedly been freed. Multiple news outlets reported Wednesday that the families of Alexander Drueke and Andy Huynh, both military veterans from Alabama who had been serving as volunteers in Ukraine, have been informed by U.S. officials that the men were released in a prisoner swap between Russia and Ukraine. "We are thrilled to announce that Alex and Andy are free," Diana Shaw, a spokesperson for both families and Druekes aunt, told CNN. "They are safely in the custody of the U.S. Embassy in Saudi Arabia and after medical checks and debriefing they will return to the United States."|
|<font color=#FF3399>[3]</font> "It's just so good to know that they are OK and that they're going to come home," Black said.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-21-22/h_c83a75febe02691c43ed6a21646b8130" target="_blank">Source</a>| "It was just so amazing to finally get to hear his voice again and speak to him," she said. Huynh and another American, Alexander John-Robert Drueke, were captured in June while fighting in Ukraine.They were released, along with eight others, in a prisoner swap between Russia and Ukraine that was spearheaded by the government of Saudi Arabia. "It's just so good to know that they are OK and that they're going to come home," Black said. Huynh could be back as early as Friday, she said, adding he has a special request for his homecoming in Alabama: spaghetti with meat, which he'd been craving while in Ukraine.|
|<font color=#FF3399>[4]</font> "The United States is appreciative of Ukraine including all prisoners of war, regardless of nationality, in its negotiations, and we look forward to these U.S. citizens being reunited with their families," Blinken said in a statement.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-21-22/h_6b9640baeb257ea48332368d892d8a49" target="_blank">Source</a>| US Secretary of State Antony Blinken on Wednesday welcomed the prisoner exchange between Ukraine and Russia that led to the release of 10 people, including two Americans. "The United States is appreciative of Ukraine including all prisoners of war, regardless of nationality, in its negotiations, and we look forward to these U.S. citizens being reunited with their families," Blinken said in a statement. He also thanked Saudi Arabia for spearheading the initiative.|
|<font color=#FF3399>[5]</font> Even after being captured, their families said the men told them they have no regrets about going over to fight with the Ukrainians.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-23-22/h_38b11d717816e5c7faa251a50c93d19d" target="_blank">Source</a>| The Americanswere capturedin June while fighting for Ukraine ina battle near Kharkiv. Their pro-Russian captors, the self-declared Donetsk People's Republic, have governed a breakaway portion of Ukraine's Donetsk region since 2014. Even after being captured, their families said the men told them they have no regrets about going over to fight with the Ukrainians.|
