# What are the potential consequences of the Nord Stream gas pipeline being decommissioned?

## Summary
The Nord Stream gas pipeline has been decommissioned due to restrictions imposed by Swedish and Danish authorities, resulting in a significant risk of gas shortages this winter <font color=#FF3399>[2]</font>. The volume of gas leaked from the pipeline is estimated to be between 7.5 and 14 million metric tons of carbon dioxide equivalent <font color=#FF3399>[1]</font>. European Union countries are attempting to end their reliance on Russian fuel, sending prices soaring and triggering emergency plans <font color=#FF3399>[2]</font>. Turkey has suggested discussing the idea of an alternative pipeline <font color=#FF3399>[3]</font>. Nord Stream operator is unable to inspect the damage due to the restrictions <font color=#FF3399>[4]</font> and the situation is being considered sabotage <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Because the pipeline was not in active service given the geopolitical situation, the environmental impactwhile still concerningis not as great a problem as it could have been.<a href="https://www.technologyreview.com/2022/10/03/1060558/heres-how-the-nord-stream-gas-pipelines-could-be-fixed/" target="_blank">Source</a>| Because the pipeline was not in active service given the geopolitical situation, the environmental impactwhile still concerningis not as great a problem as it could have been. According to estimates, the volume of gas likely to have leaked from the pipeline could have resulted in anywhere between 7.5 million and 14 million metric tons of carbon dioxide equivalent, German and Danish authorities have told reporters.|
|<font color=#FF3399>[2]</font> Several European Union states have triggered emergency plans that may lead to rationing as they race to find alternative supplies, while Britain now faces a "significant risk" of gas shortages this winter, the regulator said.<a href="https://www.reuters.com/business/energy/russias-gazprom-says-pressure-nord-stream-pipelines-has-stabilised-2022-10-03/" target="_blank">Source</a>| Europe is investigating what caused three pipelines in the Nord Stream network to burst in an act of suspected sabotage near Swedish and Danish waters that Moscow quickly sought to pin on the West, suggesting the United States stood to gain. Nord Stream, which runs from Russia to Germany, has been at the centre of a growing gas supply crisis in Europe, which until recently relied heavily on Russian fuel, sending prices soaring. Several European Union states have triggered emergency plans that may lead to rationing as they race to find alternative supplies, while Britain now faces a "significant risk" of gas shortages this winter, the regulator said. "The coast guard is responsible for the mission, but we are supporting them with units," a spokesperson for the Swedish navy, Jimmie Adamsson, told Reuters.|
|<font color=#FF3399>[3]</font> The problem is that European Union countries are trying to end their reliance on Russian oil and gas after Putin sent troops into Ukraine as part of what he calls a special military operation.<a href="https://www.reuters.com/world/europe/putin-moots-major-gas-hub-turkey-with-nord-stream-supplies-2022-10-12/" target="_blank">Source</a>| "That is, of course, if our partners are interested in this. And economic feasibility, of course." The problem is that European Union countries are trying to end their reliance on Russian oil and gas after Putin sent troops into Ukraine as part of what he calls a special military operation. Turkish Energy Minister Fatih Donmez, speaking at the same conference in Moscow, said the idea was new to him but should be discussed.|
|<font color=#FF3399>[4]</font> The operator of the Nord Stream gas pipeline said Tuesday that it is "unable to inspect" the damage following gas leaks last week due to restrictions imposed by Swedish and Danish authorities.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-04-22/h_e06796753d4021e8a4b1da35046850fa" target="_blank">Source</a>| The operator of the Nord Stream gas pipeline said Tuesday that it is "unable to inspect" the damage following gas leaks last week due to restrictions imposed by Swedish and Danish authorities. The company whose shareholders include Russian gas giant Gazprom and four European energy companies said that according to the Swedish authorities, "a ban on shipping, anchoring, diving, using of underwater vehicles, geophysical mapping, etc.|
|<font color=#FF3399>[5]</font> Neither of the Nord Stream pipelines is in operation although both still contain gas.<a href="https://www.theguardian.com/politics/2022/oct/01/truss-nord-stream-gas-pipeline-russia-damage-sabotage" target="_blank">Source</a>| "This is sabotage and it is critical infrastructure. So of course, this is a very serious situation." Neither of the Nord Stream pipelines is in operation although both still contain gas. Nord Stream 1 has not transported any gas since late August, when Russia closed it down for maintenance; Nord Stream 2 was halted after Russia invaded Ukraine in February.|
