# What are the respective situations of Paul Whelan and Brittney Griner?

## Summary
Paul Whelan and Brittney Griner are both Americans wrongfully detained in Russia. Whelan has been imprisoned since 2018 and was recently sentenced to 16 years in prison on espionage charges. <font color=#FF3399>[1]</font> Griner was sentenced to nine years in prison after pleading guilty, but she has since appealed the sentence. (2 & 4) The US government has been in negotiations with Russia to exchange Whelan and Griner for Russian citizen Viktor Bout, who is imprisoned in the United States. (3 & 5) Secretary of State Antony Blinken has announced the administration's efforts to secure the release of the two and said it is "at the very top of my priority list". <font color=#FF3399>[1]</font>

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> US Secretary of State Antony Blinken said the administration is working relentlessly to secure the release of Americans detained abroad, including Brittney Griner and Paul Whelan, who are being held in Russia.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-16-22/h_64f2c56f9c985bb3bf07b0398adba77e" target="_blank">Source</a>| US Secretary of State Antony Blinken said the administration is working relentlessly to secure the release of Americans detained abroad, including Brittney Griner and Paul Whelan, who are being held in Russia. Speaking at a news conference Friday, Blinken said the matter is "at the very top of my priority list."|
|<font color=#FF3399>[2]</font> Where the negotiations stand: A senior administration official told CNN Thursday that there has been "movement but not breakthrough" on the efforts to free Whelan and WNBA star Brittney Griner.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-17-22/h_4392813436930e3a6c7e2faf703a3705" target="_blank">Source</a>| Paul Whelan has been imprisoned in Russia for more than three years after being convicted on espionage charges that he vehemently denies. He was sentenced in June 2020 to 16 years in prison in a trial US officials denounced as unfair. Where the negotiations stand: A senior administration official told CNN Thursday that there has been "movement but not breakthrough" on the efforts to free Whelan and WNBA star Brittney Griner. The official said that the United States has urged Russia to put forward "a serious counteroffer" to the proposal on the table to secure the release of the two, but "we've not gotten a serious response back."|
|<font color=#FF3399>[3]</font> The U.S. government regards both as wrongfully detained, placing their cases with the office of its top hostage negotiator.<a href="https://www.fox5vegas.com/2022/09/16/biden-meeting-with-families-whelan-griner-white-house/" target="_blank">Source</a>| She was sentenced last month to nine years in prison after pleading guilty and has appealed the punishment. Whelan is serving a 16-year sentence on espionage-related charges that he and his family say are false. The U.S. government regards both as wrongfully detained, placing their cases with the office of its top hostage negotiator. Secretary of State Antony Blinken took the unusual step of announcing two months ago that the administration had made a substantial proposal to Russia.|
|<font color=#FF3399>[4]</font> He is still serving a nine-year sentence, but the White House has been in negotiations with Russia to exchange Whelan and Brittney Griner for Russian citizen Viktor Bout, who's imprisoned in the United States.<a href="https://people.com/politics/robert-gilman-case-former-us-marine-jailed-in-russia/" target="_blank">Source</a>| He later said he believed he had been arrested as a bargaining chip on trumped up charges. A third former Marine, Paul Whelan, who was arrested in 2018 for alleged espionage also believes he was imprisoned on false charges to be used as a potential pawn in an exchange deal. He is still serving a nine-year sentence, but the White House has been in negotiations with Russia to exchange Whelan and Brittney Griner for Russian citizen Viktor Bout, who's imprisoned in the United States. As yet, there has been no international news coverage apart from in Russian media outlets on the case of Gilman.|
|<font color=#FF3399>[5]</font> The U.S. government regards both as wrongfully detained.<a href="https://www.ny1.com/nyc/all-boroughs/news/2022/09/20/biden-griner-whelan-jake-sullivan-russia-us" target="_blank">Source</a>| She has since appealed the sentence. Whelan is serving a 16-year sentence on espionage-related charges that he and his family say are false. The U.S. government regards both as wrongfully detained. Secretary of State Antony Blinken took the unusual step of announcing two months ago that the administration had made a substantial proposal to Russia.|
