# What measures can the United States take to prevent further shipments of weapons from Iran to Russia?

## Summary
The United States is looking to disrupt Iran's weapons proliferation networks by targeting them with sanctions and other financial measures <font color=#FF3399>[1]</font>. Secretary of State Tony Blinken has said that the US is considering all available options to prevent further shipments of weapons from Iran to Russia <font color=#FF3399>[2]</font>. Iran has denied supplying Russia with weapons for use in Ukraine and is in violation of UN Security Council Resolution 2231 <font color=#FF3399>[3]</font>. It is preparing to send approximately 1,000 additional weapons, including surface-to-surface short range ballistic missiles and drones, to Russia <font color=#FF3399>[4]</font>. These weapons would give the Kremlin a substantial boost on the battlefield <font color=#FF3399>[5]</font>. To prevent further shipments, the US is looking to impose sanctions and other financial measures, as well as considering all available options <font color=#FF3399>[2, 5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> The spokesperson added the US will "vigorously" enforce all sanctions on both Russian and Iranian arms trade "to make it harder for Iran to sell these weapons to Russia."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-01-22/h_17f1a278ba96bff99d149c78675db5e7" target="_blank">Source</a>| The United States will "use every relevant and appropriate tool in our toolkit to expose, to confront, to counter" Iran's provision of weapons to Russia, State Department spokesperson Ned Price said Tuesday. Speaking at a State Department briefing, Price said the US has "taken aim at Iran's UAV (unmanned aerial vehicle) proliferation networks over the course of months now," and "we are always looking at targets that may be appropriate for this sort of response, sanctions, other, other financial measures." The spokesperson added the US will "vigorously" enforce all sanctions on both Russian and Iranian arms trade "to make it harder for Iran to sell these weapons to Russia." CNN reported Tuesdaythat Iran is preparing to send approximately 1,000 additional weapons, including surface-to-surface short range ballistic missiles and more attack drones, to Russia.|
|<font color=#FF3399>[2]</font> The US is "looking at everything that we can do, not just with sanctions" in order to disrupt the Iranian weaponry from going to Russia, Secretary of State Tony Blinken said last week.<a href="https://www.cnn.com/2022/11/01/politics/iran-missiles-russia/index.html" target="_blank">Source</a>| Iran has previously denied supplying Russia with weapons for use in Ukraine, saying it "has not and will not" do so. The Washington Post was first to report Irans plans to send missiles and additional drones to Russia. The US is "looking at everything that we can do, not just with sanctions" in order to disrupt the Iranian weaponry from going to Russia, Secretary of State Tony Blinken said last week. He said that the US is "trying to break up these networks."|
|<font color=#FF3399>[3]</font> Some background: Last week, Secretary of State Antony Blinken said the US was "looking at everything that we can do, not just with sanctions" in order to disrupt the Iranian weaponry from going to Russia.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-01-22/h_34a82a434cdfae159e8c583b54aa668f" target="_blank">Source</a>| Iran has previously denied supplying Russia with weapons for use in Ukraine, saying it "has not and will not" do so. The Washington Post was first to report Iran's plans to send missiles and additional drones to Russia. Some background: Last week, Secretary of State Antony Blinken said the US was "looking at everything that we can do, not just with sanctions" in order to disrupt the Iranian weaponry from going to Russia. But it is unclear if the US will be able to prohibit further shipments from going ahead, even as concerns mount about Iranians sending even more advanced weaponry to Russia.|
|<font color=#FF3399>[4]</font> The shipment is being closely monitored because it would be the first instance of Iran sending advanced precision guided missiles to Russia, which could give the Kremlin a substantial boost on the battlefield.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-02-22/h_4e6df92693205fc0a4e2127038012439" target="_blank">Source</a>| Iran is preparing to send approximately 1,000 additional weapons, including surface-to-surface short range ballistic missiles andmore attack drones, to Russia to use in its war against Ukraine, officials from a Western country that closely monitors Iran's weapons program told CNN. The shipment is being closely monitored because it would be the first instance of Iran sending advanced precision guided missiles to Russia, which could give the Kremlin a substantial boost on the battlefield. The last shipment of weapons from Iran to Russia included about 450 drones, officials said, which the Russians have already used to deadly effect in Ukraine.|
|<font color=#FF3399>[5]</font> Under the resolution, Iran is banned from exporting ballistic missiles until 2023.<a href="https://www.armscontrol.org/act/2022-11/news/iran-supplies-arms-russia" target="_blank">Source</a>| Ukrainians are discussing items like the German Gepard as a successful system against these threats," said Samuel Bendett, an expert on Russias use of unmanned and robotic military systems. Irans sale of the missiles and drones to Russia constitutes a violation of UN Security Council Resolution 2231, which was adopted in support of the 2015 Iran nuclear deal known as the Joint Comprehensive Plan of Action. Under the resolution, Iran is banned from exporting ballistic missiles until 2023. "[B]oth of the types of [drones] thatIran had been provisioning to Russia meet the parameters under [limitations contained in the resolution] because they are capable of a range equal to and greater than 300 kilometers," Vedant Patel, U.S. State Department principal deputy spokesperson, said on Oct. 18.|
