# What are the strategic goals of Russia in launching the missile attacks on Ukraine?

## Summary
Russia has recently launched multiple missile attacks on Ukraine, with around 100 missiles fired on Tuesday <font color=#FF3399>[1]</font>, targeting energy facilities <font color=#FF3399>[4,5]</font>. This appears to be the largest such attack since October 10th <font color=#FF3399>[4,5]</font>. The Russian military is reportedly building up defensive positions on the other side of the Dnipro River <font color=#FF3399>[2]</font>, and President Vladimir Putin has stated that nuclear weapons are not the solution to the conflict in Ukraine <font color=#FF3399>[1]</font>. The US has pledged to provide Ukraine with air defense systems <font color=#FF3399>[5]</font>, while Ukrainian President Volodymyr Zelensky has stated that 85 such strikes have been launched on Ukraine so far <font color=#FF3399>[5]</font>. This suggests that Russia's strategic goal in launching the missile attacks is to create better defensive lines throughout southern and eastern Ukraine before the arrival of winter <font color=#FF3399>[2]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Putin said an earlier warning of his readiness to use "all means available to protect Russia" didn't amount to nuclear saber-rattling but was merely a response to Western statements about their possible use of nuclear weapons.<a href="https://www.euronews.com/2022/11/02/ukraine-war-zelenskyy-calls-on-europe-to-stay-united-through-difficult-winter" target="_blank">Source</a>| Russian President Vladimir Putin recently denied having any intentions of using nuclear weapons in Ukraine but described the conflict there as part of alleged efforts by the West to secure its global domination, which he insisted are doomed to fail. Speaking last month at a conference of international foreign policy experts, Putin said it's pointless for Russia to strike Ukraine with nuclear weapons. Putin said an earlier warning of his readiness to use "all means available to protect Russia" didn't amount to nuclear saber-rattling but was merely a response to Western statements about their possible use of nuclear weapons. Kirby told reporters, "we have maintained, I believe, an appropriate level of concern about the potential use of weapons of mass destruction in Ukraine to include nuclear weapons."|
|<font color=#FF3399>[2]</font> Instead of trying to keep control of the city, they said Russian troops were building up their defensive positions on the other side of the Dnipro River, as part of a wider Russian move to establish better defensive lines throughout southern and eastern Ukraine before the arrival of winter.<a href="https://www.bbc.com/news/world-europe-63508836" target="_blank">Source</a>| Instead of trying to keep control of the city, they said Russian troops were building up their defensive positions on the other side of the Dnipro River, as part of a wider Russian move to establish better defensive lines throughout southern and eastern Ukraine before the arrival of winter.|
|<font color=#FF3399>[3]</font> The wave of strikes appears to be the largest since Oct. 10, when Russia stepped up its campaign to destroy electricity, water and gas infrastructure across Ukraine.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-15-22/h_cd44ac10f6d0449f9462d6783595aa1e" target="_blank">Source</a>| Russia fired "around 100 missiles" at cities across Ukraine on Tuesday, according to Yurii Ihnat, spokesperson for the Ukrainian Air Force command. At least a dozen cities and districts were targeted, according to a CNN analysis of the missile strikes. The wave of strikes appears to be the largest since Oct. 10, when Russia stepped up its campaign to destroy electricity, water and gas infrastructure across Ukraine. Herman Halushchenko, Ukrainian Energy Minister, confirmed that most of the targets Tuesday were energy facilities.|
|<font color=#FF3399>[4]</font> The wave of strikes appears to be the largest since Oct. 10, when Russia stepped up its campaign to destroy electricity, water and gas infrastructure across Ukraine.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-15-22/h_ec56c1ad88a30c2a9b9257a6cf1a5bf4" target="_blank">Source</a>| Some background: Russia fired "around 100 missiles" at cities across Ukraine on Tuesday, according to Yurii Ihnat, spokesperson for the Ukrainian Air Force command. At least a dozen cities and districts were targeted, according to a CNN analysis of the missile strikes. The wave of strikes appears to be the largest since Oct. 10, when Russia stepped up its campaign to destroy electricity, water and gas infrastructure across Ukraine. Herman Halushchenko, Ukrainian Energy Minister, confirmed that most of the targets Tuesday were energy facilities.|
|<font color=#FF3399>[5]</font> The wave of strikes appears to be the largest since Oct. 10, when Russia stepped up its campaign to destroy electricity, water and gas infrastructure across Ukraine.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-15-22/h_3314bf4dbe24809a7c76e09ba41fc896" target="_blank">Source</a>| Ukrainian President Volodymyr Zelensky said about 85 strikes have been launched on Ukraine so far. According to a CNN analysis of the strikes, at least a dozen cities and districts were targeted. The wave of strikes appears to be the largest since Oct. 10, when Russia stepped up its campaign to destroy electricity, water and gas infrastructure across Ukraine. Looking forward, Sullivan pledged the United States allies "will continue to provide Ukraine with what it needs to defend itself, including air defense systems.|
