# How has the conflict in Ukraine affected Russia's economy?

## Summary
The conflict in Ukraine has had a major effect on Russia's economy. Russia has ceased providing crypto services to its citizens <font color=#FF3399>[1]</font> and has been locked out of international financial markets due to the ban on certain systems <font color=#FF3399>[1]</font>. This has left millions of Ukrainians struggling to prepare for winter and to repair their homes <font color=#FF3399>[2]</font>. In July, the two countries signed a deal to resume grain exports from Ukraine, but Russia recently announced its suspension of the deal <font color=#FF3399>[3,4,5]</font>. This decision has caused a global food crisis and left Ukraine accusing Russia of creating a “hunger games” <font color=#FF3399>[4]</font>. President Zelensky has called this decision “deliberate” <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> The ban on these systems has effectively locked out the nation from major international financial markets.<a href="https://cointelegraph.com/news/what-the-russia-ukraine-conflict-has-revealed-about-crypto" target="_blank">Source</a>| Other regulated crypto exchanges such as Kraken, Crypto.com and Blockchain.com have also ceased providing crypto services to Russian citizens as a result. Meanwhile, Russian authorities seem unsure of how to handle the flurry of crypto wallet prohibitions and the occlusion of major Russian banks from the SWIFT money transfer system. The ban on these systems has effectively locked out the nation from major international financial markets. In July, the Kremlin passed a law that banned the use of cryptocurrencies for making payments.|
|<font color=#FF3399>[2]</font> Those problems have been compounded in recent weeks by Russias barrage of attacks on Ukraines power and heating infrastructure.<a href="https://www.cnn.com/2022/10/28/europe/ukraine-russia-war-winter-intl-cmd/index.html" target="_blank">Source</a>| As the weather becomes colder, millions of Ukrainians like Melnychuk are trying to prepare for what they know will be an extremely difficult winter, rushing to repair their homes and secure enough fuel to stay warm. The Ukrainian government said in July that over 800,000 homes had been damaged or destroyed since the start of the war in February, leaving thousands of people without a roof over their head. Those problems have been compounded in recent weeks by Russias barrage of attacks on Ukraines power and heating infrastructure. On Monday, Russia launched more than 50 cruise missiles at infrastructure targets across the country, the Ukrainian Air Force said.|
|<font color=#FF3399>[3]</font> Some background: In July, Ukraine and Russia agreed to the deal that allowed the resumption of vital grain exports from Ukrainian Black Sea ports, a major diplomatic breakthrough at the time, aimed at easing a global food crisis sparked by the war.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-28-22/index.html" target="_blank">Source</a>| "The impact of the agreement signed in Istanbul has been clearly demonstrated. Exports of grains and other food products under the Black Sea Grain Initiative have surpassed 9 million tonnes," Guterres said in a statement Friday. Some background: In July, Ukraine and Russia agreed to the deal that allowed the resumption of vital grain exports from Ukrainian Black Sea ports, a major diplomatic breakthrough at the time, aimed at easing a global food crisis sparked by the war. Ministers from both countries signed an agreement brokered by the United Nations and Turkey in Istanbul.|
|<font color=#FF3399>[4]</font> KYIV, Ukraine (AP) Russia announced Saturday that it will immediately suspend its implementation of a U.N.-brokered grain deal that has seen more than 9 million tons of grain exported from Ukraine during the war and has brought down soaring global food prices.<a href="https://apnews.com/article/russia-ukraine-europe-government-and-politics-3b563bd6f79f815c7e9f33505dd25334" target="_blank">Source</a>| She keeps living in this house and collects wooden debris to make an outdoor fire for cooking. (AP Photo/Efrem Lukatsky) KYIV, Ukraine (AP) Russia announced Saturday that it will immediately suspend its implementation of a U.N.-brokered grain deal that has seen more than 9 million tons of grain exported from Ukraine during the war and has brought down soaring global food prices. Ukraine accused Russia of creating a world "hunger games."|
|<font color=#FF3399>[5]</font> Ukrainian President Volodymyr Zelensky called the decision of Russia to suspend its participation from the grain export deal with Ukraine "deliberate" and "a rather predictable statement" in his nightly address Saturday.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-29-22/index.html" target="_blank">Source</a>| Ukrainian President Volodymyr Zelensky called the decision of Russia to suspend its participation from the grain export deal with Ukraine "deliberate" and "a rather predictable statement" in his nightly address Saturday. "This is not the decision they made today," Zelensky said.|
