# What steps can be taken to ensure the safety and security of the Zaporizhzhia nuclear power plant in the context of the Russia-Ukraine crisis?

## Summary
The Zaporizhzhia nuclear power plant <font color=#FF3399>[1]</font> has been subject to periodic attacks on its electricity grid <font color=#FF3399>[1]</font>, and has been forced to operate on back-up generators <font color=#FF3399>[2]</font>. The staff of the plant have allegedly been encouraged to sign contracts with Rosatom and Energoatom has been accused of corruption <font color=#FF3399>[3]</font>. Units have been disconnected due to cut power lines and the personnel were forced to start up the station mechanisms to keep the last operating unit at minimum power <font color=#FF3399>[4]</font>. Russia has asserted control over the plant and has claimed only they can ensure its physical and nuclear safety <font color=#FF3399>[5]</font>. To ensure the safety of the Zaporizhzhia nuclear power plant, more measures should be taken to protect the electricity grid <font color=#FF3399>[1]</font> and a more rigorous approach to nuclear safety should be taken <font color=#FF3399>[4]</font>. Furthermore, any contracts signed by the staff of the plant should be carefully monitored <font color=#FF3399>[3]</font>, and Ukraine should seek to establish a protection zone with the support of the International Atomic Energy Agency <font color=#FF3399>[2]</font>. Finally, it is imperative that Russia's claim of control over the plant be addressed <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> For me the important thing is to avoid a nuclear accident and reach the agreement, not to be a judge."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-02-22/h_c7907d667d259a8dcfa682d9eae5669d" target="_blank">Source</a>| Regarding the current status of the plant, Grossi said that "right now the plant has electricity to ensure the operation of cooling and emergency systems," but "some nodes of the electricity grid that supply it are being attacked periodically, with surgically precise strikes." Asked who was responsible for those strikes, Grossi said, "It is not my job to assign responsibility. For me the important thing is to avoid a nuclear accident and reach the agreement, not to be a judge." He also spoke about three other nuclear plants in Ukraine: Rivne, South Ukraine and Khmelnytskyi.|
|<font color=#FF3399>[2]</font> MILAN, Dec 2 (Reuters) - The International Atomic Energy Agency hopes to reach an agreement with Russia and Ukraine to create a protection zone at the Zaporizhzhia nuclear power plant by the end of the year, the head of the U.N. atomic watchdog was quoted as saying.<a href="https://www.reuters.com/world/europe/iaea-chief-hopes-find-solution-zaporizhzhia-nuclear-plant-by-year-end-2022-12-02/" target="_blank">Source</a>| MILAN, Dec 2 (Reuters) - The International Atomic Energy Agency hopes to reach an agreement with Russia and Ukraine to create a protection zone at the Zaporizhzhia nuclear power plant by the end of the year, the head of the U.N. atomic watchdog was quoted as saying. The nuclear plant, Europe's biggest, provided about a fifth of Ukraine's electricity before Russia's invasion, and has been forced to operate on back-up generators a number of times.|
|<font color=#FF3399>[3]</font> Despite working in an industry that would obviously be targeted by Putin, no measures were taken to promote their safety, even though many stayed voluntarily to work in the plant, in an attempt to help the war effort.<a href="https://unherd.com/2022/12/were-russians-working-in-zaporizhzhya/" target="_blank">Source</a>| Recent reports now allege that staff at the plant were "encouraged" to sign contracts with Rosatom. There are also allegations that the management of Ukraines National Nuclear Energy Company, Energoatom, left the staff of Zaporizhzhya without support during the Russian invasion. Despite working in an industry that would obviously be targeted by Putin, no measures were taken to promote their safety, even though many stayed voluntarily to work in the plant, in an attempt to help the war effort. Allegations of corruption at Energoatom have been raised at a national level.|
|<font color=#FF3399>[4]</font> Taking into account the basics of nuclear safety and the necessary conservative approach, the station had to be shut down as the threat of further military action loomed.<a href="https://www.neimagazine.com/features/featurezaporizhzhia-chronicle-of-a-tragedy-10418377/" target="_blank">Source</a>| Units were disconnected more than once due to cut power lines. To keep the last operating unit at minimum power, the personnel were even forced to start up the station mechanisms, such as, for example, the pumps of the cooling pond were switched to their maximum output. Taking into account the basics of nuclear safety and the necessary conservative approach, the station had to be shut down as the threat of further military action loomed. But what seems rational for one reactor is not so clear for a large nuclear power plant that provides a quarter of the electricity of a large country.|
|<font color=#FF3399>[5]</font> We presume that only we are able to ensure the physical and nuclear safety of ZNPP."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-08-22/h_b6b0b29731bbfd6fee7bf6e946461a90" target="_blank">Source</a>| "There can be no talk of any withdrawal of the Zaporizhzhia NPP from Russian control or transfer of control over it to some 'third party,'" Zakharova responded. "The station is located on Russian territory and is fully controlled by Russia. We presume that only we are able to ensure the physical and nuclear safety of ZNPP." Some background: Zaporizhzhia is one of the four Ukrainian regions annexed by Russian President Vladimir Putin in defiance of international law.|
