# Can Ukrainian forces sustain momentum and drive the Russians out of Luhansk?

## Summary
Ukrainian forces have made significant gains in the recent weeks, pushing Russian forces out of the strategic city of Izium and reclaiming more than 3,000 square kilometers of territory in the process <font color=#FF3399>[2]</font>. This has been followed by a new offensive against Russian defenses in the border of the Donetsk and Luhansk regions, with the city of Lysychansk as the apparent target <font color=#FF3399>[5]</font>. The success of the Ukrainian counteroffensives has been in part due to Kiev's defensive preparations since 2014, as well as American-supplied rocket launchers which have enabled Ukraine to reach behind Russian lines <font color=#FF3399>[3, 4]</font>. With momentum on their side, Ukrainian forces may be able to drive the Russians out of Luhansk, although the outcome of this campaign remains to be seen.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> They had captured nearly all of Luhansk by early July of this year, but their efforts since to take control of neighboring Donetsk have stalled.<a href="https://www.nytimes.com/live/2022/09/04/world/ukraine-russia-war-news" target="_blank">Source</a>| But Ukraines new attempt to regain ground in the southern province of Kherson, which was lost to Moscow at the start of the war, has shifted the dynamics in the east. After failing to capture Ukraines capital early in the war, Russian forces switched focus to try to seize control of the eastern Donbas region, which is made up of Donetsk and Luhansk provinces. They had captured nearly all of Luhansk by early July of this year, but their efforts since to take control of neighboring Donetsk have stalled. That is in part because of a weekslong pause by Moscow in its offensive to rotate and refresh troops, but also because Ukraine has been preparing defensive positions in Donetsk since 2014 when rebels loyal to Russia seized government buildings there and in Luhansk, beginning a long trench war with Ukrainian forces that are difficult to dislodge.|
|<font color=#FF3399>[2]</font> Over the past week, Ukrainian forces have recaptured more than 3,000 square kilometers of territory -- more than Russian forces have captured in all their operations since April.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-12-22/h_cd5d2dafbd60746d2642da73de3a2589" target="_blank">Source</a>| Russian troops were forced to flee the strategic city of Izium -- their main bastion in northeastern Ukraine -- on Saturday after a swift Ukrainian counteroffensive. It was Moscow's worst defeat since its retreat from Kyiv in March -- and a sign that the war might be entering a new phase. Over the past week, Ukrainian forces have recaptured more than 3,000 square kilometers of territory -- more than Russian forces have captured in all their operations since April. Back in Russia, senior Russian and Chinese officials have put on a united front to pave the way for an expected meeting between Putin and Xi on the sidelines of a regional summit in Uzbekistan -- their first face-to-face meeting since Russia's invasion of Ukraine.|
|<font color=#FF3399>[3]</font> Ukraines forces have continued to press their counterattack in Kharkiv, reportedly taking control of almost the entire province.<a href="https://www.theguardian.com/world/2022/sep/13/collaborators-with-russian-forces-are-fleeing-say-ukrainian-officials" target="_blank">Source</a>| Russians and their collaborators are fleeing from Luhansk region, heading towards Russia". Luhansk makes up the Donbas region with Donetsk to the south. Ukraines forces have continued to press their counterattack in Kharkiv, reportedly taking control of almost the entire province. Russia has launched dozens of air and missile strikes on power plants and other locations in apparent retaliation for Kyivs success.|
|<font color=#FF3399>[4]</font> By July, Russia had taken all of Luhansk, but the advance stalled in neighboring Donetsk as longer range, US-supplied HIMARS rocket launchers enabled Ukraine to reach behind Russian lines and disrupt logistics.<a href="https://www.washingtonpost.com/business/energy/why-ukraines-donbas-region-matters-to-putin/2022/09/12/3bd4a4f4-3285-11ed-a0d6-415299bfebd5_story.html" target="_blank">Source</a>| As the city fell in May, Russia concentrated on securing the entire Donbas, diverting troops from a failed attempt to take the Ukrainian capital, Kyiv. Russian artillery pounded Ukrainian defenses before inching forward at the cost of high casualties on both sides. By July, Russia had taken all of Luhansk, but the advance stalled in neighboring Donetsk as longer range, US-supplied HIMARS rocket launchers enabled Ukraine to reach behind Russian lines and disrupt logistics. In September, Ukraine launched counteroffensives, recapturing a large swathe of territory east of the city of Kharkiv.|
|<font color=#FF3399>[5]</font> Saturday's rapid advance did not end with Izium, as Ukraine appeared to have opened a new front against Russian defenses on the border of the Donetsk and Luhansk regions.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-11-22/h_bb8d2c8c355fa8b1e5833a5a144239ab" target="_blank">Source</a>| Saturday's rapid advance did not end with Izium, as Ukraine appeared to have opened a new front against Russian defenses on the border of the Donetsk and Luhansk regions. The head of the regional military administration for Luhansk, Serhiy Hayday, indicated the city of Lysychansk was the target of the new offensive.|
