# How will the US-Ukraine partnership be strengthened through President Zelensky's visit?

## Summary
The US-Ukraine partnership is being strengthened through President Zelensky's visit through several measures. President Biden is sending almost $2 billion in additional security assistance to Ukraine, including a sophisticated new air defense system <font color=#FF3399>[2]</font>. This visit is also symbolically bolstering America's role as the "arsenal of democracy" <font color=#FF3399>[3]</font> and sending a public rebuke to Russian President Vladimir Putin <font color=#FF3399>[2]</font>. Congress is also on the verge of approving $45 billion in aid to Ukraine and NATO allies <font color=#FF3399>[4]</font>, in addition to the humanitarian and military aid that has already been sent since the conflict began <font color=#FF3399>[4]</font>. President Zelensky's visit to the White House and address to Congress in prime time <font color=#FF3399>[5]</font> serves as a powerful message to Moscow that US investment in Ukraine's defense will only grow <font color=#FF3399>[1]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> With this visit, Ukraine received the Patriot air-defense system, the most advanced weapon system that the United States has yet to provide.<a href="https://www.atlanticcouncil.org/blogs/new-atlanticist/experts-react-why-zelenskyy-chose-washington-for-his-first-wartime-trip-abroad/" target="_blank">Source</a>| A powerful message sent to Moscow, with one awkward moment Zelenskyys visit was a success for presidents Biden and Zelenskyy and strengthened the US-Ukraine relationship. With this visit, Ukraine received the Patriot air-defense system, the most advanced weapon system that the United States has yet to provide. This served as a clear message to Moscow that US investment in Ukraines defense will only grow.|
|<font color=#FF3399>[2]</font> President Volodymyr Zelenskys White House visit Wednesday will symbolically bolster Americas role as the arsenal of democracy in the bitter war for Ukraines survival and send a stunning public rebuke to Russian President Vladimir Putin.<a href="https://www.cnn.com/2022/12/21/politics/us-visit-zelensky-analysis/index.html" target="_blank">Source</a>| CNN President Volodymyr Zelenskys White House visit Wednesday will symbolically bolster Americas role as the arsenal of democracy in the bitter war for Ukraines survival and send a stunning public rebuke to Russian President Vladimir Putin. The trip Zelenskys first outside Ukraine since Russias invasion in February also highlights President Joe Bidens historic role in reviving the Western alliance that kept the Soviet Union at bay and is now countering new expansionism by Moscow in an effective proxy war between nuclear superpowers.|
|<font color=#FF3399>[3]</font> Ukrainian President Volodymyr Zelensky will pay a dramatic surprise visit to Washington on Wednesday, using his first trip outside his homeland since it was invaded 300 days ago to rally his top international partner behind sustained military and economic assistance.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-21-22/h_da153cf1cee7747dbec4e5e8dfa335fa" target="_blank">Source</a>| Ukrainian President Volodymyr Zelensky will pay a dramatic surprise visit to Washington on Wednesday, using his first trip outside his homeland since it was invaded 300 days ago to rally his top international partner behind sustained military and economic assistance. He will visit the Oval Office in the afternoon for extended talks with US President Joe Biden, who will announce he is sending nearly $2 billion in additional security assistance to Ukraine, includinga sophisticated new air defense system.|
|<font color=#FF3399>[4]</font> In conjunction with Zelenskyys visit, Biden also announced a $1.85 billion military package featuring a Patriot missile battery to bolster Ukraines defenses against Russian attacks.<a href="https://www.vox.com/policy-and-politics/2022/12/21/23520639/ukrainian-president-volodymyr-zelenskyy-biden-congress" target="_blank">Source</a>| Its an investment in the global security and democracy," Zelenskyy said. Congress is on the verge of approving another $45 billion in aid to Ukraine and NATO allies, in addition to more than $65 billion in humanitarian and military aid that has already been sent since the conflict began. In conjunction with Zelenskyys visit, Biden also announced a $1.85 billion military package featuring a Patriot missile battery to bolster Ukraines defenses against Russian attacks. "Thanks from our ordinary people to your ordinary people," Zelenskyy said earlier at the White House.|
|<font color=#FF3399>[5]</font> He will visit the Oval Office this afternoon for extended talks with US President Joe Biden, who will announce he is sending nearly $2 billion in additional security assistance to Ukraine, includinga sophisticated new air defense system.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-21-22/h_d89252349bdca29259641d2256cdc20d" target="_blank">Source</a>| Ukrainian President Volodymyr Zelensky has arrived in the United States, a source familiar with his travels tells CNN. Zelensky landed at Joint Base Andrews, a separate source familiar said. He will visit the Oval Office this afternoon for extended talks with US President Joe Biden, who will announce he is sending nearly $2 billion in additional security assistance to Ukraine, includinga sophisticated new air defense system. The two will convene a White House news conference before Zelensky addresses a joint meeting of Congress on Capitol Hill in prime time.|
