# How is the Ukrainian government responding to the missile attacks, and what measures is it taking to ensure the safety of its citizens?

## Summary
The Ukrainian government is responding to the missile attacks with a variety of measures to protect its citizens. President Volodymyr Zelensky has declared that around 10 million Ukrainians are currently without electricity, with some cities also suspending the supply of heating and internet and communication issues. <font color=#FF3399>[1]</font> Russia has ordered tens of thousands of civilians living near the eastern bank of the Dnipro River to relocate, <font color=#FF3399>[2]</font> and Moscow has been ferrying people out of an area it controls in Kherson on the west bank of the Dnipro River. <font color=#FF3399>[3]</font> Furthermore, Russia has fired "around 100 missiles" at cities across Ukraine on Tuesday, <font color=#FF3399>[4]</font> and the leaders of the G20 have offered "full support" for Poland following an explosion in the country's east. <font color=#FF3399>[5]</font> The Ukrainian government is continuing to work to ensure the safety of its citizens amidst the missile attacks.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Ukrainian President Volodymyr Zelensky said about 10 million Ukrainians are without electricity Tuesday night after waves of Russian missile attacks earlier in the day.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-15-22/h_ec56c1ad88a30c2a9b9257a6cf1a5bf4" target="_blank">Source</a>| Ukrainian President Volodymyr Zelensky said about 10 million Ukrainians are without electricity Tuesday night after waves of Russian missile attacks earlier in the day. In his daily video address, Zelensky said, Zelensky added thatLviv and some other cities suspended the supply of heating and that there also were issues with the internet and other modes of communication.|
|<font color=#FF3399>[2]</font> Russia says it has been taking residents to safety from the path of a Ukrainian advance.<a href="https://www.reuters.com/world/europe/grain-ships-sail-ukraine-ports-russian-missiles-knock-out-power-across-country-2022-10-31/" target="_blank">Source</a>| Moscow has already been ferrying people out of an area it controls in Kherson on the west bank of the Dnipro River, and this week announced that the evacuation zone would also include a 15 km buffer area on the east bank. But the comments appear to be the first time Putin has endorsed the evacuations personally. Russia says it has been taking residents to safety from the path of a Ukrainian advance. Kyiv says the measures have included forced deportations of civilians, a war crime, which Russia denies.|
|<font color=#FF3399>[3]</font> Russia has ordered tens of thousands of Ukrainian civilians living near the eastern bank of the Dnipro River to relocate, an order Kyiv says amounts to "forced displacement."<a href="https://www.voanews.com/a/ukraine-calls-for-isolating-russia-after-latest-missile-attacks/6814180.html" target="_blank">Source</a>| Russia has ordered tens of thousands of Ukrainian civilians living near the eastern bank of the Dnipro River to relocate, an order Kyiv says amounts to "forced displacement." Russian-installed authorities reported relocating 70,000 residents due to concerns of a major Ukrainian counterattack.|
|<font color=#FF3399>[4]</font> Russia unleashed a torrent of missiles on Ukraine Tuesday, the same day that Ukrainian President Volodymyr Zelesnky delivered a video speech to the G20 and a week after Russian forces retreated from the southern city of Kherson.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-15-22/h_2d2bf0cf254d57153418f418f7bfb266" target="_blank">Source</a>| Russia unleashed a torrent of missiles on Ukraine Tuesday, the same day that Ukrainian President Volodymyr Zelesnky delivered a video speech to the G20 and a week after Russian forces retreated from the southern city of Kherson. Here's what we know so far.|
|<font color=#FF3399>[5]</font> The wave of strikes appears to be the largest since Oct. 10, when Russia stepped up its campaign to destroy electricity, water and gas infrastructure across Ukraine.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-15-22/h_7f5e94a0dce088cef21f3ccdd455b183" target="_blank">Source</a>| Russia fired "around 100 missiles" at cities across Ukraine on Tuesday, Yurii Ihnat, a spokesperson for the Ukrainian Air Force command, said previously. At least a dozen cities and districts were targeted, according to a CNN analysis of the missile strikes. The wave of strikes appears to be the largest since Oct. 10, when Russia stepped up its campaign to destroy electricity, water and gas infrastructure across Ukraine. The leaders also offered "full support" for Poland following an explosion in the country's east and said they would "remain in close touch" to determine the appropriate next steps.|
