# What motivated the Norwegian Nobel Committee to award the Nobel Peace Prize to human rights campaigners in Ukraine, Russia and Belarus?

## Summary
The Norwegian Nobel Committee awarded the Nobel Peace Prize to three human rights activists and organizations from Belarus, Russia and Ukraine <font color=#FF3399>[1]</font> to honor their "outstanding effort to document war crimes, human right abuses and the abuse of power" <font color=#FF3399>[2]</font>. The award was intended to honor the work of Memorial, a human rights organization established in 1987 to remember the victims of the Soviet Union’s oppression <font color=#FF3399>[3]</font>. It also acknowledged the work of CCL, which was established in 2007 to promote human rights values in Ukraine and strengthen democracy <font color=#FF3399>[4]</font>, and Olha Matviichuk, who has been fighting for human rights across the three countries <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> The winners were honored for "an outstanding effort to document war crimes, human right abuses and the abuse of power" in their respective countries.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-07-22/h_98f3516703a278bfe3d32be8d05dd318" target="_blank">Source</a>| The Nobel Peace Prize has been awarded to human rights campaigners in Ukraine, Russia and Belarus. Belarusian human rights advocate Ales Bialiatski and two organizations from Russia and Ukraine Memorial and the Center for Civil Liberties, respectively were announced as the winners of the 2022 award on Friday morning. The winners were honored for "an outstanding effort to document war crimes, human right abuses and the abuse of power" in their respective countries. "They have for many years promoted the right to criticise power and protect the fundamental rights of citizens," the Norwegian Nobel Committee said.|
|<font color=#FF3399>[2]</font> It was a strong rebuke of Russian President Vladimir Putin on his 70th birthday.<a href="https://www.axios.com/2022/10/03/nobel-prize-announcements-2022" target="_blank">Source</a>| A Ukrainian counteroffensive has pushed back Russian forces in some areas annexed by the Kremlin, a move widely denounced by western countries as illegal. The committee said it wanted to honor "three outstanding champions of human rights, democracy and peaceful co-existence" in the neighboring countries of Belarus, Russia and Ukraine. It was a strong rebuke of Russian President Vladimir Putin on his 70th birthday. Literature|
|<font color=#FF3399>[3]</font> Russian human rights organization Memorial, one of the winners of the 2022 Nobel Peace Prize, was established in 1987 by human rights activists in the former Soviet Union to expose the abuses and atrocities of the Stalinist era.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-07-22/h_ab13d0e1f7a9e22d692397bbdf8064dc" target="_blank">Source</a>| Russian human rights organization Memorial, one of the winners of the 2022 Nobel Peace Prize, was established in 1987 by human rights activists in the former Soviet Union to expose the abuses and atrocities of the Stalinist era. The group "wanted to ensure that the victims of the communist regime's oppression would never be forgotten," according to the Nobel committee.|
|<font color=#FF3399>[4]</font> Matviichuk, who described herself as an empathetic person, acknowledged that years of documenting the worst of humanity had taken its own emotional toll on her and her colleagues at CCL.<a href="https://www.washingtonpost.com/world/2022/10/14/ukrainian-nobel-laureate-demands-new-approach-wartime-justice/" target="_blank">Source</a>| While some Ukrainians criticized the Nobel committee for jointly recognizing rights defenders in Belarus and Russia, Matviichuk described a common fight that human rights defenders were waging across the three countries. "This is about humans, not about countries," she said. Matviichuk, who described herself as an empathetic person, acknowledged that years of documenting the worst of humanity had taken its own emotional toll on her and her colleagues at CCL. "I believe in human dignity," she said.|
|<font color=#FF3399>[5]</font> The committee commended its work on strengthening Ukrainian civil society and the pressure that it's put on authorities to "make Ukraine a full-fledged democracy."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-07-22/h_9422c8b5b492267791ed61d268362e27" target="_blank">Source</a>| Ukraine's Center for Civil Liberties (CCL), another of Friday's Nobel Peace Prize winners, was established in 2007 to promote human rights values in Ukraine and strengthen democracy in the country. The committee commended its work on strengthening Ukrainian civil society and the pressure that it's put on authorities to "make Ukraine a full-fledged democracy." "The center is playing a pioneering role in holding guilty parties accountable for their crimes," it said.|
