# What is the purpose of the Russian missile strikes in Kyiv?

## Summary
The Russian missile strikes in Kyiv are part of a strategy to terrorize Ukrainians and are in violation of the laws of war <font color=#FF3399>[1]</font>. The strikes have been occurring intermittently since mid-October and have damaged or destroyed civilian infrastructure, leaving millions of Ukrainians without electricity, heat, water, and other critical services <font color=#FF3399>[1]</font>. The Ukrainian military has reported increasing success in shooting down incoming rockets and drones, but the strikes have nevertheless intensified <font color=#FF3399>[2, 4]</font>. On Thursday, the largest wave of strikes occurred, damaging power stations and other critical infrastructure <font color=#FF3399>[3]</font>. The shelling also concentrated on populated areas on the Dnipro River's right bank <font color=#FF3399>[5]</font>. Ukraine had requested Patriot missile batteries from the United States as a way to bolster its air defences, and President Joe Biden agreed to provide them <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Repeated missile and drone attacks since October, which have damaged or destroyed civilian infrastructure, are part of a strategy by the Kremlin to terrorize Ukrainians and is in violation of the laws of war, according to experts.<a href="https://www.cnn.com/2022/12/16/europe/ukraine-russia-missile-strikes-friday-intl/index.html" target="_blank">Source</a>| "They have set a goal to leave Ukrainians without light, water and heat," Ukraines Prime Minister Denys Shmyhal told a government meeting, adding that 60 of the 76 missiles fired at Ukraine were intercepted by its air defense forces. Russias persistent and pervasive attacks on Ukraines energy grid have, at least temporarily, left millions of civilians without electricity, heat, water and other critical services in the freezing winter months. Repeated missile and drone attacks since October, which have damaged or destroyed civilian infrastructure, are part of a strategy by the Kremlin to terrorize Ukrainians and is in violation of the laws of war, according to experts. Ukrainian energy operator Ukrenergo reported on Friday that more than 50% of the countrys energy capacity was lost due to Russian strikes on thermal and hydroelectric power plants and substations, activating "emergency mode."|
|<font color=#FF3399>[2]</font> Fridays attack took place after the United States this week agreed to give a Patriot missile battery to Ukraine to further boost the countrys defense.<a href="https://www.pbs.org/newshour/world/russia-launches-another-major-missile-attack-across-ukraine" target="_blank">Source</a>| Russian strikes on electricity and water systems have occurred intermittently since mid-October, increasing the suffering of the population as winter approaches. But the Ukrainian military has reported increasing success in shooting down incoming rockets and explosive drones. Fridays attack took place after the United States this week agreed to give a Patriot missile battery to Ukraine to further boost the countrys defense. Russias Foreign Ministry warned Thursday that the sophisticated system and any crews accompanying it would be a legitimate target for the Russian military.|
|<font color=#FF3399>[3]</font> KYIV, Ukraine (AP) Russian missiles hit Ukraine Thursday in the biggest wave of strikes in weeks, damaging power stations and other critical infrastructure during freezing winter weather.<a href="https://www.kktv.com/2022/12/29/ukraine-facing-another-russian-missile-attack/" target="_blank">Source</a>| KYIV, Ukraine (AP) Russian missiles hit Ukraine Thursday in the biggest wave of strikes in weeks, damaging power stations and other critical infrastructure during freezing winter weather. Russia fired 69 missiles at energy facilities and Ukrainian forces shot down 54, Ukrainian military chief Gen. Valerii Zaluzhnyi said.|
|<font color=#FF3399>[4]</font> Fighting is intensifying in southern Ukraine where officials said 33 Russian rockets were fired at civilian targets in the city of Kherson on Wednesday alone as Moscow doubles down on its calls for Kyiv to meet its demands before any talks to end the war.<a href="https://www.nbcnews.com/news/world/russia-ukraine-war-rockets-civilians-kherson-zelenskyy-putin-peace-rcna63436" target="_blank">Source</a>| Fighting is intensifying in southern Ukraine where officials said 33 Russian rockets were fired at civilian targets in the city of Kherson on Wednesday alone as Moscow doubles down on its calls for Kyiv to meet its demands before any talks to end the war. Wednesday's shelling concentrated on populated areas on the Dnipro River's right bank, according to the daily report by the General Staff of the Armed Forces of Ukraine.|
|<font color=#FF3399>[5]</font> Ukraine had previously requested Patriots, saying that they would help bolster its air defences as Russian missile strikes on critical infrastructure have become more regular.<a href="https://www.reuters.com/business/aerospace-defense/russia-says-patriot-missiles-kyiv-wont-help-settle-ukraine-conflict-2022-12-22/" target="_blank">Source</a>| Zelenskiy's visit to the United States was his first trip outside the country since Russia invaded it on Feb. 24. Before addressing a joint meeting of Congress, Zelenskiy held a meeting with U.S. President Joe Biden at the White House, during which Biden pledged to deliver one Patriot surface-to-air missile battery systems. Ukraine had previously requested Patriots, saying that they would help bolster its air defences as Russian missile strikes on critical infrastructure have become more regular. The Patriot is one of the most advanced U.S. air defence systems, capable of intercepting threats, such as aircraft and ballistic missiles.|
