# How has the Russian missile strike in Dnipro impacted the ongoing Russia-Ukraine conflict?

## Summary
The ongoing Russia-Ukraine conflict has been exacerbated by a Russian missile strike in Dnipro, Ukraine's third-largest city. The strike on the nine-story apartment building resulted in five fatalities and 27 injuries, including six children <font color=#FF3399>[2]</font>. Furthermore, Russian missiles have targeted energy and industrial objects in Kharkiv, the country's second-largest city <font color=#FF3399>[3,4,5]</font>, and have caused emergency power cuts in the region. Russian artillery attacks have also resulted in three deaths in the city of Avdiivka, where fighting is most intense <font color=#FF3399>[5]</font>. Additionally, Ukraine reported that they were able to shoot down 25 of 38 Russian missiles of different types <font color=#FF3399>[1]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> The strikes caused emergency blackouts in multiple regions, such as the Kharkiv region and the city of Kharkiv Ukraines second-largest city in the countrys northeast.<a href="https://www.eurasiareview.com/15012023-russia-damages-critical-infrastructure-across-ukraine-in-massive-attack/" target="_blank">Source</a>| Local authorities reported that Ukraines air defense downed Russian missiles in Mykolaiv, Odesa, Kyiv, Khmelnytskyi, Vinnytsia, and Ivano-Frankivsk. Ukraines top military commander said his forces shot down 21 of the 33 cruise missiles Russia fired. The strikes caused emergency blackouts in multiple regions, such as the Kharkiv region and the city of Kharkiv Ukraines second-largest city in the countrys northeast. In the western Lviv Oblast, Governor Maksym Kozytskyi said there might be interruptions in the power and water supply because of missile damage.|
|<font color=#FF3399>[2]</font> Russia, which invaded Ukraine last February, has been pounding its energy infrastructure with missiles and drones since October, causing sweeping blackouts and disruptions to central heating and running water.<a href="https://www.reuters.com/world/europe/russian-missile-attack-hits-infrastructure-kyiv-officials-2023-01-14/" target="_blank">Source</a>| The exterior of the rest of the building was badly damaged. Wounded people were carried away on stretchers. Russia, which invaded Ukraine last February, has been pounding its energy infrastructure with missiles and drones since October, causing sweeping blackouts and disruptions to central heating and running water. Ukraine shot down 25 of 38 Russian missiles of different types, the Air Force said.|
|<font color=#FF3399>[3]</font> A regional Ukrainian leader said five people were killed by a Russian missile that struck a nine-story apartment building in the central Ukrainian city of Dnipro.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-1-14-23/h_c4f7d05271e6ece82df46a6a89eb5883" target="_blank">Source</a>| A regional Ukrainian leader said five people were killed by a Russian missile that struck a nine-story apartment building in the central Ukrainian city of Dnipro. At least 27 people were injured, including six children.|
|<font color=#FF3399>[4]</font> No casualties have been reported, but emergency power cuts in the city and other settlements of the region were possible, the official said.<a href="https://apnews.com/article/russia-ukraine-kyiv-vitali-klitschko-explosions-401d8116d95d67e3afbe8de8eb8cf65a" target="_blank">Source</a>| On Saturday morning, two Russian missiles hit Kharkiv, Ukraines second-largest city. The strikes with S-300 missiles targeted "energy and industrial objects of Kharkiv and the (outlying) region," governor Syniehubov said. No casualties have been reported, but emergency power cuts in the city and other settlements of the region were possible, the official said. In the city of Avdiivka in eastern Ukraine where fighting is most intense, three people were killed in Russian artillery attacks on Saturday, mayor Vitalii Barabash said.|
|<font color=#FF3399>[5]</font> No casualties have been reported, but emergency power cuts in the city and other settlements of the region were possible, the official said.<a href="https://www.gpb.org/news/2023/01/15/the-uk-pledges-tanks-ukraine-russian-missiles-target-multiple-cities" target="_blank">Source</a>| On Saturday morning, two Russian missiles hit Kharkiv, Ukraine's second-largest city. The strikes with S-300 missiles targeted "energy and industrial objects of Kharkiv and the (outlying) region," governor Syniehubov said. No casualties have been reported, but emergency power cuts in the city and other settlements of the region were possible, the official said. In the city of Avdiivka in eastern Ukraine where fighting is most intense, three people were killed in Russian artillery attacks on Saturday, mayor Vitalii Barabash said.|
