# What strategies can Ukraine use to ensure their territorial integrity and sovereignty is respected in any potential negotiations with Russia?

## Summary
Ukraine has stated that any negotiations with Russia must include the withdrawal of all Russian troops from Ukrainian territory <font color=#FF3399>[3]</font> and the restoration of all occupied lands <font color=#FF3399>[2]</font>. Ukraine also insists that Russia should face prosecution for its war crimes and provide compensation for the war damage <font color=#FF3399>[3]</font>. If negotiations are not successful, Ukraine is willing to ask assistance from its allies and defend itself against Russian aggression <font color=#FF3399>[2]</font>. On social media, the Ukrainian President's security adviser has suggested that the only way negotiations can start is when Ukraine regains all its borders and that any talks should be held with the next leader of the Russian Federation <font color=#FF3399>[5]</font>. Therefore, Ukraine must rely on its allies and military strength to protect its sovereignty and territorial integrity in any potential negotiations with Russia <font color=#FF3399>[1,2,3,5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Russian ultimatums are well-known: we came with tanks, admit defeat and [the loss of territory].'<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-08-22/h_e4ee0ce0c78f2f1bacb5878596a1cdcd" target="_blank">Source</a>| "The main condition of the [Ukrainian] President of is restoration of [Ukrainian] territorial integrity," Oleksiy Danilov, secretary of Ukraine's National Security and Defense Council,said on Twitter. Mykhailo Podolyak, an adviser to Ukrainian President Volodymyr Zelensky,asked on Twitter: "What do you mean by the word negotiations'? Russian ultimatums are well-known: we came with tanks, admit defeat and [the loss of territory].' This is unacceptable.|
|<font color=#FF3399>[2]</font> said the "only way" for negotiations to start is "when we get regain all our borders."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-08-22/h_11303d1a1eeb1ad5e9b106e087830967" target="_blank">Source</a>| Ukraine should talk to Russia, she said, but if negotiations aren't successful, "we have to ask assistance from our allies, defend ourselves, and push them out of here." Vlad, a 31-year-old who provided only his first name because he's serving in the military. said the "only way" for negotiations to start is "when we get regain all our borders." Negotiations, he said, are impossible, "because their attitude to us is not human."|
|<font color=#FF3399>[3]</font> Some, like General Mark Milley, thought Russias withdrawal from the city it occupied for eight months could be the tactical advantage Ukraine needed to kick-start negotiations to end the war.<a href="https://www.foxnews.com/world/us-calls-ukraine-liberate-citizens-chances-peace-talks-diminish" target="_blank">Source</a>| Chances of peace negotiations between Kyiv and Moscow seem to have once again diminished following Russias withdrawal from the southern city of Kherson with a top U.S. official Saturday calling on Ukraine to "liberate" all its citizens from Russian "barbarity." Some, like General Mark Milley, thought Russias withdrawal from the city it occupied for eight months could be the tactical advantage Ukraine needed to kick-start negotiations to end the war. Russia this week even signaled it was open to talks, though Ukrainian President Volodymyr Zelenskyy said he would only engage in discussions of peace with Russia so long as it returned all occupied lands, provide compensation for war damage and faced prosecution for its war crimes.|
|<font color=#FF3399>[4]</font> Russia said on Friday that it was committed to achieving the goals of what it calls its "special military operation" in Ukraine, adding such goals could be achieved through peace talks but that Kyiv's position meant holding peace talks was impossible.<a href="https://www.reuters.com/world/turkey-seeks-ukraine-peace-talks-despite-western-actions-erdogan-says-2022-11-12/" target="_blank">Source</a>| There have been no public attempts to reconvene peace talks between the two sides since initiatives to bring about a ceasefire in Istanbul during the first weeks of the conflict broke down without progress. Ukraine denied on Tuesday that it was under Western pressure to negotiate with Russia, doubling down on its insistence that talks could be held only if Russia relinquishes all of the territory it has occupied since the February invasion. Russia said on Friday that it was committed to achieving the goals of what it calls its "special military operation" in Ukraine, adding such goals could be achieved through peace talks but that Kyiv's position meant holding peace talks was impossible. Reporting by Azra Ceylan and Jonathan Spicer Editing by Frank Jack Daniel and Frances Kerry|
|<font color=#FF3399>[5]</font> It is hard to say whether Kyivs "all or nothing" rhetoric derives from a deep conviction that it is going to prevail or if it is just posturing to mobilise people in the face of aggression and avoid signalling weakness to the adversary.<a href="https://www.aljazeera.com/opinions/2022/11/13/after-kherson-can-ukraine-and-russia-talk-peace" target="_blank">Source</a>| Meanwhile, on social media, Zelenskyys security adviser Mikhaylo Podolyak has been reiterating that the withdrawal of all Russian troops from Ukrainian territory is unattainable while Putin remains in power. "Therefore, we are constructive in our assessment: We will talk with the next leader of RF," he wrote in a recent tweet, referring to the Russian Federation. It is hard to say whether Kyivs "all or nothing" rhetoric derives from a deep conviction that it is going to prevail or if it is just posturing to mobilise people in the face of aggression and avoid signalling weakness to the adversary. While Ukraine has not exhausted its offensive potential, it is doubtful it can sustain a war of attrition with its more powerful neighbour in the long run, even with all the military and financial support it gets from the West.|
