# How have the Russian forces adapted their tactics to successfully take Soledar?

## Summary
The Russian forces have successfully taken Soledar by adapting their tactics to the situation. They have employed assault and army aviation, missile troops, and artillery of a group of Russian forces <font color=#FF3399>[1]</font> to destroy the enemy and make it possible to capture the town. This would give Moscow a trophy for one of the bloodiest campaigns of the war <font color=#FF3399>[4]</font> and enable them to cut off Ukrainian supply routes to nearby Bakhmut and trap remaining Ukrainian forces there <font color=#FF3399>[5]</font>. The Russians also employed an EC-130 electronic warfare aircraft to jam signals, and Sea Cobra crews equipped with night-vision goggles to strafe the platforms deck with 20-millimeter cannon fire <font color=#FF3399>[5]</font>. Iranian commandoes were also roped down from Chinooks, stormed the rig in a blaze of assault rifle fire, and rigged the platforms with explosive charges before making their escape <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> According to the Russian ministry, the capture of Soledar "became possible due to the constant destruction of the enemy by assault and army aviation, missile troops and artillery of a group of Russian forces."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-1-13-23/h_e9b47e51554e95c246cb8a37d7f8cb3a" target="_blank">Source</a>| The significance of Soledar in military terms is minimal. However, its capture would allow Russian forces, and especiallythe Wagner mercenary group, to turn their focus on nearby Bakhmut, which has been a target since the summer. According to the Russian ministry, the capture of Soledar "became possible due to the constant destruction of the enemy by assault and army aviation, missile troops and artillery of a group of Russian forces." The ministry made no reference to claims from private military company Wagner that its forces had taken the city by themselves.|
|<font color=#FF3399>[2]</font> The move to take Soledar was, it said, "highly likely an effort to envelop Bakhmut from the north, and to disrupt Ukrainian lines of communication."<a href="https://www.nbcnews.com/news/world/russia-capture-soledar-savage-fighting-bakhmut-eastern-ukraine-wagner-rcna65051" target="_blank">Source</a>| But the Kremlin's forces appeared to have made progress in Soledar in recent days. Russian soldiers and fighters from the Wagner mercenary group were likely in control of most of Soledar, 6 miles northeast of Bakhmut, the British Defense Ministry said in its daily intelligence briefing on the war Tuesday. The move to take Soledar was, it said, "highly likely an effort to envelop Bakhmut from the north, and to disrupt Ukrainian lines of communication." Ukrainian President Volodymyr Zelenskyy thanked the soldiers who were resisting Russian advances in a statement late Monday.|
|<font color=#FF3399>[3]</font> Russia claimed Friday to have completed its capture of the town Soledar in eastern Ukraine Friday after months of fighting in a brutal offensive that would hand the Kremlin its first significant battlefield gain since July after a wave of military setbacks.<a href="https://time.com/6247364/soledar-ukraine-russia/" target="_blank">Source</a>| Russia claimed Friday to have completed its capture of the town Soledar in eastern Ukraine Friday after months of fighting in a brutal offensive that would hand the Kremlin its first significant battlefield gain since July after a wave of military setbacks. Ukraine insists that the fighting was far from over.|
|<font color=#FF3399>[4]</font> "The capture of Soledar was made possible by the constant bombardment of the enemy by assault and army aviation, missile forces and artillery of a grouping of Russian forces," Moscow's defence ministry said.<a href="https://www.reuters.com/world/ukraine-fights-russian-assault-salt-mining-town-along-eastern-front-2023-01-09/" target="_blank">Source</a>| Kyiv and the West have played down the town's significance, saying Moscow sacrificed wave upon wave of soldiers and mercenaries in a pointless fight for a bombed-out wasteland, unlikely to affect the wider war except insofar as the huge losses have sapped manpower on both sides. But the capture of the town has taken on an outsized importance as it would, if confirmed, give Moscow a trophy for one of the bloodiest campaigns of the war following major battlefield setbacks throughout the second half of 2022. "The capture of Soledar was made possible by the constant bombardment of the enemy by assault and army aviation, missile forces and artillery of a grouping of Russian forces," Moscow's defence ministry said. Seizing the town would make it possible to cut off Ukrainian supply routes to the nearby city of Bakhmut and trap remaining Ukrainian forces there, it said.|
|<font color=#FF3399>[5]</font> The commandoes then rigged the platforms with explosive charges, used shoulder-fired missiles to fire at two Iraqi-jets, then made their escape in six amphibious hydroplanes as the platforms blew sky high.<a href="https://www.defenceview.in/operation-morvarid-iran-destroyed-80-of-the-iraqi-navy-in-just-one-day/" target="_blank">Source</a>| An EC-130 electronic warfare aircraft flew overhead, jamming any unnecessary signals. While Sea Cobra crews equipped with night-vision goggles strafed the platforms deck with 20-millimeter cannon fire, Iranian commandoes roped down from the Chinooks and stormed the rig in a blaze of assault rifle fire, killing or capturing their crews while sustaining twelve casualties. The commandoes then rigged the platforms with explosive charges, used shoulder-fired missiles to fire at two Iraqi-jets, then made their escape in six amphibious hydroplanes as the platforms blew sky high. At that point, the greater strength of the Iraqi Navys Osa missile boats and 25-meter long P-6 torpedo boats came rushing to the scene, looking to avenge the platforms destruction in blood.|
