# What is the European Union's strategy for supporting Ukraine in the Russia-Ukraine crisis?

## Summary
The European Union is taking a multifaceted approach to support Ukraine in the Russia-Ukraine crisis. To prioritize support, the EU is allocating $50 billion for Ukraine's 2023 budget <font color=#FF3399>[2]</font>. Additionally, France is reinforcing their military presence on NATO's eastern flank with extra troops, tanks, and weapons <font color=#FF3399>[3]</font>. After an urgent call between French President Emmanuel Macron and Ukrainian President Volodymyr Zelensky, Macron said France would provide increased support with military equipment <font color=#FF3399>[4]</font>. Finally, the EU is sending more military equipment to Ukraine, including long-range weapons from France <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> "We will continue to support Ukraine from the financial, humanitarian, and military perspectives," the French president said.<a href="https://newseu.cgtn.com/news/2022-10-08/Macron-ups-Ukraine-military-aid-after-criticism-over-low-spending-1dWJsVKfsJy/index.html" target="_blank">Source</a>| French President Emmanuel Macron has announced that he will step up arms supplies to Ukraine in the wake of criticism that Paris wasn't doing enough to help the war effort since Russia's launched its attack on its neighbor eight months ago. "We will continue to support Ukraine from the financial, humanitarian, and military perspectives," the French president said. That pledge came on Thursday from Prague, as Macron attended a summit made up of 44 state leaders for the inaugural meeting of the European Political Community.|
|<font color=#FF3399>[2]</font> Committing to provide an extra $50 billion for 2023 would fully finance Ukraines 2023 budget and could be done using International Monetary Fund special drawing rights, alleviating the strain on Western budgets.The second is to be more realistic.<a href="https://www.washingtonpost.com/business/ukraines-song-to-macron-is-awfully-bittersweet/2022/10/14/e5c2659e-4b7d-11ed-8153-96ee97b218d2_story.html" target="_blank">Source</a>| The first is to prioritize support for Ukraine. Economist Jacob Nell, in a co-authored paper published last month, says Ukraines armed forces have been effective in destroying a large volume of Russian military equipment and capability at a low cost. Committing to provide an extra $50 billion for 2023 would fully finance Ukraines 2023 budget and could be done using International Monetary Fund special drawing rights, alleviating the strain on Western budgets.The second is to be more realistic. The long list of European post-pandemic spending items includes public health and climate change and points to tax increases, not cuts.|
|<font color=#FF3399>[3]</font> "In view of the situation on the eastern flank of NATO, in view of the violence of the fighting in Ukraine, in this war led by the Russian Federation, the President of the Republic has decided to raise our defensive posture on the eastern flank of Europe," French Defence Minister Sebastien Lecornu told a hearing of the Senate Defence Committee.<a href="https://www.euronews.com/2022/10/11/france-to-boost-its-forces-on-natos-eastern-flank-after-russian-missile-strikes-on-ukraine" target="_blank">Source</a>| France says it will reinforce its military presence on NATO's eastern flank in the coming weeks with additional troops, tanks and weapons. It comes as Russia escalated its war in Ukraine this week with massive missile strikes across the country, and follows an announcement by President Macron last week of a 100 million arms fund for Ukraine. "In view of the situation on the eastern flank of NATO, in view of the violence of the fighting in Ukraine, in this war led by the Russian Federation, the President of the Republic has decided to raise our defensive posture on the eastern flank of Europe," French Defence Minister Sebastien Lecornu told a hearing of the Senate Defence Committee. Paris, which is the framework nation of a NATO mission in Romania, currently has 350 French soldiers, as well as Belgians and Dutch, and plans to deploy a dozen armoured infantry vehicles (VBCI) and a dozen Leclerc tanks in the country in the next few weeks, Lecornu said.|
|<font color=#FF3399>[4]</font> "We discussed the strengthening of our air defense, the need for a tough European and international reaction, as well as increased pressure on the Russian Federation," Zelensky tweeted Monday.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-10-22/h_87907d3936d3ae2391da1439ac533653" target="_blank">Source</a>| Ukrainian President Volodymyr Zelensky says he had an urgent call with French President Emmanuel Macron on Monday, amid waves of Russian missile attacks across the country. "We discussed the strengthening of our air defense, the need for a tough European and international reaction, as well as increased pressure on the Russian Federation," Zelensky tweeted Monday. Macron said France would be ready to increase support in terms of military equipment to Ukraine during the call.|
|<font color=#FF3399>[5]</font> The European Union will send more military equipment to Ukraine, including long-range weapons from France, according to French President Emmanuel Macron.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-06-22/h_c3afb339e3faeb9d6267967dca952c7e" target="_blank">Source</a>| The European Union will send more military equipment to Ukraine, including long-range weapons from France, according to French President Emmanuel Macron. The EU is continuing to "advance the demands" it has received from Ukraine, including for French-madeCAESARself-propelledhowitzers, Macron said at a news conference in Prague on Thursday.|
