# What is the reason for Britain's Chancellor of the Exchequer Nadeem Zahawi to be in the US?

## Summary
Nadeem Zahawi, the UK Chancellor of the Exchequer, traveled to the US to discuss the G7's plan to cap the price of Russian oil <font color=#FF3399>[1]</font>. The idea is to reduce the Russian government's revenue, which is currently being used to fund military aggression <font color=#FF3399>[1]</font>. The plan has received support from the UK <font color=#FF3399>[1]</font> and requires the involvement of more countries if it is to be successful <font color=#FF3399>[1]</font>. The Kremlin has already responded to the plan by refusing to sell oil to countries that abide by the price cap <font color=#FF3399>[4]</font>. French Finance Minister Bruno Le Maire has called for an international outreach to make the plan a global measure against the war, rather than a Western measure against Russia <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> She also met with UK Chancellor of the Exchequer Nadhim Zahawi, who has offered British support for the plan, but noted that to be more effective, the plan would require more countries to come on board.<a href="https://oilprice.com/Energy/Oil-Prices/Oil-Prices-Fall-More-Than-3-As-G7-Discusses-Price-Cap-For-Russian-Crude.html" target="_blank">Source</a>| The initial idea was to maintain a cap above Russias cost of production to keep Russian oil on the market but reduce revenues for its war coffers. On Wednesday, Yellen said she was "optimistic" that the G7 would come to a price-capping agreement. She also met with UK Chancellor of the Exchequer Nadhim Zahawi, who has offered British support for the plan, but noted that to be more effective, the plan would require more countries to come on board. While Russian crude is selling at a $20/barrel discount now, it has not worked to stymie Moscows oil revenues thanks to Russia finding new markets in India and China.|
|<font color=#FF3399>[2]</font> It comes as part of Russias escalating efforts to turn the Wests sanctions against itself by weaponizing hydrocarbon exports but while the high oil prices (themselves partly driven by sanctions) have proven a boon to Russia, it is gas supplies that have proven the most effective weapon.<a href="https://www.geopoliticalmonitor.com/the-energy-war-in-europe-gas-and-the-russian-oil-price-cap/" target="_blank">Source</a>| Putin is going for option b) trying to turn its own cul de sac into the EUs: "relax the sanctions and well resume gas supplies." It is no coincidence that this apparent indefinite halting of gas via a major pipeline came shortly after the G7 group of countries agreed in principle to apply a price cap to the trading of Russian oil from December. It comes as part of Russias escalating efforts to turn the Wests sanctions against itself by weaponizing hydrocarbon exports but while the high oil prices (themselves partly driven by sanctions) have proven a boon to Russia, it is gas supplies that have proven the most effective weapon. Russias latest move is especially effective given the energy crisis in the EU: through curbing supplies to Europe, Russia can both push gas prices even higher and deprive Europe of a key commodity ahead of what Moscow no doubt hopes will be a cold, hard winter.|
|<font color=#FF3399>[3]</font> Finance ministers from the G7 nations released a joint statement announcing that they have agreed to implement a price cap on Russian oil and petroleum products in order to "reduce Russian revenues and Russia's ability to fund its war of aggression."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-02-22/h_5575752ce49534331660afd321225998" target="_blank">Source</a>| Finance ministers from the G7 nations released a joint statement announcing that they have agreed to implement a price cap on Russian oil and petroleum products in order to "reduce Russian revenues and Russia's ability to fund its war of aggression." "Today we confirm our joint political intention to finalise and implement a comprehensive prohibition of services which enable maritime transportation of Russian-origin crude oil and petroleum products globally the provision of such services would only be allowed if the oil and petroleum products are purchased at or below a price ("the price cap") determined by the broad coalition of countries adhering to and implementing the price cap," the statement reads.|
|<font color=#FF3399>[4]</font> Following months of planning, the oil price cap is a bid to limit the Kremlins earnings on exports of its most important commodity and reduce financial support for its war against Ukraine.<a href="https://foreignpolicy.com/2022/09/06/russia-oil-price-cap-putin-war-sanctions-energy-g7-europe-crisis/" target="_blank">Source</a>| After the G-7 announcement, the Kremlin immediately said that Russia would not sell any oil to countries abiding by the price cap. Last weeks bold announcement by the G-7 of a price cap on purchases of Russian oil has met with skepticism and ridicule from media commentators and pundits. Following months of planning, the oil price cap is a bid to limit the Kremlins earnings on exports of its most important commodity and reduce financial support for its war against Ukraine. After the G-7 announcement, the Kremlin immediately said that Russia would not sell any oil to countries abiding by the price cap.|
|<font color=#FF3399>[5]</font> The G-7 which consists of the U.S., Canada, France, Germany, the U.K., Italy and Japan is yet to finalize how the price cap will be implemented, a process that Le Maire acknowledged will be "quite difficult."<a href="https://www.cnbc.com/2022/09/03/france-says-imposing-a-price-cap-on-russian-oil-will-be-difficult.html" target="_blank">Source</a>| "You need an outreach because we don't want this measure to be only a Western measure," Le Maire told CNBC's Steve Sedgwick at the Ambrosetti Forum in Italy. "It should not be a Western measure against Russia, it should be a global measure against war," he added. The G-7 which consists of the U.S., Canada, France, Germany, the U.K., Italy and Japan is yet to finalize how the price cap will be implemented, a process that Le Maire acknowledged will be "quite difficult." However, it is expected to be ready before early December when EU sanctions on seaborne imports of Russian crude kick in.|
