# How could a Chernobyl-style disaster be prevented at the Zaporizhzhia nuclear power plant?

## Summary
A Chernobyl-style disaster at the Zaporizhzhia nuclear power plant could be prevented by the establishment of a safety and security protection zone around the plant <font color=#FF3399>[1, 5]</font>. Both Ukraine and Russia have accused each other of shelling the plant <font color=#FF3399>[2]</font>, and the ongoing war has caused communication and emergency preparedness and response mechanisms to be broken <font color=#FF3399>[3]</font>. On September 5, the plant was disconnected from the national electricity grid, requiring emergency measures to prevent essential cooling procedures from being interrupted <font color=#FF3399>[4]</font>. International Atomic Energy Agency Director General Rafael Grossi has met with the foreign ministers of Ukraine and Russia to try and establish a safety and security protection zone around the plant <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Though the plant has been witnessing intense shelling and explosion, experts don't think anything disastrous would happen, at least for now.<a href="https://www.theweek.in/news/world/2022/09/28/russian-referendum-fate-of-zaporizhzhia-nuclear-power-plant-uncertain.html" target="_blank">Source</a>| With annexation on the cards, the fate of the Zaporizhzhia nuclear power plant (NPP) is uncertain. The plant, located on the eastern bank of the Dnipro river, has been under Russian control since the beginning of the war but is still being operated by Ukrainian workers. Though the plant has been witnessing intense shelling and explosion, experts don't think anything disastrous would happen, at least for now. Reason: Russia hopes to use the plant to serve its own electricity market.|
|<font color=#FF3399>[2]</font> The international community has been on high alert about nuclear safety, yet experts believea Chernobyl-style disaster is unlikely.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-17-22/h_7dc0b03ad7b5b6356439496a8a23b9c5" target="_blank">Source</a>| Both Ukraine and Russia have accused each other of shelling the site. CNN cannot independently verify either government's claims. The international community has been on high alert about nuclear safety, yet experts believea Chernobyl-style disaster is unlikely. Yet risks remain, one of which is potential damage to nuclear waste stored openly on site in ponds of water and in casks, according to Petro Kotin, president of Energoatom, which runs nuclear power plants in Ukraine.|
|<font color=#FF3399>[3]</font> In the case of an accident, it will be impossible to take all the necessary steps to prevent the spread of radiation and damage to inhabitants in the region.<a href="https://www.wilsoncenter.org/blog-post/why-zaporizhzhia-nuclear-power-plant-mattersfor-whole-world" target="_blank">Source</a>| This happened again on September 5. In the Russian occupation of NPP, emergency preparedness and response mechanisms are broken as well as communication possibilities. In the case of an accident, it will be impossible to take all the necessary steps to prevent the spread of radiation and damage to inhabitants in the region. The disaster will affect Ukraine and neighboring states, depending on the direction of the wind at the moment of the accident.|
|<font color=#FF3399>[4]</font> Repeated shelling and fires had disconnected the Zaporizhzhia plant from the national electricity grid, requiring emergency measures to prevent essential cooling procedures from being interrupted.<a href="https://www.washingtonpost.com/world/2022/09/19/ukraine-russia-war-nuclear-plant-pugacheva/" target="_blank">Source</a>| Russia did not immediately comment on the allegation. Fears that Russias war in Ukraine could cause a nuclear catastrophe had focused so far on the countrys largest atomic energy station, in Zaporizhzhia, where all six reactors have now been shut down. Repeated shelling and fires had disconnected the Zaporizhzhia plant from the national electricity grid, requiring emergency measures to prevent essential cooling procedures from being interrupted. Advertisement|
|<font color=#FF3399>[5]</font> International Atomic Energy Agency Director General Rafael Grossi said he met the foreign ministers of Ukraine and Russia on the sidelines of the UN General Assembly on Wednesday in an effort to establish a safety and security protection zone around the Zaporizhzhia nuclear power plant.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-21-22/h_4bb8d0e0b4a35dcf7e626495bf63063e" target="_blank">Source</a>| International Atomic Energy Agency Director General Rafael Grossi said he met the foreign ministers of Ukraine and Russia on the sidelines of the UN General Assembly on Wednesday in an effort to establish a safety and security protection zone around the Zaporizhzhia nuclear power plant. Grossi had meetings with Ukrainian Foreign Minister Dymtro Kuleba and Russia's Foreign Minister Sergei Lavrov.|
