# What are the implications of the use of longer-range weaponry in the Ukraine-Russia conflict?

## Summary
The Ukrainian army recently targeted the city of Melitopol, a key hub that could help Ukrainian forces take back the Zaporizhzhia region and potentially even reach the Russian-occupied Crimea <font color=#FF3399>[1]</font>. To take back the city, Ukrainian forces used long-range precision missiles, diversion, and attacks on elected representatives of the occupation authorities <font color=#FF3399>[2]</font>. This indicates the importance of longer-range weaponry in the Ukraine-Russia conflict, as it can help Ukrainian forces reach further than they could before and potentially even drive Russian forces back to Crimea <font color=#FF3399>[3]</font>. This was demonstrated further by Ukrainian forces striking a hotel in Luhansk which allegedly housed a Wagner mercenary unit <font color=#FF3399>[4]</font>. Ukrainian forces also launched a missile attack on the city of Melitopol which killed two people and wounded 10 <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> As it explained, Ukrainian forces are seeking to isolate and destroy enemy troops in and around the city, using long-range precision missiles, diversion and attacks on elected representatives of the occupation authorities.<a href="https://tvpworld.com/65096013/ukrainian-forces-take-melitopol-as-a-target-hinting-offensives-direction-us-daily" target="_blank">Source</a>| The Ukrainian army has recently taken the Russian-occupied city of Melitopol as its target, indicating that the Ukrainians next move is likely to be an offensive to push Russian forces out of southern Ukraine, the "New York Times" daily wrote. As it explained, Ukrainian forces are seeking to isolate and destroy enemy troops in and around the city, using long-range precision missiles, diversion and attacks on elected representatives of the occupation authorities. "Melitopol is a key hub, and regaining control over it could help Ukraines forces take back not only the full Zaporizhzhia region, but also the rest of neighbouring Kherson," it explained, further adding that the move "could then potentially even give them a path to drive Russian forces all the way back to Crimea, which the Russians had controlled prior to the invasion."|
|<font color=#FF3399>[2]</font> Ukrainian forces struck the Russian-occupied city ofMelitopolover the weekend, opening a new front in Kyiv's fight to reclaim land in the south of the country and underlining the importance of longer-range weaponry.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-13-22/h_6cc26eee5ea9574348b5fe2588371dae" target="_blank">Source</a>| Ukrainian forces struck the Russian-occupied city ofMelitopolover the weekend, opening a new front in Kyiv's fight to reclaim land in the south of the country and underlining the importance of longer-range weaponry. The attacks struck a number of different locations, including a church being used as a base by Russian forces, according to the city's exiled mayor, Ivan Fedorov, who shared a video filmed at night of a fire burning in the distance.|
|<font color=#FF3399>[3]</font> "If Melitopol falls, the entire defense (of the occupiers) to Kherson collapses, the Ukrainian armed forces jump right to the border with Crimea on the isthmus," said Arestovych.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-12-22/h_759eb6dea28a0d0ec33d2659d745ecea" target="_blank">Source</a>| It is a major Russian logistics hub and has been in Russian hands since the early days of the invasion. Some background: Oleksiy Arestovych, an adviser to Ukrainian President Volodymyr Zelensky, underlined the importance of the city in comments made to local media outlet Feigin Live on Saturday. "If Melitopol falls, the entire defense (of the occupiers) to Kherson collapses, the Ukrainian armed forces jump right to the border with Crimea on the isthmus," said Arestovych. The attacks on Melitopol came as Ukrainian forces also struck a hotel in Luhansk which allegedly housed a Wagner mercenary unit.|
|<font color=#FF3399>[4]</font> The Ukrainian military has not yet confirmed or commented on the attack.<a href="https://www.cnn.com/2022/12/11/europe/ukraine-crimea-melitopol-odesa-intl-hnk/index.html" target="_blank">Source</a>| Alexei Kulemzin, head of the Russian-backed city administration, said Ukraine launched 20 Grad missiles around 5:54 a.m. local time Sunday in the direction of the Voroshilovsky and Kalininsky districts. Kulemzin said Ukraine also shelled the citys Kyivskiy district late Saturday night around 11:03 p.m. local time. The Ukrainian military has not yet confirmed or commented on the attack. Donetsk has been held by Russian-backed separatists since 2014.|
|<font color=#FF3399>[5]</font> Ukraine launched a missile attack on the Russian-occupied city of Melitopol Saturday, according to officials on both sides.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-11-22/h_18b347fc4f4476aba1d5c702297c4603" target="_blank">Source</a>| Ukraine launched a missile attack on the Russian-occupied city of Melitopol Saturday, according to officials on both sides. Melitopol's Moscow-installed administrators said four missiles struck the city, killing two people and wounding 10.|
