# What inquiries are being conducted into the Brovary helicopter crash?

## Summary
The helicopter crash in Brovary, Ukraine, has resulted in the death of 14 people, including a minor, and the injury of 25 people, including 11 children <font color=#FF3399>[1]</font>. Ukrainian authorities have launched an investigation into the cause of the crash and are considering several versions, such as violation of flight rules <font color=#FF3399>[2]</font>, technical malfunction <font color=#FF3399>[3]</font>, and intentional destruction <font color=#FF3399>[4]</font>. President Zelensky has described the deaths as "a truly great loss for the state" <font color=#FF3399>[5]</font>, and the Security Services are actively searching for possible causes <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> The Security Service investigation into the incident is considering several versions of what had caused the crash, including violation of flight security rules, technical malfunction of the helicopter, and intentional actions to destroy the vehicle.<a href="https://news.yahoo.com/kindergarten-morning-kyiv-suburb-turned-194021274.html" target="_blank">Source</a>| All 10 people onboard, including Interior Minister Denys Monastyrsky and his first deputy Yevhen Yenin, died. The incident also injured 25 people, including 11 children, who were all hospitalized, according to the State Emergency Service. The Security Service investigation into the incident is considering several versions of what had caused the crash, including violation of flight security rules, technical malfunction of the helicopter, and intentional actions to destroy the vehicle. The authorities promised to share first findings in the near future.|
|<font color=#FF3399>[2]</font> The SBU state security service said it was investigating possible causes, including a breach of flight rules, a technical malfunction and the intentional destruction of the helicopter.<a href="https://www.theguardian.com/world/live/2023/jan/18/russia-ukraine-war-live-pressure-mounts-on-germany-to-send-tanks-chancellor-scholz-due-to-speak-in-davos" target="_blank">Source</a>| The most recent update, on Wednesday afternoon, suggested one child had been killed, after previous reports that the number was at least three. Officials gave no immediate account of the cause of the crash. The SBU state security service said it was investigating possible causes, including a breach of flight rules, a technical malfunction and the intentional destruction of the helicopter. Monastyrsky, who was responsible for the police and security inside Ukraine, is the most senior Ukrainian official to die since the war began.|
|<font color=#FF3399>[3]</font> Ukrainian authorities have not yet released the official report on the causes of the accident.<a href="https://www.plenglish.com/news/2023/01/24/pilot-error-caused-ukrainian-helicopters-crash/" target="_blank">Source</a>| The aircraft of the State Emergency Service of Ukraine, which was flying to the Kharkov region and had the leadership of the Ministry of Internal Affairs on board, crashed in the morning of January 18 into a kindergarten in Brovary. As a result of the crash, 14 people, including a minor, were killed, and 25 persons, including 11 children, were injured. Ukrainian authorities have not yet released the official report on the causes of the accident. jg/abo/mem/gfa|
|<font color=#FF3399>[4]</font> The Ukrainian Security Services launched an investigation into the crash, and posted on Facebook that "several versions of the tragedy are being considered."<a href="https://www.cnn.com/2023/01/18/europe/helicopter-crash-ukraine-intl/index.html" target="_blank">Source</a>| The crash has stunned the country at a critical moment in the war: Ukraine has been imploring Western allies for more weaponry as Russian strikes hit its critical infrastructure and civilian populations with abandon. Ukraines President Zelensky called the deaths "a truly great loss for the state" later on Wednesday, adding that "hundreds of people were involved in extinguishing the fire, searching and rescuing the injured, and carrying out the initial investigative actions." The Ukrainian Security Services launched an investigation into the crash, and posted on Facebook that "several versions of the tragedy are being considered." They include: "Violation of flight rule, technical malfunction of the helicopter (and) deliberate actions to destroy the helicopter."|
|<font color=#FF3399>[5]</font> Zelenskyy said the national police and security services were working to determine the cause of the crash.<a href="https://www.usatoday.com/story/news/world/2023/01/18/ukraine-helicopter-crash-kills-top-officials/11073708002/" target="_blank">Source</a>| "Unspeakable pain," Zelenskyy said. "Bright memory to everyone whose life was taken by this black morning." Zelenskyy said the national police and security services were working to determine the cause of the crash. There was no initial information indicating the helicopter, which was flying in foggy conditions, was shot down.|
