# What are the implications of the Russia-Ukraine conflict for nuclear safety and security in Europe?

## Summary
The Russia-Ukraine conflict has posed a worrying threat to nuclear safety and security in Europe. Russia has captured the Zaporizhzhia nuclear plant since March <font color=#FF3399>[2]</font>, leading to shelling at and around the site <font color=#FF3399>[1, 3, 4, 5]</font> that has damaged infrastructure, cut power lines and put the nuclear plant in a precarious position <font color=#FF3399>[5]</font>. Fearing a potential nuclear disaster, Poland has distributed iodine tablets to regional fire departments to help protect against radioactive exposure in the event of such a disaster <font color=#FF3399>[3]</font>. The international community has been on high alert in response to the conflict, with the International Atomic Energy Agency (IAEA) monitoring the situation closely <font color=#FF3399>[5]</font>. Meanwhile, the White House has been working with the IAEA and Ukrainian energy regulators to ensure there is no threat posed by a disaster <font color=#FF3399>[4]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> The international community has been on high alert about nuclear safety, yet experts believea Chernobyl-style disaster is unlikely.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-17-22/h_7dc0b03ad7b5b6356439496a8a23b9c5" target="_blank">Source</a>| Both Ukraine and Russia have accused each other of shelling the site. CNN cannot independently verify either government's claims. The international community has been on high alert about nuclear safety, yet experts believea Chernobyl-style disaster is unlikely. Yet risks remain, one of which is potential damage to nuclear waste stored openly on site in ponds of water and in casks, according to Petro Kotin, president of Energoatom, which runs nuclear power plants in Ukraine.|
|<font color=#FF3399>[2]</font> It remains close to the frontline, and has come under fire repeatedly in recent months, raising fears of a nuclear catastrophe.<a href="https://www.reuters.com/world/europe/russia-says-zaporizhzhia-nuclear-plant-water-pipe-damaged-by-shell-2022-09-21/" target="_blank">Source</a>| MOSCOW, Sept 21 (Reuters) - Russia's defence ministry on Wednesday said that a large-caliber shell had damaged a technical water pipe at the Zaporizhzhia nuclear plant in Ukraine, Russian state-owned news agency RIA reported. The Zaporizhzhia nuclear plant was captured by Russian forces in March. It remains close to the frontline, and has come under fire repeatedly in recent months, raising fears of a nuclear catastrophe. Both Ukraine and Russia blame each other for shelling the facility.|
|<font color=#FF3399>[3]</font> Shelling at the site of Zaporizhzhia - Europe's biggest nuclear power plant - has damaged buildings close to its six reactors and cut power cables, risking a nuclear catastrophe that would affect neighbouring countries.<a href="https://www.reuters.com/world/europe/poland-distributes-iodine-pills-fears-grow-over-ukraine-nuclear-plant-2022-09-22/" target="_blank">Source</a>| WARSAW, Sept 22 (Reuters) - Poland, concerned about fighting around Ukraine's Zaporizhzhia nuclear power plant, has distributed iodine tablets to regional fire departments to give to people in the event of radioactive exposure, a deputy minister said on Thursday. Iodine is considered a way of protecting the body against conditions such as thyroid cancer in case of radioactive exposure. Shelling at the site of Zaporizhzhia - Europe's biggest nuclear power plant - has damaged buildings close to its six reactors and cut power cables, risking a nuclear catastrophe that would affect neighbouring countries. Russia and Ukraine blame each other for the shelling around the plant.|
|<font color=#FF3399>[4]</font> Russia and Ukraine have blamed each other for the shelling.<a href="https://www.cnn.com/2022/09/27/politics/ukraine-funding-request-nuclear-power-plant/index.html" target="_blank">Source</a>| The facility, held by Russian troops since March, has for weeks served as an increasingly hazardous flashpoint in the war. Shelling at and around the site has damaged infrastructure, cut power lines and drawn a sustained international effort to de-escalate the situation. Russia and Ukraine have blamed each other for the shelling. "Weve been working with the International Atomic Energy Agency and with Ukrainian energy regulators to try to make sure that there is no threat posed by a meltdown or something else from the plant," Jake Sullivan, the White House national security adviser, said Sunday on CBS "Face the Nation."|
|<font color=#FF3399>[5]</font> Russia and Ukraine have blamed each other for shelling at the site of the Zaporizhzhia nuclear power plant (ZNPP) that has damaged buildings and caused the disconnection of power lines.<a href="https://www.reuters.com/world/europe/main-power-line-back-up-zaporizhzhia-nuclear-power-plant-iaea-says-2022-09-17/" target="_blank">Source</a>| "With the main line's reconnection yesterday afternoon, the three back-up power lines are again being held in reserve," the International Atomic Energy Agency watchdog said in a statement. "The three other main external 750 kV (kilovolt) power lines that were lost earlier during the conflict remain down," it added. Russia and Ukraine have blamed each other for shelling at the site of the Zaporizhzhia nuclear power plant (ZNPP) that has damaged buildings and caused the disconnection of power lines. "While the ZNPP's power status has improved over the past week in sharp contrast to earlier this month when all power lines at one stage were down and it depended on its last operating reactor for vital electricity supplies the general situation for the plant located in the middle of a war zone remains precarious," the IAEA said.|
