# What was the purpose of the Russian shelling in Nikopol during the Russia-Ukraine crisis?

## Summary
The Russian shelling of Nikopol was part of a special military operation launched on February 24th <font color=#FF3399>[3]</font> to demilitarize and "denazify" Ukraine <font color=#FF3399>[2]</font>. This shelling occurred in the Dnipropetrovsk region of Nikopol district, across the river from the Zaporizhzhia nuclear power station, which had been seized by Russia <font color=#FF3399>[1]</font>. The shelling damaged residential buildings and power lines <font color=#FF3399>[5]</font>. The goal of the shelling was to push south to the Sea of Azov and encircle the troops now on the east bank of the Dnieper River <font color=#FF3399>[4]</font>. Energoatom, the Ukrainian nuclear power company, had accused Russia of bringing Grad multiple launch rocket systems near reactor number 6, likely with the aim of shelling Nikopol and Marzanets <font color=#FF3399>[1]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> The likely aim, Energoatom alleged, was to shell Nikopol and the nearby town of Marzanets, using their position as cover.<a href="https://www.theguardian.com/world/2022/dec/12/safety-of-zaporizhzhia-nuclear-plant-hangs-in-the-balance" target="_blank">Source</a>| The Ukrainians insist they are extremely careful about what they shoot at, even when they receive fire from the vicinity of the Zaporizhzhia plant. On Thursday, the Ukrainian nuclear power company, Energoatom, accused Russia of bringing Grad multiple launch rocket systems near reactor number 6, which is near the area of where spent nuclear fuel is kept. The likely aim, Energoatom alleged, was to shell Nikopol and the nearby town of Marzanets, using their position as cover. The walls of the reactors are thick enough to withstand artillery fire, but a direct hit on the spent fuel containers could well lead to the release of radioactive material into the atmosphere.|
|<font color=#FF3399>[2]</font> Russia has always claimed that the aim of its special operation is to demilitarize and "denazify" Ukraine and that only military infrastructure is being targeted.<a href="https://www.business-standard.com/article/international/over-1-5-million-people-left-without-power-in-ukraine-s-port-city-odesa-122121100377_1.html" target="_blank">Source</a>| Notably, the Zaporizhzhia nuclear power station, which is seized by Russia, is located across the river from the Nikopol district, which is situated in the Dnipropetrovsk area, reported CNN. Russia launched a special military operation in on February 24, after the Donetsk and Luhansk People's Republics (DPR and LPR) appealed for help in defending themselves against the Kyiv forces. Russia has always claimed that the aim of its special operation is to demilitarize and "denazify" Ukraine and that only military infrastructure is being targeted. Moscow boosts production of powerful arms|
|<font color=#FF3399>[3]</font> Last night Russian troops struck two communities in the Dnipropetrovsk regions Nikopol district with heavy artillery.<a href="https://www.ukrinform.net/rubric-ato/3631358-russian-invaders-strike-dnipropetrovsk-regions-nikopol-district-with-heavy-artillery.html" target="_blank">Source</a>| Last night Russian troops struck two communities in the Dnipropetrovsk regions Nikopol district with heavy artillery. The relevant statement was made by Dnipropetrovsk Regional Military Administration Head Valentyn Reznichenko on Telegram, an Ukrinform correspondent reports.|
|<font color=#FF3399>[4]</font> But the long-term goal, Dadak said, was to push south to the Sea of Azov .<a href="https://www.washingtonpost.com/world/2022/12/03/after-kherson-ukraines-military-ponders-new-push-south-east/" target="_blank">Source</a>| The soldiers took turns warming up in a dugout with a wood-burning stove and just enough room for two small beds. Their main focus was to hold a defensive position, just behind the front line, and prevent the Russians from advancing north to the highway that connects Zaporizhzhia to the Donetsk region. But the long-term goal, Dadak said, was to push south to the Sea of Azov . With the right momentum, Ukrainian forces could encircle the troops now on the east bank of Dnieper River after surrendering the city of Kherson and towns on the west bank.|
|<font color=#FF3399>[5]</font> Valentyn Reznichenko said Russian shelling damaged residential buildings and power lines.<a href="https://abcnews.go.com/International/wireStory/nato-chief-fears-ukraine-war-widen-wider-conflict-94860216" target="_blank">Source</a>| In the neighboring Zaporizhzhia region, Russian forces shelled Nikopol and Chervonohryhorivka, which are across the Dnieper River from the Russia-occupied Zaporizhzhia nuclear power plant. Zaporizhzhia Gov. Valentyn Reznichenko said Russian shelling damaged residential buildings and power lines. In the Kharkiv region of northeastern Ukraine, Gov.|
