# What are the risks of a nuclear accident at the Zaporizhzhia nuclear power plant?

## Summary
The International Atomic Energy Agency (IAEA) has warned of the risk of a "severe nuclear accident" at the Zaporizhzhia nuclear power plant in Ukraine due to shelling in the area <font color=#FF3399>[2,4]</font>. The IAEA has noted that the physical integrity of the plant has been compromised by weeks of shelling <font color=#FF3399>[3]</font> and that disruptions in power to cool reactor cores could potentially lead to a meltdown <font color=#FF3399>[4]</font>. Russia and Ukraine have accused each other of shelling at the site, and the IAEA has called for an immediate stop to the shelling in order to reduce the risk of catastrophe <font color=#FF3399>[5]</font>. The agency's Director General, Rafael Grossi, also called for a more formal protection zone to be set up around the plant to further reduce the risk <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> So there's this real risk that any radioactivity released would be potentially economically devastating as well.<a href="https://www.npr.org/2022/09/05/1121144977/a-sixth-reactor-at-ukraine-s-zaporizhzhia-nuclear-power-plant-is-now-off-the-gri" target="_blank">Source</a>| There would be no easy way to get international help to the plant. And if that's not scary enough, Zaporizhzhia sits in the middle of some of Ukraine's most fertile farmland. So there's this real risk that any radioactivity released would be potentially economically devastating as well. SHAPIRO: That's NPR's Geoff Brumfiel.|
|<font color=#FF3399>[2]</font> "Any further escalation affecting the six-reactor plant could lead to a severe nuclear accident with potentially grave radiological consequences for human health and the environment in Ukraine and elsewhere," the IAEA warned.<a href="https://www.cbsnews.com/news/ukraine-zaporizhzhia-nuclear-power-plant-risks-chernobyl-comparison/" target="_blank">Source</a>| After the shutdown, Zaporizhzhia will enter a "cold state," according to Ukrainian nuclear operator Energoatom. But the integrity of the plant has been compromised by weeks of shelling, according to a 52-page report compiled by the United Nations-backed global nuclear watchdog, the International Atomic Energy Agency (IAEA), which sent a team of inspectors to Zaporizhzhia at the beginning of September. "Any further escalation affecting the six-reactor plant could lead to a severe nuclear accident with potentially grave radiological consequences for human health and the environment in Ukraine and elsewhere," the IAEA warned. The agency's Director General, Rafael Grossi, noted in the report that the Ukrainian technicians who've continued operating the plant under Russian occupation are "under constant high stress and pressure, especially with the limited staff available."|
|<font color=#FF3399>[3]</font> A "serious situation" developedafter the power infrastructure feeding the city of Enerhodar which houses the plant operators and their families was destroyed by shelling, IAEA Director General Rafael Mariano Grossi said in a statement.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-09-22/h_b101932d09ed4e30a17b9a2972c38086" target="_blank">Source</a>| The director of the International Atomic Energy Agency issued a dire warning urgently calling for the immediate cessation of shelling in the area surroundingthe Russian-controlled Zaporizhzhia nuclear power plant due to the risk of a "nuclear accident." A "serious situation" developedafter the power infrastructure feeding the city of Enerhodar which houses the plant operators and their families was destroyed by shelling, IAEA Director General Rafael Mariano Grossi said in a statement. The shelling has led to a complete power blackout with no running water, power or sewage in the city.|
|<font color=#FF3399>[4]</font> Grossi warned that the gravest risk to the ZNPP is physical damage to equipment, from shelling, that could lead to a release of radiation, adding that disruptions in external power to cool reactor cores could lead to a meltdown.<a href="https://www.securitycouncilreport.org/whatsinblue/2022/09/ukraine-briefing-on-the-zaporizhzhia-nuclear-power-plant.php" target="_blank">Source</a>| Speaking to reporters on 2 September, Grossi said that none of what the agency refers to as the seven pillars of nuclear safetywhich include physical integrity, reliable external power, and availability of spare partsare intact at the ZNPP. He noted that the plants physical integrity has been "violated several times", adding that most of the damage to the ZNPP occurred during shelling in August. Grossi warned that the gravest risk to the ZNPP is physical damage to equipment, from shelling, that could lead to a release of radiation, adding that disruptions in external power to cool reactor cores could lead to a meltdown. The IAEA released a report today (6 September) about the nuclear safety, security and safeguards situation at several nuclear facilities in Ukraine, which includes an overview of the findings of the IAEAs 1 September visit.|
|<font color=#FF3399>[5]</font> A runaway chain reaction can, however, cause a major accident like those at Fukushima or Chernobyl.<a href="https://www.reuters.com/world/europe/zaporizhzhia-nuclear-power-plants-shutdown-2022-09-12/" target="_blank">Source</a>| Russia and Ukraine have accused each other of shelling at the site that has damaged buildings and brought down power lines essential to cooling fuel in its six reactors, even when the reactors are in cold shutdown as they are now. Controlled fission, the splitting of nuclear fuel atoms inside a reactor core, generates heat that turns water into steam to spin turbines and produce electricity. A runaway chain reaction can, however, cause a major accident like those at Fukushima or Chernobyl. Grossi has called for an immediate stop to the shelling as well as for a more formal protection zone to be set up around the plant to reduce the risk of catastrophe.|
