# What is the long-term impact that the shelling in Nikopol will have on the region's civilians?

## Summary
The shelling of Nikopol in the Zaporizhzhia region of Ukraine, combined with shelling in the neighboring Kharkiv region and the Donetsk region, has caused immense human suffering and destruction of residential buildings, power lines, and water supply systems <font color=#FF3399>[1, 2, 3, 4, 5]</font>. As a result, thousands of families are now without water and energy, with homes and gas pipelines damaged <font color=#FF3399>[3, 4]</font>. This shelling has been ongoing since February, when Russian President Vladimir Putin invaded Ukraine <font color=#FF3399>[2]</font>, and has caused severe long-term impacts on the region’s civilians.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Valentyn Reznichenko said Russian shelling damaged residential buildings and power lines.<a href="https://abcnews.go.com/International/wireStory/nato-chief-fears-ukraine-war-widen-wider-conflict-94860216" target="_blank">Source</a>| In the neighboring Zaporizhzhia region, Russian forces shelled Nikopol and Chervonohryhorivka, which are across the Dnieper River from the Russia-occupied Zaporizhzhia nuclear power plant. Zaporizhzhia Gov. Valentyn Reznichenko said Russian shelling damaged residential buildings and power lines. In the Kharkiv region of northeastern Ukraine, Gov.|
|<font color=#FF3399>[2]</font> "Russian missiles and drones continue to rain down on Ukrainian cities, civilians and critical infrastructure, causing enormous human suffering as winter sets in."<a href="https://apnews.com/article/russia-ukraine-nato-kyiv-climate-and-environment-europe-14a03b7a3d9b44598928ab209a82b775" target="_blank">Source</a>| In Berlin, NATO Secretary-General Jens Stoltenberg praised the "heroic resistance of the Ukrainian people" against Russias attacks, saying that with the help of allies "Ukraine has made significant gains" on the battlefield. "But we should not underestimate Russia," Stoltenberg warned in a speech at the Berlin Security Conference. "Russian missiles and drones continue to rain down on Ukrainian cities, civilians and critical infrastructure, causing enormous human suffering as winter sets in." The NATO chief said Russian President Vladimir Putin had made "two big strategic mistakes" when he invaded Ukraine in February: underestimating Ukraine and underestimating the support NATO and its allies were willing to provide so the country could defense itself.|
|<font color=#FF3399>[3]</font> Energy workers have already started eliminating consequences.<a href="https://www.ukrinform.net/rubric-ato/3628490-russian-troops-fire-half-a-hundred-shells-at-nikopol-district.html" target="_blank">Source</a>| In Chervonohryhorivka community, a line that powered a pumping station of the local water supply company was cut off. More than 9,000 families from several villages and towns were left without water supply. Energy workers have already started eliminating consequences. In Marhanets community, private houses and a gas pipeline were damaged," Reznichenko added.|
|<font color=#FF3399>[4]</font> "Although residential buildings and cars were damaged, no one was reported injured in the shelling," Yevtushenko added.<a href="https://www.business-standard.com/article/international/over-1-5-million-people-left-without-power-in-ukraine-s-port-city-odesa-122121100377_1.html" target="_blank">Source</a>| Meanwhile, in November, the Nikopol district in southern was hit by Russian shells, according to the head of the Nikopol district military administration, as per CNN. "About sixty shells and rocket munitions fell on peaceful settlements," the head of the administration of the Nikopol district, Yevhen Yevtushenko said in a Telegram post. "Although residential buildings and cars were damaged, no one was reported injured in the shelling," Yevtushenko added. Notably, the Zaporizhzhia nuclear power station, which is seized by Russia, is located across the river from the Nikopol district, which is situated in the Dnipropetrovsk area, reported CNN.|
|<font color=#FF3399>[5]</font> There were no casualties, he said.<a href="https://www.cnn.com/2022/12/11/europe/ukraine-crimea-melitopol-odesa-intl-hnk/index.html" target="_blank">Source</a>| Donetsk has been held by Russian-backed separatists since 2014. Ukraines southern Dnipropetrovsk region was also shelled overnight with Grad and heavy artillery, Valentyn Reznichenko, the head of the Dnipropetrovsk regional military administration, said on Telegram Sunday. There were no casualties, he said. The communities of Nikopol, Chervonohryhorivka and Marhanets were hit, Reznichenko said, adding that more than 50 shells were fired.|
