# What are the long-term implications of the deputies' actions for Russian politics?

## Summary
The recent actions of municipal deputies in Moscow, St. Petersburg and Kolpino, calling for the resignation of Russian President Vladimir Putin, have long-term implications for Russian politics. <font color=#FF3399>[1]</font> In a rare display of dissent, several deputies have appealed to the Duma for Putin's impeachment for alleged high treason. <font color=#FF3399>[2]</font> The deputies have even gone as far as posting a petition on Twitter demanding his resignation. <font color=#FF3399>[3]</font> Despite the risk of fines and jail time, some deputies are still standing by their calls for Putin to step down. <font color=#FF3399>[4]</font> This is further evidenced by the fact that other municipal deputies in Moscow and St. Petersburg have joined the call for his resignation. <font color=#FF3399>[5]</font> As the protests continue, it remains to be seen how Putin's government will respond and what this will mean for the future of Russian politics.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Several elected deputies in the St. Petersburg area have been summoned by police after calling for the impeachment of Russian President Vladimir Putin.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-09-22/h_a3a7dc69d56736f29fc46275b565b3e6" target="_blank">Source</a>| Several elected deputies in the St. Petersburg area have been summoned by police after calling for the impeachment of Russian President Vladimir Putin. In a rare display of dissent in Russia, the local deputies from the Smolninskoye municipality appealed to the Russian Duma to impeach Putin for what they called crimes of high treason.|
|<font color=#FF3399>[2]</font> "We believe that the decision made by president Putin to start the special military operation is detrimental to the security of Russia and its citizens," he said.<a href="https://news.yahoo.com/russian-forces-ordered-retreat-kharkiv-190800110.html" target="_blank">Source</a>| As Ukraine began a successful counterattack against Russian-occupied positions in the Kharkiv region, deputies from St Petersburgs Smolninsky District issued a statement calling for Mr Putin to be tried for treason. Dmitry Palyuga, one of the councillors, tweeted that the motion was supported by most of the districts deputies. "We believe that the decision made by president Putin to start the special military operation is detrimental to the security of Russia and its citizens," he said. Criticism of the Russian president has also crept up into the national state TV discourse.|
|<font color=#FF3399>[3]</font> "We, the municipal deputies of Russia, believe that the actions of its president Vladimir Putin are detrimental to Russias and its citizens future.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-13-22/h_5ec7b367f6a1438740ed9472229ca097" target="_blank">Source</a>| Deputies from 18 municipal districts in Moscow, St. Petersburg and Kolpino have called for Russian President Vladimir Putins resignation, according to a petition with a list of signatures posted on Twitter on Monday. "We, the municipal deputies of Russia, believe that the actions of its president Vladimir Putin are detrimental to Russias and its citizens future. We demand Vladimir Putin's resignation from the post of the President of the Russian Federation," said the petition posted by Ksenia Thorstrom, a local deputy of the Semenovsky District in Saint Petersburg.|
|<font color=#FF3399>[4]</font> "I don't want them to fear retaliation from the police," he told CNN's Erin Burnett, After receiving support from some people, Yuferev said he believes public opinion is shifting, as compared to when Putin first attacked Ukraine.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-14-22/h_ea6ca53e34fc3a34038c0d094532ecae" target="_blank">Source</a>| Nikita Yuferev, a deputy in Smolninskoye Municipal District in St. Petersburg, is not backing down from his calls for Russian President Vladimir Putin to resign even after having to pay a fine in court for speaking out, with a threat of jail time coming next. Yuferev said he is doing it for his children, saying that he wants them to be able to speak their minds at demonstrations and protests. "I don't want them to fear retaliation from the police," he told CNN's Erin Burnett, After receiving support from some people, Yuferev said he believes public opinion is shifting, as compared to when Putin first attacked Ukraine. In addition to offering to pay the fines and legal fees, another person offered to buy him a ticket to move his family to Mexico where he could feel safe.|
|<font color=#FF3399>[5]</font> Shared by St. Petersburg councilwoman Ksenia Thorstrom, the document says, "We, the municipal deputies of Russia, believe that President Vladimir Putins actions harm the future of Russia and its citizens."<a href="https://meduza.io/en/news/2022/09/12/municipal-deputies-in-moscow-and-st-petersburg-demand-putin-s-resignation" target="_blank">Source</a>| Nearly two dozen municipal deputies in Moscow and St. Petersburg have signed a petition demanding Vladimir Putins resignation as president. Shared by St. Petersburg councilwoman Ksenia Thorstrom, the document says, "We, the municipal deputies of Russia, believe that President Vladimir Putins actions harm the future of Russia and its citizens." Last week, municipal deputies in Moscows Lomonosovsky District also demanded Putins resignation.|
