# How has the Ukrainian military responded to the Russian shelling in Kherson?

## Summary
The Ukrainian military has responded to the Russian shelling in Kherson by retreating to the city of Mykolaiv to ensure the survivability of their troops and prevent the Russians from gaining air superiority <font color=#FF3399>[1, 5]</font>. This has been necessary due to the flat and marshy terrain of the region and failure to destroy key bridges leading to Kherson and Zaporizhzhia <font color=#FF3399>[4]</font>. Since the liberation of Kherson on November 11, Russian forces have continued shelling from positions on the other side of the Dnipro River and local officials say the city and other settlements are hit dozens of times daily <font color=#FF3399>[2]</font>. This shelling has resulted in at least three fatalities and six injuries, and has damaged infrastructure and a senior citizens home <font color=#FF3399>[3, 5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Civilians in the southern Ukrainian city of Kherson continue to shelter from Russian bombardment, with local officials saying that both the city and other recently liberated settlements are hit dozens of times daily.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-19-22/h_111fb1cec9451ddadc7a99d1181f8590" target="_blank">Source</a>| Civilians in the southern Ukrainian city of Kherson continue to shelter from Russian bombardment, with local officials saying that both the city and other recently liberated settlements are hit dozens of times daily. Russian forces "shelled the territory of Kherson region 69 times" on Sunday, said Yaroslav Yanushevych, head of Kherson region military administration, adding that the attacks killed at least three people, injured six, struck a hotel and apartment buildings, and also damaged infrastructure in the region that was recaptured in November.|
|<font color=#FF3399>[2]</font> Ukrainian forces are retaliating and say they hit a concentration of Russian weaponry in the town of Kakhovka on the east bank.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-23-22/h_32bb7d91d1f5aedcd906d3df8fb299be" target="_blank">Source</a>| "Within a month we have managed to restore almost 100% of electricity supply to Kherson region," he said. "However, constant shelling, including of critical infrastructure, does not allow the city of Kherson to have permanent electricity supply.Kherson city is without electricity again," added Khlan. Ukrainian forces are retaliating and say they hit a concentration of Russian weaponry in the town of Kakhovka on the east bank. But they say the Russians are digging in along the west bank, creating fortifications.|
|<font color=#FF3399>[3]</font> The shelling has been especially intense in Kherson since Russian forces withdrew and Ukraine's army reclaimed the city in November.<a href="https://www.npr.org/2022/12/24/1145443678/ukraine-kherson-deadly-shelling-russians" target="_blank">Source</a>| Saturday marks 10 months since the start of the Russian invasion. Ukraine has faced a blistering onslaught of Russian artillery fire, missiles, shelling and drone attacks since early October, much of it targeting the energy infrastructure in a bid to cut electricity and heating services as the freezing winter advances. The shelling has been especially intense in Kherson since Russian forces withdrew and Ukraine's army reclaimed the city in November. Earlier Saturday, the Donetsk regional governor, Pavlo Kyrylenko, said two people were killed and five wounded in shelling there over the past day.|
|<font color=#FF3399>[4]</font> Ukrainian forces liberated the city from Russian occupation on Nov. 11 but officials say Kremlin forces have continued shelling it from positions on the other side of the Dnipro River.<a href="https://www.reuters.com/world/europe/one-killed-kherson-shelling-governor-2022-12-17/" target="_blank">Source</a>| Yaroslav Yanushevych said on Telegram that Russian troops had struck a western district of Kherson - a port city on the Black Sea - with artillery and rocket fire. In addation to the fatality, a 70-year-old woman was wounded. Ukrainian forces liberated the city from Russian occupation on Nov. 11 but officials say Kremlin forces have continued shelling it from positions on the other side of the Dnipro River. In a separate message on Saturday, Yanushevych said Russian troops had shelled a senior citizens' home in a village just outside Kherson.|
|<font color=#FF3399>[5]</font> Ukraines outnumbered military, meanwhile, had withdrawn from Kherson for the southern city of Mykolaiv, said Maj. Oleksandr Fedyunin, a military spokesman.<a href="https://www.pbs.org/newshour/world/khersons-rapid-fall-at-start-of-russian-invasion-leaves-unanswered-questions" target="_blank">Source</a>| Flat and marshy, the Kherson region has few forests or other natural barriers to halt the tanks and troops from nearby Crimea that hosts Russias Black Sea fleet and air bases. In addition, Ukrainian officials such as Kherson Mayor Ihor Kolykhaev told the newspaper Ukrainska Pravda in May that the failure to destroy key bridges leading to the Kherson and Zaporizhzhia regions was a mistake that helped the Russians, although he stressed he was not a military man. Ukraines outnumbered military, meanwhile, had withdrawn from Kherson for the southern city of Mykolaiv, said Maj. Oleksandr Fedyunin, a military spokesman. That withdrawal "ensured the survivability of troops and did not allow the enemy to gain fire superiority in the air," said Bohdan Senyk, chief spokesman for the army.|
