# How many of the Russian detained anti-war protesters were women?

## Summary
According to OVD-Info, over half (51%) of the names made public of the more than 1,300 people detained nationwide in the anti-war protest crackdown were women <font color=#FF3399>[3,4]</font>, making it the biggest anti-government protest by share of women in recent history <font color=#FF3399>[2,3]</font>. The full scale of arrests remains unknown <font color=#FF3399>[2,3]</font>. Women protesters have demonstrated against the government's recent announcement of a 15-year jail sentence for those refusing the draft <font color=#FF3399>[1,2]</font>. Those detained included 40 protesters in Yekaterinburg, one of whom was in a wheelchair and shouted in reference to the Russian president <font color=#FF3399>[4,5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Over half of the anti-war demonstrators detained across Russia on Wednesday are women, according to the independent protest monitoring group OVD-Info, making it the biggest anti-government protest by share of women in recent history.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-22-22/h_02406074db93bd5ebdcf3d4d828f38e7" target="_blank">Source</a>| Over half of the anti-war demonstrators detained across Russia on Wednesday are women, according to the independent protest monitoring group OVD-Info, making it the biggest anti-government protest by share of women in recent history. Of the names made public, women made up 51% of those held in the anti-war protest crackdown, though the watchdog specified the full scale of arrests remains unknown.|
|<font color=#FF3399>[2]</font> Just over half the detained protesters whose names were made public are women, OVD-Info also said, making it the biggest anti-government protest by share of women in recent history.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-23-22/h_f5ee26d93d6a9ed19c575c6e7550293c" target="_blank">Source</a>| The government has said that punishment for refusing the draft is now 15 years in jail. Of the more than 1,300 people detained nationwide, more than 500 were in Moscow and more than 520 in St. Petersburg, according to OVD-Info. Just over half the detained protesters whose names were made public are women, OVD-Info also said, making it the biggest anti-government protest by share of women in recent history. The watchdog specified the full scale of the arrests remains unknown, however.|
|<font color=#FF3399>[3]</font> Just over half the detained protesters whose names were made public are women, OVD-Info also said, making it the biggest anti-government protest by share of women in recent history.<a href="https://www.cnn.com/2022/09/22/europe/russia-protests-partial-mobilization-ukraine-intl-hnk/index.html" target="_blank">Source</a>| The government has said that punishment for refusing the draft is now 15 years in jail. Of the more than 1,300 people detained nationwide, more than 500 were in Moscow and more than 520 in St. Petersburg, according to OVD-Info. Just over half the detained protesters whose names were made public are women, OVD-Info also said, making it the biggest anti-government protest by share of women in recent history. The watchdog specified the full scale of the arrests remains unknown, however.|
|<font color=#FF3399>[4]</font> In Ekaterinburg, Russias fourth-largest city, police hauled on to buses some of the 40 protesters who were detained at an anti-war rally.<a href="https://www.theguardian.com/world/2022/sep/22/russia-protests-more-than-1300-arrested-at-anti-war-demonstrations-ukraine" target="_blank">Source</a>| Alina Skvortsova, 20, said she hoped Russians would soon understand the nature of the Kremlins offensive in neighbouring Ukraine. "As soon as they really understand, they will come out on to the street, despite the fear," she said. In Ekaterinburg, Russias fourth-largest city, police hauled on to buses some of the 40 protesters who were detained at an anti-war rally. One woman in a wheelchair shouted, referring to the Russian president: "Goddamn bald-headed nut job.|
|<font color=#FF3399>[5]</font> In Yekaterinburg, Russias fourth-largest city, police hauled onto buses some of the 40 protesters who were detained at an anti-war rally.<a href="https://www.aljazeera.com/news/2022/9/22/over-1300-people-arrested-in-russia-amid-mobilisation-protests" target="_blank">Source</a>| "Everyone is scared. I am for peace and I dont want to have to shoot," said protester Vasily Fedorov, a student wearing a pacifist symbol on his chest, AFP reported. In Yekaterinburg, Russias fourth-largest city, police hauled onto buses some of the 40 protesters who were detained at an anti-war rally. One woman in a wheelchair shouted, referring to the Russian president: "Goddamn bald-headed nut job.|
