# How has Russia responded to the missile strike in Poland?

## Summary
Russia has denied firing the missile that hit the Polish village, describing the allegation as an "intentional provocation with the goal of escalating the situation" <font color=#FF3399>[1]</font>. The incident marked the first time a NATO-member has been directly hit during the conflict <font color=#FF3399>[2]</font>. Poland's President Duda stated that it was likely a Russian-made S-300 rocket <font color=#FF3399>[3]</font> and that the ultimate responsibility lies with Russia <font color=#FF3399>[4]</font>. NATO's Secretary-General said the blast was likely caused by a Ukrainian air defense missile that went astray but that Russia was ultimately responsible because it started the war <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Russia, however, outright denied firing the missile that hit the Polish village.<a href="https://www.npr.org/2022/11/16/1137087227/a-russian-made-missile-explodes-in-poland-killing-2-people" target="_blank">Source</a>| He called the explosion a major escalation. Earlier Tuesday, Ukraine was hit by nearly 100 Russian missile strikes, which have killed even more ordinary people. Russia, however, outright denied firing the missile that hit the Polish village. They've called that allegation a, quote, "intentional provocation with the goal of escalating the situation."|
|<font color=#FF3399>[2]</font> It is not known who fired the missile, or exactly where it was launched from.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-16-22/h_ad5c59ec89e4c52e2274a3f6444e7ace" target="_blank">Source</a>| Global leaders gathered at the conference attempted to alleviate a potential escalation in the Kremlin's war on Ukraine after Poland said a "Russian-made" missile struck an area outside the rural village of Przewodow and killed two people. The incident marked the first time a NATO-member has been directly hit during the conflict. It is not known who fired the missile, or exactly where it was launched from. CNN's Kevin Liptak contributed reporting.|
|<font color=#FF3399>[3]</font> Both Russian and Ukrainian forces have used Russian-made munitions during the conflict, including the S-300 surface-to-air missile system, which Kyiv has deployed as part of its air defenses.<a href="https://www.cnn.com/2022/11/16/europe/poland-missile-russia-ukraine-investigation-wednesday-intl-hnk/index.html" target="_blank">Source</a>| "There is no indication that this was an intentional attack on Poland. Most likely, it was a Russian-made S-300 rocket," Duda said in a tweet earlier Wednesday. Both Russian and Ukrainian forces have used Russian-made munitions during the conflict, including the S-300 surface-to-air missile system, which Kyiv has deployed as part of its air defenses. The incident in Poland, a NATO country, prompted ambassadors from the US-led military alliance to hold an emergency meeting in Brussels Wednesday.|
|<font color=#FF3399>[4]</font> He also said that the ultimate responsibility lies with Russia, which launched a barrage of missile attacks on Ukraine on Tuesday.<a href="https://www.france24.com/en/europe/20221116-live-un-chief-warns-absolutely-essential-to-avoid-escalating-war-in-ukraine" target="_blank">Source</a>| It's very likely that it was a rocket used in anti-missile defence, meaning that it was used by Ukraine's defence forces," he told reporters. Duda described the blast in the village as most likely an unfortunate accident. He also said that the ultimate responsibility lies with Russia, which launched a barrage of missile attacks on Ukraine on Tuesday. 11:59am: Germany offers to aid Polish air patrols after rocket strike|
|<font color=#FF3399>[5]</font> Poland has been conducting its own investigation into what happened.<a href="https://www.reuters.com/world/us/how-biden-white-house-scrambled-after-poland-missile-blast-2022-11-18/" target="_blank">Source</a>| He was a little more vague answering reporters' questions after the meeting, saying it was "unlikely" that the missile was fired from Russia based on its trajectory. Later, NATO's secretary-general said the blast was likely caused by a Ukrainian air defense missile that went astray but that Russia was ultimately responsible because it started the war. Poland has been conducting its own investigation into what happened. The U.S. military has sent American explosives experts to the site to help with the probe, at Poland's request, a U.S. official said.|
