# How has the Swedish government supported the IAEA's mission in Ukraine?

## Summary
The Swedish government has supported the International Atomic Energy Agency's mission to maintain and improve the safety of Ukraine's nuclear power plants by pledging $1,947,000 (20 million Swedish krona) <font color=#FF3399>[1]</font>. The European Union has also called for swift accountability for war crimes in Ukraine <font color=#FF3399>[2]</font>. Finland has suggested that it may consider joining NATO without Sweden if Turkey continues to block their joint bid <font color=#FF3399>[3]</font>. The IAEA mission in Khmelnytsky is also due to start soon and the IAEA Director General has pledged their full support in restoring any damage <font color=#FF3399>[4]</font>. The head of the IAEA also visited the South Ukraine Nuclear Power Plant to mark the permanent presence of the UN nuclear watchdog at the site <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> The Swedish government on Thursday pledged $1,947,000 (20 million Swedish krona) to the International Atomic Energy Agency (IAEA) to support its nuclear safety mission in Ukraine.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-1-26-23/h_65adb244bc1afed7edb9070483b8a116" target="_blank">Source</a>| The Swedish government on Thursday pledged $1,947,000 (20 million Swedish krona) to the International Atomic Energy Agency (IAEA) to support its nuclear safety mission in Ukraine. "Strengthening the IAEA's important work to maintain and improve the safety of Ukrainian nuclear power plants is a matter of urgency,"Forssell added.|
|<font color=#FF3399>[2]</font> The blocs 27 justice ministers met in Stockholm, where they discussed collecting evidence as well as setting up a new international tribunal to prosecute Moscows aggression.<a href="https://www.theguardian.com/world/2023/jan/27/russia-ukraine-war-at-a-glance-what-we-know-on-day-338-of-the-invasion" target="_blank">Source</a>| The European Union wants swift accountability for "horrific" crimes in Ukraine, EU justice ministers have said. But the member states differ over the methods in a debate about how to bring prosecutions, seek evidence or fund war damage repairs, Reuters reports. The blocs 27 justice ministers met in Stockholm, where they discussed collecting evidence as well as setting up a new international tribunal to prosecute Moscows aggression. Gunnar Strommer, Swedens justice minister, said "Nobody doing this kind of war crimes shall go free.|
|<font color=#FF3399>[3]</font> Sweden and Finland rushed to apply for NATO membership following Moscow's invasion, abandoning their long-standing non-alignment policy.<a href="https://www.france24.com/en/europe/20230124-finland-must-consider-joining-nato-without-sweden-finnish-fm-says" target="_blank">Source</a>| Finlands foreign minister suggested Tuesday that the country may consider joining NATO without neighbouring Sweden if Turkey continues to block their joint bid to enter the military alliance. Pekka Haavisto later backpedaled, but his comments were the first time a leading government official in either Nordic country appeared to raise doubts about becoming NATO members together, at a time when the alliance is seeking to present a united front in the face of Russia's war in Ukraine. Sweden and Finland rushed to apply for NATO membership following Moscow's invasion, abandoning their long-standing non-alignment policy. To gain membership they need the approval of all existing NATO members, including Turkey, which has so far blocked the expansion.|
|<font color=#FF3399>[4]</font> Following the meeting,Shmyhal said,"For the first time in the history of mankind, nuclear facilities have become an element of an offensive military strategy," adding that Grossi pledged the IAEA's full support in "our efforts to ensure nuclear safety," including at the Zaporizhzhia nuclear power plant.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-1-18-23/h_edc0b0e2fb215d02f52a4830854b575f" target="_blank">Source</a>| The IAEA mission at Khmelnytsky nuclear power plant will alsobe functioning soon, Prime Minister Denys Shmyhal said at a press conference, with all the missions' work continuing during wartime and afterward to restore any damage. The IAEA continues to expand its presence in Ukraine, Director GeneralRafael Grossi said. Following the meeting,Shmyhal said,"For the first time in the history of mankind, nuclear facilities have become an element of an offensive military strategy," adding that Grossi pledged the IAEA's full support in "our efforts to ensure nuclear safety," including at the Zaporizhzhia nuclear power plant. Remember: Zaporizhzhia, with six reactors, is the largest nuclear power station in Europe.|
|<font color=#FF3399>[5]</font> The head of the agency is in Ukraine this week to "establish a continuous presence of nuclear safety and security experts at all the countrys nuclear power facilities," the IAEA previously announced.<a href="https://egyptindependent.com/iaea-chief-marks-permanent-presence-at-ukrainian-nuclear-plant/" target="_blank">Source</a>| The head of the International Atomic Energy Agency on Monday visited the South Ukraine Nuclear Power Plant to mark the permanent presence of the UN nuclear watchdog at the site. The head of the agency is in Ukraine this week to "establish a continuous presence of nuclear safety and security experts at all the countrys nuclear power facilities," the IAEA previously announced. "Now we are setting this permanent presence here," Rafael Mariano Grossi said in a video posted to his Twitter account.|
