# How might the delays in grain shipments impact the global food supply?

## Summary
The UN and other related parties are urgently calling for measures to be taken to prevent delays to ships sailing under the Black Sea Grain Initiative <font color=#FF3399>[2]</font>, as the current backlog of 150 vessels around Istanbul has the potential to cause disruptions to the supply chain and port operations <font color=#FF3399>[3]</font>. If this is not addressed, farmers will not have access to fertilizers at the right time and at a price they can afford as the planting season begins, resulting in dramatic effects on food production and food prices worldwide <font color=#FF3399>[4, 5]</font>. This could lead to a crisis of availability in 2023 and 2024 <font color=#FF3399>[4, 5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Russias invasion of Ukraine cut off shipments of grain and fertiliser from the two key world suppliers, causing food shortages and rising prices, especially in developing countries.<a href="https://www.euronews.com/2022/10/27/ukraine-war-ukrainian-and-russian-grain-deal-could-be-extended-past-november" target="_blank">Source</a>| A senior UN official has said that the deal for returning Ukrainian grain and Russian grain and fertiliser to world markets will likely be extended beyond mid-November. However, Russias UN ambassador has said that Moscow needs to see movement on its own exports first. Russias invasion of Ukraine cut off shipments of grain and fertiliser from the two key world suppliers, causing food shortages and rising prices, especially in developing countries. The deal, brokered by the UN and Turkey in July, has seen more than 8.5 million metric tons of foodstuffs shipped from three Black Sea ports in Ukraine, but it runs out in November, necessitating discussions on a renewal.|
|<font color=#FF3399>[2]</font> "If food and fertilizers do not reach global markets now, farmers will not have fertilizers at the right time and at a price they can afford as the planting season begins, endangering crops in all regions of the world in 2023 and 2024, with dramatic effect on food production and food prices worldwide.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-28-22/index.html" target="_blank">Source</a>| It came after months of negotiations and promises to unblock ports on the Black Sea to allow the safe passage of grain and oilseeds some of Ukraines most important exports. Guterres underlined the urgency to renew the deal on Nov. 19. "If food and fertilizers do not reach global markets now, farmers will not have fertilizers at the right time and at a price they can afford as the planting season begins, endangering crops in all regions of the world in 2023 and 2024, with dramatic effect on food production and food prices worldwide. The current crisis of affordability will turn into a crisis of availability," the statement said.|
|<font color=#FF3399>[3]</font> Palla confirmed there are currently "over 150 vessels waiting around Istanbul to move, and these delays have the potential to cause disruptions to the supply chain and port operations."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-24-22/h_1c126ffbb9875e3e93da72c0d7c04a78" target="_blank">Source</a>| The United Nations is calling for "urgent measures to be taken" to prevent delays to ships sailing under the Black Sea Grain Initiative, UN spokeswoman Ismini Palla told CNN on Sunday. Ukrainian officials have claimed that Moscow is intentionally slowing down food shipments made under the agreement signed in July by Ukraine, Russia, Turkey and the UN. Palla confirmed there are currently "over 150 vessels waiting around Istanbul to move, and these delays have the potential to cause disruptions to the supply chain and port operations." She told CNN that the Joint Coordination Centre (JCC) comprised of representatives from Russia, Turkey, Ukraine and the UN has acknowledged the problem of delays and is discussing ways to address the backlog.|
|<font color=#FF3399>[4]</font> If food and fertilizers do not reach global markets now, farmers will not have fertilizers at the right time and at a price they can afford as the planting season begins, endangering crops in all regions of the world in 2023 and 2024, with dramatic effect on food production and food prices worldwide.<a href="https://reliefweb.int/report/ukraine/secretary-general-urges-renewal-full-implementation-black-sea-grain-initiative-noting-resultant-food-price-drop-has-saved-100-million-people-extreme-poverty" target="_blank">Source</a>| The United Nations continues its active and constant engagement with all parties towards that goal. We underline the urgency of doing so to contribute to food security across the world, and to cushion the suffering that this global cost-of-living crisis is inflicting on billions of people. If food and fertilizers do not reach global markets now, farmers will not have fertilizers at the right time and at a price they can afford as the planting season begins, endangering crops in all regions of the world in 2023 and 2024, with dramatic effect on food production and food prices worldwide. The current crisis of affordability will turn into a crisis of availability.|
|<font color=#FF3399>[5]</font> If food and fertilizers do not reach global markets now, farmers will not have fertilizers at the right time and at a price they can afford as the planting season begins, endangering crops in all regions of the world in 2023 and 2024, with dramatic effect on food production and food prices worldwide.<a href="https://reliefweb.int/report/ukraine/secretary-general-urges-renewal-full-implementation-black-sea-grain-initiative-noting-resultant-food-price-drop-has-saved-100-million-people-extreme-poverty" target="_blank">Source</a>| The United Nations continues its active and constant engagement with all parties towards that goal. We underline the urgency of doing so to contribute to food security across the world, and to cushion the suffering that this global cost-of-living crisis is inflicting on billions of people. If food and fertilizers do not reach global markets now, farmers will not have fertilizers at the right time and at a price they can afford as the planting season begins, endangering crops in all regions of the world in 2023 and 2024, with dramatic effect on food production and food prices worldwide. The current crisis of affordability will turn into a crisis of availability.|
