# What is the goal of the price cap?

## Summary
The G-7 economic powers have agreed on a plan to impose a price cap on Russian oil in order to reduce Moscow's ability to fund its war in Ukraine <font color=#FF3399>[2]</font> and to minimize the economic damage of the conflict, especially on low and middle-income countries <font color=#FF3399>[3]</font>. The measure is specifically designed to reduce Russian revenues and its ability to fund its war of aggression <font color=#FF3399>[1]</font>. It is also intended to be a global measure against war <font color=#FF3399>[5]</font>. The price cap will begin on December 5, 2020 <font color=#FF3399>[2]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> The West's biggest economies on Friday agreed to impose a price cap on Russian oil in an attempt to reduce Moscow's ability to fund its war in Ukraine without further stoking global inflation.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-05-22/h_792e0a8e2f9d5ab91d578008d6355694" target="_blank">Source</a>| The West's biggest economies on Friday agreed to impose a price cap on Russian oil in an attempt to reduce Moscow's ability to fund its war in Ukraine without further stoking global inflation. Finance ministers from the G7 group of countries the United States, Japan, Canada, Germany, France, Italy and the United Kingdom said they would ban the provision of "services which enable maritime transportation of Russian-origin crude oil and petroleum products globally" above the price cap.|
|<font color=#FF3399>[2]</font> Officials in G7 countries, including U.S. Treasury Secretary Janet Yellen, say the unprecedented measure, set to begin Dec. 5, will cut the price Russia receives for oil without reducing its petroleum exports to world consumers.<a href="https://www.reuters.com/business/energy/g7s-price-cap-russian-oil-begins-take-shape-2022-09-12/" target="_blank">Source</a>| WASHINGTON, Sept 12 (Reuters) - The Group of Seven countries is working to cap the price of Russian oil in an attempt to limit Moscow's ability to fund its invasion of Ukraine, a plan analysts say could work in the long term but might boost oil prices in coming months. Officials in G7 countries, including U.S. Treasury Secretary Janet Yellen, say the unprecedented measure, set to begin Dec. 5, will cut the price Russia receives for oil without reducing its petroleum exports to world consumers. Russian President Vladimir Putin could push back, causing stress in oil markets even as the plan comes together.|
|<font color=#FF3399>[3]</font> At their virtual meeting, the finance ministers said the oil price cap plan was "specifically designed" to reduce Russian revenues and its ability to "fund its war of aggression".<a href="https://www.bbc.com/news/business-62770283" target="_blank">Source</a>| At their virtual meeting, the finance ministers said the oil price cap plan was "specifically designed" to reduce Russian revenues and its ability to "fund its war of aggression". They also said they wanted to minimise the damaging economic fallout of the conflict, "especially on low and middle-income countries".|
|<font color=#FF3399>[4]</font> The price cap's goal is to reduce Russian revenues, weaken the country's ability to fund its war and Ukraine and also ease the impact of the war on global energy prices, the statement said.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-02-22/h_5575752ce49534331660afd321225998" target="_blank">Source</a>| Finance ministers from the G7 nations released a joint statement announcing that they have agreed to implement a price cap on Russian oil and petroleum products in order to "reduce Russian revenues and Russia's ability to fund its war of aggression." "Today we confirm our joint political intention to finalise and implement a comprehensive prohibition of services which enable maritime transportation of Russian-origin crude oil and petroleum products globally the provision of such services would only be allowed if the oil and petroleum products are purchased at or below a price ("the price cap") determined by the broad coalition of countries adhering to and implementing the price cap," the statement reads. The price cap's goal is to reduce Russian revenues, weaken the country's ability to fund its war and Ukraine and also ease the impact of the war on global energy prices, the statement said. The measure builds on existing sanctions, particularly those in the sixth EU package, it added.|
|<font color=#FF3399>[5]</font> But aside from cutting Russia's oil revenues a key source of funding for President Vladimir Putin's war chest Le Maire said the policy should be implemented as a "global measure against war."<a href="https://www.cnbc.com/2022/09/03/france-says-imposing-a-price-cap-on-russian-oil-will-be-difficult.html" target="_blank">Source</a>| The G-7 economic powers announced Friday that they had agreed on a plan to impose a set price on Russian oil. The initiative is the latest attempt to apply economic pressure on Moscow over its invasion of Ukraine. But aside from cutting Russia's oil revenues a key source of funding for President Vladimir Putin's war chest Le Maire said the policy should be implemented as a "global measure against war." "You need an outreach because we don't want this measure to be only a Western measure," Le Maire told CNBC's Steve Sedgwick at the Ambrosetti Forum in Italy.|
