# What role has NATO played in responding to the missile attacks on Ukraine?

## Summary
NATO and G7 leaders have condemned Russia's "barbaric missile attacks" on Ukrainian cities and civilian infrastructure <font color=#FF3399>[1]</font>. NATO has so far responded with a consensus to provide Ukraine with arms supplies as a deterrent to Russia's recklessness <font color=#FF3399>[2]</font>. According to a CNN analysis, at least a dozen cities and districts in Ukraine have been targeted with missiles and drones <font color=#FF3399>[3]</font>. The United States has promised to provide Ukraine with air defense systems <font color=#FF3399>[4]</font>, and Ukrainian First Lady Olena Zelenska has called on the global technology community to aid her country in combating the Russian invasion <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> NATO and G7 leaders released a joint statement following their emergency meeting on the margins of the G20, condemning the "barbaric missile attacks that Russia perpetrated on Ukrainian cities and civilian infrastructure on Tuesday."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-15-22/h_7f5e94a0dce088cef21f3ccdd455b183" target="_blank">Source</a>| NATO and G7 leaders released a joint statement following their emergency meeting on the margins of the G20, condemning the "barbaric missile attacks that Russia perpetrated on Ukrainian cities and civilian infrastructure on Tuesday." Russia fired "around 100 missiles" at cities across Ukraine on Tuesday, Yurii Ihnat, a spokesperson for the Ukrainian Air Force command, said previously.|
|<font color=#FF3399>[2]</font> Up to now, the broad Nato consensus has been that Russian escalation would lead to stepped-up arms supplies to Ukraine, and that rather than any form of direct Nato involvement would serve as a deterrent to Russian recklessness.<a href="https://www.theguardian.com/world/live/2022/nov/15/russia-ukraine-war-live-news-updates-kherson-victory-marks-beginning-of-end-of-russian-war-zelenskiy-says" target="_blank">Source</a>| "Deliberate armed attack is a real thing," Alberque said. "Two misfired cruise or ballistic missiles aint it." Up to now, the broad Nato consensus has been that Russian escalation would lead to stepped-up arms supplies to Ukraine, and that rather than any form of direct Nato involvement would serve as a deterrent to Russian recklessness. That is the most likely response this time, and there will be a debate within Nato on whether it warrants a step up in the sort of military assistance being provided.|
|<font color=#FF3399>[3]</font> Looking forward, Sullivan pledged the United States allies "will continue to provide Ukraine with what it needs to defend itself, including air defense systems.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-15-22/h_3314bf4dbe24809a7c76e09ba41fc896" target="_blank">Source</a>| According to a CNN analysis of the strikes, at least a dozen cities and districts were targeted. The wave of strikes appears to be the largest since Oct. 10, when Russia stepped up its campaign to destroy electricity, water and gas infrastructure across Ukraine. Looking forward, Sullivan pledged the United States allies "will continue to provide Ukraine with what it needs to defend itself, including air defense systems. We will stand with Ukraine for as long as it takes."|
|<font color=#FF3399>[4]</font> From the beginning of the war, air defense has been a key component of Ukraines resistance to the Russian invasion.<a href="https://www.grid.news/story/global/2022/11/11/nasams-the-latest-western-weapon-sent-to-ukraine-aims-to-knock-russian-missiles-out-of-the-sky/" target="_blank">Source</a>| Reznikovs excitement was understandable, if a little cryptic to the uninitiated. Not everyone will know what "NASAMS" stands for, but some hope it may soon be a household name. From the beginning of the war, air defense has been a key component of Ukraines resistance to the Russian invasion. It has taken on an even greater significance since early October, when Russia stepped up its campaign of missiles and drone strikes targeting Ukraines cities and infrastructure.|
|<font color=#FF3399>[5]</font> Ukrainian First Lady Olena Zelenska made an impassioned speech on Tuesday calling on the global technology community to aid her country and combat Russia's invasion.<a href="https://www.cnbc.com/2022/11/02/russia-ukraine-live-updates.html" target="_blank">Source</a>| Ukraines first lady Olena Zelenska smiles during a standing ovation following Ukraines President Volodymyr Zelenski's address via a video during the 77th Session of the United Nations General Assembly at U.N. Headquarters in New York City, September 21, 2022. Ukrainian First Lady Olena Zelenska made an impassioned speech on Tuesday calling on the global technology community to aid her country and combat Russia's invasion. Speaking at the Web Summit conference in Lisbon, Zelenska told attendees that technology has become "battlefield" in the Russian war against Ukraine.|
