# How will Russia respond to the price cap set by western nations?

## Summary
Russia will not recognize the price cap set by western nations on its oil exports and is threatening to cut production and refuse to export oil to countries that impose the cap <font color=#FF3399>[2, 4]</font>. Deputy Prime Minister Alexander Novak said on state TV that Russia will only sell oil and oil products to countries that are willing to work with it on market terms, even if it has to reduce production <font color=#FF3399>[4]</font>. Additionally, President Vladimir Putin warned that prices could spike if there are cuts <font color=#FF3399>[2]</font>. Finally, while the Biden administration seems to fear overcompliance more than undercompliance, it must be prepared to enforce the cap with penalties if needed, as Putin could remove oil supplies from the global marketplace by shutting in large quantities of Russian oil <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> "One thing is obvious here - we will not recognize any price caps," Peskov said Monday during his daily conference call with journalists, adding that Russia would prepare a response to the measure.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-05-22/h_314d10b666cf8bf679059a86c6b23a8f" target="_blank">Source</a>| Moscow will not recognize a price cap on its oil exports implemented by a group of western nations, according to Kremlin spokesperson Dmitry Peskov. "One thing is obvious here - we will not recognize any price caps," Peskov said Monday during his daily conference call with journalists, adding that Russia would prepare a response to the measure. On Friday, the European Union's 27 member states capped the price of Russian oil at $60 a barrel, with Australia and the Group of 7 nations -- Canada, France, Germany, Italy, Japan, the United Kingdom and the United States -- implementing the price cap from Monday.|
|<font color=#FF3399>[2]</font> Russia, the world's biggest exporter of fossil fuels, could cut oil production and will refuse to sell oil to any country that imposes the West's "stupid" price cap, Russian President Vladimir Putin said on Dec. 9.<a href="https://www.reuters.com/business/energy/biden-energy-envoy-hochstein-happy-with-russian-oil-price-cap-so-far-2022-12-13/" target="_blank">Source</a>| He said he spoke on Tuesday morning with the chief executive of "one of the largest crude trading houses" who told him that they have started trading crude below the price cap. Hochstein did not detail that discussion further. Russia, the world's biggest exporter of fossil fuels, could cut oil production and will refuse to sell oil to any country that imposes the West's "stupid" price cap, Russian President Vladimir Putin said on Dec. 9. Such threats have made some market players anxious that prices could spike if there are cuts.|
|<font color=#FF3399>[3]</font> Russia can sell at or below the price cap and keep its oil flowing onto global markets, at lower prices for importers and with the benefit of best-in-class G7 services.<a href="https://home.treasury.gov/news/press-releases/jy1141" target="_blank">Source</a>| This price is set at a level that Russia has historically accepted, which is above its cost of production and comparable with prices Russia sold at prior to its war in Ukraine. Russia has multiple options to respond to the price cap. Russia can sell at or below the price cap and keep its oil flowing onto global markets, at lower prices for importers and with the benefit of best-in-class G7 services. Alternatively, Russia can rely on non-G7 service providers, which are limited in scale, more expensive, and less reliable.|
|<font color=#FF3399>[4]</font> Russia will not export oil to countries that impose price caps even if production is cut, Russian Deputy Prime Minister Alexander Novak said on Russia state TV Sunday.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-04-22/h_fe6184f75b5043a15c312b2c3eb3532a" target="_blank">Source</a>| Russia will not export oil to countries that impose price caps even if production is cut, Russian Deputy Prime Minister Alexander Novak said on Russia state TV Sunday. "We will sell oil and oil products to those countries that will work with us on market terms, even if we have to somewhat reduce production," he added.|
|<font color=#FF3399>[5]</font> Could Putin respond by just cutting off oil sales?<a href="https://www.energypolicy.columbia.edu/publications/what-success-or-failure-would-look-price-cap-russian-oil/" target="_blank">Source</a>| [6] The Biden administration seems to fear overcompliance more than undercompliance. But if this expectation proves incorrect, Washington must be prepared to vigorously enforce the cap with penalties. Could Putin respond by just cutting off oil sales? Yes, Putin himself could remove oil supplies from the global marketplace by shutting in large quantities of Russian oil.|
