# How have Western countries responded to increased use of kamikaze drones by Russia in Ukraine?

## Summary
Western countries have responded to Russia's increased use of kamikaze drones in Ukraine by providing Kyiv with more air defense systems and ammunition <font color=#FF3399>[1]</font> and attempting to prevent Iran from acquiring dual-use components <font color=#FF3399>[4]</font>. US Secretary of State Antony Blinken has called the use of the drones "appalling" and vowed to crack down on their provision <font color=#FF3399>[3]</font>. Canada and the US will also keep working with their allies and partners to expose, deter, and counter Iran's provision of these weapons <font color=#FF3399>[5]</font>. <font color=#FF3399>[2]</font>

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Kyiv says Moscow has used Iranian-supplied kamikaze drones in strikes against Kyiv, Vinnytsia,Odesa, Zaporizhzhia and other cities across Ukraine in recent weeks, and pleaded with Western countries to step up their assistance in the face of the new challenge.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-17-22/h_acad2b553a31e40076c26c574aac3af3" target="_blank">Source</a>| Ukraine has repeatedly asked its allies to supply it with more air defense systems and ammunition after Russia stepped up its use of "kamikaze drones" in its brutal assault against the country. Kyiv says Moscow has used Iranian-supplied kamikaze drones in strikes against Kyiv, Vinnytsia,Odesa, Zaporizhzhia and other cities across Ukraine in recent weeks, and pleaded with Western countries to step up their assistance in the face of the new challenge. Drones have played a significant role in the conflict since Russia launched its full-scale invasion of Ukraine in late February, but their use has increased since Moscow acquired the new drones from Iran over the summer.|
|<font color=#FF3399>[2]</font> Ukrainian officials have pleaded with Western countries to step up their assistance in the face of the new challenge, in addition to developing its own technology to counter the strikes.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-16-22/h_1350e11d991341044c6b9bfffce32d60" target="_blank">Source</a>| Most recently, the southern Ukrainian city of Zaporizhzhia was hit with four strikes by kamikaze drones overnight Saturday. Authorities said Moscow has also used them in assaults against Kyiv, Vinnytsia,Odesa and other cities across Ukraine in recent weeks. Ukrainian officials have pleaded with Western countries to step up their assistance in the face of the new challenge, in addition to developing its own technology to counter the strikes. Kamikaze drones, or suicide drones, are a type of aerial weapon system.|
|<font color=#FF3399>[3]</font> Meanwhile, Antony Blinken, US secretary of state, called the use of the drones "appalling" and vowed to crack down on their use.<a href="https://www.independent.ie/world-news/europe/kremlins-attacks-on-ukraine-deploy-iranian-drones-built-from-us-parts-that-are-bought-online-42105088.html" target="_blank">Source</a>| Harsh sanctions on Iran mean its engineers are forced to use household technologies to build military-grade machines. Ukrainian officials are working with counterparts from G7 countries to prevent Tehran from acquiring dual-use components in the future. Meanwhile, Antony Blinken, US secretary of state, called the use of the drones "appalling" and vowed to crack down on their use. "Canada and the US will keep working with our allies and partners to expose, deter, and counter Irans provision of these weapons," he said.|
|<font color=#FF3399>[4]</font> Meanwhile, Antony Blinken, US secretary of state, called the use of the drones "appalling" and vowed to crack down on their use.<a href="https://www.independent.ie/world-news/europe/kremlins-attacks-on-ukraine-deploy-iranian-drones-built-from-us-parts-that-are-bought-online-42105088.html" target="_blank">Source</a>| Harsh sanctions on Iran mean its engineers are forced to use household technologies to build military-grade machines. Ukrainian officials are working with counterparts from G7 countries to prevent Tehran from acquiring dual-use components in the future. Meanwhile, Antony Blinken, US secretary of state, called the use of the drones "appalling" and vowed to crack down on their use. "Canada and the US will keep working with our allies and partners to expose, deter, and counter Irans provision of these weapons," he said.|
|<font color=#FF3399>[5]</font> Ukrainian officials say Russia has been deploying an increasingly familiar weapon in its attacks: "kamikaze drones."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-16-22/h_95cc4ca2e4d8bb2872f6c46902bda4ab" target="_blank">Source</a>| Ukrainian officials say Russia has been deploying an increasingly familiar weapon in its attacks: "kamikaze drones." Most recently, the southern Ukrainian city of Zaporizhzhia was hit with four strikes bykamikaze dronesovernight Saturday.|
