# How has the presence of Russian forces affected the daily lives of civilians in Melitopol?

## Summary
The presence of Russian forces in Melitopol has had a devastating effect on the daily lives of civilians. The mayor of the city, Ivan Fedorov, reported that the city has been turned into a "huge military base" <font color=#FF3399>[1]</font> and civilians are prohibited from approaching the area of the Melitopol airfield <font color=#FF3399>[1]</font>. The Russians have been conducting offensive actions, attacking units of the defence forces, carrying out fortification equipment along the borders and conducting aerial reconnaissance <font color=#FF3399>[2]</font>. In late June, a massive explosion rocked the outskirts of the city which was determined to be a 90 kilogram rocket fired from the US-provided Himars system <font color=#FF3399>[5]</font>. This system has gone on to destroy bridges, supply depots and command headquarters, crippling Russia's ability to function <font color=#FF3399>[5]</font>. As a result of this, it has become extremely difficult for civilians to leave the city, with only 150-200 people per day being able to leave through Vasylivka <font color=#FF3399>[4]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Fedorov also reported that "civilians are prohibited from approaching the area of the Melitopol airfield."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-14-22/h_dce9d898240a4b6a13187074d5919cc0" target="_blank">Source</a>| The mayor of the southern Ukrainian city of Melitopol, Ivan Fedorov, says Russian forces have turned the city into a "huge military base" while under their occupation. Melitopol has been held by Russian forces since the early days of the invasion. Fedorov also reported that "civilians are prohibited from approaching the area of the Melitopol airfield."|
|<font color=#FF3399>[2]</font> The invaders continue to strike critical infrastructure and civilian housing in violation of international humanitarian law, and the laws and customs of war.<a href="https://news.yahoo.com/armed-forces-ukraine-successfully-operating-162944956.html" target="_blank">Source</a>| The Russians are conducting offensive actions on the Bakhmut, Avdiivka and Novopavlivka fronts. Russian troops are attacking units of the defence forces along the contact line, carrying out fortification equipment along the borders on certain fronts, and conducting aerial reconnaissance. The invaders continue to strike critical infrastructure and civilian housing in violation of international humanitarian law, and the laws and customs of war. Over the course of the day, the Russians carried out one missile and 12 air strikes.|
|<font color=#FF3399>[3]</font> It has been extremely difficult for civilians to leave the city, Fedorov added.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-04-22/h_150a8688e7b2af06a222b6b2397aadfc" target="_blank">Source</a>| "There was a barracks and equipment. It was one of the hardest targets in terms of reaching it, in terms of the air defense and the location." It has been extremely difficult for civilians to leave the city, Fedorov added. "Today 150 to 200 people per day leave through Vasylivka (the only available route from occupied territory to Ukrainian-held areas) compared to 1,000 people as it was."|
|<font color=#FF3399>[4]</font> It has been extremely difficult for civilians to leave the city, Fedorov added.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-04-22/h_150a8688e7b2af06a222b6b2397aadfc" target="_blank">Source</a>| "There was a barracks and equipment. It was one of the hardest targets in terms of reaching it, in terms of the air defense and the location." It has been extremely difficult for civilians to leave the city, Fedorov added. "Today 150 to 200 people per day leave through Vasylivka (the only available route from occupied territory to Ukrainian-held areas) compared to 1,000 people as it was."|
|<font color=#FF3399>[5]</font> It wiped out an ammunition dump heralding the crucial impact of Himars rockets, that have gone on to destroy bridges, supply depots and command headquarters, crippling Russias ability to function.<a href="https://www.thenationalnews.com/world/europe/2022/11/13/ukraines-himars-rockets-can-now-target-crimea/" target="_blank">Source</a>| The systems devastating abilities were first demonstrated in late June when a massive explosion rocked the outskirts of the only city taken by Russia during its nine-month invasion. The Russians claimed that an agricultural warehouse had caught fire but the Ukrainians said it was a 90 kilogram rocket fired from the system. It wiped out an ammunition dump heralding the crucial impact of Himars rockets, that have gone on to destroy bridges, supply depots and command headquarters, crippling Russias ability to function. As part of its $20 billion military package, the US has sent 34 vehicles that can fire six of the $110,000 GMLRS rockets from a single pod in under a minute.|
