# What potential risks does the oil price cap pose to global energy markets?

## Summary
The G7 recently agreed to a price cap on Russian oil to help protect consumers and businesses from global supply disruptions. However, this could have a destabilizing effect on world energy markets. Russia has warned that it will stop supplying countries that adhere to the cap [1], and the Biden administration called the cuts agreed to in October "shortsighted" and said they would hurt low- and middle-income countries by pushing energy prices higher [2]. Urals has been trading at discounts of around $23 in recent days, and the EU agreement includes a mechanism to adjust the level of the cap to ensure it is always 5% below the market rate [3]. This could lead to Russia retaliating by slashing its output, which could cause markets to become volatile [4].

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Fears of overcompliance explain why senior US officials have made compliance expectations relatively simple[5] and have repeatedly downplayed the threat of American penalties when companies accidentally violate the policy.<a href="https://www.energypolicy.columbia.edu/publications/what-success-or-failure-would-look-price-cap-russian-oil/" target="_blank">Source</a>| The result could be a major drop in the supply of Russian oil available on the global market, which could increase prices for everyone. (Of course, if the supply of Russian oil is squeezed but global energy prices do not increase, that would not be a problem from the perspective of the G7.) Fears of overcompliance explain why senior US officials have made compliance expectations relatively simple[5] and have repeatedly downplayed the threat of American penalties when companies accidentally violate the policy. What would failure look like?|
|<font color=#FF3399>[2]</font> "The price cap will encourage the flow of discounted Russian oil onto global markets and is designed to help protect consumers and businesses from global supply disruptions," Treasury Secretary Janet Yellen said in a statement.<a href="https://finance.yahoo.com/news/us-joins-eu-and-g-7-to-cap-russian-oil-prices-at-60-barrel-232259347.html" target="_blank">Source</a>| The cap also ensures oil can keep flowing to the global market, preventing a spike in global oil prices as governments around the world work to tamp down multi-decade highs in inflation. Russias invasion has been a large contributor to the spike in oil prices this year. "The price cap will encourage the flow of discounted Russian oil onto global markets and is designed to help protect consumers and businesses from global supply disruptions," Treasury Secretary Janet Yellen said in a statement. "The price cap will particularly benefit low- and medium-income countries who have already borne the brunt of elevated energy and food prices."|
|<font color=#FF3399>[3]</font> "One thing is obvious and indisputable: the adoption of these decisions is a step towards destabilizing the world energy markets," he said.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-05-22/h_314d10b666cf8bf679059a86c6b23a8f" target="_blank">Source</a>| "Such measures will not affect it." However the price cap would have an effect on the stability of the energy market, said Peskov. "One thing is obvious and indisputable: the adoption of these decisions is a step towards destabilizing the world energy markets," he said.|
|<font color=#FF3399>[4]</font> The risk of settling on a lower price is that Russia could retaliate by slashing its output, which would roil markets.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-04-22/h_fe6184f75b5043a15c312b2c3eb3532a" target="_blank">Source</a>| Urals has been trading at discounts of around $23 in recent days. Reuters reported that the EU agreement included a mechanism to adjust the level of the cap to ensure it was always 5% below the market rate. The risk of settling on a lower price is that Russia could retaliate by slashing its output, which would roil markets. Russia previously warned that it will stop supplying countries that adhere to the cap.|
|<font color=#FF3399>[5]</font> Since then, oil prices have instead pulled back, as traders have focused on how ongoing coronavirus lockdowns in China and global recession fears could hit demand.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-04-22/h_9cddb659f5f02e708ae64fc4e884dfed" target="_blank">Source</a>| The cuts agreed to in October, the biggest since the start of the pandemic, drew criticism from the United States. The Biden administration called them "shortsighted" and said they would hurt low- and middle-income countries by pushing energy prices higher. Since then, oil prices have instead pulled back, as traders have focused on how ongoing coronavirus lockdowns in China and global recession fears could hit demand. Markets could be volatile in the coming days, however.|
