# What are the implications of Russia's control of the Zaporizhzhia nuclear power plant on the security of the region?

## Summary
The Zaporizhzhia nuclear power plant, located in the contested region on the Ukrainian-Russian border, has been under Russia’s control since the start of the war. This has raised concerns about the safety of the area amid shelling around the plant <font color=#FF3399>[1]</font>. Ukraine has requested the control of the facility to be returned to their authorities and for Russia to withdraw their personnel and troops <font color=#FF3399>[1]</font>. The IAEA has refused to recognize Russia as the owner of the power plant <font color=#FF3399>[1]</font>. The European Parliament, as well as Ukrainian Prime Minister Shmyhal, are seeking to create a nuclear safety and security protection zone around the plant <font color=#FF3399>[2]</font>. This would function like a “bubble”, excluding military action from both sides <font color=#FF3399>[2]</font>. However, the area remains exposed to shelling and a blackout could potentially cause a nuclear disaster <font color=#FF3399>[2]</font>. In addition, the Russian Foreign Intelligence (SVR) Director has accused Ukraine of using the power plant as a safe haven to store weapons <font color=#FF3399>[3]</font>. These claims have been denied but the possibility of increased military activity in the coming months has raised the IAEA’s concerns <font color=#FF3399>[4]</font>. Therefore, the situation around the Zaporizhzhia nuclear power plant has been described

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Shmyhal said Ukraine has asked that the control of the Zaporizhzhia facility be returned to Ukrainian authorities and that there is a "complete withdrawal" ofRussian troops and Rosatom personnel from the plant.Grossi assured Ukraine that the IAEA would never recognize Russia as the owner of the Zaporizhzhia nuclear power plant., according to Shmyhal.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-1-18-23/h_edc0b0e2fb215d02f52a4830854b575f" target="_blank">Source</a>| The area, and the nuclear complex, has been under Russian controlsince the beginning of the war. Grossi and other nuclear experts have been concerned about the threat of a nuclear accident amid shelling around the plant. Shmyhal said Ukraine has asked that the control of the Zaporizhzhia facility be returned to Ukrainian authorities and that there is a "complete withdrawal" ofRussian troops and Rosatom personnel from the plant.Grossi assured Ukraine that the IAEA would never recognize Russia as the owner of the Zaporizhzhia nuclear power plant., according to Shmyhal. The prime minister added that Ukraine will "continue to insist on limiting Russia's rights and privileges in the IAEA and terminating cooperation with Russia in the nuclear sphere."|
|<font color=#FF3399>[2]</font> This safety zone would function like a "bubble" to exclude military action by both sides.<a href="https://www.thenationalnews.com/world/europe/2023/01/24/un-nuclear-chief-headed-to-tehran-in-february/" target="_blank">Source</a>| In addition to discussing Iran, Mr Grossi was in Brussels to drum up political support for the IAEAs safeguarding activities at Europes largest nuclear power plant, located in the contested Zaporizhzhia region of Ukraine. Mr Grossi said that he was trying to convince Russia and Ukraine to establish a nuclear safety zone around the plant, which is in Russian-controlled territory but operated by Ukrainian technical staff. This safety zone would function like a "bubble" to exclude military action by both sides. He warned that the plant continued to be exposed to shelling and that another blackout, which happened in November, could cause a nuclear disaster.|
|<font color=#FF3399>[3]</font> He is mounting a new push to create a nuclear safety and security protection zone around the Zaporizhzhia plant, which has been hit by rockets and artillery shells in past months.<a href="https://www.politico.eu/article/ukraine-war-military-nuclear-accident-atomic-safety-chief-rafael-mariano-grossi/" target="_blank">Source</a>| Enerhodar, the city housing the plant, lies on the banks of the Dnipro River, one side of which is under Russian control while the other is in Ukrainian hands. Grossi was in Brussels earlier this week to speak to the European Parliament and attend a gathering of EU foreign ministers. He is mounting a new push to create a nuclear safety and security protection zone around the Zaporizhzhia plant, which has been hit by rockets and artillery shells in past months. Although the attacks have subsided in recent weeks, Grossi said there were "thousands of troops" near the plant.|
|<font color=#FF3399>[4]</font> The situation in the recent days around Zaporizhzhia has been "pretty tense" with shelling in the vicinity of the Zaporizhzia nuclear site, Grossi added.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-1-24-23/h_d6955f8da3d8d83bd88e1ef757f17988" target="_blank">Source</a>| On Monday, the Russian Foreign Intelligence (SVR) DirectorSergey Naryshkin accused Ukraine in a statement of "stockpiling weapons and ammunition provided by the West on the territories of nuclear power plants." Regarding the situation on the ground in Ukraine, Grossi told European lawmakers that the possibility of increased military activity in the coming months "raises our degree of concern" about the potential impact on Ukraine's nuclear infrastructure. The situation in the recent days around Zaporizhzhia has been "pretty tense" with shelling in the vicinity of the Zaporizhzia nuclear site, Grossi added.|
|<font color=#FF3399>[5]</font> Grossi described Zaporizhzhia as a "flash point' in the war, as it is on Russian occupied territory.<a href="https://euobserver.com/ukraine/156639" target="_blank">Source</a>| "For months Russian armed forces have been using these Ukrainian power plants as safe havens to store ammunition and launch attacks on neighbouring areas," German MEP David McAllister, chair of the foreign affairs committee, said after the meeting. "We do hope negotiations will conclude shortly, allowing for early establishment of this protection zone," French MEP Nathalie Loiseau said. Grossi described Zaporizhzhia as a "flash point' in the war, as it is on Russian occupied territory. "It has this quite bizarre situation: a Ukrainian facility in Russian-controlled territory, managed by Russians, but operated by Ukrainians," Grossi said.|
