# What are the primary targets of the Russian shelling in Kherson?

## Summary
The Russian shelling in Kherson has been targeting the city, its infrastructure, and the energy supply. <font color=#FF3399>[1]</font> The bombardment has killed at least three people and injured six, including a 6-year-old girl. <font color=#FF3399>[2]</font> Halyna Luhova, head of Kherson city military administration, stated that the heating systems and water supply have been impacted due to the sniper fire and shelling from mortars, artillery, and Grad multiple-launch rocket systems. <font color=#FF3399>[3]</font> Moreover, Ukrainian President Volodymyr Zelenskyy decried the war during the soccer World Cup. <font color=#FF3399>[4]</font> The shelling has been especially intense since the Russian forces withdrew from the city and it was reclaimed by the Ukrainian army in November. <font color=#FF3399>[5]</font> These attacks have caused civilians to evacuate the region in search of safety.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Russian forces "shelled the territory of Kherson region 69 times" on Sunday, said Yaroslav Yanushevych, head of Kherson region military administration, adding that the attacks killed at least three people, injured six, struck a hotel and apartment buildings, and also damaged infrastructure in the region that was recaptured in November.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-19-22/h_111fb1cec9451ddadc7a99d1181f8590" target="_blank">Source</a>| Civilians in the southern Ukrainian city of Kherson continue to shelter from Russian bombardment, with local officials saying that both the city and other recently liberated settlements are hit dozens of times daily. Russian forces "shelled the territory of Kherson region 69 times" on Sunday, said Yaroslav Yanushevych, head of Kherson region military administration, adding that the attacks killed at least three people, injured six, struck a hotel and apartment buildings, and also damaged infrastructure in the region that was recaptured in November. Heating systems and water supply impacted: Halyna Luhova, head of Kherson city military administration, gave the following updates: In one district, the heating system needed water from the Dnipro river, but collecting it "is impossible due to sniper fire and shelling from mortars, artillery and Grad multiple-launch rocket systems," she said, recommending that people from such districts leave the city.|
|<font color=#FF3399>[2]</font> Ukraine has faced a blistering onslaught of Russian artillery fire, missiles, shelling and drone attacks since early October, much of it targeting the energy infrastructure in a bid to cut electricity and heating services as the freezing winter advances.<a href="https://www.npr.org/2022/12/24/1145443678/ukraine-kherson-deadly-shelling-russians" target="_blank">Source</a>| Yanushevych said scores of others, including a 6-year-old girl, were wounded by Russian shelling a day earlier. Saturday marks 10 months since the start of the Russian invasion. Ukraine has faced a blistering onslaught of Russian artillery fire, missiles, shelling and drone attacks since early October, much of it targeting the energy infrastructure in a bid to cut electricity and heating services as the freezing winter advances. The shelling has been especially intense in Kherson since Russian forces withdrew and Ukraine's army reclaimed the city in November.|
|<font color=#FF3399>[3]</font> In the latest phase of the war that Russia began nearly 10 months ago, Moscows forces have been heavily targeting infrastructure serving civilians, such as water and electricity supply lines, compounding Ukrainians suffering as winter sets in.<a href="https://www.militarytimes.com/flashpoints/ukraine/2022/12/18/russian-shelling-targets-heart-of-city-of-kherson/" target="_blank">Source</a>| Regional governor Yaroslav Yanushevych said Sunday that Russia had carried out 54 attacks with rocket, mortar and tank fire over the previous day, killing three people and wounding six. Meanwhile, in Russia, the governor of the Belgorod region, Vyacheslav Gladkov, said Sunday that one person was killed and eight wounded in Ukrainian shelling of the region, which lies along Ukraines northern border. In the latest phase of the war that Russia began nearly 10 months ago, Moscows forces have been heavily targeting infrastructure serving civilians, such as water and electricity supply lines, compounding Ukrainians suffering as winter sets in. Ukrainian President Volodymyr Zelenskyy used the final of the soccer World Cup to decry war.|
|<font color=#FF3399>[4]</font> The invaders attacked peaceful settlements of the region with artillery, MLRS, mortars and tanks."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-23-22/h_32bb7d91d1f5aedcd906d3df8fb299be" target="_blank">Source</a>| Ukrainian officials say that Russian shelling across the Dnipro river in Kherson has increased, with more than sixty strikes on Wednesday alone. Yaroslav Yanushevych, head of the Kherson region military administration, said that the Russians "shelled the territory of Kherson region 61 times. The invaders attacked peaceful settlements of the region with artillery, MLRS, mortars and tanks." About half the strikes hit the city of Kherson, including private and apartment buildings, he said.|
|<font color=#FF3399>[5]</font> Ukraine has faced a blistering onslaught of Russian artillery fire, missiles, shelling and drone attacks since early October, much of it targeting the energy infrastructure in a bid to cut electricity and heating services as the freezing winter advances.<a href="https://www.nbcnews.com/news/world/russia-ukraine-war-zelenskyy-christmas-message-putin-kherson-shelling-rcna63185" target="_blank">Source</a>| Yanushevych called on people to "evacuate" the region where the shelling has been especially intense after Russian forces withdrew from the city of Kherson last month and it was reclaimed by the Ukrainian army. For those who had been internally displaced, he said there were "free places to live in other regions." Ukraine has faced a blistering onslaught of Russian artillery fire, missiles, shelling and drone attacks since early October, much of it targeting the energy infrastructure in a bid to cut electricity and heating services as the freezing winter advances. Earlier Saturday, the Donetsk regional governor, Pavlo Kyrylenko, said two people were killed and five wounded in shelling there over the past day.|
