# How have Russian forces been able to maintain a sustained level of shelling of Kherson and other recently liberated settlements?

## Summary
Since the liberation of Kherson in November, Russian forces have been able to maintain a sustained level of shelling of the city and other recently liberated settlements in southern Ukraine, such as Donetsk. <font color=#FF3399>[1]</font> Attacks on Kherson have been particularly intense since the liberation, with local officials saying that the city and other settlements have been hit dozens of times daily, <font color=#FF3399>[2]</font> leading to several fatalities and injuries, as well as extensive damage to infrastructure, buildings, and a senior citizens' home. <font color=#FF3399>[3, 4, 5]</font> Moreover, volunteer forces have been unable to stop the Russian advance, <font color=#FF3399>[3]</font> indicating the strength of the Russian presence in the region.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Civilians in the southern Ukrainian city of Kherson continue to shelter from Russian bombardment, with local officials saying that both the city and other recently liberated settlements are hit dozens of times daily.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-19-22/h_111fb1cec9451ddadc7a99d1181f8590" target="_blank">Source</a>| Civilians in the southern Ukrainian city of Kherson continue to shelter from Russian bombardment, with local officials saying that both the city and other recently liberated settlements are hit dozens of times daily. Russian forces "shelled the territory of Kherson region 69 times" on Sunday, said Yaroslav Yanushevych, head of Kherson region military administration, adding that the attacks killed at least three people, injured six, struck a hotel and apartment buildings, and also damaged infrastructure in the region that was recaptured in November.|
|<font color=#FF3399>[2]</font> The shelling has been especially intense in Kherson since Russian forces withdrew and Ukraine's army reclaimed the city in November.<a href="https://www.npr.org/2022/12/24/1145443678/ukraine-kherson-deadly-shelling-russians" target="_blank">Source</a>| Saturday marks 10 months since the start of the Russian invasion. Ukraine has faced a blistering onslaught of Russian artillery fire, missiles, shelling and drone attacks since early October, much of it targeting the energy infrastructure in a bid to cut electricity and heating services as the freezing winter advances. The shelling has been especially intense in Kherson since Russian forces withdrew and Ukraine's army reclaimed the city in November. Earlier Saturday, the Donetsk regional governor, Pavlo Kyrylenko, said two people were killed and five wounded in shelling there over the past day.|
|<font color=#FF3399>[3]</font> Civilian volunteers were unable to hold back the Russian forces from Kherson, a port city with a prewar population of 280,000 that is home to a ship-building industry.<a href="https://www.pbs.org/newshour/world/khersons-rapid-fall-at-start-of-russian-invasion-leaves-unanswered-questions" target="_blank">Source</a>| Despite their lack of training and equipment, the volunteers have played a crucial role in the war and were a key reason Kyiv wasnt occupied, said Mykhailo Samus, founder of New Geopolitics Research Network, a Ukrainian think tank. "When a (Russian) sabotage group gets into a city, they expect to see civilians, but they found a lot of people with Kalashnikov guns and it was a disaster for Russians," Samus said. Civilian volunteers were unable to hold back the Russian forces from Kherson, a port city with a prewar population of 280,000 that is home to a ship-building industry. Kherson is just north of Crimea, which Russia illegally annexed in 2014.|
|<font color=#FF3399>[4]</font> Ukrainian forces liberated the city from Russian occupation on Nov. 11 but officials say Kremlin forces have continued shelling it from positions on the other side of the Dnipro River.<a href="https://www.reuters.com/world/europe/one-killed-kherson-shelling-governor-2022-12-17/" target="_blank">Source</a>| Yaroslav Yanushevych said on Telegram that Russian troops had struck a western district of Kherson - a port city on the Black Sea - with artillery and rocket fire. In addation to the fatality, a 70-year-old woman was wounded. Ukrainian forces liberated the city from Russian occupation on Nov. 11 but officials say Kremlin forces have continued shelling it from positions on the other side of the Dnipro River. In a separate message on Saturday, Yanushevych said Russian troops had shelled a senior citizens' home in a village just outside Kherson.|
|<font color=#FF3399>[5]</font> Russian shelling of Kherson city and areas along the Dnipro has been sustained since Ukrainian forces liberated the west bank in November.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-23-22/h_32bb7d91d1f5aedcd906d3df8fb299be" target="_blank">Source</a>| About half the strikes hit the city of Kherson, including private and apartment buildings, he said. One person was killed in action, while two residents of Kherson region sustained injuries. Russian shelling of Kherson city and areas along the Dnipro has been sustained since Ukrainian forces liberated the west bank in November. Serhiy Khlan, a member of Kherson regional council, said the number of attacks was increasing.|
