# What safety measures were in place when the Brovary helicopter crashed?

## Summary
On January 18, a helicopter carrying Ukrainian Interior Minister Denys Monastyrsky, First Deputy Interior Minister Yevhen Yenin and State Secretary Yury Lubkovich crashed in the town of Brovary, Ukraine. All 10 people onboard, including the three officials, were killed and 25 people including 11 children were injured and hospitalized. Possible causes of the crash are being investigated by the Security Service, including violation of flight security rules, technical malfunction of the helicopter, and intentional actions to destroy the vehicle. Reportedly, the pilot had chosen to fly over Brovary for fear of a missile strike from the Belarus direction and the radio-electronic suppression used by the Ukrainian armed forces had disrupted the work of navigation tools. Furthermore, the pilot was flying too low, in poor visibility conditions, while the red lights on high-rise rooftops were out, due to power shortages <font color=#FF3399>[1,2,3]</font>. Experts suggest that the helicopters in Ukraine are technically better than their Soviet counterparts, however, there is still the possibility of a technical malfunction <font color=#FF3399>[4]</font>. Sadly, it is believed that one child was killed in the crash, although no immediate account of the cause has been given <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> At the same time, the radio-electronic suppression used by the Ukrainian armed forces disrupted the work of navigation tools.<a href="https://meduza.io/en/news/2023/01/24/ukrainian-media-brovary-helicopter-crash-was-due-to-fog-and-disrupted-navigation" target="_blank">Source</a>| The accident took the lives of several Ukrainian officials: Interior Minister Denys Monastyrsky, First Deputy Interior Minister Yevhen Yenin, and State Secretary Yury Lubkovich. One of the journalists sources explained that the helicopter pilot chose to fly over Brovary for fear of a missile strike from the Belarus direction. At the same time, the radio-electronic suppression used by the Ukrainian armed forces disrupted the work of navigation tools. Sources have also mentioned that the pilot was flying too low, in poor visibility conditions, while the red lights on high-rise rooftops were out, due to power shortages.|
|<font color=#FF3399>[2]</font> The Security Service investigation into the incident is considering several versions of what had caused the crash, including violation of flight security rules, technical malfunction of the helicopter, and intentional actions to destroy the vehicle.<a href="https://news.yahoo.com/kindergarten-morning-kyiv-suburb-turned-194021274.html" target="_blank">Source</a>| All 10 people onboard, including Interior Minister Denys Monastyrsky and his first deputy Yevhen Yenin, died. The incident also injured 25 people, including 11 children, who were all hospitalized, according to the State Emergency Service. The Security Service investigation into the incident is considering several versions of what had caused the crash, including violation of flight security rules, technical malfunction of the helicopter, and intentional actions to destroy the vehicle. The authorities promised to share first findings in the near future.|
|<font color=#FF3399>[3]</font> According to the sources, the helicopter was flying at a very low altitude in poor visibility conditions, so the pilot failed to spot a tall building in time, and in the evasive maneuver he failed to prevent a collision with a kindergarten.<a href="https://www.plenglish.com/news/2023/01/24/pilot-error-caused-ukrainian-helicopters-crash/" target="_blank">Source</a>| The media outlet assured that the causes of the disaster in which the head of the Ministry of Internal Affairs, Denis Monastirski, died were included in the preliminary report by experts. According to the sources, the helicopter was flying at a very low altitude in poor visibility conditions, so the pilot failed to spot a tall building in time, and in the evasive maneuver he failed to prevent a collision with a kindergarten. The aircraft of the State Emergency Service of Ukraine, which was flying to the Kharkov region and had the leadership of the Ministry of Internal Affairs on board, crashed in the morning of January 18 into a kindergarten in Brovary.|
|<font color=#FF3399>[4]</font> "There are no helicopters in the world that are 100% safe.<a href="https://jam-news.net/why-did-a-helicopter-crash-in-ukraine/" target="_blank">Source</a>| In terms of technical performance they are definitely better than their Soviet counterparts, which Ukraine uses more. "Its like comparing Mercedes and Zhiguli." "There are no helicopters in the world that are 100% safe. We cannot rule out a technical malfunction as a possible cause of the disaster," Tomenchuk says.|
|<font color=#FF3399>[5]</font> The SBU state security service said it was investigating possible causes, including a breach of flight rules, a technical malfunction and the intentional destruction of the helicopter.<a href="https://www.theguardian.com/world/live/2023/jan/18/russia-ukraine-war-live-pressure-mounts-on-germany-to-send-tanks-chancellor-scholz-due-to-speak-in-davos" target="_blank">Source</a>| The most recent update, on Wednesday afternoon, suggested one child had been killed, after previous reports that the number was at least three. Officials gave no immediate account of the cause of the crash. The SBU state security service said it was investigating possible causes, including a breach of flight rules, a technical malfunction and the intentional destruction of the helicopter. Monastyrsky, who was responsible for the police and security inside Ukraine, is the most senior Ukrainian official to die since the war began.|
