# What is the capability of Ukraine's air defense systems in repelling the missile attacks from Russian missiles in Kyiv?

## Summary
Ukraine's air defense systems have demonstrated their capability in repelling the missile attacks from Russian forces in Kyiv. Context 1 reported that Ukrainian air defense forces shot down 37 of "about 40" rockets that entered the city's airspace, with one person injured. Context 2 revealed that a commander, who asked to be identified only by the call sign "Hera" for security reasons, stated that a cruise missile was shot down by a machine gun from the city's territorial defense mobile group. Context 3 mentioned that U.S. President Joe Biden had pledged to deliver one Patriot surface-to-air missile battery system to Ukraine, which is one of the most advanced U.S. air defense systems and is capable of intercepting threats such as aircraft and ballistic missiles. Contexts 4 and 5 reported that numerous missile attacks have been reported across Ukraine, with Russian forces firing 69 missiles causing casualties and blackouts, of which 54 were successfully shot down by Ukrainian air defense units.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> At the site of one attempted strike in Kyiv, military commanders told The Associated Press that the citys territorial defense mobile group had shot down a cruise missile with a machine gun.<a href="https://www.pbs.org/newshour/world/russia-launches-another-major-missile-attack-across-ukraine" target="_blank">Source</a>| Ukrainian air defense forces shot down 37 of "about 40" that entered the citys airspace, and one person was injured, it said. Ukraines air force said Russian forces had fired cruise missiles from the Admiral Makarov frigate in the Black Sea, while Kh-22 cruise missiles were fired from long-range Tu-22M3 bombers over the Sea of Azov, and tactical aircraft fired guided missiles. At the site of one attempted strike in Kyiv, military commanders told The Associated Press that the citys territorial defense mobile group had shot down a cruise missile with a machine gun. It wasnt immediately clear whether other Ukrainian fire may have contributed to downing the rocket.|
|<font color=#FF3399>[2]</font> "Almost impossible to hit a missile with a machine gun, but it was done," said a commander who asked to be identified only by the call sign "Hera" for security reasons.<a href="https://apnews.com/article/russia-ukraine-kyiv-5d3e5ee5e93b6402d5214b3cf094fa1c" target="_blank">Source</a>| At the site of one attempted strike in Kyiv, military commanders told The Associated Press that the citys territorial defense mobile group had shot down a cruise missile with a machine gun. It wasnt immediately clear whether other Ukrainian fire may have contributed to downing the rocket. "Almost impossible to hit a missile with a machine gun, but it was done," said a commander who asked to be identified only by the call sign "Hera" for security reasons. Ukrzaliznytsia, the national railway operator, said power was out in a number of stations in the eastern and central Kharkiv, Kirovohrad, Donetsk and Dnipropetrovsk regions.|
|<font color=#FF3399>[3]</font> The Patriot is one of the most advanced U.S. air defence systems, capable of intercepting threats, such as aircraft and ballistic missiles.<a href="https://www.reuters.com/business/aerospace-defense/russia-says-patriot-missiles-kyiv-wont-help-settle-ukraine-conflict-2022-12-22/" target="_blank">Source</a>| Before addressing a joint meeting of Congress, Zelenskiy held a meeting with U.S. President Joe Biden at the White House, during which Biden pledged to deliver one Patriot surface-to-air missile battery systems. Ukraine had previously requested Patriots, saying that they would help bolster its air defences as Russian missile strikes on critical infrastructure have become more regular. The Patriot is one of the most advanced U.S. air defence systems, capable of intercepting threats, such as aircraft and ballistic missiles. Ukrainian troops will learn how to use it in Germany, and it will be several months before they can deploy it on the battlefield.|
|<font color=#FF3399>[4]</font> Ukrainian air defense units successfully shot down 54 of the missiles.<a href="https://www.politico.eu/article/ukraine-war-belarus-downed-missile-russia-provocation/" target="_blank">Source</a>| "This can lead to catastrophic consequences for everyone," said Anatoly Glaz, a spokesman for the Belarusian foreign ministry, according to Radio Liberty. The missile report came amid a massive Russian assault against Ukraine on Thursday, with 69 missiles fired, causing casualties and blackouts throughout the country. Ukrainian air defense units successfully shot down 54 of the missiles. The Ukrainian defense ministry neither confirmed nor denied Belarusian reports, but said it suspected a "provocation" by Moscow.|
|<font color=#FF3399>[5]</font> They also heard the air defense systems working in the Ukrainian capital.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-16-22/h_69ebf33df3506408b40097537a9303c2" target="_blank">Source</a>| Missile attacks have been reported across Ukraine on Friday, including in Kyiv, Odesa, Poltava, Zhytomyr, Kharkiv and Sumy. CNN teams in Kyiv have reported hearing explosions, as well as seeing and hearing missiles. They also heard the air defense systems working in the Ukrainian capital. Earlier Friday, the deputy head of the Ukrainian Presidential Office urged people to stay in shelters as air raid sirens sounded across the country.|
