# What are the objectives of the Ukrainian military in their push towards Kherson city?

## Summary
The Ukrainian military is advancing towards the city of Kherson in the southern Kherson region, which was illegally annexed by Russia in September. <font color=#FF3399>[1]</font> In an effort to root out partisan resistance, Russian forces have stepped up their scrutiny of civilians in the area, detaining locals and wearing civilian clothing. <font color=#FF3399>[2,3]</font> Ukraine's army has been pursuing a counteroffensive since the start of October and is now making advances toward the city from two directions. <font color=#FF3399>[4,5]</font> In response, Russian Defense Minister Sergey Shoigu has ordered a withdrawal of Russian forces from the west bank of the Dnipro River in Kherson region. <font color=#FF3399>[5]</font>

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> Recapturing it has been the main focus of Ukraines counteroffensive in the south, which has accelerated since the start of October.<a href="https://www.aljazeera.com/news/2022/11/7/ukraine-says-russian-forces-looting-occupying-homes-in-kherson" target="_blank">Source</a>| Moscow says it is sending residents away for safety and denies abusing civilians. Kherson lies in the only pocket of Russian-held territory on the west bank of the Dnieper River that bisects Ukraine. Recapturing it has been the main focus of Ukraines counteroffensive in the south, which has accelerated since the start of October. Ukrainian forces on the nearby front line have told the Reuters news agency in recent days that they expect a bitter fight against Russian troops determined to exact a blood price before being forced out.|
|<font color=#FF3399>[2]</font> Russian forces have stepped up their scrutiny of civilians in occupied areas of Ukraines southern Kherson region, detaining locals to root out partisan resistance, according to the Ukrainian military.<a href="https://edition.cnn.com/europe/live-news/russia-ukraine-war-news-11-07-22/h_4dec8e693a12d1887a4f6ef705e33520" target="_blank">Source</a>| Russian forces have stepped up their scrutiny of civilians in occupied areas of Ukraines southern Kherson region, detaining locals to root out partisan resistance, according to the Ukrainian military. In the occupied city of Kherson, Russian troops are now largely wearing civilian clothing and living in civilian housing as they "strengthen positions inside for conducting street battles," according to the Ukrainian military and a resident of the city with whom CNN exchanged messages.|
|<font color=#FF3399>[3]</font> The Kremlin-installed regional administration in Kherson already has moved tens of thousands of civilians out of the city, citing the threat of increased shelling as Ukraine's army pursues its counteroffensive.<a href="https://abcnews.go.com/International/wireStory/ukraines-president-accuses-russia-energy-terrorism-92655267" target="_blank">Source</a>| Russian forces seized Kherson city soon after invading Ukraine in late February. Russia illegally annexed the Kherson, Donetsk, Luhansk and Zaporizhzhia regions of Ukraine in late September and subsequently declared martial law in the four provinces. The Kremlin-installed regional administration in Kherson already has moved tens of thousands of civilians out of the city, citing the threat of increased shelling as Ukraine's army pursues its counteroffensive. Ukraines southern military spokeswoman, Natalia Humeniuk, told Ukrainian television that some Russian military personnel were disguising themselves as civilians.|
|<font color=#FF3399>[4]</font> And the Ukrainians were making sort of relatively slow advances, capturing some of these villages.<a href="https://www.npr.org/2022/11/12/1136267844/ukrainians-in-kherson-celebrate-the-withdrawal-of-russian-troops" target="_blank">Source</a>| The Ukrainians began this very methodical offensive in the south in the direction of Kherson back in September. And there was lots of fighting in outlying villages. And the Ukrainians were making sort of relatively slow advances, capturing some of these villages. But they were still dozens of miles away from Kherson.|
|<font color=#FF3399>[5]</font> His order comes as Ukrainian forces make advances toward the city of Kherson from two directions.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-09-22/h_1a8a2db31049a52c8097c6cc94f5f4a6" target="_blank">Source</a>| Russian Defense Minister Sergey Shoigu has ordered a withdrawal of Russian forces from the west bank of the Dnipro River in Kherson region, according to Russian state media. His order comes as Ukrainian forces make advances toward the city of Kherson from two directions. The Russian withdrawal would be the most significant military development since Ukrainian forces swept through the northern Kharkiv region in September.|
