# What was the extent of the damage caused by the missile in Dnipro?

## Summary
A Russian missile strike in the city of Dnipro on Saturday killed nine people, including a 15-year-old girl <font color=#FF3399>[2]</font>, and injured almost 60, including 14 children <font color=#FF3399>[4,5]</font>. The strike destroyed a section of a nine-story apartment building <font color=#FF3399>[2,3]</font>, and damaged infrastructure in other regions <font color=#FF3399>[2]</font>. Firefighters battled a blaze around some cars <font color=#FF3399>[3]</font>, and the exterior of the rest of the building was badly damaged <font color=#FF3399>[3]</font>. Search and rescue operations at the site continued into Saturday night <font color=#FF3399>[4]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> A regional Ukrainian leader said five people were killed by a Russian missile that struck a nine-story apartment building in the central Ukrainian city of Dnipro.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-1-14-23/h_c4f7d05271e6ece82df46a6a89eb5883" target="_blank">Source</a>| A regional Ukrainian leader said five people were killed by a Russian missile that struck a nine-story apartment building in the central Ukrainian city of Dnipro. At least 27 people were injured, including six children.|
|<font color=#FF3399>[2]</font> A Russian missile strike there destroyed a section of a nine-story apartment building, regional Governor Valentyn Reznichenko said.<a href="https://www.eurasiareview.com/15012023-russia-damages-critical-infrastructure-across-ukraine-in-massive-attack/" target="_blank">Source</a>| Ukrainian President Volodymyr Zelenskyy said in his nightly video address. At least nine people were killed and 64 were wounded, among them children, in the southeastern city of Dnipro. A Russian missile strike there destroyed a section of a nine-story apartment building, regional Governor Valentyn Reznichenko said. Infrastructure was also damaged in the Lviv, Ivano-Frankivsk, and Odesa regions, as well as in Kharkiv and Kyiv.|
|<font color=#FF3399>[3]</font> The exterior of the rest of the building was badly damaged.<a href="https://www.reuters.com/world/europe/russian-missile-attack-hits-infrastructure-kyiv-officials-2023-01-14/" target="_blank">Source</a>| In Dnipro, pictures showed firefighters putting out a blaze around the carcasses of some cars. A broad chunk of the apartment block was missing. The exterior of the rest of the building was badly damaged. Wounded people were carried away on stretchers.|
|<font color=#FF3399>[4]</font> He said 37 people were rescued from the building, including 6 children, and 64 people were injured, including 14 children.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-1-14-23/h_b3eae5063b0210504f64f3598147be23" target="_blank">Source</a>| Nine people, including one teenager, were killed when a Russian missile hit an apartment block in the city of Dnipro Saturday, according to the deputy head of the Ukrainian president's office. The teenager killed was a 15-year old girl, Kyrylo Tymoshenko said in an update on Telegram. He said 37 people were rescued from the building, including 6 children, and 64 people were injured, including 14 children. Search and rescue operations at the site continued into Saturday night.|
|<font color=#FF3399>[5]</font> The number of people injured in a deadly Russian missile strike that hit an apartment block in the central Ukrainian city of Dnipro on Saturday has risen to almost 60, according to an official.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-1-14-23/h_dddc9ec5cc59d2499dfe40be6948a114" target="_blank">Source</a>| The number of people injured in a deadly Russian missile strike that hit an apartment block in the central Ukrainian city of Dnipro on Saturday has risen to almost 60, according to an official. Valentyn Reznichenko, the head of the Dnipropetrovsk regional military administration, said 12 children are among the injured.|
