# How have the people of Melitopol been affected by the Ukrainian missile attack?

## Summary
The people of Melitopol have been greatly affected by the Ukrainian missile attack <font color=#FF3399>[1]</font>. The attack, which occurred on Saturday evening, was reported by both Russian and Ukrainian sources <font color=#FF3399>[2]</font>. According to the exiled mayor of Melitopol, Ivan Fedorov, around 200 occupiers were killed and 300 were wounded in the attack <font color=#FF3399>[3]</font>. In addition, 10 people were wounded according to pro-Moscow authorities <font color=#FF3399>[4]</font>. Local residents reported that over 200 Russians were killed in the attack <font color=#FF3399>[5]</font>. The injured were taken to Crimea for medical treatment, due to local hospitals being at full capacity <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> The Russian-occupied city of Melitopol in southern Ukraine saw heavy shelling at the weekend, according to both Russian and Ukrainian sources, but there are conflicting reports on the number of casualties.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-12-22/h_759eb6dea28a0d0ec33d2659d745ecea" target="_blank">Source</a>| The Russian-occupied city of Melitopol in southern Ukraine saw heavy shelling at the weekend, according to both Russian and Ukrainian sources, but there are conflicting reports on the number of casualties. Following an "evening of strikes on Russo-fascist bases, 200 occupiers were roasted [killed]" and 300 more wounded, wrote Ivan Federov, the exiled mayor of Melitopol, on Telegram on Saturday.|
|<font color=#FF3399>[2]</font> Melitopol's Moscow-installed administrators said four missiles struck the city, killing two people and wounding 10.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-11-22/h_18b347fc4f4476aba1d5c702297c4603" target="_blank">Source</a>| Ukraine launched a missile attack on the Russian-occupied city of Melitopol Saturday, according to officials on both sides. Melitopol's Moscow-installed administrators said four missiles struck the city, killing two people and wounding 10. Yevgeny Balitsky, Russia's acting governor of Zaporizhzhia, said two more missiles were shot down.|
|<font color=#FF3399>[3]</font> Fedorov also gave an update on the number of injured and killed as a result of the missile attacks, "there are dozens of Russo-fascists killed, and there are wounded, who were taken to hospitals and to Crimea: about 200 Russo-fascists went to hospitals."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-12-22/h_cf732fa350de33c620881c5cb2d8311b" target="_blank">Source</a>| Ivan Fedorov, the exiled mayor of Melitopol, said in a Ukrainian TV interview that Russian troops in the city are "redeploying" and are now "panicking" given Ukrainian strikes on the city over the weekend. Without providing any evidence he said, "they are busy moving their military groups to other places to try to hide them." Fedorov also gave an update on the number of injured and killed as a result of the missile attacks, "there are dozens of Russo-fascists killed, and there are wounded, who were taken to hospitals and to Crimea: about 200 Russo-fascists went to hospitals." The Russian-occupied city in southernUkrainesaw heavy shelling during the weekend, according to reports from both Russian and Ukrainian sources but there were conflicting reports on injured and dead.|
|<font color=#FF3399>[4]</font> The pro-Moscow authorities said a missile attack killed two people and wounded 10, while the exiled mayor said scores of "invaders" were killed.<a href="https://www.reuters.com/world/europe/ukraine-attacks-occupied-melitopol-russian-side-says-two-killed-2022-12-11/" target="_blank">Source</a>| KYIV, Dec 11 (Reuters) - Ukraine attacked occupied Melitopol in the country's southeast on Saturday evening, the Russian-installed and exiled Ukrainian authorities of the strategically located city said. The pro-Moscow authorities said a missile attack killed two people and wounded 10, while the exiled mayor said scores of "invaders" were killed. Reuters could not independently verify the reports of the attacks or deaths.|
|<font color=#FF3399>[5]</font> The injured were reportedly taken to Crimea for medical treatment, due to local hospitals being at full capacity.<a href="https://www.express.co.uk/news/world/1708101/russia-ukraine-war-barracks-melitopol-zaporizhia-oblast-annexed-regions-crimea" target="_blank">Source</a>| Local residents said around 200 Russians were wiped out in the attack. Some sources claim over 300 were killed. The injured were reportedly taken to Crimea for medical treatment, due to local hospitals being at full capacity. Ivan Fedorov, Melitopol's mayor, said on his Telegramm channel: "According to preliminary estimates, about 200 occupiers were roasted.|
