# How has the ongoing Russia-Ukraine crisis impacted the operations of the Zaporizhzhia power plant?

## Summary
The Zaporizhzhia Nuclear Power Plant in Ukraine, which has been under Russian occupation since the Feb. 24 invasion, has experienced periodic fighting and lost access to external electricity multiple times since then, prompting concern from the International Atomic Energy Agency <font color=#FF3399>[1]</font>. The plant is relying on emergency diesel generators to maintain nuclear safety and security <font color=#FF3399>[2]</font>, and the IAEA sent a team to the site to provide onsite support <font color=#FF3399>[3]</font>. Additionally, the other four Ukrainian nuclear plants - Rivne, Khmelnytskyi, South Ukraine, and Chornobyl - were forced to rely on emergency diesel generators after Russian strikes on Ukraine's energy infrastructure <font color=#FF3399>[4]</font>. Furthermore, Rosenegeatom, Russia's state nuclear energy corporation, has taken measures to ensure the power supply reserve for the nuclear safety of the Zaporizhzhia NPP <font color=#FF3399>[5]</font>. The shelling near the complex has raised fears of a nuclear accident due to the interruption of the power supply to the plant <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> The plant shut down the last of its six reactors in September but requires a steady source of electricity to maintain safeguards.<a href="https://www.businessinsider.com/russia-tortured-workers-at-zaporizhzhia-nuclear-power-plant-2022-11" target="_blank">Source</a>| Russian forces captured the Zaporizhzhia Nuclear Power Plant soon after the Feb. 24 invasion of Ukraine. It has been the site of periodic fighting that has alarmed observers, including the International Atomic Energy Agency. The plant shut down the last of its six reactors in September but requires a steady source of electricity to maintain safeguards. The plant's former director, Ihor Murashov, ran the facility for seven months under Russian occupation.|
|<font color=#FF3399>[2]</font> Ukraine's Zaporizhzhia Nuclear Power Plant lost access to external electricity again on Wednesday and is relying on emergency diesel generators, theInternational Atomic Energy Agency said, warning of the "increasingly precarious and challenging nuclear safety and security situation" at the plant.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-23-22/h_0b09fd2be6b4cc2fc585c8c4e494dade" target="_blank">Source</a>| Ukraine's Zaporizhzhia Nuclear Power Plant lost access to external electricity again on Wednesday and is relying on emergency diesel generators, theInternational Atomic Energy Agency said, warning of the "increasingly precarious and challenging nuclear safety and security situation" at the plant. The team of IAEA experts present at the power plant said it lost off-site power at 3:30 p.m. local time Wednesday when it was fully disconnected from the grid, "following reports of widespread military action targeting Ukraine's energy infrastructure," IAEA said in a statement.|
|<font color=#FF3399>[3]</font> The move sparked concerns over the fate of the Ukrainian technicians who have operated the plant since its occupation by Russian forces.<a href="https://www.cnn.com/2022/11/20/europe/zaporizhzhia-iaea-warning-intl/index.html" target="_blank">Source</a>| Intense shelling near the complex this summer sparked concerns of a nuclear accident, prompting the IAEA to send a team there. Russian President Vladimir Putin signed a decree in October federalizing the plant which is located about 120 kilometers (75 miles) from the city and sits in Russian occupied territory along the Dnipro River. The move sparked concerns over the fate of the Ukrainian technicians who have operated the plant since its occupation by Russian forces. The blasts on Saturday and Sunday ended what the IAEA said was "a relative period of calm."|
|<font color=#FF3399>[4]</font> Following Russian strikes on Ukraine's energy infrastructure, Ukraine's operational nuclear power plants of Zaporizhzhia, Rivne, South Ukraine, and Khmelnytskyi were disconnected from the grid and "forced to rely on emergency diesel generators for the electricity they needed to ensure their continued safety and security," Grossi said.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-11-25-22/h_d4fb4f08989622e2e48d006db77be90b" target="_blank">Source</a>| The four additional plants are Rivne,Khmelnytskyi, South Ukraine, and Chornobyl. Since September, IAEA experts have been providing onsite support to Zaporizhzhia, Europe's largest nuclear power plant, which is occupied by Russian forces. Following Russian strikes on Ukraine's energy infrastructure, Ukraine's operational nuclear power plants of Zaporizhzhia, Rivne, South Ukraine, and Khmelnytskyi were disconnected from the grid and "forced to rely on emergency diesel generators for the electricity they needed to ensure their continued safety and security," Grossi said. "We must do everything to prevent a nuclear accident at any of these nuclear facilities, which would only add to the terrible suffering we are already witnessing in Ukraine.|
|<font color=#FF3399>[5]</font> The plant and the area around it, including the nearby city of Enerhodar, have endured persistent shelling that has raised fears of a nuclear accident through the interruption of the power supply to the plant.<a href="https://edition.cnn.com/europe/live-news/russia-ukraine-war-news-11-28-22/h_b60c080be8b04526e0bd24727aac476a" target="_blank">Source</a>| A source at Rosenegeatom is quoted as saying that the company took into account "the great importance of the power supply reserve for the nuclear safety of the Zaporizhzhia NPP, especially in winter." The International Atomic Energy Agency has not released any information supporting Kotins statement and CNN has reached out to the UN nuclear watchdog for comment. The plant and the area around it, including the nearby city of Enerhodar, have endured persistent shelling that has raised fears of a nuclear accident through the interruption of the power supply to the plant. Russia and Ukraine continue to blame each other for the shelling.|
