# What are the legal implications of Russia’s occupation of the Zaporizhzhia nuclear power plant?

## Summary
Russia's occupation of the Zaporizhzhia Nuclear Power Plant <font color=#FF3399>[1]</font> has led to the declaration of the station as property of Russia <font color=#FF3399>[2]</font> and the creation of a state corporation to manage it <font color=#FF3399>[5]</font>. In response, the International Atomic Energy Agency (IAEA) is advocating the creation of a safety zone around the NPP <font color=#FF3399>[4]</font> and engaging in talks with both Ukraine and Russia <font color=#FF3399>[5]</font>. This has raised questions regarding the physical and nuclear safety of the plant <font color=#FF3399>[2]</font>, as well as the potential risks and treatments if nuclear power plant radioactivity is released <font color=#FF3399>[3]</font>. Despite the IAEA's efforts, the Kremlin appears to be planning to transfer control over the NPP either to Kyiv or to the International Atomic Energy Agency <font color=#FF3399>[5]</font>.

## Claims
| Claim Sentence | Context |
|---|---|
|<font color=#FF3399>[1]</font> The logic of illegitimate actions led to the declaration of the station as property of Russia.<a href="https://www.neimagazine.com/features/featurezaporizhzhia-chronicle-of-a-tragedy-10418377/" target="_blank">Source</a>| After the pseudo-referendum, Russia announced the annexation of the occupied territories. The station ended up not only in the occupied but in annexed territory. The logic of illegitimate actions led to the declaration of the station as property of Russia. Rosatom immediately created Zaporizhzhia nuclear plant enterprise and appointed a director the former chief engineer of the Russian Balakovo plant.|
|<font color=#FF3399>[2]</font> Putin also signed a decree federalizing the territory's nuclear plant, which has been occupied by Russian troops for months.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-08-22/h_b6b0b29731bbfd6fee7bf6e946461a90" target="_blank">Source</a>| We presume that only we are able to ensure the physical and nuclear safety of ZNPP." Some background: Zaporizhzhia is one of the four Ukrainian regions annexed by Russian President Vladimir Putin in defiance of international law. Putin also signed a decree federalizing the territory's nuclear plant, which has been occupied by Russian troops for months. Ukraine has said plant employees were forced to obtain Russian passports and sign employment contracts with Russia's state nuclear energy agency.|
|<font color=#FF3399>[3]</font> The Russian Foreign Ministry appears to have dealt a blow to proposals by the International Atomic Energy Agency (IAEA) to create a demilitarized and protected zone around the Zaporizhzhia nuclear power plant.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-12-05-22/h_ecbcd4bbb91d9f945609160725819964" target="_blank">Source</a>| The Russian Foreign Ministry appears to have dealt a blow to proposals by the International Atomic Energy Agency (IAEA) to create a demilitarized and protected zone around the Zaporizhzhia nuclear power plant. Foreign Ministry spokesperson Maria Zakharova responded to a question from a Russian news agency about the status of the plant, which has been occupied by Russian forces since early March.|
|<font color=#FF3399>[4]</font> Zaporizhzhia is Europe's largest nuclear power station and has been under Russian control since shortly after the invasion.<a href="https://www.usatoday.com/story/news/health/2022/12/08/nuclear-disaster-russian-war-explained/8092631001/" target="_blank">Source</a>| What are the risks and treatment if nuclear power plant radioactivity is released? A leak from Zaporizhzhia nuclear power plant is among the highest risk, experts told USA TODAY, because Russia has deliberately targeted the area. Zaporizhzhia is Europe's largest nuclear power station and has been under Russian control since shortly after the invasion. The U.N. International Atomic Energy Agency is trying to establish a safety zone around the plant because while nuclear power plants are built to withstand many natural disasters, few are designed to survive direct military attacks, said Edwin Lyman, a nuclear expert with the Union of Concerned Scientists.|
|<font color=#FF3399>[5]</font> On October 5, 2022, Vladimir Putin signed a special decree about transferring the power plant to Russia and setting up a state corporation to manage it.<a href="https://meduza.io/en/feature/2022/12/03/packing-their-bags" target="_blank">Source</a>| The Kremlin now appears to be planning to transfer control over the NPP either to Kyiv or to the International Atomic Energy Agency (IAEA). In the past, Moscow has denied any possibility of leaving the Zaporizhzhia NPP. On October 5, 2022, Vladimir Putin signed a special decree about transferring the power plant to Russia and setting up a state corporation to manage it. The IAEA continues to advocate the creation of a safety zone around the NPP, engaging in talks with both Ukraine and Russia.|
