# What are the implications of Russia suspending its participation in the Black Sea grain deal?

## Summary
The implications of Russia suspending its participation in the Black Sea grain deal are as follows:

-The move could lead to higher global food prices, as Ukraine is a major exporter of wheat and corn.

-The deal was brokered by the United Nations in order to alleviate global food shortages, and its suspension could jeopardize relief efforts.

-Ukraine's president has emphasized the importance of the deal, and its suspension could have a significant impact on the country's economy.

## Claims
| Claim Sentence | Context |
|---|---|
|Russia announced Saturday that it will move to suspend its implementation of a U.N.-brokered grain deal that has seen more than 9 million tons of grain exported from Ukraine during the war and has brought down soaring global food prices.<a href="https://www.fox9.com/news/russia-suspending-ukraine-grain-export-deal" target="_blank">Source</a>| Russia announced Saturday that it will move to suspend its implementation of a U.N.-brokered grain deal that has seen more than 9 million tons of grain exported from Ukraine during the war and has brought down soaring global food prices. The Russian Defense Ministry cited an alleged Ukrainian drone attack against Russias Black Sea Fleet ships moored off the coast of occupied Crimea, which Russia says took place early Saturday, as the reason for the move.|
|Russia has suspended participation in a UN-brokered deal to export agricultural produce from Ukrainian ports following attacks on ships in Crimea, TASS quoted the defence ministry as saying on Saturday.<a href="https://uk.sports.yahoo.com/news/live-russia-says-us-reduces-084809570.html" target="_blank">Source</a>| Russia has suspended participation in a UN-brokered deal to export agricultural produce from Ukrainian ports following attacks on ships in Crimea, TASS quoted the defence ministry as saying on Saturday. Follow FRANCE 24's live blog for all the latest developments.|
|She touted the "tremendous success" of the deal so far, crediting it with lowering global food prices and providing relief to those "most vulnerable to severe hunger."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-30-22/h_7a212ad0102564430de7de246a316266" target="_blank">Source</a>| "Russia's comments about suspending its participation in the Black Sea Grain Initiative are regrettable. This life-saving agreement between Russia,Ukraine, and Turkey, brokered in July by the United Nations, has allowed the export of more than nine million metric tons of grain and other food products to populations around the world in the midst of a devastating global food crisis," USAID Administrator Samantha Power wrote in a statement Sunday. She touted the "tremendous success" of the deal so far, crediting it with lowering global food prices and providing relief to those "most vulnerable to severe hunger." Remember: Moscow announced it was leaving the grain deal after blaming Ukraine for adrone attackon Crimea Saturday.|
|Russia has suspended participation in the UN-brokered Ukraine grain deal following drone attacks on its ships in Crimea.<a href="https://www.news18.com/videos/ivideos/russia-suspends-ukraine-grain-deal-top-wagner-officer-killed-in-combat-putin-ends-mobilisation-6268975.html" target="_blank">Source</a>| Russia has suspended participation in the UN-brokered Ukraine grain deal following drone attacks on its ships in Crimea. Moscow warned that the deployment of US nuclear bombs in Europe would lower the "nuclear threshold".|
|TheBlack Sea Grain Initiative brokered in July by the UN and Turkey ended months of the blockade, allowing grain ships to navigate a safe corridor through the Black Sea, helping alleviate global food shortages.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-20-22/h_a745a8d56b576bafa7cef6099dece796" target="_blank">Source</a>| Before the war, wheat supplies from Russia and Ukraine accounted for almost 30% of global trade, and Ukraine is the world's fourth-largest exporter of corn and the fifth-largest exporter of wheat, according to the US State Department. However, Moscow's blockade of Black Sea ports earlier this year stalled millions of tons of grain exports from Ukraine. TheBlack Sea Grain Initiative brokered in July by the UN and Turkey ended months of the blockade, allowing grain ships to navigate a safe corridor through the Black Sea, helping alleviate global food shortages. Earlier this week, Ukrainian President Volodymyr Zelensky emphasized the importance of the deal, adding that since July Ukraine has exported 8 million tons of food by sea.|
