# What has been the effect of the Russia-Ukraine crisis on relations between Russia and the West?

## Summary
The Russia-Ukraine crisis has led to a deterioration in relations between Russia and the West. The West has imposed sanctions on Russia and does not recognize the results of the "sham referendums" held in Russian-occupied parts of Ukraine. Russia, in turn, has lashed out against the West, accusing it of trying to "divide" and "weaken" the country.

## Claims
| Claim Sentence | Context |
|---|---|
|In response, the U.S., the European Union and the United Nations all rejected the Crimea referendum as illegal and sanctioned Russia.<a href="https://www.npr.org/2022/09/27/1125322026/russia-ukraine-referendums" target="_blank">Source</a>| The official outcome of that referendum, which was also denounced as a farce by international observers, was that more than 95% of voters wanted to join the Russian Federation. Following the vote, Moscow quickly annexed Crimea. In response, the U.S., the European Union and the United Nations all rejected the Crimea referendum as illegal and sanctioned Russia. Western leaders say the elections in Russian-occupied parts of Ukraine are also illegal under international law and that they will not accept the outcome.|
|Sept. 24: Russian Foreign Minister Sergey Lavrov told the U.N. General Assembly that the West is out to "destroy and fracture Russia."<a href="https://www.npr.org/2022/09/26/1124114574/ukraine-war-updates-regions-vote-on-joining-russia-putin-orders-a-draft-sept-26" target="_blank">Source</a>| Sept. 22: Ukraine and Russia announced a prisoner swap involving the release of more than 200 Ukrainian and foreign citizens from Russia including two U.S. military veterans and more than 50 prisoners from Ukraine, including Ukrainian pro-Russian opposition leader Viktor Medvedchuk. Sept. 23: In what the U.S. and others called "sham referendums," voting began in four Russian-occupied regions of Ukraine on whether to join Russia. Sept. 24: Russian Foreign Minister Sergey Lavrov told the U.N. General Assembly that the West is out to "destroy and fracture Russia." On Thursday, he appeared at a Security Council meeting on Ukraine to deliver his own remarks and then left.|
|The war has brought an energy crunch for much of Western Europe, with German officials seeing the disruption of Russian supplies as a Kremlin power play to pressure Europe over its support for Ukraine.<a href="https://www.pbs.org/newshour/world/pro-moscow-officials-say-one-occupied-area-of-ukraine-has-voted-to-join-russia" target="_blank">Source</a>| The wars human toll was also reflected in a U.N. human rights monitoring missions first comprehensive look at violations and abuses Russia and Ukraine committed between Feb. 1 and July 31, the first five months of Russias invasion. Matilda Bogner, the missions chief, said Ukrainian prisoners of war appeared to have faced "systematic" mistreatment, "not only upon their capture, but also following their transfer to places of internment" in Russian-controlled areas of Ukraine and Russia itself. The war has brought an energy crunch for much of Western Europe, with German officials seeing the disruption of Russian supplies as a Kremlin power play to pressure Europe over its support for Ukraine. The danger to energy supplies grew when seismologists reported Tuesday that explosions rattled the Baltic Sea before unusual leaks were discovered on two underwater natural gas pipelines running from Russia to Germany.|
|The plans, which are being held under military occupation and effectively carried out at gunpoint, have been strongly condemned by both the government of Ukraine and its allies in the West.<a href="https://www.cnn.com/2022/09/23/europe/occupied-ukraine-referendum-russia-intl-hnk/index.html" target="_blank">Source</a>| The votes, which are expected to take place over five days, were called by pro-Russian officials in the self-declared republics of Donetsk and Luhansk, and in Russian-held parts of Kherson and Zaporizhzhia in the south, with questions on the ballot varying slightly depending on the region. Together the four regions make up around 18% of Ukraines territory. The plans, which are being held under military occupation and effectively carried out at gunpoint, have been strongly condemned by both the government of Ukraine and its allies in the West. The European Union has said it wont recognize the results and has indicated it is preparing a new package of sanctions against Russia.|
|With world opinion pushing Moscow deeper into isolation over the war, Russia lashed out against the West.<a href="https://apnews.com/article/russia-ukraine-putin-donetsk-government-and-politics-4ad18c2400a1cc04276f8ef5902a3e85" target="_blank">Source</a>| "Each body has its own story," Synyehubov said. Experts commissioned by the U.N. Human Rights Council also presented evidence of potential war crimes, including beatings, electric shocks and forced nudity in Russian detention facilities, and expressed grave concerns about extrajudicial killings the team was working to document in Kharkiv and the regions of Kyiv, Chernihiv and Sumy. With world opinion pushing Moscow deeper into isolation over the war, Russia lashed out against the West. Its U.S. ambassador, Anataly Antonov, said at a Moscow conference Friday about the 1962 Cuban missile crisis that Washington is trying to bring Russia "to its knees" and divide it into "several fiefdoms" while stripping it of its nuclear weapons and its permanent seat at the U.N. Security Council.|
