# What are Macron's goals in providing military aid to Ukraine?

## Summary
Macron's goals in providing military aid to Ukraine are to help the country defend against missile and drone attacks, and to help it resist Russian assaults. He has pledged to send air defense systems, radars, missiles and weapons to Ukraine in the coming weeks, and has also announced a $98 million fund to allow Ukraine to directly purchase military aid from French manufacturers.

## Claims
| Claim Sentence | Context |
|---|---|
|"We will continue to support Ukraine from the financial, humanitarian, and military perspectives," the French president said.<a href="https://newseu.cgtn.com/news/2022-10-08/Macron-ups-Ukraine-military-aid-after-criticism-over-low-spending-1dWJsVKfsJy/index.html" target="_blank">Source</a>| French President Emmanuel Macron has announced that he will step up arms supplies to Ukraine in the wake of criticism that Paris wasn't doing enough to help the war effort since Russia's launched its attack on its neighbor eight months ago. "We will continue to support Ukraine from the financial, humanitarian, and military perspectives," the French president said. That pledge came on Thursday from Prague, as Macron attended a summit made up of 44 state leaders for the inaugural meeting of the European Political Community.|
|France will send air defense systems, radars, missiles and weapons toUkraine in the coming weeks to defend against missile and drone attacks, French President Emmanuel Macron said in an interview with broadcaster France 2 on Wednesday.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-12-22/h_03aa4a3ef36be5da53c968e61c91faec" target="_blank">Source</a>| France will send air defense systems, radars, missiles and weapons toUkraine in the coming weeks to defend against missile and drone attacks, French President Emmanuel Macron said in an interview with broadcaster France 2 on Wednesday. Macron, whose comments come after Ukraine experienced a wave of Russian missile attacks, said the French supplies would specifically help defeat these kinds of threats.|
|Speaking during a news conference after an informal European Union leaders' summit in Prague, French President Emmanuel Macron said the fund would "enable Ukraine to buy directly from our manufacturers the equipment it needs most to support its war effort and its resistance to Russian assaults."<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-07-22/h_6c4efd552764c414e9fd7a96cafd3764" target="_blank">Source</a>| France has announced a $98 million (100 million euro) fund allowing Ukraine to directly purchase military aid from French manufacturers. Speaking during a news conference after an informal European Union leaders' summit in Prague, French President Emmanuel Macron said the fund would "enable Ukraine to buy directly from our manufacturers the equipment it needs most to support its war effort and its resistance to Russian assaults." This follows remarks Macron made during a news conference on Thursday evening, which saw him pledge to send further French CAESAR howitzers to Ukraine.|
|Macron said France would be ready to increase support in terms of military equipment to Ukraine during the call.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-10-22/h_87907d3936d3ae2391da1439ac533653" target="_blank">Source</a>| Ukrainian President Volodymyr Zelensky says he had an urgent call with French President Emmanuel Macron on Monday, amid waves of Russian missile attacks across the country. "We discussed the strengthening of our air defense, the need for a tough European and international reaction, as well as increased pressure on the Russian Federation," Zelensky tweeted Monday. Macron said France would be ready to increase support in terms of military equipment to Ukraine during the call. The French president told Zelensky of his "extreme concerns" over the bombardment of Kyiv and other Ukrainian cities, which lead to the damage of critical infrastructure civilian casualties.|
|The European Union will send more military equipment to Ukraine, including long-range weapons from France, according to French President Emmanuel Macron.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-06-22/h_c3afb339e3faeb9d6267967dca952c7e" target="_blank">Source</a>| The European Union will send more military equipment to Ukraine, including long-range weapons from France, according to French President Emmanuel Macron. The EU is continuing to "advance the demands" it has received from Ukraine, including for French-madeCAESARself-propelledhowitzers, Macron said at a news conference in Prague on Thursday.|
