# What are the implications of a dirty bomb being used in Ukraine?

## Summary
A dirty bomb is a weapon that combines conventional explosives like dynamite and radioactive material like uranium. It is often referred to as a weapon for terrorists, not countries, as it is designed to spread fear and panic more than eliminate any military target. There is no record of such a weapon ever being used successfully. On Monday, the UN's nuclear watchdog has said it will send safeguard inspectors to visit two nuclear locations in Ukraine at the request of authorities in Kyiv.

Ukraine denies any plans to develop a dirty bomb. However, Russia is accusing Ukraine ofplanning to use a so-called dirty bomb, an allegation dismissed by Kyiv and its Western allies as a false-flag operation that Moscow could use as a pretext to escalate the Kremlin'swar against its neighbor. A dirty bomb uses conventional explosives to detonate a cache of radioactive material with the aim of spreading radioactive contamination. Its a cruder and less deadly device than a nuclear bomb, although it has the potential for significant civilian harm and widespread economic damage if detonated in an urban area.

## Claims
| Claim Sentence | Context |
|---|---|
|There is no record of such a weapon ever being used successfully.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-25-22/h_ca47defba48eeff2aeb78f5ed6567642" target="_blank">Source</a>| A dirty bomb is a weapon that combines conventional explosives like dynamite and radioactive material like uranium. It is often referred to as a weapon for terrorists, not countries, as it is designed to spread fear and panic more than eliminate any military target. There is no record of such a weapon ever being used successfully. On Monday, the UN's nuclear watchdog has said it will send safeguard inspectors to visit two nuclear locations in Ukraine at the request of authorities in Kyiv.|
|Its a cruder and less deadly device than a nuclear bomb, although it has the potential for significant civilian harm and widespread economic damage if detonated in an urban area.<a href="https://www.washingtonpost.com/national-security/2022/10/26/russia-ukraine-nuclear-dirty-bomb-putin-grossi/" target="_blank">Source</a>| "Theyre going to go there and check the material balance because we know every gram of nuclear material in Ukraine," Grossi said of his inspection teams. A dirty bomb uses conventional explosives to detonate a cache of radioactive material with the aim of spreading radioactive contamination. Its a cruder and less deadly device than a nuclear bomb, although it has the potential for significant civilian harm and widespread economic damage if detonated in an urban area. Ukraine denies any plans to develop a dirty bomb.|
|It is often referred to as a weapon for terrorists, not countries, as it is designed to spread fear and panic more than eliminate any military target.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-25-22/h_047d103a7f851ebb32f47b45678d00f5" target="_blank">Source</a>| Russia is accusing Ukraine ofplanning to use a so-called dirty bomb, an allegation dismissed by Kyiv and its Western allies as a false-flag operation that Moscow could use as a pretext to escalate the Kremlin'swar against its neighbor. A dirty bomb is a weapon that combines conventional explosives like dynamite and radioactive material like uranium. It is often referred to as a weapon for terrorists, not countries, as it is designed to spread fear and panic more than eliminate any military target. Ukrainian officials have repeatedly denied Moscow's accusations and Kyiv's foreign minister has invited UN inspectors to visit Ukraine to show they "have nothing to hide."|
|Dirty bombs combine conventional explosives with radioactive material and are designed to spread radioactivity that can cause death and contamination.<a href="https://www.voanews.com/a/iaea-to-inspect-2-ukrainian-sites-russia-alleges-are-producing-dirty-bombs-/6809078.html" target="_blank">Source</a>| For several days, Russian officials have alleged without evidence that Ukraine is planning to develop and use a so-called dirty bomb in its conflict with Russia. Ukraine and its Western allies have strongly denied the allegations and suspect they are being made as a pretext for some type of escalation in the war in Ukraine, possibly a "false-flag" operation by Moscow. Dirty bombs combine conventional explosives with radioactive material and are designed to spread radioactivity that can cause death and contamination. "In this case, there has been a very clear indication from a very high official of the Russian Federation about work clandestine work, in fact to divert nuclear material," the IAEA chief told reporters after he met privately with the U.N. Security Council.|
|But pulling the plug on a deal regarded as a vital step to ease the global food crisis threatens to extend the conflicts significance deeper beyond Europe.<a href="https://www.bnnbloomberg.ca/russia-halting-involvement-in-ukraine-grain-safe-transit-deal-1.1839070" target="_blank">Source</a>| Eight months after Russia invaded its neighbor, the war is taking an even crueler turn with winter just weeks away. Millions of Ukrainians are without power because of rolling blackouts due to Russias bombing campaign, Iran is supplying armed drones to Putins forces and Russian officials have claimed -- in comments rejected by Kyiv -- that Ukraine is planning a "dirty bomb." But pulling the plug on a deal regarded as a vital step to ease the global food crisis threatens to extend the conflicts significance deeper beyond Europe. Condemnation was swift from Ukraines allies.|
