# What is the status of negotiations around the establishment of a nuclear safety and security zone around the Zaporizhzhia nuclear power plant?

## Summary
The head of the International Atomic Energy Agency, Rafael Grossi, is expected to visit Moscow and Kyiv next week to continue talks on the establishment of a nuclear safety and security zone around the Russian-held Zaporizhzhia nuclear power plant in Ukraine.

## Claims
| Claim Sentence | Context |
|---|---|
|Rafael Mariano Grossi, director general of the International Atomic Energy Agency, is expected to travel to Kyiv and Moscow next week, according to a press statement by the IAEA released Saturday.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-01-22/h_8adeb7592f45f7e27f330db2a6e00124" target="_blank">Source</a>| Rafael Mariano Grossi, director general of the International Atomic Energy Agency, is expected to travel to Kyiv and Moscow next week, according to a press statement by the IAEA released Saturday. The visit is part of ongoing efforts around "implementing a nuclear safety and security zone around the ZNPP (Zaporizhzhia nuclear power plant) as soon as possible," according to the statement.|
|The head of the International Atomic Energy Agency (IAEA) Rafael Grossi will be travelling to Kyiv and Moscow later this week, the UN nuclear watchdog said Tuesday.<a href="https://www.hindustantimes.com/world-news/iaea-chief-to-travel-to-kyiv-and-moscow-later-this-week-amid-war-101664918798595.html" target="_blank">Source</a>| The head of the International Atomic Energy Agency (IAEA) Rafael Grossi will be travelling to Kyiv and Moscow later this week, the UN nuclear watchdog said Tuesday. Grossi will "continue his consultations" on setting up a nuclear safety and protection zone around Ukraine's Russian-held Zaporizhzhia nuclear power plant, the IAEA said in a statement.|
|Following the detention of Ihor Murashov, Director General of Ukraines Zaporizhzhya Nuclear Power Plant (ZNPP), and the deteriorating security situation at the nuclear plant, UN nuclear watchdog chief Rafael Grossi is expected to visit Moscow and Kyiv next week to hold a dialogue.<a href="https://www.republicworld.com/world-news/russia-ukraine-crisis/iaea-chief-expected-to-visit-kyiv-and-moscow-next-week-as-russia-detains-director-general-articleshow.html" target="_blank">Source</a>| Following the detention of Ihor Murashov, Director General of Ukraines Zaporizhzhya Nuclear Power Plant (ZNPP), and the deteriorating security situation at the nuclear plant, UN nuclear watchdog chief Rafael Grossi is expected to visit Moscow and Kyiv next week to hold a dialogue. He is expected to bring up the prospect of the creation of a protection zone around the Russian-held Zaporizhzhia nuclear power plant in Ukraine, the watchdog said in a statement published on Sunday.|
|The month started with Director General Grossi and an IAEA team visiting the Zaporizhzhia facility (and establishing a permanent presence at the facility), with DG Grossi later beginning talks on creating a demilitarized zone around power plant.<a href="https://www.stimson.org/2022/nuclear-security-news-and-member-updates-september-2022/" target="_blank">Source</a>| Bleak? Yes, but not without hope. The month started with Director General Grossi and an IAEA team visiting the Zaporizhzhia facility (and establishing a permanent presence at the facility), with DG Grossi later beginning talks on creating a demilitarized zone around power plant. The General Conference has seen more discussion on issues important to the INSF, such as encouraging and listening to more diverse voices in our field (helped in part by the good efforts of several INSF members).|
|VIENNA, Oct 1 (Reuters) - U.N. nuclear watchdog chief Rafael Grossi is expected to hold talks in Moscow and Kyiv next week on the creation of a protection zone around the Russian-held Zaporizhzhia nuclear power plant (ZNPP) in Ukraine, the watchdog said on Saturday.<a href="https://www.reuters.com/world/europe/iaea-says-its-chief-is-expected-visit-moscow-kyiv-next-week-2022-10-01/" target="_blank">Source</a>| VIENNA, Oct 1 (Reuters) - U.N. nuclear watchdog chief Rafael Grossi is expected to hold talks in Moscow and Kyiv next week on the creation of a protection zone around the Russian-held Zaporizhzhia nuclear power plant (ZNPP) in Ukraine, the watchdog said on Saturday. "Director General Grossi continues his consultations and other efforts aimed at agreeing and implementing a nuclear safety and security zone around the ZNPP as soon as possible.|
