# What are the advantages of using kamikaze drones in Ukraine?

## Summary
Kamikaze drones are small, portable, and difficult to detect, making them ideal for attacking targets from a distance. They are also relatively cheap, which makes them attractive for use in large numbers. In addition, their precision-guided missiles and large payloads make them deadly weapons.

## Claims
| Claim Sentence | Context |
|---|---|
|ZALA Aero says the advantages of KUB-BLA include "high accuracy, hidden launch, noiselessness, and ease of use."<a href="https://eurasiantimes.com/russian-troops-step-up-use-of-kamikaze-cuba-drones-frontline/" target="_blank">Source</a>| Its outstanding features include silent operation, stealth design, long loiter capability, and, most significantly, the ability to identify its target using AI. The drones have an accuracy between 5 to 10 m. ZALA Aero says the advantages of KUB-BLA include "high accuracy, hidden launch, noiselessness, and ease of use." "The explosive can be delivered to the target regardless of how well hidden it is.|
|They are small, portable and can be easily launched, but their main advantage is that they are hard to detect and can be fired from a distance.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-17-22/h_acad2b553a31e40076c26c574aac3af3" target="_blank">Source</a>| Kamikaze drones, or suicide drones, are a type of aerial weapon system. They are known as a loitering munition because they are capable of circling for some time in an area identified as a potential target and only striking once an enemy asset is identified. They are small, portable and can be easily launched, but their main advantage is that they are hard to detect and can be fired from a distance. Why are they called "Kamikaze"?|
|Kamikaze drones are far cheaper than bigger, more sophisticated Western models, so they can be deployed by the dozens and deliver a big scare factor.<a href="https://www.aljazeera.com/news/2022/10/20/mass-drones-are-a-worry-for-the-future-of-warfare" target="_blank">Source</a>| Kamikaze drones are far cheaper than bigger, more sophisticated Western models, so they can be deployed by the dozens and deliver a big scare factor. A little before 7am on Monday, people in Kyiv heard a whining sound overhead before identifying where it was coming from a group of "kamikaze" drones flying into the city.|
|They are small, portable and can be easily launched but their main advantage is that they are hard to detect and can be fired from a distance.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-16-22/h_95cc4ca2e4d8bb2872f6c46902bda4ab" target="_blank">Source</a>| They are known as a "loitering munition" because they are capable of waiting in an area identified as a potential target and only strike once an enemy asset is identified. The drones are capable of carrying precision-guided missiles and have a payload of approximately 50 kilograms (110 pounds). They are small, portable and can be easily launched but their main advantage is that they are hard to detect and can be fired from a distance. CNN's Ivana Kottasov and Josh Pennington contributed to this report.|
|They are small, portable and can be easily launched but their main advantage is that they are hard to detect and can be fired from a distance.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-16-22/h_1350e11d991341044c6b9bfffce32d60" target="_blank">Source</a>| They are known as a "loitering munition" because they are capable of waiting in an area identified as a potential target and only strike once an enemy asset is identified. The drones are capable of carrying precision-guided missiles and have a payload of approximately 50 kilograms (110 pounds). They are small, portable and can be easily launched but their main advantage is that they are hard to detect and can be fired from a distance. Ties to Iran: The Ukrainian military andUS intelligencesay Russia is using Iranian-made attack drones.|
