# What is the potential impact of a nuclear accident at the Zaporizhzhia nuclear power plant?

## Summary
The potential impact of a nuclear accident at the Zaporizhzhia nuclear power plant is very grave, and could have disastrous consequences for the region.

## Claims
| Claim Sentence | Context |
|---|---|
|The situation at the plant is a source of international concern because of fears that repeated shelling of the plant's territory - for which Kyiv and Moscow blame each other - could lead to a nuclear accident.<a href="https://www.reuters.com/world/europe/iaea-chief-zaporizhzhia-nuclear-power-plant-is-ukrainian-facility-2022-10-06/" target="_blank">Source</a>| Russia has occupied the Zaporizhzhia nuclear power plant (ZNPP), Europe's largest, since shortly after its invasion of Ukraine, but Ukrainian staff have continued to operate it. The ZNPP is located in a part of southern Ukraine that Putin has formally incorporated into Russia after holding what Moscow called referendums, in a move condemned by Kyiv and its Western partners as an illegal land grab. The situation at the plant is a source of international concern because of fears that repeated shelling of the plant's territory - for which Kyiv and Moscow blame each other - could lead to a nuclear accident. Director-General of the International Atomic Energy Agency (IAEA) Rafael Grossi speaks to the media after a meeting with Ukraine's President Volodymyr Zelenskiy, amid Russia's attack on Ukraine, in Kyiv, Ukraine October 6, 2022.|
|Joint Statement on the High-Level Meeting on the Safety and Security of Civil Nuclear Facilities in Armed Conflicts : "We, the ministers of Foreign Affairs of Canada, France, Germany, Italy, Japan, the United Kingdom, Ukraine and the United States of America, and senior officials from the Republic of Korea and Switzerland, as well as the High Representative of the European Union for Foreign Affairs and Security Policy, wish to express our grave concern regarding the threats posed to the safety and security of nuclear facilities devoted to peaceful purposes in Ukraine and their personnel, significantly raising the risk of a nuclear accident."<a href="https://www.stimson.org/2022/nuclear-security-news-and-member-updates-september-2022/" target="_blank">Source</a>| : "North Korean leader Kim Jong Un stressed his country will never abandon the nuclear weapons it needs to counter the United States, which he accused of pushing to weaken the Norths defenses and eventually collapse his government, state media said Friday. Kim made the comments during a speech Thursday at North Koreas rubber-stamp parliament, where members passed legislation governing the use of nuclear weapons, which Kim described as a step to cement the countrys nuclear status and make clear such weapons will not be bargained." Joint Statement on the High-Level Meeting on the Safety and Security of Civil Nuclear Facilities in Armed Conflicts : "We, the ministers of Foreign Affairs of Canada, France, Germany, Italy, Japan, the United Kingdom, Ukraine and the United States of America, and senior officials from the Republic of Korea and Switzerland, as well as the High Representative of the European Union for Foreign Affairs and Security Policy, wish to express our grave concern regarding the threats posed to the safety and security of nuclear facilities devoted to peaceful purposes in Ukraine and their personnel, significantly raising the risk of a nuclear accident." : "We, the ministers of Foreign Affairs of Canada, France, Germany, Italy, Japan, the United Kingdom, Ukraine and the United States of America, and senior officials from the Republic of Korea and Switzerland, as well as the High Representative of the European Union for Foreign Affairs and Security Policy, wish to express our grave concern regarding the threats posed to the safety and security of nuclear facilities devoted to peaceful purposes in Ukraine and their personnel, significantly raising the risk of a nuclear accident."|
|"As you know, I've been displaying efforts to tryand avoid a nuclear accident that could be very detrimental in general terms and in particular in the region," Grossi told Putin.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-11-22/h_18f979d7169ceeb276ae3a0ffc704a66" target="_blank">Source</a>| In any case, we are open to this dialogue and are glad to see you." Grossi said that the their discussion today is "very important and indispensable," since "we do have issues that have to do with nuclear safety, nuclear security in particular at the Zaporizhzhia nuclear power plant." "As you know, I've been displaying efforts to tryand avoid a nuclear accident that could be very detrimental in general terms and in particular in the region," Grossi told Putin.|
|The plant and the area around it, including the nearby city of Enerhodar, have endured persistent shelling that has raised fears of a nuclear accident through the interruption of the power supply to the plant.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-02-22/h_0ffb48ba822207b515d6d252c07cef5f" target="_blank">Source</a>| "He reiterated that this detention has a very significant impact on at least two of the seven indispensable nuclear safety and security pillars that he outlined at the beginning of the conflict in Ukraine," the IAEA said. Zaporizhzhia, the largest nuclear complex of its kind in Europe, was seized by Russian forces at the start of the war. The plant and the area around it, including the nearby city of Enerhodar, have endured persistent shelling that has raised fears of a nuclear accident through the interruption of the power supply to the plant. Russia and Ukraine have accused each other of acts of nuclear terrorism.|
|"Such a detention of any member of the plant staff would be a source of grave concern in itself, but also for its psychological impact and pressure on the rest of the staff - which is detrimental to nuclear safety and security," said Grossi.<a href="https://www.ukrinform.net/rubric-economy/3584005-iaea-chief-to-visit-kyiv-moscow-next-week-following-abduction-of-znpp-chief-by-russian-forces.html" target="_blank">Source</a>| After receiving information about the detention by the Russian forces of Ihor Murashov, Director General of Ukraines Zaporizhzhya Nuclear Power Plant (ZNPP), the International Atomic Energy Agency (IAEA) chief Rafael Grossi is set to visit Ukraine and Russia. That's according to the IAEA press service, Ukrinform reports. "Such a detention of any member of the plant staff would be a source of grave concern in itself, but also for its psychological impact and pressure on the rest of the staff - which is detrimental to nuclear safety and security," said Grossi. Furthermore, the Director General of the ZNPP has the responsibility to ensure the nuclear safety and security of the plant.|
