# How might the restarting of one of the reactors at the Zaporizhzhia nuclear power plant impact the situation?

## Summary
If one of the reactors at the Zaporizhzhia nuclear power plant is restarted, it could potentially lead to a nuclear accident due to the ongoing fighting in the area. This would put the lives of those in the vicinity at risk and also cause environmental damage. The International Atomic Energy Agency has called for a nuclear safety zone to be established around the plant as soon as possible to try and prevent such an accident from occurring.

## Claims
| Claim Sentence | Context |
|---|---|
|But they still require electricity to prevent them from overheating to the point of a meltdown that could cause radiation to pour from Europes largest nuclear plant.<a href="https://www.pbs.org/newshour/world/ukraines-zaporizhzhia-nuclear-power-plant-loses-external-power-again" target="_blank">Source</a>| The Russian-occupied Zaporizhzhia Nuclear Power Plant suffered a "blackout" when a missile damaged an electrical substation, leading to the emergency shutdown of the plants last remaining outside power source, operator Energoatom reported. All six of the reactors were stopped earlier due to the war. But they still require electricity to prevent them from overheating to the point of a meltdown that could cause radiation to pour from Europes largest nuclear plant. Energoatom said diesel generators were supplying the plant but Russian troops blocked a convoy carrying additional fuel for the backup equipment.|
|The situation at the plant is a source of international concern because of fears that repeated shelling of the plant's territory - for which Kyiv and Moscow blame each other - could lead to a nuclear accident.<a href="https://www.reuters.com/world/europe/iaea-chief-zaporizhzhia-nuclear-power-plant-is-ukrainian-facility-2022-10-06/" target="_blank">Source</a>| Russia has occupied the Zaporizhzhia nuclear power plant (ZNPP), Europe's largest, since shortly after its invasion of Ukraine, but Ukrainian staff have continued to operate it. The ZNPP is located in a part of southern Ukraine that Putin has formally incorporated into Russia after holding what Moscow called referendums, in a move condemned by Kyiv and its Western partners as an illegal land grab. The situation at the plant is a source of international concern because of fears that repeated shelling of the plant's territory - for which Kyiv and Moscow blame each other - could lead to a nuclear accident. Director-General of the International Atomic Energy Agency (IAEA) Rafael Grossi speaks to the media after a meeting with Ukraine's President Volodymyr Zelenskiy, amid Russia's attack on Ukraine, in Kyiv, Ukraine October 6, 2022.|
|Its capture, and the ongoing fighting at the site, have set off global alarms over the possibility of catastrophic damage and deadly plumes of radioactive fallout.<a href="https://www.nytimes.com/2022/10/09/science/ukraine-nuclear-power-plant-crisis.html" target="_blank">Source</a>| Analysts divide the 42-year history into intensifying stages. The dangers soared in March when Russian troops attacked the six reactors at the Zaporizhzhia power plant in Ukraine and seized control of the giant complex. Its capture, and the ongoing fighting at the site, have set off global alarms over the possibility of catastrophic damage and deadly plumes of radioactive fallout. Russias siege of the Zaporizhzhia site is without precedent in the history of warfare, with an invading power aiming to extract economic leverage over a highly complex power generation plant.|
|Ukrainian technicians continued running it after Russian troops seized the power station, and its last reactor was shut down in September as a precautionary measure amid ongoing shelling nearby.<a href="https://www.npr.org/2022/10/01/1126385655/russia-accused-kidnapping-head-ukraine-nuclear-plant" target="_blank">Source</a>| "His detention by (Russia) jeopardizes the safety of Ukraine and Europe's largest nuclear power plant," said Energoatom President Petro Kotin said, demanding the director's immediate release. The power plant repeatedly has been caught in the crossfire of the war in Ukraine. Ukrainian technicians continued running it after Russian troops seized the power station, and its last reactor was shut down in September as a precautionary measure amid ongoing shelling nearby. Amid growing international sanctions and condemnation of Russia, a Ukrainian counteroffensive that has embarrassed the Kremlin appeared on the verge of retaking more ground.|
|The head of the UNs nuclear watchdog, Rafael Grossi, was in Kyiv on Thursday to discuss his calls to establish a nuclear safety zone around the plant "as soon as possible," the IAEA said in a statement.<a href="https://www.cnn.com/2022/10/06/europe/russia-ukraine-zaporizhzhia-city-plant-intl/index.html" target="_blank">Source</a>| The Zaporizhzhia plant has been subject to intense scrutiny since its occupation shortly after Russias invasion in late February. Intense shelling near the facility this summer sparked concerns of a nuclear accident, prompting the International Atomic Energy Agency to send a team there. The head of the UNs nuclear watchdog, Rafael Grossi, was in Kyiv on Thursday to discuss his calls to establish a nuclear safety zone around the plant "as soon as possible," the IAEA said in a statement. Grossi will also visit Russia in the coming days.|
