# What is the long-term strategy for the US in supporting Ukraine?

## Summary
The United States will continue to support Ukraine in its defense against Russia, including providing advanced air defense systems. The US will also continue to work with allies and partners to impose costs on Russia and hold it accountable for its actions in Ukraine.

## Claims
| Claim Sentence | Context |
|---|---|
|President Biden pledged to continue supporting Ukraine as it defends itself from Russian aggression for as long as it takes, including the provision today of a new $625 million security assistance package that includes additional weapons and equipment, including HIMARS, artillery systems and ammunition, and armored vehicles.<a href="https://www.whitehouse.gov/briefing-room/statements-releases/2022/10/04/readout-of-president-bidens-call-with-president-zelenskyy-of-ukraine-10/" target="_blank">Source</a>| President Joseph R. Biden, Jr., joined by Vice President Kamala Harris, spoke today with President Volodymyr Zelenskyy of Ukraine to underscore that the United States will never recognize Russias purported annexation of Ukrainian territory. President Biden pledged to continue supporting Ukraine as it defends itself from Russian aggression for as long as it takes, including the provision today of a new $625 million security assistance package that includes additional weapons and equipment, including HIMARS, artillery systems and ammunition, and armored vehicles. President Biden also affirmed the continued readiness of the United States to impose severe costs on any individual, entity, or country that provides support to Russias purported annexation.|
|"He also underscored his ongoing engagement with allies and partners to continue imposing costs on Russia, holding Russia accountable for its war crimes and atrocities, and providing Ukraine with security, economic, and humanitarian assistance," the readout continued.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-10-22/h_41294d04001fdcae771da5132a3028cd" target="_blank">Source</a>| US President Joe Biden spoke with Ukrainian President Volodymyr Zelensky on Monday to condemn Russia's recent missile strikes and pledge continued US security assistance, including advanced air defense systems, according to a White House readout of the call. The readout did not provide additional details on what advanced air defense systems were discussed. "He also underscored his ongoing engagement with allies and partners to continue imposing costs on Russia, holding Russia accountable for its war crimes and atrocities, and providing Ukraine with security, economic, and humanitarian assistance," the readout continued. In a statement earlier Monday, Biden said the recent wave of Russian strikes "once again demonstrate the utter brutality of Mr.Putin's illegal war on the Ukrainian people."|
|President Biden pledged to continue providing Ukraine with the support needed to defend itself, including advanced air defense systems.<a href="https://www.whitehouse.gov/briefing-room/statements-releases/2022/10/10/readout-of-president-joe-bidens-call-with-president-volodymyr-zelenskyy-of-ukraine/" target="_blank">Source</a>| President Joseph R. Biden, Jr., spoke today with President Volodymyr Zelenskyy of Ukraine. He expressed his condemnation of Russias missile strikes across Ukraine, including in Kyiv, and conveyed his condolences to the loved ones of those killed and injured in these senseless attacks. President Biden pledged to continue providing Ukraine with the support needed to defend itself, including advanced air defense systems. He also underscored his ongoing engagement with allies and partners to continue imposing costs on Russia, holding Russia accountable for its war crimes and atrocities, and providing Ukraine with security, economic, and humanitarian assistance.|
|We must continue to jointly oppose the aggression of the Russian Federation!"<a href="https://www.ukrinform.net/rubric-polytics/3583649-zelensky-thanks-biden-for-additional-12b-in-aid.html" target="_blank">Source</a>| The president noted that the law provides the financing of defense programs, as well as powerful direct budget support to Ukraine. "This help is more important today than ever. We must continue to jointly oppose the aggression of the Russian Federation!" the tweet concludes.|
|On Monday, US President Joe Biden spoke with Ukrainian President Volodymyr Zelensky to condemn Russia's recent missile strikes and pledge continued US security assistance, including advanced air defense systems, according to a White House readout of the call.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-10-11-22/h_722c4dbb79752893211cc5f694d6fe9d" target="_blank">Source</a>| Russia's Ambassador to the United States Anatoly Antonov on Monday warned Washington and its allies against supplying Ukraine with more weapons, warning it could lead to further escalation of the war. On Monday, US President Joe Biden spoke with Ukrainian President Volodymyr Zelensky to condemn Russia's recent missile strikes and pledge continued US security assistance, including advanced air defense systems, according to a White House readout of the call. The readout did not provide additional details on what advanced air defense systems were discussed, but the US previously committed to providing Ukraine with National Advanced Surface-to-Air Missile Systems (NASAMS) that would be capable of engaging Russian cruise missiles.|
