# How will the closure of the Russian border affect Russian citizens who are in transit to other countries?

## Summary
The closure of the Russian border will affect Russian citizens who are in transit to other countries by significantly restricting their right to enter Finland. In addition, the Finnish government will also be able to control the border between Finland and Russia using a border fence.

## Claims
| Claim Sentence | Context |
|---|---|
|It will drastically limit the capacity to receive visa applications in Russia," the ministry added.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-29-22/h_872f4092953d8cd1824078d482accdce" target="_blank">Source</a>| Since then, there has been an exodus of citizens fleeing the country and thousands of Russians have entered neighboring Finland. "The resolution aims to stop tourism and related transit from Russia altogether. It will drastically limit the capacity to receive visa applications in Russia," the ministry added. "The resolution will not prevent travelling when it is deemed necessary for humanitarian reasons, for national interests or for meeting Finland's international obligations."|
|The government of Finland will "significantly" restrict the right of Russian citizens to enter the country as tourists or as transit when traveling to other parts of the Schengen area, the Finnish government said in a statement on Wednesday.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-28-22/h_a08b679f06dec8520259a3df6945c204" target="_blank">Source</a>| The government of Finland will "significantly" restrict the right of Russian citizens to enter the country as tourists or as transit when traveling to other parts of the Schengen area, the Finnish government said in a statement on Wednesday. "In addition, the Government received a briefing on ways to enhance control at the border between Finland and Russia using a border fence," it added.|
|Of that number, many were "in transit to other countries," he added.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-28-22/h_eef02663059d97e36573c32aaf6cab93" target="_blank">Source</a>| Since that time, hundreds of thousandshave fledto neighboring countries in a desperate bid to avoid military conscription. Last weekend saw a record number of Russians entering neighboring Finland via its land border since the Kremlin's announcement, with 16,886 Russians arriving in total over Saturday and Sunday, according to the border guard's head of international affairs, Matti Pitkaniitty. Of that number, many were "in transit to other countries," he added. Finland and Russia share a 1,340-km (830-mile) land border, with several border crossings.|
|The entry of Russian citizens to Finland is closed only for tourist visa holders, but other types of trips are still possible, according to the Russian ambassador to Helsinki.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-30-22/h_64cc02d609ee513f8ebc180276a169a5" target="_blank">Source</a>| The entry of Russian citizens to Finland is closed only for tourist visa holders, but other types of trips are still possible, according to the Russian ambassador to Helsinki. "From today, the Finns prohibit the entry of Russians for tourist purposes.|
|Frontex estimates that illegal border crossings are likely to increase if the Russian Federation decides to close the border for potential conscripts.<a href="https://frontex.europa.eu/media-centre/news/news-release/update-situation-at-the-eu-s-land-border-with-russia-X3iWuK" target="_blank">Source</a>| The majority of them hold residence permits or visas to EU Member States or Schengen Associated Countries, others have dual citizenships. Member States are also reporting entries by Ukrainian citizens in need of temporary protection as they flee the eastern occupied region of Ukraine via Russia. Frontex estimates that illegal border crossings are likely to increase if the Russian Federation decides to close the border for potential conscripts. On 19 September, Poland, Lithuania, Latvia and Estonia introduced restrictions regarding the entry of Russian citizens travelling solely for the purpose of tourism or leisure.|
