# What is the status of efforts to secure the release of Paul Whelan and Brittney Griner?

## Summary
The United States has made a "serious offer" to negotiate the return of WNBA star Brittney Griner and former US Marine Paul Whelan, but Russia has not yet responded. Griner is currently serving a nine-year sentence in Russia after pleading guilty to drug charges, and Whelan is serving a 16-year sentence on espionage-related charges. The US government regards both as wrongfully detained, and Secretary of State Antony Blinken has said that the administration has made a substantial proposal to Russia.

## Claims
| Claim Sentence | Context |
|---|---|
|National Security Council coordinator John Kirby says Russia has not responded to the "substantial proposal" the U.S. offered back in July regarding the release of WNBA star Brittney Griner and former U.S. Marine Paul Whelan.<a href="https://www.foxnews.com/sports/russia-responded-us-offer-regarding-brittney-griner-paul-whelan-release-biden-administration-says" target="_blank">Source</a>| National Security Council coordinator John Kirby says Russia has not responded to the "substantial proposal" the U.S. offered back in July regarding the release of WNBA star Brittney Griner and former U.S. Marine Paul Whelan. Kirby told the media during Fridays White House press briefing that the U.S. has made a "serious offer" to negotiate the return of Griner and Whelan, but added that those discussions are "still ongoing."|
|Where the negotiations stand: A senior administration official told CNN Thursday that there has been "movement but not breakthrough" on the efforts to free Whelan and WNBA star Brittney Griner.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-17-22/h_4392813436930e3a6c7e2faf703a3705" target="_blank">Source</a>| Paul Whelan has been imprisoned in Russia for more than three years after being convicted on espionage charges that he vehemently denies. He was sentenced in June 2020 to 16 years in prison in a trial US officials denounced as unfair. Where the negotiations stand: A senior administration official told CNN Thursday that there has been "movement but not breakthrough" on the efforts to free Whelan and WNBA star Brittney Griner. The official said that the United States has urged Russia to put forward "a serious counteroffer" to the proposal on the table to secure the release of the two, but "we've not gotten a serious response back."|
|Her legal team in Russia has appealed the nine-year sentence.<a href="https://www.cnn.com/2022/09/22/sport/brittney-griner-usa-basketball-world-cup-spt-intl/index.html" target="_blank">Source</a>| The tournament start comes a week after Griners wife, Cherelle Griner, met with US President Joe Biden to plead her wifes case as the US negotiates the release of the WNBA star and former US Marine Paul Whelan. Griner was detained in February for carrying vape cartridges containing cannabis oil in her luggage and pleaded guilty to drug charges, saying she accidentally packed the drugs in a hurry. Her legal team in Russia has appealed the nine-year sentence. Griners teammates and other WNBA players have also shown solidarity with the eight-time All-Star by boycotting playing in Russia during the offseason.|
|The U.S. government regards both as wrongfully detained, placing their cases with the office of its top hostage negotiator.<a href="https://www.fox5vegas.com/2022/09/16/biden-meeting-with-families-whelan-griner-white-house/" target="_blank">Source</a>| She was sentenced last month to nine years in prison after pleading guilty and has appealed the punishment. Whelan is serving a 16-year sentence on espionage-related charges that he and his family say are false. The U.S. government regards both as wrongfully detained, placing their cases with the office of its top hostage negotiator. Secretary of State Antony Blinken took the unusual step of announcing two months ago that the administration had made a substantial proposal to Russia.|
|He was sentenced in June 2020 to 16 years in prison in a trial US officials denounced as unfair.<a href="https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-17-22/h_582299caa1b481ba8fee8c900ff9e6a6" target="_blank">Source</a>| Her legal team in Russia has appealed the sentence. Whelan has been imprisoned in Russia for more than three years after being convicted on espionage charges that he vehemently denies. He was sentenced in June 2020 to 16 years in prison in a trial US officials denounced as unfair.|
